/**
 * Airport-to-Outstation Route Data
 * 23 routes covering Delhi, Jaipur, Chandigarh, Dehradun, Srinagar, and Amritsar airports
 */

export const airportRoutes = {
  "delhi-airport-to-jaipur-taxi": {
    slug: "delhi-airport-to-jaipur-taxi",
    airport: "Delhi IGI Airport",
    airportCode: "DEL",
    airportCity: "Delhi",
    terminals: [
      { name: "Terminal 1 (T1)", type: "Domestic", airlines: "IndiGo, SpiceJet (select flights)", pickup: "Arrival Gate exit, taxi stand area", driveTime: "4.5-5 hrs to Jaipur" },
      { name: "Terminal 2 (T2)", type: "Domestic", airlines: "Expanded domestic operations", pickup: "Ground floor arrival exit", driveTime: "4.5-5 hrs to Jaipur" },
      { name: "Terminal 3 (T3)", type: "International + Domestic", airlines: "Air India, Vistara, Emirates, all international", pickup: "Arrival hall, meeting point near Starbucks", driveTime: "5-5.5 hrs to Jaipur" },
    ],
    destination: "Jaipur",
    destinationState: "Rajasthan",
    distance: "280 km",
    time: "4.5-5 hours",
    highway: "NH48 via Gurgaon-Jaipur Expressway",
    fares: {
      sedan: { price: "4,500", vehicle: "Swift Dzire / Amaze", seats: 4 },
      suv: { price: "6,500", vehicle: "Innova / Ertiga", seats: 6 },
      tempo: { price: "12,000", vehicle: "Tempo Traveller 12-seater", seats: 12 },
    },
    meetAndGreet: true,
    flightTracking: true,
    pickupPoints: ["Arrival Gate T3", "Arrival Gate T1D", "Prepaid Taxi Counter"],
    highlights: ["Flight tracking included", "Meet & greet at arrival", "Fixed fare, no surge", "Yamuna Expressway route", "24/7 availability"],
    destinationAttractions: ["Hawa Mahal", "Amber Fort", "City Palace", "Jantar Mantar", "Nahargarh Fort", "Jal Mahal"],
    description: [
      "Landing at Delhi IGI Airport and heading to the Pink City? Our Delhi Airport to Jaipur taxi service offers a seamless, stress-free transfer. Your driver tracks your flight in real-time, meets you at the arrival gate with a name board, and drives you directly to your Jaipur destination in a comfortable AC vehicle.",
      "The 280 km drive via NH48 takes approximately 4.5 to 5 hours. The route passes through Gurgaon and along the Delhi-Jaipur Expressway, offering a smooth highway ride. Whether you are a business traveller, tourist heading to see the Amber Fort, or a family visiting relatives, we ensure you reach Jaipur safely and on time.",
      "Unlike airport prepaid taxis or ride-hailing apps with surge pricing, our fixed fare of just Rs 4,500 for a sedan covers everything -- tolls, parking, driver allowance, and meet & greet service. No hidden charges, no surprises. Book for early morning, late night, or any flight time.",
    ],
    faqs: [
      { question: "How much does a taxi from Delhi Airport to Jaipur cost?", answer: "Fixed fare: Sedan (Swift Dzire) Rs 4,500, SUV (Innova/Ertiga) Rs 6,500, Tempo Traveller Rs 12,000. All fares include tolls, parking, and meet & greet. No surge pricing." },
      { question: "How long does it take from Delhi Airport to Jaipur?", answer: "The drive takes 4.5 to 5 hours via NH48 (Delhi-Jaipur Expressway). Late night journeys can be faster at around 4 hours due to less traffic." },
      { question: "Can I book for a late night flight arriving at Delhi Airport?", answer: "Yes, we operate 24/7. Whether your flight lands at 2 AM or 11 PM, your driver will be waiting. Night charges are already included in the fare." },
      { question: "What if my flight is delayed?", answer: "We track your flight in real-time. If delayed, the driver adjusts accordingly. No extra waiting charges for flight delays up to 3 hours." },
      { question: "Which terminal will my driver be at?", answer: "Your driver will be at whichever terminal your flight arrives at -- T1, T2, or T3. We confirm the terminal before your arrival and the driver waits at the designated pickup zone." },
      { question: "Is there a return trip from Jaipur to Delhi Airport?", answer: "Yes, we offer both one-way and round trips. For round trips, we offer a 10% discount. The driver times the departure based on your flight schedule." },
      { question: "Can I make a stop on the way to Jaipur?", answer: "Yes, you can request a stop at Neemrana Fort or any highway restaurant. A brief stop of 20-30 minutes is complimentary. Extended detours may have additional charges." },
      { question: "Do you provide child seats?", answer: "Child and baby seats are available on request at no extra charge. Please mention this at the time of booking so we can arrange it in advance." },
    ],
    relatedRoutes: ["delhi-airport-to-agra-taxi", "delhi-airport-to-chandigarh-taxi", "delhi-airport-to-shimla-taxi", "jaipur-airport-to-udaipur-taxi", "jaipur-airport-to-pushkar-taxi"],
  },

  "delhi-airport-to-haridwar-taxi": {
    slug: "delhi-airport-to-haridwar-taxi",
    airport: "Delhi IGI Airport",
    airportCode: "DEL",
    airportCity: "Delhi",
    terminals: [
      { name: "Terminal 1 (T1)", type: "Domestic", airlines: "IndiGo, SpiceJet (select flights)", pickup: "Arrival Gate exit, taxi stand area", driveTime: "5-5.5 hrs to Haridwar" },
      { name: "Terminal 2 (T2)", type: "Domestic", airlines: "Expanded domestic operations", pickup: "Ground floor arrival exit", driveTime: "5-5.5 hrs to Haridwar" },
      { name: "Terminal 3 (T3)", type: "International + Domestic", airlines: "Air India, Vistara, Emirates, all international", pickup: "Arrival hall, meeting point near Starbucks", driveTime: "5.5-6 hrs to Haridwar" },
    ],
    destination: "Haridwar",
    destinationState: "Uttarakhand",
    distance: "230 km",
    time: "5-6 hours",
    highway: "NH334 via Meerut-Muzaffarnagar",
    fares: {
      sedan: { price: "3,800", vehicle: "Swift Dzire / Amaze", seats: 4 },
      suv: { price: "5,500", vehicle: "Innova / Ertiga", seats: 6 },
      tempo: { price: "10,000", vehicle: "Tempo Traveller 12-seater", seats: 12 },
    },
    meetAndGreet: true,
    flightTracking: true,
    pickupPoints: ["Arrival Gate T3", "Arrival Gate T1D", "Prepaid Taxi Counter"],
    highlights: ["Flight tracking included", "Meet & greet at arrival", "Fixed fare, no surge", "Direct highway route", "Ganga Aarti timing coordination"],
    destinationAttractions: ["Har Ki Pauri", "Ganga Aarti", "Mansa Devi Temple", "Chandi Devi Temple", "Rajaji National Park", "Saptrishi Ashram"],
    description: [
      "Flying into Delhi and heading to the holy city of Haridwar? Our Delhi Airport to Haridwar taxi service ensures a comfortable, direct transfer from any IGI Airport terminal to the banks of the Ganga. Your driver tracks your flight and meets you at the arrival gate.",
      "The 230 km journey via NH334 through Meerut and Muzaffarnagar takes approximately 5-6 hours. We can coordinate your arrival to catch the famous evening Ganga Aarti at Har Ki Pauri. Many pilgrims and spiritual seekers prefer this direct airport transfer over trains or buses.",
      "Our fixed fare starts at just Rs 3,800 for a sedan with no hidden charges. Tolls, parking, and driver allowance are all included. Perfect for pilgrims visiting Haridwar, tourists heading to Rishikesh, or Char Dham Yatra travellers starting their journey.",
    ],
    faqs: [
      { question: "How much does a taxi from Delhi Airport to Haridwar cost?", answer: "Fixed fare: Sedan Rs 3,800, SUV Rs 5,500, Tempo Traveller Rs 10,000. All inclusive of tolls and parking. No surge pricing at any time." },
      { question: "How long is the drive from Delhi Airport to Haridwar?", answer: "The drive takes 5 to 6 hours via NH334 through Meerut. Late night drives can be shorter due to reduced traffic." },
      { question: "Can you drop me directly at Har Ki Pauri?", answer: "Yes, we can drop you at Har Ki Pauri, your hotel, or any specific ghat or ashram in Haridwar. Just specify your destination at booking." },
      { question: "Can I continue to Rishikesh from Haridwar?", answer: "Absolutely. Rishikesh is just 25 km from Haridwar. We can either drop you in Rishikesh or offer a combined Haridwar-Rishikesh drop for a small additional fare." },
      { question: "Is the taxi available for late night flights?", answer: "Yes, we operate 24/7. Your driver will be waiting regardless of your flight time. Night charges are included in the quoted fare." },
      { question: "What if my flight is delayed?", answer: "We track your flight in real-time and adjust pickup accordingly. No extra charges for delays up to 3 hours." },
    ],
    relatedRoutes: ["delhi-airport-to-rishikesh-taxi", "delhi-airport-to-dehradun-taxi", "dehradun-airport-to-haridwar-taxi", "dehradun-airport-to-rishikesh-taxi"],
  },

  "delhi-airport-to-shimla-taxi": {
    slug: "delhi-airport-to-shimla-taxi",
    airport: "Delhi IGI Airport",
    airportCode: "DEL",
    airportCity: "Delhi",
    terminals: [
      { name: "Terminal 1 (T1)", type: "Domestic", airlines: "IndiGo, SpiceJet (select flights)", pickup: "Arrival Gate exit, taxi stand area", driveTime: "7-8 hrs to Shimla" },
      { name: "Terminal 2 (T2)", type: "Domestic", airlines: "Expanded domestic operations", pickup: "Ground floor arrival exit", driveTime: "7-8 hrs to Shimla" },
      { name: "Terminal 3 (T3)", type: "International + Domestic", airlines: "Air India, Vistara, Emirates, all international", pickup: "Arrival hall, meeting point near Starbucks", driveTime: "7.5-8.5 hrs to Shimla" },
    ],
    destination: "Shimla",
    destinationState: "Himachal Pradesh",
    distance: "350 km",
    time: "7-8 hours",
    highway: "NH44 via Chandigarh, then NH5 to Shimla",
    fares: {
      sedan: { price: "6,000", vehicle: "Swift Dzire / Amaze", seats: 4 },
      suv: { price: "8,500", vehicle: "Innova / Ertiga", seats: 6 },
      tempo: { price: "15,000", vehicle: "Tempo Traveller 12-seater", seats: 12 },
    },
    meetAndGreet: true,
    flightTracking: true,
    pickupPoints: ["Arrival Gate T3", "Arrival Gate T1D", "Prepaid Taxi Counter"],
    highlights: ["Flight tracking included", "Meet & greet at arrival", "Fixed fare, no surge", "Scenic hill drive", "Experienced hill drivers"],
    destinationAttractions: ["The Ridge", "Mall Road", "Jakhoo Temple", "Kufri", "Christ Church", "Shimla State Museum"],
    description: [
      "Flying into Delhi and dreaming of the cool hills of Shimla? Our Delhi Airport to Shimla taxi service provides a comfortable, direct transfer from IGI Airport to the Queen of Hills. Your driver is an experienced hill road specialist who knows every curve of the mountain route.",
      "The 350 km journey takes 7-8 hours via NH44 through Chandigarh, then climbing via NH5 into the Himalayas. The drive becomes scenic once you cross Chandigarh, with beautiful views of pine forests and mountain valleys. We recommend taking a break at Chandigarh or Solan along the way.",
      "Our fixed fare of Rs 6,000 for a sedan includes everything -- tolls, parking, and driver allowance. For families, our SUV option at Rs 8,500 offers extra space for luggage and a more comfortable mountain drive. All vehicles are well-maintained with experienced drivers who regularly ply this route.",
    ],
    faqs: [
      { question: "How much does a taxi from Delhi Airport to Shimla cost?", answer: "Fixed fare: Sedan Rs 6,000, SUV Rs 8,500, Tempo Traveller Rs 15,000. Includes tolls, parking, and driver charges. No hidden costs." },
      { question: "How long does it take from Delhi Airport to Shimla?", answer: "The drive takes 7-8 hours. The first half is highway driving through Chandigarh, and the second half is scenic mountain road. Night journeys can be slightly faster." },
      { question: "Are the drivers experienced in hill driving?", answer: "Yes, all our Shimla route drivers are experienced hill road specialists. They regularly ply the Chandigarh-Shimla mountain route and know every hairpin turn." },
      { question: "Can we stop at Chandigarh on the way?", answer: "Yes, a brief 30-minute stop at Chandigarh for food or sightseeing is complimentary. Extended stops or detours may incur a small additional charge." },
      { question: "Is the drive safe at night?", answer: "We recommend starting early rather than driving the mountain section at night. However, our drivers are experienced and can handle night driving if needed. The highway portion is well-lit." },
      { question: "What if it snows in Shimla?", answer: "During winter, our vehicles carry chains for snow conditions. Our drivers are trained for snow driving. In extreme weather, we may suggest a stop in Chandigarh and continue when safe." },
    ],
    relatedRoutes: ["delhi-airport-to-chandigarh-taxi", "delhi-airport-to-manali-taxi", "chandigarh-airport-to-shimla-taxi", "delhi-airport-to-dehradun-taxi"],
  },

  "delhi-airport-to-manali-taxi": {
    slug: "delhi-airport-to-manali-taxi",
    airport: "Delhi IGI Airport",
    airportCode: "DEL",
    airportCity: "Delhi",
    terminals: [
      { name: "Terminal 1 (T1)", type: "Domestic", airlines: "IndiGo, SpiceJet (select flights)", pickup: "Arrival Gate exit, taxi stand area", driveTime: "11-13 hrs to Manali" },
      { name: "Terminal 2 (T2)", type: "Domestic", airlines: "Expanded domestic operations", pickup: "Ground floor arrival exit", driveTime: "11-13 hrs to Manali" },
      { name: "Terminal 3 (T3)", type: "International + Domestic", airlines: "Air India, Vistara, Emirates, all international", pickup: "Arrival hall, meeting point near Starbucks", driveTime: "12-14 hrs to Manali" },
    ],
    destination: "Manali",
    destinationState: "Himachal Pradesh",
    distance: "540 km",
    time: "11-13 hours",
    highway: "NH44 via Chandigarh, then NH3 via Kullu",
    fares: {
      sedan: { price: "9,000", vehicle: "Swift Dzire / Amaze", seats: 4 },
      suv: { price: "12,500", vehicle: "Innova / Ertiga", seats: 6 },
      tempo: { price: "20,000", vehicle: "Tempo Traveller 12-seater", seats: 12 },
    },
    meetAndGreet: true,
    flightTracking: true,
    pickupPoints: ["Arrival Gate T3", "Arrival Gate T1D", "Prepaid Taxi Counter"],
    highlights: ["Flight tracking included", "Meet & greet at arrival", "Fixed fare, no surge", "Scenic Beas Valley drive", "Experienced mountain drivers"],
    destinationAttractions: ["Rohtang Pass", "Solang Valley", "Hadimba Temple", "Old Manali", "Beas River", "Naggar Castle"],
    description: [
      "Flying into Delhi and heading straight to the mountain paradise of Manali? Our Delhi Airport to Manali taxi service provides a comfortable long-distance transfer with experienced hill drivers. Your driver tracks your flight and meets you at the arrival gate, ready for the adventure ahead.",
      "The 540 km journey takes 11-13 hours via NH44 through Chandigarh, then through the stunning Kullu Valley along the Beas River. The drive is one of India's most scenic routes, passing through Ambala, Chandigarh, Bilaspur, Mandi, and Kullu before reaching Manali. Most travellers prefer an overnight departure.",
      "Our fixed fare of Rs 9,000 for a sedan includes all tolls, parking, and driver allowance. For the long mountain journey, we recommend our SUV option at Rs 12,500 for extra comfort. All drivers are experienced mountain route specialists who regularly ply the Chandigarh-Manali highway.",
    ],
    faqs: [
      { question: "How much does a taxi from Delhi Airport to Manali cost?", answer: "Fixed fare: Sedan Rs 9,000, SUV Rs 12,500, Tempo Traveller Rs 20,000. All inclusive of tolls, parking, and driver allowance." },
      { question: "How long is the drive from Delhi Airport to Manali?", answer: "The drive takes 11-13 hours depending on traffic and road conditions. The route goes via Chandigarh and Kullu Valley. Many travellers prefer overnight departure." },
      { question: "Can we take an overnight trip?", answer: "Yes, overnight departures are popular for this route. You can sleep during the highway portion and wake up to the beautiful mountain scenery near Kullu-Manali." },
      { question: "Is it better to fly to Chandigarh and then drive to Manali?", answer: "If direct flights to Chandigarh are available, that reduces the drive to about 8-9 hours. However, Delhi offers more flight options and our direct transfer is very comfortable." },
      { question: "Can we stop at Chandigarh for the night?", answer: "Yes, we can arrange an overnight halt at Chandigarh. The driver will wait and continue to Manali the next morning. Additional night halt charges apply." },
      { question: "Are the roads safe to Manali?", answer: "The NH3 via Kullu is well-maintained. Our experienced hill drivers know the route well. During monsoon season, we monitor road conditions and take alternate routes if needed." },
    ],
    relatedRoutes: ["delhi-airport-to-shimla-taxi", "delhi-airport-to-chandigarh-taxi", "chandigarh-airport-to-manali-taxi", "delhi-airport-to-dehradun-taxi"],
  },

  "delhi-airport-to-chandigarh-taxi": {
    slug: "delhi-airport-to-chandigarh-taxi",
    airport: "Delhi IGI Airport",
    airportCode: "DEL",
    airportCity: "Delhi",
    terminals: [
      { name: "Terminal 1 (T1)", type: "Domestic", airlines: "IndiGo, SpiceJet (select flights)", pickup: "Arrival Gate exit, taxi stand area", driveTime: "4.5-5 hrs to Chandigarh" },
      { name: "Terminal 2 (T2)", type: "Domestic", airlines: "Expanded domestic operations", pickup: "Ground floor arrival exit", driveTime: "4.5-5 hrs to Chandigarh" },
      { name: "Terminal 3 (T3)", type: "International + Domestic", airlines: "Air India, Vistara, Emirates, all international", pickup: "Arrival hall, meeting point near Starbucks", driveTime: "5-5.5 hrs to Chandigarh" },
    ],
    destination: "Chandigarh",
    destinationState: "Punjab/Haryana",
    distance: "250 km",
    time: "4.5-5 hours",
    highway: "NH44 (Delhi-Chandigarh Expressway)",
    fares: {
      sedan: { price: "4,200", vehicle: "Swift Dzire / Amaze", seats: 4 },
      suv: { price: "6,000", vehicle: "Innova / Ertiga", seats: 6 },
      tempo: { price: "11,000", vehicle: "Tempo Traveller 12-seater", seats: 12 },
    },
    meetAndGreet: true,
    flightTracking: true,
    pickupPoints: ["Arrival Gate T3", "Arrival Gate T1D", "Prepaid Taxi Counter"],
    highlights: ["Flight tracking included", "Meet & greet at arrival", "Fixed fare, no surge", "Expressway route", "24/7 availability"],
    destinationAttractions: ["Rock Garden", "Sukhna Lake", "Rose Garden", "Capitol Complex", "Elante Mall", "Sector 17 Market"],
    description: [
      "Need a reliable taxi from Delhi IGI Airport to the City Beautiful? Our Delhi Airport to Chandigarh taxi service offers a seamless transfer via the Delhi-Chandigarh Expressway. Flight tracking and meet & greet are included as standard with every booking.",
      "The 250 km drive via NH44 takes just 4.5 to 5 hours on the excellent expressway. The route is one of India's best highways, making for a smooth and comfortable ride. Whether you are heading to Chandigarh for business, visiting PU, or connecting onward to Shimla or Manali, we get you there safely.",
      "Our fixed fare starts at Rs 4,200 for a sedan -- significantly less than what airport taxi counters charge. All tolls, parking, and driver allowance are included. No hidden fees, no surge pricing, just reliable service at a fixed price.",
    ],
    faqs: [
      { question: "How much does a taxi from Delhi Airport to Chandigarh cost?", answer: "Fixed fare: Sedan Rs 4,200, SUV Rs 6,000, Tempo Traveller Rs 11,000. All fares include tolls, parking, and driver charges." },
      { question: "How long is the drive from Delhi Airport to Chandigarh?", answer: "The drive takes 4.5 to 5 hours via the Delhi-Chandigarh Expressway (NH44). Late night drives can be as quick as 4 hours." },
      { question: "Can I continue to Shimla or Manali from Chandigarh?", answer: "Yes, we offer extended transfers from Delhi Airport to Shimla (via Chandigarh) or to Manali. The driver can continue to your final destination." },
      { question: "Which expressway is used?", answer: "We use the Delhi-Chandigarh Expressway (NH44), one of India's best highways. The road is well-maintained with regular service stops." },
      { question: "Is there a return trip available?", answer: "Yes, we offer both one-way and round trips. Round trip bookings get a 10% discount." },
      { question: "What if my flight arrives late at night?", answer: "We operate 24/7. Night charges are included in the fare. Your driver tracks the flight and adjusts timing accordingly." },
    ],
    relatedRoutes: ["delhi-airport-to-shimla-taxi", "delhi-airport-to-manali-taxi", "chandigarh-airport-to-shimla-taxi", "chandigarh-airport-to-manali-taxi"],
  },

  "delhi-airport-to-dehradun-taxi": {
    slug: "delhi-airport-to-dehradun-taxi",
    airport: "Delhi IGI Airport",
    airportCode: "DEL",
    airportCity: "Delhi",
    terminals: [
      { name: "Terminal 1 (T1)", type: "Domestic", airlines: "IndiGo, SpiceJet (select flights)", pickup: "Arrival Gate exit, taxi stand area", driveTime: "5.5-6 hrs to Dehradun" },
      { name: "Terminal 2 (T2)", type: "Domestic", airlines: "Expanded domestic operations", pickup: "Ground floor arrival exit", driveTime: "5.5-6 hrs to Dehradun" },
      { name: "Terminal 3 (T3)", type: "International + Domestic", airlines: "Air India, Vistara, Emirates, all international", pickup: "Arrival hall, meeting point near Starbucks", driveTime: "6-6.5 hrs to Dehradun" },
    ],
    destination: "Dehradun",
    destinationState: "Uttarakhand",
    distance: "260 km",
    time: "5.5-6 hours",
    highway: "NH334 via Meerut-Roorkee",
    fares: {
      sedan: { price: "4,300", vehicle: "Swift Dzire / Amaze", seats: 4 },
      suv: { price: "6,200", vehicle: "Innova / Ertiga", seats: 6 },
      tempo: { price: "11,500", vehicle: "Tempo Traveller 12-seater", seats: 12 },
    },
    meetAndGreet: true,
    flightTracking: true,
    pickupPoints: ["Arrival Gate T3", "Arrival Gate T1D", "Prepaid Taxi Counter"],
    highlights: ["Flight tracking included", "Meet & greet at arrival", "Fixed fare, no surge", "Direct route via Roorkee", "Onward Mussoorie transfer available"],
    destinationAttractions: ["Robber's Cave", "Sahastradhara", "Forest Research Institute", "Mindrolling Monastery", "Rajaji National Park", "Clock Tower"],
    description: [
      "Landing at Delhi Airport and need to reach Dehradun, the gateway to Uttarakhand? Our Delhi Airport to Dehradun taxi service offers a comfortable, direct transfer. Your driver tracks your flight and is ready at the arrival gate when you land.",
      "The 260 km drive via NH334 through Meerut and Roorkee takes 5.5 to 6 hours. This is a popular route for travellers heading to Dehradun for ISBT, Doon School, or continuing to Mussoorie. The highway is well-maintained and offers a smooth ride.",
      "Starting at just Rs 4,300 for a sedan, our fixed fare includes everything. If you are continuing to Mussoorie (35 km beyond Dehradun), we can extend the trip for a small additional fare. Perfect for hill station getaways and Uttarakhand adventures.",
    ],
    faqs: [
      { question: "How much does a taxi from Delhi Airport to Dehradun cost?", answer: "Fixed fare: Sedan Rs 4,300, SUV Rs 6,200, Tempo Traveller Rs 11,500. Tolls, parking, and driver charges included." },
      { question: "How long does it take from Delhi Airport to Dehradun?", answer: "5.5 to 6 hours via NH334 through Meerut and Roorkee. Night journeys may be slightly faster." },
      { question: "Can the driver continue to Mussoorie?", answer: "Yes, Mussoorie is 35 km from Dehradun. We can drop you directly in Mussoorie for an additional Rs 800." },
      { question: "Is it better to fly to Dehradun instead?", answer: "Dehradun has Jolly Grant Airport, but Delhi offers more flights and often cheaper fares. Our road transfer is comfortable and you avoid the small Dehradun airport hassle." },
      { question: "What about luggage for hill station trips?", answer: "Sedans accommodate 2 large suitcases + 2 cabin bags. For more luggage, choose our SUV. Tempo Travellers have a large luggage compartment." },
      { question: "Can I book for a round trip?", answer: "Yes, round trips get a 10% discount. We also offer Dehradun + Mussoorie packages for tourists." },
    ],
    relatedRoutes: ["delhi-airport-to-haridwar-taxi", "delhi-airport-to-rishikesh-taxi", "dehradun-airport-to-mussoorie-taxi", "dehradun-airport-to-haridwar-taxi"],
  },

  "delhi-airport-to-rishikesh-taxi": {
    slug: "delhi-airport-to-rishikesh-taxi",
    airport: "Delhi IGI Airport",
    airportCode: "DEL",
    airportCity: "Delhi",
    terminals: [
      { name: "Terminal 1 (T1)", type: "Domestic", airlines: "IndiGo, SpiceJet (select flights)", pickup: "Arrival Gate exit, taxi stand area", driveTime: "5.5-6.5 hrs to Rishikesh" },
      { name: "Terminal 2 (T2)", type: "Domestic", airlines: "Expanded domestic operations", pickup: "Ground floor arrival exit", driveTime: "5.5-6.5 hrs to Rishikesh" },
      { name: "Terminal 3 (T3)", type: "International + Domestic", airlines: "Air India, Vistara, Emirates, all international", pickup: "Arrival hall, meeting point near Starbucks", driveTime: "6-7 hrs to Rishikesh" },
    ],
    destination: "Rishikesh",
    destinationState: "Uttarakhand",
    distance: "245 km",
    time: "5.5-6.5 hours",
    highway: "NH334 via Meerut-Haridwar",
    fares: {
      sedan: { price: "4,000", vehicle: "Swift Dzire / Amaze", seats: 4 },
      suv: { price: "5,800", vehicle: "Innova / Ertiga", seats: 6 },
      tempo: { price: "10,500", vehicle: "Tempo Traveller 12-seater", seats: 12 },
    },
    meetAndGreet: true,
    flightTracking: true,
    pickupPoints: ["Arrival Gate T3", "Arrival Gate T1D", "Prepaid Taxi Counter"],
    highlights: ["Flight tracking included", "Meet & greet at arrival", "Fixed fare, no surge", "Via Haridwar route", "Yoga capital direct transfer"],
    destinationAttractions: ["Laxman Jhula", "Ram Jhula", "Triveni Ghat", "Beatles Ashram", "Neer Garh Waterfall", "River Rafting"],
    description: [
      "Flying into Delhi for your Rishikesh adventure? Our Delhi Airport to Rishikesh taxi service provides a direct, comfortable transfer from IGI Airport to the Yoga Capital of the World. Perfect for international yoga enthusiasts, adventure seekers, and spiritual travellers.",
      "The 245 km journey via NH334 takes 5.5 to 6.5 hours, passing through Meerut and Haridwar before reaching Rishikesh. The route offers a transition from bustling Delhi to the serene Ganga banks. Many international travellers prefer this direct airport transfer over multiple connections.",
      "At just Rs 4,000 for a sedan, this is the most convenient way to reach Rishikesh from Delhi Airport. The driver can drop you at Laxman Jhula, Ram Jhula, Tapovan, or any ashram or hotel in Rishikesh. All tolls and parking included in the fare.",
    ],
    faqs: [
      { question: "How much is a taxi from Delhi Airport to Rishikesh?", answer: "Sedan Rs 4,000, SUV Rs 5,800, Tempo Traveller Rs 10,500. Fixed fares with tolls and parking included." },
      { question: "How long does it take to reach Rishikesh from Delhi Airport?", answer: "5.5 to 6.5 hours via NH334 through Haridwar. The drive passes through scenic countryside before reaching the Ganga." },
      { question: "Can you drop me at a specific ashram in Rishikesh?", answer: "Yes, we drop you at any location in Rishikesh -- ashrams, hotels, Laxman Jhula, Ram Jhula, or Tapovan. Just specify when booking." },
      { question: "Can I stop at Haridwar on the way?", answer: "Haridwar is on the route. A brief stop for darshan at Har Ki Pauri is complimentary. Extended visits may have a small waiting charge." },
      { question: "Is the taxi available for adventure groups?", answer: "Yes, our Tempo Traveller can accommodate groups of up to 12 for rafting trips, yoga retreats, or adventure camps. Group discounts available." },
      { question: "What about early morning or late night flights?", answer: "We operate 24/7. Night charges are included in the fare. Flight tracking ensures your driver is always on time." },
    ],
    relatedRoutes: ["delhi-airport-to-haridwar-taxi", "delhi-airport-to-dehradun-taxi", "dehradun-airport-to-rishikesh-taxi", "dehradun-airport-to-haridwar-taxi"],
  },

  "delhi-airport-to-mathura-taxi": {
    slug: "delhi-airport-to-mathura-taxi",
    airport: "Delhi IGI Airport",
    airportCode: "DEL",
    airportCity: "Delhi",
    terminals: [
      { name: "Terminal 1 (T1)", type: "Domestic", airlines: "IndiGo, SpiceJet (select flights)", pickup: "Arrival Gate exit, taxi stand area", driveTime: "2.5-3 hrs to Mathura" },
      { name: "Terminal 2 (T2)", type: "Domestic", airlines: "Expanded domestic operations", pickup: "Ground floor arrival exit", driveTime: "2.5-3 hrs to Mathura" },
      { name: "Terminal 3 (T3)", type: "International + Domestic", airlines: "Air India, Vistara, Emirates, all international", pickup: "Arrival hall, meeting point near Starbucks", driveTime: "3-3.5 hrs to Mathura" },
    ],
    destination: "Mathura",
    destinationState: "Uttar Pradesh",
    distance: "185 km",
    time: "2.5-3.5 hours",
    highway: "Yamuna Expressway",
    fares: {
      sedan: { price: "3,500", vehicle: "Swift Dzire / Amaze", seats: 4 },
      suv: { price: "5,000", vehicle: "Innova / Ertiga", seats: 6 },
      tempo: { price: "9,000", vehicle: "Tempo Traveller 12-seater", seats: 12 },
    },
    meetAndGreet: true,
    flightTracking: true,
    pickupPoints: ["Arrival Gate T3", "Arrival Gate T1D", "Prepaid Taxi Counter"],
    highlights: ["Flight tracking included", "Meet & greet at arrival", "Fixed fare, no surge", "Yamuna Expressway fast route", "Vrindavan add-on available"],
    destinationAttractions: ["Krishna Janmabhoomi", "Dwarkadhish Temple", "Vrindavan", "Banke Bihari Temple", "Govardhan Hill", "Kusum Sarovar"],
    description: [
      "Flying into Delhi for a pilgrimage to Lord Krishna's birthplace? Our Delhi Airport to Mathura taxi service offers a direct, comfortable transfer via the Yamuna Expressway. Your driver tracks your flight and meets you at the arrival gate with a name board.",
      "The 185 km drive via the Yamuna Expressway takes just 2.5 to 3.5 hours, making Mathura an easy reach from Delhi Airport. The expressway is one of India's finest highways, ensuring a smooth and fast ride to the holy city. We can also include a stop at Vrindavan, just 15 km from Mathura.",
      "At Rs 3,500 for a sedan, our fixed fare includes all tolls (Yamuna Expressway toll included), parking, and driver charges. Perfect for pilgrims, Holi festival visitors, or tourists exploring the Krishna circuit. Vrindavan add-on available for a small additional fare.",
    ],
    faqs: [
      { question: "How much is a taxi from Delhi Airport to Mathura?", answer: "Sedan Rs 3,500, SUV Rs 5,000, Tempo Traveller Rs 9,000. Yamuna Expressway toll and all charges included." },
      { question: "How long is the drive?", answer: "Just 2.5 to 3.5 hours via the Yamuna Expressway. This is one of the fastest airport transfers available." },
      { question: "Can you also take me to Vrindavan?", answer: "Yes, Vrindavan is just 15 km from Mathura. We can include Vrindavan drop for Rs 300 extra." },
      { question: "Can I continue to Agra from Mathura?", answer: "Agra is 60 km from Mathura. We offer combined Mathura-Agra transfers. Ask for our package pricing." },
      { question: "Is the service available during Holi?", answer: "Yes, we operate during all festivals including Holi. Advance booking is recommended during festival seasons as demand is high." },
      { question: "What about return trips?", answer: "We offer one-way and round trips. Round trips include a 10% discount." },
    ],
    relatedRoutes: ["delhi-airport-to-agra-taxi", "delhi-airport-to-jaipur-taxi", "delhi-airport-to-lucknow-taxi"],
  },

  "delhi-airport-to-noida-cab": {
    slug: "delhi-airport-to-noida-cab",
    airport: "Delhi IGI Airport",
    airportCode: "DEL",
    airportCity: "Delhi",
    terminals: [
      { name: "Terminal 1 (T1)", type: "Domestic", airlines: "IndiGo, SpiceJet (select flights)", pickup: "Arrival Gate exit, taxi stand area", driveTime: "40-60 min to Noida" },
      { name: "Terminal 2 (T2)", type: "Domestic", airlines: "Expanded domestic operations", pickup: "Ground floor arrival exit", driveTime: "40-60 min to Noida" },
      { name: "Terminal 3 (T3)", type: "International + Domestic", airlines: "Air India, Vistara, Emirates, all international", pickup: "Arrival hall, meeting point near Starbucks", driveTime: "45-70 min to Noida" },
    ],
    destination: "Noida",
    destinationState: "Uttar Pradesh",
    distance: "35 km",
    time: "40-70 minutes",
    highway: "DND Flyway / Noida Expressway",
    fares: {
      sedan: { price: "1,200", vehicle: "Swift Dzire / Amaze", seats: 4 },
      suv: { price: "1,800", vehicle: "Innova / Ertiga", seats: 6 },
      tempo: { price: "3,500", vehicle: "Tempo Traveller 12-seater", seats: 12 },
    },
    meetAndGreet: true,
    flightTracking: true,
    pickupPoints: ["Arrival Gate T3", "Arrival Gate T1D", "Prepaid Taxi Counter"],
    highlights: ["Flight tracking included", "Meet & greet at arrival", "Fixed fare, no surge", "DND Flyway route", "Greater Noida coverage"],
    destinationAttractions: ["Worlds of Wonder", "Okhla Bird Sanctuary", "Botanical Garden", "DLF Mall of India", "Noida Film City", "Sector 18 Market"],
    description: [
      "Need a reliable cab from Delhi Airport to Noida? Skip the unreliable app cabs with surge pricing and book our fixed-fare airport transfer. Your driver tracks your flight, meets you at the arrival gate, and drives you directly to any location in Noida or Greater Noida.",
      "The 35 km drive typically takes 40-70 minutes depending on traffic. We use the DND Flyway or Noida Expressway for the fastest route. Whether you are heading to a corporate office in Sector 62, a home in Greater Noida, or a hotel near Expo Centre, we cover all Noida locations.",
      "At just Rs 1,200 for a sedan, our fixed fare beats the surge-priced app cabs, especially during peak hours and late night arrivals. No hidden charges, no cancellations, and guaranteed pickup. The fare includes DND toll and all other charges.",
    ],
    faqs: [
      { question: "How much is a cab from Delhi Airport to Noida?", answer: "Fixed fare: Sedan Rs 1,200, SUV Rs 1,800, Tempo Traveller Rs 3,500. DND toll and all charges included." },
      { question: "How long does it take to reach Noida from Delhi Airport?", answer: "40-70 minutes depending on traffic and which sector in Noida. Late night arrivals typically take just 40 minutes." },
      { question: "Do you cover Greater Noida?", answer: "Yes, we cover all of Noida and Greater Noida. Sectors, Pari Chowk, Knowledge Park, Expo Centre -- all locations covered." },
      { question: "Why not use Uber/Ola from the airport?", answer: "App cabs often have surge pricing at airports (2-3x normal), frequent cancellations, and long wait times. Our fixed fare and guaranteed pickup save you hassle." },
      { question: "Is the fare the same for all Noida sectors?", answer: "Yes, the quoted fare covers any location in Noida city. Greater Noida destinations beyond Pari Chowk may have a small additional charge." },
      { question: "Can I book for a return trip to the airport?", answer: "Yes, we offer airport drop services from Noida. Same fixed pricing with timed departure based on your flight." },
    ],
    relatedRoutes: ["delhi-airport-to-gurgaon-cab", "delhi-airport-to-agra-taxi", "delhi-airport-to-mathura-taxi"],
  },

  "delhi-airport-to-gurgaon-cab": {
    slug: "delhi-airport-to-gurgaon-cab",
    airport: "Delhi IGI Airport",
    airportCode: "DEL",
    airportCity: "Delhi",
    terminals: [
      { name: "Terminal 1 (T1)", type: "Domestic", airlines: "IndiGo, SpiceJet (select flights)", pickup: "Arrival Gate exit, taxi stand area", driveTime: "25-45 min to Gurgaon" },
      { name: "Terminal 2 (T2)", type: "Domestic", airlines: "Expanded domestic operations", pickup: "Ground floor arrival exit", driveTime: "25-45 min to Gurgaon" },
      { name: "Terminal 3 (T3)", type: "International + Domestic", airlines: "Air India, Vistara, Emirates, all international", pickup: "Arrival hall, meeting point near Starbucks", driveTime: "30-50 min to Gurgaon" },
    ],
    destination: "Gurgaon",
    destinationState: "Haryana",
    distance: "30 km",
    time: "25-50 minutes",
    highway: "NH48 / Delhi-Gurgaon Expressway",
    fares: {
      sedan: { price: "1,000", vehicle: "Swift Dzire / Amaze", seats: 4 },
      suv: { price: "1,500", vehicle: "Innova / Ertiga", seats: 6 },
      tempo: { price: "3,000", vehicle: "Tempo Traveller 12-seater", seats: 12 },
    },
    meetAndGreet: true,
    flightTracking: true,
    pickupPoints: ["Arrival Gate T3", "Arrival Gate T1D", "Prepaid Taxi Counter"],
    highlights: ["Flight tracking included", "Meet & greet at arrival", "Fixed fare, no surge", "Expressway route", "Corporate billing available"],
    destinationAttractions: ["Cyber Hub", "Kingdom of Dreams", "Ambience Mall", "Sohna Road", "Golf Course Road", "Sector 29 Market"],
    description: [
      "Need a quick, reliable cab from Delhi Airport to Gurgaon? Our fixed-fare airport transfer beats the surge-priced app cabs every time. Flight tracking and meet & greet ensure a hassle-free pickup from any terminal.",
      "The 30 km drive takes just 25-50 minutes via the Delhi-Gurgaon Expressway (NH48). Whether heading to DLF Cyber City, Golf Course Road, Sohna Road, or any Gurgaon sector, we guarantee fixed pricing with no surge. Popular with corporate travellers and tech professionals.",
      "At just Rs 1,000 for a sedan, our rate is lower than airport prepaid counters and immune to the surge pricing that app cabs charge during peak hours. Corporate billing and monthly invoicing available for business travellers. Book once, use us every time.",
    ],
    faqs: [
      { question: "How much is a cab from Delhi Airport to Gurgaon?", answer: "Fixed fare: Sedan Rs 1,000, SUV Rs 1,500, Tempo Traveller Rs 3,000. No surge pricing at any time. Toll included." },
      { question: "How long does it take?", answer: "25-50 minutes depending on traffic. Late night arrivals are typically under 30 minutes. The expressway makes it a quick ride." },
      { question: "Do you offer corporate billing?", answer: "Yes, we offer corporate billing with monthly invoicing. Many Gurgaon companies use our service for employee airport transfers." },
      { question: "Can I book a regular airport pickup service?", answer: "Yes, we offer subscription plans for frequent flyers. Fixed monthly rates with guaranteed availability." },
      { question: "Is the fare same for all Gurgaon locations?", answer: "The base fare covers most Gurgaon locations. Areas beyond Sohna Road or Manesar may have a small additional charge." },
      { question: "Why choose you over airport prepaid taxis?", answer: "Our vehicles are newer, rates are fixed (often lower than prepaid), you get flight tracking, meet & greet, and a confirmed driver before landing." },
    ],
    relatedRoutes: ["delhi-airport-to-noida-cab", "delhi-airport-to-jaipur-taxi", "delhi-airport-to-chandigarh-taxi"],
  },

  "delhi-airport-to-amritsar-taxi": {
    slug: "delhi-airport-to-amritsar-taxi",
    airport: "Delhi IGI Airport",
    airportCode: "DEL",
    airportCity: "Delhi",
    terminals: [
      { name: "Terminal 1 (T1)", type: "Domestic", airlines: "IndiGo, SpiceJet (select flights)", pickup: "Arrival Gate exit, taxi stand area", driveTime: "7.5-8.5 hrs to Amritsar" },
      { name: "Terminal 2 (T2)", type: "Domestic", airlines: "Expanded domestic operations", pickup: "Ground floor arrival exit", driveTime: "7.5-8.5 hrs to Amritsar" },
      { name: "Terminal 3 (T3)", type: "International + Domestic", airlines: "Air India, Vistara, Emirates, all international", pickup: "Arrival hall, meeting point near Starbucks", driveTime: "8-9 hrs to Amritsar" },
    ],
    destination: "Amritsar",
    destinationState: "Punjab",
    distance: "450 km",
    time: "7.5-9 hours",
    highway: "NH44 via Karnal-Jalandhar",
    fares: {
      sedan: { price: "7,500", vehicle: "Swift Dzire / Amaze", seats: 4 },
      suv: { price: "10,500", vehicle: "Innova / Ertiga", seats: 6 },
      tempo: { price: "18,000", vehicle: "Tempo Traveller 12-seater", seats: 12 },
    },
    meetAndGreet: true,
    flightTracking: true,
    pickupPoints: ["Arrival Gate T3", "Arrival Gate T1D", "Prepaid Taxi Counter"],
    highlights: ["Flight tracking included", "Meet & greet at arrival", "Fixed fare, no surge", "NH44 highway route", "Golden Temple direct drop"],
    destinationAttractions: ["Golden Temple", "Jallianwala Bagh", "Wagah Border", "Partition Museum", "Hall Bazaar", "Gobindgarh Fort"],
    description: [
      "Flying into Delhi and heading to the holy city of Amritsar? Our Delhi Airport to Amritsar taxi provides a comfortable long-distance transfer via NH44, one of India's best national highways. Your driver meets you at the arrival gate with flight tracking and name board.",
      "The 450 km drive via NH44 through Karnal, Ambala, Ludhiana, and Jalandhar takes 7.5 to 9 hours. The Grand Trunk Road route passes through the heart of Punjab, offering glimpses of India's agricultural heartland. Overnight departures are popular for this route.",
      "Our fixed fare of Rs 7,500 for a sedan includes all tolls, parking, and driver allowance. Popular with NRI families visiting the Golden Temple, Wagah Border visitors, and Punjabi families returning home. Group discounts available for Tempo Traveller bookings.",
    ],
    faqs: [
      { question: "How much is a taxi from Delhi Airport to Amritsar?", answer: "Sedan Rs 7,500, SUV Rs 10,500, Tempo Traveller Rs 18,000. All inclusive of tolls and driver charges." },
      { question: "How long is the drive?", answer: "7.5 to 9 hours via NH44. The GT Road route through Punjab is well-maintained. Night journeys are often faster." },
      { question: "Can you drop me directly at the Golden Temple?", answer: "Yes, we drop you at the Golden Temple, your hotel, or any specific location in Amritsar. Just specify at booking time." },
      { question: "Is an overnight drive recommended?", answer: "Yes, many travellers prefer overnight departure. You can sleep during the drive and arrive fresh in Amritsar by morning." },
      { question: "Can I visit Wagah Border on the way?", answer: "Wagah Border is about 30 km from Amritsar city. We can include a Wagah Border visit in your itinerary for a small additional charge." },
      { question: "Do you have NRI-friendly services?", answer: "Yes, we are experienced with NRI travellers. Our drivers speak basic English, accept advance booking, and can assist with luggage and hotel check-in." },
    ],
    relatedRoutes: ["delhi-airport-to-chandigarh-taxi", "amritsar-airport-to-city-taxi", "delhi-airport-to-jaipur-taxi"],
  },

  "delhi-airport-to-lucknow-taxi": {
    slug: "delhi-airport-to-lucknow-taxi",
    airport: "Delhi IGI Airport",
    airportCode: "DEL",
    airportCity: "Delhi",
    terminals: [
      { name: "Terminal 1 (T1)", type: "Domestic", airlines: "IndiGo, SpiceJet (select flights)", pickup: "Arrival Gate exit, taxi stand area", driveTime: "9-10 hrs to Lucknow" },
      { name: "Terminal 2 (T2)", type: "Domestic", airlines: "Expanded domestic operations", pickup: "Ground floor arrival exit", driveTime: "9-10 hrs to Lucknow" },
      { name: "Terminal 3 (T3)", type: "International + Domestic", airlines: "Air India, Vistara, Emirates, all international", pickup: "Arrival hall, meeting point near Starbucks", driveTime: "9.5-11 hrs to Lucknow" },
    ],
    destination: "Lucknow",
    destinationState: "Uttar Pradesh",
    distance: "550 km",
    time: "9-11 hours",
    highway: "Agra-Lucknow Expressway via Yamuna Expressway",
    fares: {
      sedan: { price: "8,500", vehicle: "Swift Dzire / Amaze", seats: 4 },
      suv: { price: "12,000", vehicle: "Innova / Ertiga", seats: 6 },
      tempo: { price: "20,000", vehicle: "Tempo Traveller 12-seater", seats: 12 },
    },
    meetAndGreet: true,
    flightTracking: true,
    pickupPoints: ["Arrival Gate T3", "Arrival Gate T1D", "Prepaid Taxi Counter"],
    highlights: ["Flight tracking included", "Meet & greet at arrival", "Fixed fare, no surge", "Expressway fast route", "Overnight travel available"],
    destinationAttractions: ["Bara Imambara", "Chota Imambara", "Rumi Darwaza", "Hazratganj", "British Residency", "Ambedkar Park"],
    description: [
      "Flying into Delhi and need to reach Lucknow, the City of Nawabs? Our Delhi Airport to Lucknow taxi service offers a comfortable long-distance transfer via the Yamuna and Agra-Lucknow Expressways -- two of India's best highways connected end-to-end.",
      "The 550 km journey takes 9-11 hours via the expressway route. The first leg on the Yamuna Expressway takes you past Mathura, then the Agra-Lucknow Expressway whisks you through to the capital of Uttar Pradesh. This is India's longest expressway journey and remarkably comfortable.",
      "At Rs 8,500 for a sedan, our fixed fare is economical for the distance covered. Popular with families, government officials, and travellers who prefer door-to-door comfort over connecting flights or overnight trains. Overnight departures are recommended for this route.",
    ],
    faqs: [
      { question: "How much is a taxi from Delhi Airport to Lucknow?", answer: "Sedan Rs 8,500, SUV Rs 12,000, Tempo Traveller Rs 20,000. All expressway tolls and charges included." },
      { question: "How long is the drive?", answer: "9-11 hours via the Yamuna and Agra-Lucknow Expressways. The expressway route is fast and comfortable." },
      { question: "Is overnight travel recommended?", answer: "Yes, many travellers depart at night and arrive by morning. The expressway is well-lit with regular rest stops." },
      { question: "Can I stop at Agra on the way?", answer: "Yes, Agra is on the route. A brief stop for Taj Mahal viewing or food is possible. Extended stops may have additional charges." },
      { question: "Why not fly directly to Lucknow?", answer: "Direct flights exist but can be expensive. Our road transfer is door-to-door, avoids second airport hassle, and is cost-effective for families." },
      { question: "Is the expressway safe at night?", answer: "Yes, the Yamuna and Agra-Lucknow Expressways have excellent lighting, patrol services, and rest areas. Our drivers are experienced in overnight drives." },
    ],
    relatedRoutes: ["delhi-airport-to-agra-taxi", "delhi-airport-to-mathura-taxi", "delhi-airport-to-jaipur-taxi"],
  },

  // === JAIPUR AIRPORT ROUTES ===

  "jaipur-airport-to-udaipur-taxi": {
    slug: "jaipur-airport-to-udaipur-taxi",
    airport: "Jaipur International Airport",
    airportCode: "JAI",
    airportCity: "Jaipur",
    terminals: [
      { name: "Terminal 1", type: "Domestic", airlines: "IndiGo, SpiceJet, Air India, Vistara", pickup: "Arrival hall exit, taxi pickup zone", driveTime: "6-7 hrs to Udaipur" },
      { name: "Terminal 2", type: "International", airlines: "International charter and scheduled flights", pickup: "International arrival exit", driveTime: "6-7 hrs to Udaipur" },
    ],
    destination: "Udaipur",
    destinationState: "Rajasthan",
    distance: "395 km",
    time: "6-7 hours",
    highway: "NH48 via Ajmer-Chittorgarh",
    fares: {
      sedan: { price: "6,500", vehicle: "Swift Dzire / Amaze", seats: 4 },
      suv: { price: "9,000", vehicle: "Innova / Ertiga", seats: 6 },
      tempo: { price: "16,000", vehicle: "Tempo Traveller 12-seater", seats: 12 },
    },
    meetAndGreet: true,
    flightTracking: true,
    pickupPoints: ["Terminal 1 Arrival", "Terminal 2 Arrival", "Airport Exit Gate"],
    highlights: ["Flight tracking included", "Meet & greet at arrival", "Fixed fare, no surge", "Scenic Rajasthan drive", "Chittorgarh stop available"],
    destinationAttractions: ["City Palace Udaipur", "Lake Pichola", "Jag Mandir", "Sajjangarh Palace", "Fateh Sagar Lake", "Bagore Ki Haveli"],
    description: [
      "Landing at Jaipur Airport and heading to the romantic Lake City of Udaipur? Our Jaipur Airport to Udaipur taxi service provides a comfortable, scenic transfer through the heart of Rajasthan. Your driver meets you at the arrival gate with flight tracking and a name board.",
      "The 395 km drive via NH48 through Ajmer and Chittorgarh takes 6-7 hours. The route passes through classic Rajasthani landscape -- rolling Aravalli hills, ancient forts, and vibrant villages. You can request a stop at Chittorgarh Fort, one of India's largest forts, along the way.",
      "Our fixed fare of Rs 6,500 for a sedan covers everything. This is a popular route for tourists completing the Rajasthan Golden Triangle circuit or heading to Udaipur for destination weddings. SUVs recommended for extra comfort on this scenic drive.",
    ],
    faqs: [
      { question: "How much is a taxi from Jaipur Airport to Udaipur?", answer: "Sedan Rs 6,500, SUV Rs 9,000, Tempo Traveller Rs 16,000. All tolls and charges included in the fare." },
      { question: "How long is the drive?", answer: "6-7 hours via NH48 through Ajmer and Chittorgarh. The route is scenic with good road conditions." },
      { question: "Can we stop at Chittorgarh Fort?", answer: "Yes, Chittorgarh is on the route. A 1-hour stop at the fort is available. Please inform at booking time." },
      { question: "Is this route popular for weddings?", answer: "Very popular. Udaipur is India's top wedding destination. We provide decorated vehicles and group transfers for wedding parties." },
      { question: "Can I book a return trip?", answer: "Yes, round trips get a 10% discount. We also offer multi-day Rajasthan tour packages." },
      { question: "What about luggage for families?", answer: "Sedans fit 2 large bags + 2 cabin bags. Choose SUV for families with more luggage. Tempo Traveller for large groups." },
    ],
    relatedRoutes: ["jaipur-airport-to-pushkar-taxi", "jaipur-airport-to-agra-taxi", "delhi-airport-to-jaipur-taxi"],
  },

  "jaipur-airport-to-pushkar-taxi": {
    slug: "jaipur-airport-to-pushkar-taxi",
    airport: "Jaipur International Airport",
    airportCode: "JAI",
    airportCity: "Jaipur",
    terminals: [
      { name: "Terminal 1", type: "Domestic", airlines: "IndiGo, SpiceJet, Air India, Vistara", pickup: "Arrival hall exit, taxi pickup zone", driveTime: "2.5-3 hrs to Pushkar" },
      { name: "Terminal 2", type: "International", airlines: "International charter and scheduled flights", pickup: "International arrival exit", driveTime: "2.5-3 hrs to Pushkar" },
    ],
    destination: "Pushkar",
    destinationState: "Rajasthan",
    distance: "145 km",
    time: "2.5-3 hours",
    highway: "NH48 via Ajmer",
    fares: {
      sedan: { price: "2,800", vehicle: "Swift Dzire / Amaze", seats: 4 },
      suv: { price: "4,000", vehicle: "Innova / Ertiga", seats: 6 },
      tempo: { price: "7,500", vehicle: "Tempo Traveller 12-seater", seats: 12 },
    },
    meetAndGreet: true,
    flightTracking: true,
    pickupPoints: ["Terminal 1 Arrival", "Terminal 2 Arrival", "Airport Exit Gate"],
    highlights: ["Flight tracking included", "Meet & greet at arrival", "Fixed fare, no surge", "Quick 2.5 hour drive", "Ajmer Sharif stop available"],
    destinationAttractions: ["Pushkar Lake", "Brahma Temple", "Pushkar Camel Fair", "Savitri Temple", "Varaha Temple", "Rose Garden"],
    description: [
      "Flying into Jaipur for the sacred town of Pushkar? Our Jaipur Airport to Pushkar taxi service offers a quick, comfortable transfer. The 145 km drive via Ajmer takes just 2.5 to 3 hours, making it perfect for same-day arrivals.",
      "Pushkar is one of India's most sacred pilgrimage towns, famous for the Brahma Temple and the annual Pushkar Camel Fair. The route passes through Ajmer, where you can request a stop at the famous Ajmer Sharif Dargah if you wish.",
      "At just Rs 2,800 for a sedan, this is an affordable and convenient airport transfer. Popular with international backpackers, spiritual travellers, and Camel Fair visitors. The drive through Rajasthan countryside is pleasant and scenic.",
    ],
    faqs: [
      { question: "How much is a taxi from Jaipur Airport to Pushkar?", answer: "Sedan Rs 2,800, SUV Rs 4,000, Tempo Traveller Rs 7,500. All tolls included." },
      { question: "How long is the drive?", answer: "Just 2.5 to 3 hours via NH48 through Ajmer. A quick and comfortable ride." },
      { question: "Can I stop at Ajmer Sharif on the way?", answer: "Yes, Ajmer is on the route. A 30-45 minute stop at the Dargah is complimentary." },
      { question: "Is this available during Pushkar Camel Fair?", answer: "Yes, but advance booking is essential during the Camel Fair season as demand is very high." },
      { question: "Can I get a return trip to Jaipur Airport?", answer: "Yes, we offer both one-way and round trips. The driver times departure based on your flight." },
      { question: "Do you cover Ajmer as well?", answer: "Yes, we can drop you in Ajmer instead of Pushkar, or include both locations in your trip." },
    ],
    relatedRoutes: ["jaipur-airport-to-udaipur-taxi", "jaipur-airport-to-agra-taxi", "delhi-airport-to-jaipur-taxi"],
  },

  "jaipur-airport-to-agra-taxi": {
    slug: "jaipur-airport-to-agra-taxi",
    airport: "Jaipur International Airport",
    airportCode: "JAI",
    airportCity: "Jaipur",
    terminals: [
      { name: "Terminal 1", type: "Domestic", airlines: "IndiGo, SpiceJet, Air India, Vistara", pickup: "Arrival hall exit, taxi pickup zone", driveTime: "4-5 hrs to Agra" },
      { name: "Terminal 2", type: "International", airlines: "International charter and scheduled flights", pickup: "International arrival exit", driveTime: "4-5 hrs to Agra" },
    ],
    destination: "Agra",
    destinationState: "Uttar Pradesh",
    distance: "240 km",
    time: "4-5 hours",
    highway: "NH21 via Bharatpur-Fatehpur Sikri",
    fares: {
      sedan: { price: "4,000", vehicle: "Swift Dzire / Amaze", seats: 4 },
      suv: { price: "5,800", vehicle: "Innova / Ertiga", seats: 6 },
      tempo: { price: "10,000", vehicle: "Tempo Traveller 12-seater", seats: 12 },
    },
    meetAndGreet: true,
    flightTracking: true,
    pickupPoints: ["Terminal 1 Arrival", "Terminal 2 Arrival", "Airport Exit Gate"],
    highlights: ["Flight tracking included", "Meet & greet at arrival", "Fixed fare, no surge", "Golden Triangle route", "Fatehpur Sikri stop available"],
    destinationAttractions: ["Taj Mahal", "Agra Fort", "Fatehpur Sikri", "Mehtab Bagh", "Itimad-ud-Daulah", "Sikandra"],
    description: [
      "Flying into Jaipur and heading to see the Taj Mahal? Our Jaipur Airport to Agra taxi completes the famous Golden Triangle route. Your driver tracks your flight and meets you at the Jaipur Airport arrival gate for a comfortable transfer to Agra.",
      "The 240 km drive via NH21 through Bharatpur and Fatehpur Sikri takes 4-5 hours. This is one of the most popular tourist routes in India, and we can include a stop at the UNESCO World Heritage Site of Fatehpur Sikri along the way.",
      "At Rs 4,000 for a sedan, this fixed-fare transfer is perfect for Golden Triangle tourists, Taj Mahal visitors, and families. All tolls and parking included. We can drop you directly at your Agra hotel or the Taj Mahal east gate.",
    ],
    faqs: [
      { question: "How much is a taxi from Jaipur Airport to Agra?", answer: "Sedan Rs 4,000, SUV Rs 5,800, Tempo Traveller Rs 10,000. All charges included." },
      { question: "How long is the drive?", answer: "4-5 hours via NH21 through Bharatpur. The route passes near Fatehpur Sikri." },
      { question: "Can we visit Fatehpur Sikri on the way?", answer: "Yes, Fatehpur Sikri is near the route. A 1-hour stop is available at no extra charge." },
      { question: "Can I go directly to Taj Mahal from Jaipur Airport?", answer: "Yes, if timing permits, we can take you directly to the Taj Mahal. We can also arrange Agra sightseeing." },
      { question: "Is this part of a Golden Triangle tour?", answer: "Yes, this is the Jaipur-Agra leg of the Golden Triangle. We offer complete Delhi-Agra-Jaipur packages." },
      { question: "What about Bharatpur Bird Sanctuary?", answer: "Keoladeo National Park in Bharatpur is on the route. A stop can be arranged on request." },
    ],
    relatedRoutes: ["jaipur-airport-to-udaipur-taxi", "jaipur-airport-to-pushkar-taxi", "delhi-airport-to-agra-taxi", "delhi-airport-to-jaipur-taxi"],
  },

  // === CHANDIGARH AIRPORT ROUTES ===

  "chandigarh-airport-to-shimla-taxi": {
    slug: "chandigarh-airport-to-shimla-taxi",
    airport: "Chandigarh International Airport",
    airportCode: "IXC",
    airportCity: "Chandigarh",
    terminals: [
      { name: "Main Terminal", type: "Domestic + International", airlines: "IndiGo, Air India, SpiceJet, GoFirst, international charters", pickup: "Arrival hall exit, designated taxi zone", driveTime: "3-4 hrs to Shimla" },
    ],
    destination: "Shimla",
    destinationState: "Himachal Pradesh",
    distance: "120 km",
    time: "3-4 hours",
    highway: "NH5 via Pinjore-Solan",
    fares: {
      sedan: { price: "3,000", vehicle: "Swift Dzire / Amaze", seats: 4 },
      suv: { price: "4,500", vehicle: "Innova / Ertiga", seats: 6 },
      tempo: { price: "8,000", vehicle: "Tempo Traveller 12-seater", seats: 12 },
    },
    meetAndGreet: true,
    flightTracking: true,
    pickupPoints: ["Arrival Hall Exit", "Airport Taxi Zone", "Main Gate"],
    highlights: ["Flight tracking included", "Meet & greet at arrival", "Fixed fare, no surge", "Scenic mountain drive", "Expert hill drivers"],
    destinationAttractions: ["The Ridge", "Mall Road", "Jakhoo Temple", "Kufri", "Christ Church", "Shimla Heritage Railway"],
    description: [
      "Landing at Chandigarh Airport for a Shimla hill station getaway? Our Chandigarh Airport to Shimla taxi is the most popular airport transfer in the region. The scenic 120 km mountain drive with our experienced hill drivers is the perfect start to your vacation.",
      "The 3-4 hour drive via NH5 through Pinjore and Solan is one of India's most beautiful mountain routes. Pine forests, apple orchards, and stunning valley views make this more than just a transfer -- it is the beginning of your Shimla experience. Our drivers know every hairpin turn on this road.",
      "At Rs 3,000 for a sedan, this is significantly cheaper than any other option from Chandigarh Airport. All our drivers are hill-road specialists with years of experience on the Chandigarh-Shimla route. Vehicles are well-maintained with good brakes and tyres suited for mountain roads.",
    ],
    faqs: [
      { question: "How much is a taxi from Chandigarh Airport to Shimla?", answer: "Sedan Rs 3,000, SUV Rs 4,500, Tempo Traveller Rs 8,000. All tolls and charges included." },
      { question: "How long is the drive?", answer: "3-4 hours. The first 30 minutes are on the plains, then the scenic mountain drive begins." },
      { question: "Are the drivers experienced in hill driving?", answer: "Yes, all our Shimla route drivers specialize in mountain roads. They drive this route daily and know every curve." },
      { question: "Can I stop at Pinjore Gardens?", answer: "Yes, Pinjore Gardens is on the route. A brief stop is complimentary." },
      { question: "What about winter snow conditions?", answer: "Our vehicles carry snow chains in winter. Drivers are trained for snow conditions. In extreme weather, we advise on safe travel times." },
      { question: "Is night driving safe on this route?", answer: "The route is narrow mountain road and best driven during daylight. However, our drivers can handle night driving if needed." },
    ],
    relatedRoutes: ["chandigarh-airport-to-manali-taxi", "delhi-airport-to-shimla-taxi", "delhi-airport-to-chandigarh-taxi"],
  },

  "chandigarh-airport-to-manali-taxi": {
    slug: "chandigarh-airport-to-manali-taxi",
    airport: "Chandigarh International Airport",
    airportCode: "IXC",
    airportCity: "Chandigarh",
    terminals: [
      { name: "Main Terminal", type: "Domestic + International", airlines: "IndiGo, Air India, SpiceJet, GoFirst, international charters", pickup: "Arrival hall exit, designated taxi zone", driveTime: "7-8 hrs to Manali" },
    ],
    destination: "Manali",
    destinationState: "Himachal Pradesh",
    distance: "310 km",
    time: "7-8 hours",
    highway: "NH21 via Bilaspur-Mandi-Kullu",
    fares: {
      sedan: { price: "5,500", vehicle: "Swift Dzire / Amaze", seats: 4 },
      suv: { price: "8,000", vehicle: "Innova / Ertiga", seats: 6 },
      tempo: { price: "14,000", vehicle: "Tempo Traveller 12-seater", seats: 12 },
    },
    meetAndGreet: true,
    flightTracking: true,
    pickupPoints: ["Arrival Hall Exit", "Airport Taxi Zone", "Main Gate"],
    highlights: ["Flight tracking included", "Meet & greet at arrival", "Fixed fare, no surge", "Beas Valley scenic route", "Experienced mountain drivers"],
    destinationAttractions: ["Rohtang Pass", "Solang Valley", "Hadimba Temple", "Old Manali", "Beas River", "Manikaran Hot Springs"],
    description: [
      "Flying into Chandigarh for a Manali adventure? Our Chandigarh Airport to Manali taxi offers the most comfortable way to reach the mountain paradise. The 310 km journey through the Beas Valley is one of India's most scenic drives.",
      "The 7-8 hour drive via NH21 passes through Bilaspur, Sundernagar, Mandi, and the stunning Kullu Valley. You will see the landscape transform from plains to mountains, with the Beas River as your companion for much of the journey. Our drivers are experienced mountain route specialists.",
      "At Rs 5,500 for a sedan, this transfer is far more comfortable and reliable than shared taxis or buses. The route includes some of the most beautiful scenery in Himachal Pradesh. We recommend starting early to enjoy the views and reach Manali by evening.",
    ],
    faqs: [
      { question: "How much is a taxi from Chandigarh Airport to Manali?", answer: "Sedan Rs 5,500, SUV Rs 8,000, Tempo Traveller Rs 14,000. All tolls and charges included." },
      { question: "How long is the drive?", answer: "7-8 hours via NH21 through Kullu Valley. The mountain portion is scenic but takes time due to curves." },
      { question: "Should I start early?", answer: "Yes, early morning departure is recommended to enjoy the scenery and reach Manali before dark." },
      { question: "Can I stop at Manikaran?", answer: "Yes, Manikaran is near Kullu and can be visited en route. A 1-hour stop is available." },
      { question: "Is the road safe during monsoon?", answer: "The route can be affected by landslides during heavy monsoon. We monitor conditions and use alternate routes when needed." },
      { question: "Can I book for a group trip?", answer: "Yes, our Tempo Traveller seats 12 comfortably. Group discounts available for large bookings." },
    ],
    relatedRoutes: ["chandigarh-airport-to-shimla-taxi", "delhi-airport-to-manali-taxi", "delhi-airport-to-chandigarh-taxi"],
  },

  // === DEHRADUN AIRPORT ROUTES ===

  "dehradun-airport-to-mussoorie-taxi": {
    slug: "dehradun-airport-to-mussoorie-taxi",
    airport: "Jolly Grant Airport Dehradun",
    airportCode: "DED",
    airportCity: "Dehradun",
    terminals: [
      { name: "Main Terminal", type: "Domestic", airlines: "IndiGo, Air India, SpiceJet, Vistara", pickup: "Arrival exit, taxi pickup area", driveTime: "1-1.5 hrs to Mussoorie" },
    ],
    destination: "Mussoorie",
    destinationState: "Uttarakhand",
    distance: "35 km",
    time: "1-1.5 hours",
    highway: "Dehradun-Mussoorie Road via Rajpur",
    fares: {
      sedan: { price: "1,200", vehicle: "Swift Dzire / Amaze", seats: 4 },
      suv: { price: "1,800", vehicle: "Innova / Ertiga", seats: 6 },
      tempo: { price: "3,500", vehicle: "Tempo Traveller 12-seater", seats: 12 },
    },
    meetAndGreet: true,
    flightTracking: true,
    pickupPoints: ["Arrival Exit", "Airport Main Gate", "Taxi Pickup Zone"],
    highlights: ["Flight tracking included", "Meet & greet at arrival", "Fixed fare, no surge", "Scenic mountain drive", "Quick 1-hour transfer"],
    destinationAttractions: ["Mall Road", "Kempty Falls", "Gun Hill", "Camel's Back Road", "Lal Tibba", "Company Garden"],
    description: [
      "Flying into Dehradun's Jolly Grant Airport for a Mussoorie getaway? Our airport to Mussoorie taxi is the quickest way to reach the Queen of Hills. The scenic 35 km mountain drive takes just 1 to 1.5 hours.",
      "The drive from Jolly Grant Airport climbs through Rajpur Road and up the winding mountain road to Mussoorie. The views become increasingly spectacular as you ascend, with glimpses of the Doon Valley below. Our drivers are hill road experts who know every turn.",
      "At just Rs 1,200 for a sedan, this is the most affordable and convenient airport transfer to Mussoorie. No haggling with local taxi drivers at the airport. Fixed fare, flight tracking, and a comfortable vehicle waiting for you.",
    ],
    faqs: [
      { question: "How much is a taxi from Dehradun Airport to Mussoorie?", answer: "Sedan Rs 1,200, SUV Rs 1,800, Tempo Traveller Rs 3,500. Fixed fare with no hidden charges." },
      { question: "How long is the drive?", answer: "Just 1 to 1.5 hours. The airport is at the base and Mussoorie is atop the mountain." },
      { question: "Can you drop me at Mall Road?", answer: "Yes, we drop you at Mall Road, your hotel, or any specific location in Mussoorie. Library Chowk, Picture Palace -- anywhere you need." },
      { question: "What about traffic to Mussoorie?", answer: "During peak season and weekends, the road can be congested near Mussoorie town. We plan accordingly and use the best route." },
      { question: "Is the driver experienced in mountain driving?", answer: "Yes, all our drivers on this route are hill-road specialists. They drive to Mussoorie daily." },
      { question: "Can I book a Mussoorie to Dehradun Airport drop?", answer: "Yes, we offer return transfers timed to your flight departure." },
    ],
    relatedRoutes: ["dehradun-airport-to-haridwar-taxi", "dehradun-airport-to-rishikesh-taxi", "delhi-airport-to-dehradun-taxi"],
  },

  "dehradun-airport-to-haridwar-taxi": {
    slug: "dehradun-airport-to-haridwar-taxi",
    airport: "Jolly Grant Airport Dehradun",
    airportCode: "DED",
    airportCity: "Dehradun",
    terminals: [
      { name: "Main Terminal", type: "Domestic", airlines: "IndiGo, Air India, SpiceJet, Vistara", pickup: "Arrival exit, taxi pickup area", driveTime: "45-60 min to Haridwar" },
    ],
    destination: "Haridwar",
    destinationState: "Uttarakhand",
    distance: "55 km",
    time: "45-60 minutes",
    highway: "NH7 via Rishikesh bypass",
    fares: {
      sedan: { price: "1,500", vehicle: "Swift Dzire / Amaze", seats: 4 },
      suv: { price: "2,200", vehicle: "Innova / Ertiga", seats: 6 },
      tempo: { price: "4,000", vehicle: "Tempo Traveller 12-seater", seats: 12 },
    },
    meetAndGreet: true,
    flightTracking: true,
    pickupPoints: ["Arrival Exit", "Airport Main Gate", "Taxi Pickup Zone"],
    highlights: ["Flight tracking included", "Meet & greet at arrival", "Fixed fare, no surge", "Quick 45-min transfer", "Ganga Aarti coordination"],
    destinationAttractions: ["Har Ki Pauri", "Ganga Aarti", "Mansa Devi Temple", "Chandi Devi Temple", "Shantikunj", "Saptrishi Ashram"],
    description: [
      "Landing at Dehradun's Jolly Grant Airport for a Haridwar pilgrimage? Our airport to Haridwar taxi gets you to the holy city in just 45-60 minutes. Jolly Grant is the closest airport to Haridwar, making this the most convenient airport transfer.",
      "The 55 km drive on NH7 is smooth and quick. We can coordinate your arrival to catch the famous evening Ganga Aarti at Har Ki Pauri. Whether you are visiting for the Kumbh Mela, a regular pilgrimage, or starting a Char Dham Yatra, we get you there comfortably.",
      "At Rs 1,500 for a sedan, our fixed fare is the best deal from Jolly Grant Airport. No haggling with airport taxi drivers, no surge pricing. Just a clean car, professional driver, and a smooth ride to the banks of the Ganga.",
    ],
    faqs: [
      { question: "How much is a taxi from Dehradun Airport to Haridwar?", answer: "Sedan Rs 1,500, SUV Rs 2,200, Tempo Traveller Rs 4,000. All inclusive fixed fare." },
      { question: "How long is the drive?", answer: "Just 45-60 minutes. Jolly Grant Airport is the nearest airport to Haridwar." },
      { question: "Can you coordinate with Ganga Aarti timings?", answer: "Yes, the evening Ganga Aarti at Har Ki Pauri is around 6-7 PM. We time the transfer to ensure you reach in time." },
      { question: "Can I continue to Rishikesh?", answer: "Rishikesh is just 20 km from Haridwar. We can include both cities in your transfer." },
      { question: "Is this available during Kumbh Mela?", answer: "Yes, but advance booking is essential during Kumbh and major festival periods." },
      { question: "Can you drop me at a specific ghat?", answer: "Yes, we drop you at Har Ki Pauri, your hotel, ashram, or any ghat in Haridwar." },
    ],
    relatedRoutes: ["dehradun-airport-to-rishikesh-taxi", "dehradun-airport-to-mussoorie-taxi", "delhi-airport-to-haridwar-taxi"],
  },

  "dehradun-airport-to-rishikesh-taxi": {
    slug: "dehradun-airport-to-rishikesh-taxi",
    airport: "Jolly Grant Airport Dehradun",
    airportCode: "DED",
    airportCity: "Dehradun",
    terminals: [
      { name: "Main Terminal", type: "Domestic", airlines: "IndiGo, Air India, SpiceJet, Vistara", pickup: "Arrival exit, taxi pickup area", driveTime: "30-45 min to Rishikesh" },
    ],
    destination: "Rishikesh",
    destinationState: "Uttarakhand",
    distance: "45 km",
    time: "30-45 minutes",
    highway: "NH7 direct route",
    fares: {
      sedan: { price: "1,200", vehicle: "Swift Dzire / Amaze", seats: 4 },
      suv: { price: "1,800", vehicle: "Innova / Ertiga", seats: 6 },
      tempo: { price: "3,500", vehicle: "Tempo Traveller 12-seater", seats: 12 },
    },
    meetAndGreet: true,
    flightTracking: true,
    pickupPoints: ["Arrival Exit", "Airport Main Gate", "Taxi Pickup Zone"],
    highlights: ["Flight tracking included", "Meet & greet at arrival", "Fixed fare, no surge", "Quick 30-min transfer", "Direct to ashram/hotel"],
    destinationAttractions: ["Laxman Jhula", "Ram Jhula", "Triveni Ghat", "Beatles Ashram", "White Water Rafting", "Yoga Ashrams"],
    description: [
      "Flying into Dehradun for Rishikesh? Jolly Grant Airport is the closest airport to the Yoga Capital, and our taxi service gets you there in just 30-45 minutes. Perfect for international yoga students, adventure seekers, and spiritual travellers.",
      "The 45 km drive is straightforward and scenic, following the path towards the Ganga. We can drop you at Laxman Jhula, Ram Jhula, Tapovan, Neelkanth Road, or any ashram or resort in Rishikesh. The transfer is quick and comfortable.",
      "At Rs 1,200 for a sedan, this is the easiest airport transfer to Rishikesh. No need to negotiate with local taxi drivers at the small Jolly Grant Airport. Your driver is waiting with your name, flight tracked, vehicle ready.",
    ],
    faqs: [
      { question: "How much is a taxi from Dehradun Airport to Rishikesh?", answer: "Sedan Rs 1,200, SUV Rs 1,800, Tempo Traveller Rs 3,500. Fixed fare, no hidden charges." },
      { question: "How long does it take?", answer: "Just 30-45 minutes. This is the fastest airport transfer to Rishikesh." },
      { question: "Can you drop me at a specific ashram?", answer: "Yes, we drop you at Parmarth Niketan, Sivananda Ashram, Beatles Ashram, or any location in Rishikesh." },
      { question: "Is this popular with international visitors?", answer: "Very popular. Many international yoga students and backpackers use this service for a hassle-free airport transfer." },
      { question: "Can I book rafting or activities through you?", answer: "We focus on transportation, but can recommend trusted local activity providers for rafting, bungee jumping, etc." },
      { question: "What about return transfers?", answer: "Yes, we offer airport drop from Rishikesh timed to your departure flight." },
    ],
    relatedRoutes: ["dehradun-airport-to-haridwar-taxi", "dehradun-airport-to-mussoorie-taxi", "delhi-airport-to-rishikesh-taxi"],
  },

  // === SRINAGAR AIRPORT ROUTES ===

  "srinagar-airport-to-gulmarg-taxi": {
    slug: "srinagar-airport-to-gulmarg-taxi",
    airport: "Sheikh ul-Alam International Airport Srinagar",
    airportCode: "SXR",
    airportCity: "Srinagar",
    terminals: [
      { name: "Main Terminal", type: "Domestic + International", airlines: "IndiGo, Air India, SpiceJet, Vistara, GoFirst", pickup: "Arrival hall exit, taxi pickup zone", driveTime: "1.5-2 hrs to Gulmarg" },
    ],
    destination: "Gulmarg",
    destinationState: "Jammu & Kashmir",
    distance: "50 km",
    time: "1.5-2 hours",
    highway: "Srinagar-Tangmarg Road",
    fares: {
      sedan: { price: "2,500", vehicle: "Swift Dzire / Amaze", seats: 4 },
      suv: { price: "3,500", vehicle: "Innova / Ertiga", seats: 6 },
      tempo: { price: "6,500", vehicle: "Tempo Traveller 12-seater", seats: 12 },
    },
    meetAndGreet: true,
    flightTracking: true,
    pickupPoints: ["Arrival Hall Exit", "Airport Main Gate", "Designated Taxi Zone"],
    highlights: ["Flight tracking included", "Meet & greet at arrival", "Fixed fare, no surge", "Scenic Kashmir drive", "Gondola ride coordination"],
    destinationAttractions: ["Gulmarg Gondola", "Apharwat Peak", "Gulmarg Golf Course", "Strawberry Valley", "Khilanmarg", "Skiing (winter)"],
    description: [
      "Flying into Srinagar for the ski paradise of Gulmarg? Our Srinagar Airport to Gulmarg taxi service provides a comfortable transfer through the stunning Kashmir Valley. The 50 km mountain drive takes just 1.5 to 2 hours.",
      "The drive from Srinagar Airport climbs through Tangmarg towards Gulmarg, with breathtaking views of snow-capped mountains, rice paddies, and charming Kashmiri villages. In winter, the road becomes a winter wonderland; in summer, it is carpeted with wildflowers.",
      "At Rs 2,500 for a sedan, our fixed fare transfer beats the inflated rates at the airport taxi counter. Our drivers are local Kashmiris who know the mountain roads perfectly and can recommend the best activities in Gulmarg based on the season.",
    ],
    faqs: [
      { question: "How much is a taxi from Srinagar Airport to Gulmarg?", answer: "Sedan Rs 2,500, SUV Rs 3,500, Tempo Traveller Rs 6,500. Fixed fare with all charges included." },
      { question: "How long is the drive?", answer: "1.5 to 2 hours from the airport. The road climbs gradually through beautiful scenery." },
      { question: "Is the road open in winter?", answer: "Yes, the Srinagar-Gulmarg road is maintained year-round. In heavy snowfall, chains may be needed -- our vehicles are equipped." },
      { question: "Should I book an SUV in winter?", answer: "Yes, SUVs are recommended during winter months for better traction on snowy roads. They also handle the luggage better." },
      { question: "Can I visit Srinagar on the way?", answer: "The airport is in Srinagar. We can arrange a brief city visit before heading to Gulmarg, or a separate Srinagar sightseeing tour." },
      { question: "Can I book a Gulmarg to Srinagar Airport transfer?", answer: "Yes, return transfers are available timed to your departure flight." },
    ],
    relatedRoutes: ["srinagar-airport-to-pahalgam-taxi"],
  },

  "srinagar-airport-to-pahalgam-taxi": {
    slug: "srinagar-airport-to-pahalgam-taxi",
    airport: "Sheikh ul-Alam International Airport Srinagar",
    airportCode: "SXR",
    airportCity: "Srinagar",
    terminals: [
      { name: "Main Terminal", type: "Domestic + International", airlines: "IndiGo, Air India, SpiceJet, Vistara, GoFirst", pickup: "Arrival hall exit, taxi pickup zone", driveTime: "2.5-3 hrs to Pahalgam" },
    ],
    destination: "Pahalgam",
    destinationState: "Jammu & Kashmir",
    distance: "95 km",
    time: "2.5-3 hours",
    highway: "Srinagar-Pahalgam Road via Anantnag",
    fares: {
      sedan: { price: "3,500", vehicle: "Swift Dzire / Amaze", seats: 4 },
      suv: { price: "5,000", vehicle: "Innova / Ertiga", seats: 6 },
      tempo: { price: "9,000", vehicle: "Tempo Traveller 12-seater", seats: 12 },
    },
    meetAndGreet: true,
    flightTracking: true,
    pickupPoints: ["Arrival Hall Exit", "Airport Main Gate", "Designated Taxi Zone"],
    highlights: ["Flight tracking included", "Meet & greet at arrival", "Fixed fare, no surge", "Valley of Shepherds route", "Lidder River views"],
    destinationAttractions: ["Betaab Valley", "Aru Valley", "Chandanwari", "Lidder River", "Baisaran", "Amarnath Yatra base"],
    description: [
      "Landing at Srinagar Airport for the Valley of Shepherds? Our Srinagar Airport to Pahalgam taxi service takes you through the heart of the Kashmir Valley to one of India's most beautiful hill stations. The 95 km scenic drive takes 2.5 to 3 hours.",
      "The route passes through the saffron town of Pampore, Awantipora, and Anantnag before climbing into the pine-forested valley of Pahalgam along the Lidder River. The scenery transforms from flat rice paddies to towering Himalayan peaks.",
      "At Rs 3,500 for a sedan, this is the most reliable transfer to Pahalgam. Popular with Amarnath Yatra pilgrims, Bollywood fans visiting Betaab Valley, and nature lovers seeking the pristine beauty of Kashmir. Our local Kashmiri drivers know the best routes and can suggest off-beat stops.",
    ],
    faqs: [
      { question: "How much is a taxi from Srinagar Airport to Pahalgam?", answer: "Sedan Rs 3,500, SUV Rs 5,000, Tempo Traveller Rs 9,000. All charges included." },
      { question: "How long is the drive?", answer: "2.5 to 3 hours through the beautiful Kashmir Valley. The drive itself is a scenic experience." },
      { question: "Is this route safe?", answer: "Yes, the Srinagar-Pahalgam route is a well-travelled tourist corridor. Our drivers are local and know the area well." },
      { question: "Can I visit Betaab Valley on arrival day?", answer: "If you arrive by afternoon, we can include a Betaab Valley visit on the way. It is near Pahalgam." },
      { question: "Is this the route for Amarnath Yatra?", answer: "Yes, Pahalgam is one of the base camps for Amarnath Yatra. We provide pilgrim transfers during the yatra season." },
      { question: "Can I book a Kashmir package?", answer: "Yes, we offer Srinagar-Gulmarg-Pahalgam-Sonmarg packages. Ask about our multi-day Kashmir tour transfers." },
    ],
    relatedRoutes: ["srinagar-airport-to-gulmarg-taxi"],
  },

  // === AMRITSAR AIRPORT ROUTES ===

  "amritsar-airport-to-city-taxi": {
    slug: "amritsar-airport-to-city-taxi",
    airport: "Sri Guru Ram Dass Jee International Airport",
    airportCode: "ATQ",
    airportCity: "Amritsar",
    terminals: [
      { name: "Main Terminal", type: "Domestic + International", airlines: "IndiGo, Air India, SpiceJet, Vistara, GoFirst, International flights", pickup: "Arrival hall exit, taxi pickup area", driveTime: "20-30 min to city" },
    ],
    destination: "Amritsar City",
    destinationState: "Punjab",
    distance: "12 km",
    time: "20-30 minutes",
    highway: "Airport Road to GT Road",
    fares: {
      sedan: { price: "800", vehicle: "Swift Dzire / Amaze", seats: 4 },
      suv: { price: "1,200", vehicle: "Innova / Ertiga", seats: 6 },
      tempo: { price: "2,500", vehicle: "Tempo Traveller 12-seater", seats: 12 },
    },
    meetAndGreet: true,
    flightTracking: true,
    pickupPoints: ["Arrival Hall Exit", "Airport Main Gate", "International Arrival Exit"],
    highlights: ["Flight tracking included", "Meet & greet at arrival", "Fixed fare, no surge", "Golden Temple direct drop", "NRI-friendly service"],
    destinationAttractions: ["Golden Temple", "Jallianwala Bagh", "Wagah Border", "Partition Museum", "Hall Bazaar", "Gobindgarh Fort"],
    description: [
      "Landing at Amritsar Airport and heading to the Golden Temple? Our airport to city taxi service provides a quick, reliable transfer. The 12 km drive takes just 20-30 minutes, getting you to your destination without any airport taxi hassle.",
      "Sri Guru Ram Dass Jee International Airport serves both domestic and international flights, including flights from UK, Canada, and Middle East. Our NRI-friendly drivers speak English and Punjabi, and can help you navigate the city for your first visit.",
      "At just Rs 800 for a sedan, our fixed fare is unbeatable. We drop you at the Golden Temple, your hotel, bus stand, railway station, or anywhere in Amritsar city. No meter tampering, no overcharging, just reliable fixed-fare service. Popular with NRI families and international Sikh pilgrims.",
    ],
    faqs: [
      { question: "How much is a taxi from Amritsar Airport to Golden Temple?", answer: "Sedan Rs 800, SUV Rs 1,200, Tempo Traveller Rs 2,500. Fixed fare to any city location including Golden Temple." },
      { question: "How long does it take?", answer: "Just 20-30 minutes from the airport to the city center or Golden Temple." },
      { question: "Do you serve international flights?", answer: "Yes, we serve all flights including international arrivals from UK, Canada, Dubai, etc. Our service is NRI-friendly." },
      { question: "Can you take me to Wagah Border?", answer: "Wagah Border is 30 km from the airport. We offer a separate Wagah Border transfer for Rs 1,500 (sedan)." },
      { question: "Is the driver English-speaking?", answer: "Yes, our drivers speak English and Punjabi. They can also assist with basic Hindi translation." },
      { question: "Can I book a city tour?", answer: "Yes, we offer Amritsar city tour packages covering Golden Temple, Jallianwala Bagh, Wagah Border, and local food spots." },
    ],
    relatedRoutes: ["delhi-airport-to-amritsar-taxi"],
  },
};

/**
 * Get all routes from a specific airport
 */
export function getRoutesByAirport(airportCity) {
  return Object.values(airportRoutes).filter(
    (route) => route.airportCity.toLowerCase() === airportCity.toLowerCase()
  );
}

/**
 * Get related route data for internal linking
 */
export function getRelatedRoutes(slug) {
  const route = airportRoutes[slug];
  if (!route || !route.relatedRoutes) return [];
  return route.relatedRoutes
    .filter((relSlug) => airportRoutes[relSlug])
    .map((relSlug) => ({
      slug: relSlug,
      airport: airportRoutes[relSlug].airport,
      destination: airportRoutes[relSlug].destination,
      price: airportRoutes[relSlug].fares.sedan.price,
      time: airportRoutes[relSlug].time,
    }));
}

/**
 * Get all route slugs for static params
 */
export function getAllAirportRouteSlugs() {
  return Object.keys(airportRoutes);
}
