export const familyTripData = {
  "shimla": {
    slug: "family-trip-shimla-from-delhi",
    destination: "Shimla",
    tagline: "The Queen of Hills Awaits Your Family",
    distance: "350 km",
    duration: "3-4 Days",
    bestSeason: "March to June, October to December",
    altitude: "2,276 m",
    familySize: "4-6 members",
    vehicle: {
      name: "Toyota Innova Crysta",
      type: "SUV",
      seats: 7,
      features: ["Spacious boot for family luggage", "Rear AC vents for kids", "Comfortable captain seats", "Smooth hill drive capability"],
    },
    price: { sedan: 8500, suv: 11500, tempo: 16000 },
    packageIncludes: ["Delhi to Shimla round trip by AC cab", "Experienced hill driver", "All toll and parking charges", "Local sightseeing in Shimla", "Driver night allowance"],
    kidFriendlyActivities: [
      { name: "Toy Train Ride (Kalka-Shimla)", description: "UNESCO heritage railway through 102 tunnels and 800+ bridges. Kids absolutely love this scenic 5-hour journey." },
      { name: "Jakhu Temple & Monkey Point", description: "Short trek to the famous Hanuman statue at 2,455m. Kids enjoy spotting langur monkeys along the trail." },
      { name: "Ice Skating at Shimla Rink", description: "Asia's only natural open-air ice skating rink (seasonal, Dec-Feb). Fun for the whole family." },
      { name: "Kufri Adventure Park", description: "Pony rides, yak rides, and snow activities. Perfect half-day outing for children of all ages." },
      { name: "The Ridge & Mall Road Walk", description: "Open space for kids to run around, street food, toy shops, and beautiful mountain views." },
    ],
    itinerary: [
      { day: 1, title: "Delhi to Shimla", description: "Early morning departure from Delhi. Drive via Chandigarh-Kalka highway. Stop at Pinjore Gardens for kids to stretch. Arrive Shimla by evening. Check into family hotel. Evening walk on Mall Road." },
      { day: 2, title: "Shimla Local Sightseeing", description: "Visit Jakhu Temple, The Ridge, Christ Church, Scandal Point. Afternoon at Kufri for snow activities and pony rides. Evening shopping on Mall Road for woolens and toys." },
      { day: 3, title: "Naldehra & Mashobra", description: "Drive to Naldehra (22 km) for India's oldest golf course views. Visit Mashobra for apple orchards. Kids enjoy nature walks and picnic spots. Return to Shimla for farewell dinner." },
      { day: 4, title: "Shimla to Delhi", description: "Post breakfast checkout. Optional Toy Train ride from Shimla to Kalka (book in advance). Drive back to Delhi with stop at Haveli restaurant near Murthal for parathas. Reach Delhi by 8-9 PM." },
    ],
    hotelAreas: ["Mall Road (premium, walkable)", "Kufri Road (budget-friendly, scenic)", "Mashobra (quiet, nature retreats)", "Lakkar Bazaar (mid-range, central)"],
    safetyFeatures: [
      "GPS-tracked vehicles with real-time location sharing",
      "Experienced hill drivers with 5+ years mountain driving",
      "Child seat available on request (free)",
      "First-aid kit in every vehicle",
      "24/7 emergency helpline support",
      "Multiple rest stops planned for kids",
    ],
    travelTips: [
      "Book Toy Train tickets 2-3 weeks in advance on IRCTC",
      "Pack warm clothes even in summer - Shimla evenings are cold",
      "Carry motion sickness medicine for kids on hill roads",
      "Best time: May-June for summer escape, Dec-Jan for snow",
      "Keep snacks and water handy for the 7-8 hour drive",
    ],
    faqs: [
      { question: "How much does a family trip to Shimla from Delhi by car cost?", answer: "A family trip to Shimla from Delhi costs Rs 8,500 for a sedan (4 pax), Rs 11,500 for an Innova Crysta (6 pax), and Rs 16,000 for a Tempo Traveller (10+ pax). This includes round trip, toll, parking, and driver charges for 3-4 days." },
      { question: "Is Shimla safe for families with small children?", answer: "Absolutely! Shimla is one of the safest hill stations in India for families. The roads are well-maintained, hotels are family-friendly, and the weather is pleasant. We provide child seats on request and plan extra rest stops for families with young kids." },
      { question: "How long does it take to drive from Delhi to Shimla?", answer: "Delhi to Shimla takes approximately 7-8 hours via NH-44 through Chandigarh and Kalka. The distance is about 350 km. We recommend an early 5 AM start to avoid traffic and reach by afternoon." },
      { question: "What is the best time to visit Shimla with kids?", answer: "May-June is ideal for summer holidays with pleasant weather (15-25 deg C). December-February is perfect for snow experience. Avoid July-September monsoon season as roads can be slippery." },
      { question: "Can we do a Shimla-Manali combo family trip?", answer: "Yes! We offer a 6-7 day Shimla-Manali combo package. Shimla (2 nights) + Manali (3 nights) is perfect for families. The drive from Shimla to Manali is scenic but long (250 km, 7-8 hours), so we plan an overnight stop at Kullu." },
      { question: "Do you provide baby car seats for Shimla trips?", answer: "Yes, we provide baby car seats and booster seats free of charge on request. Please mention the child age when booking so we can arrange the appropriate seat. Safety of your little ones is our priority." },
    ],
  },
  "manali": {
    slug: "family-trip-manali-from-delhi",
    destination: "Manali",
    tagline: "Snow, Adventure & Mountain Magic for Your Family",
    distance: "540 km",
    duration: "4-5 Days",
    bestSeason: "April to June, October to December",
    altitude: "2,050 m",
    familySize: "4-6 members",
    vehicle: {
      name: "Toyota Innova Crysta",
      type: "SUV",
      seats: 7,
      features: ["Powerful engine for mountain terrain", "Spacious for family luggage", "Rear AC for comfortable hill travel", "High ground clearance for hill roads"],
    },
    price: { sedan: 11000, suv: 14500, tempo: 20000 },
    packageIncludes: ["Delhi to Manali round trip by AC cab", "Experienced hill driver", "All toll and parking charges", "Local Manali and Solang Valley sightseeing", "Driver night allowance", "Rohtang Pass permit assistance"],
    kidFriendlyActivities: [
      { name: "Solang Valley Snow Activities", description: "Skiing, snowboarding, snow tubing, and building snowmen. Open year-round with snow from November to April." },
      { name: "Hadimba Temple & Forest Walk", description: "Ancient wooden temple surrounded by deodar forests. Kids love the open spaces and occasional snow." },
      { name: "Vashisht Hot Springs", description: "Natural hot water springs perfect for a fun family dip. Kids are fascinated by naturally warm water." },
      { name: "Old Manali Market Walk", description: "Quirky cafes, toy shops, and street food. Kids enjoy the vibrant atmosphere and river views." },
      { name: "River Rafting (Age 8+)", description: "Gentle Grade 2 rapids on Beas River suitable for families. Exciting yet safe adventure for older kids." },
    ],
    itinerary: [
      { day: 1, title: "Delhi to Manali", description: "Early 4 AM departure from Delhi. Drive via Chandigarh, Mandi, Kullu. Stop at Murthal for breakfast, Bilaspur for lunch. Arrive Manali by evening (12-14 hours). Check into hotel and rest." },
      { day: 2, title: "Solang Valley & Rohtang", description: "Drive to Solang Valley for snow activities, paragliding views, and ropeway ride. If Rohtang Pass is open (June-Oct), visit the snow point. Return for evening walk at Mall Road." },
      { day: 3, title: "Manali Local Sightseeing", description: "Visit Hadimba Temple, Manu Temple, Vashisht Hot Springs, Tibetan Monastery. Afternoon at Club House for indoor games and bowling. Evening shopping at Old Manali." },
      { day: 4, title: "Kullu & Naggar", description: "Drive to Kullu for river rafting (optional). Visit Naggar Castle and Roerich Art Gallery. Apple orchard visit if in season. Return to Manali for farewell dinner." },
      { day: 5, title: "Manali to Delhi", description: "Post breakfast checkout. Drive back to Delhi with scenic stops at Pandoh Dam and Sundernagar Lake. Reach Delhi by 10-11 PM." },
    ],
    hotelAreas: ["Mall Road (central, walkable)", "Old Manali (scenic, riverside)", "Log Huts Area (quiet, government area)", "Solang Road (close to snow activities)"],
    safetyFeatures: [
      "GPS-tracked vehicles with real-time sharing",
      "Experienced hill drivers with 8+ years Manali route",
      "Child seat available on request (free)",
      "First-aid kit and oxygen cylinder in vehicle",
      "24/7 emergency helpline",
      "Night halt at Chandigarh option for families with toddlers",
    ],
    travelTips: [
      "Start very early (4-5 AM) to reach Manali before dark",
      "Book Rohtang Pass permits online at least 1 day in advance",
      "Carry warm jackets even in summer - Manali nights are cold",
      "Keep motion sickness tablets for kids (curvy roads after Mandi)",
      "Carry snacks, games, and entertainment for the long 12-hour drive",
      "Consider night halt at Chandigarh to split the journey for small kids",
    ],
    faqs: [
      { question: "How much does a family trip to Manali from Delhi cost by car?", answer: "A 4-5 day family trip to Manali from Delhi costs Rs 11,000 for a sedan, Rs 14,500 for an Innova Crysta, and Rs 20,000 for a Tempo Traveller. This includes round trip, toll, parking, and driver allowance." },
      { question: "Is the Delhi to Manali road safe for families?", answer: "Yes, the Delhi-Manali highway (NH-21) is well-maintained. Our experienced hill drivers know every turn. We plan rest stops every 2-3 hours and can arrange a night halt at Chandigarh for families with small children." },
      { question: "How long is the Delhi to Manali drive?", answer: "Delhi to Manali is approximately 540 km and takes 12-14 hours by car. We recommend starting at 4-5 AM to reach by evening. Alternatively, families can break the journey with an overnight stop at Chandigarh." },
      { question: "What should we pack for a Manali family trip?", answer: "Pack warm clothes (even in summer), comfortable walking shoes, rain jackets, sunscreen, motion sickness medicine for kids, snacks for the drive, and camera. We provide a packing checklist when you book." },
      { question: "Can we visit Rohtang Pass with kids?", answer: "Yes, Rohtang Pass is open June to October. Children above 3 years can visit. We recommend warm clothes, sunglasses, and keeping the visit to 1-2 hours as altitude (3,978m) may cause mild discomfort. Solang Valley is a better alternative for toddlers." },
      { question: "Is river rafting in Kullu safe for kids?", answer: "River rafting in Kullu is available for children aged 8 and above. Grade 2 rapids are gentle and safe with professional guides and life jackets. For younger kids, we recommend the zipline at Solang Valley instead." },
    ],
  },
  "jaipur": {
    slug: "family-trip-jaipur-from-delhi",
    destination: "Jaipur",
    tagline: "The Pink City Royal Adventure for Families",
    distance: "280 km",
    duration: "2-3 Days",
    bestSeason: "October to March",
    altitude: "431 m",
    familySize: "4-6 members",
    vehicle: {
      name: "Toyota Innova Crysta",
      type: "SUV",
      seats: 7,
      features: ["Spacious for family with luggage", "Comfortable highway cruiser", "Rear AC for kids", "Easy entry/exit for elderly family members"],
    },
    price: { sedan: 5500, suv: 7500, tempo: 12000 },
    packageIncludes: ["Delhi to Jaipur round trip by AC cab", "All toll and parking charges", "Full Jaipur local sightseeing", "Amber Fort, City Palace, Hawa Mahal", "Driver allowance"],
    kidFriendlyActivities: [
      { name: "Elephant Ride at Amber Fort", description: "Ride up to the majestic Amber Fort on an elephant. An unforgettable experience for kids and adults alike." },
      { name: "Nahargarh Fort Sunset View", description: "Drive up to Nahargarh for panoramic Jaipur views. Kids love the fort tunnels and the sunset is magical." },
      { name: "Chokhi Dhani Village Resort", description: "Traditional Rajasthani village experience with puppet shows, magic, camel rides, and authentic thali dinner." },
      { name: "Jaipur Zoo & Birla Mandir", description: "Jaipur Zoo has crocodiles, deer, and birds. Birla Mandir is a stunning white marble temple kids love." },
      { name: "Albert Hall Museum", description: "Egypt mummy, dinosaur fossils, and royal artifacts keep kids fascinated for hours. Beautiful at night with lighting." },
    ],
    itinerary: [
      { day: 1, title: "Delhi to Jaipur", description: "Morning departure from Delhi (6-7 AM). Drive via NH-48 expressway (4-5 hours). Stop at Neemrana Fort for breakfast. Arrive Jaipur by noon. Visit Amber Fort with elephant ride. Evening at Chokhi Dhani." },
      { day: 2, title: "Jaipur City Tour", description: "Visit City Palace, Hawa Mahal, Jantar Mantar (kids love the giant sundial). Lunch at a rooftop restaurant. Afternoon at Albert Hall Museum. Evening shopping at Johari Bazaar for bangles and souvenirs." },
      { day: 3, title: "Jaipur to Delhi", description: "Morning visit to Nahargarh Fort for views. Drive to Jal Mahal for photos. Depart for Delhi post lunch. Optional stop at Kingdom of Dreams, Gurgaon. Reach Delhi by 7-8 PM." },
    ],
    hotelAreas: ["MI Road (central, premium)", "Amer Road (near Amber Fort)", "C-Scheme (modern, restaurants)", "Bani Park (budget-friendly, quiet)"],
    safetyFeatures: [
      "GPS-tracked vehicles",
      "Experienced Delhi-Jaipur highway drivers",
      "Child seat available on request",
      "First-aid kit in every vehicle",
      "24/7 emergency helpline",
      "Expressway driving only (safer, faster)",
    ],
    travelTips: [
      "Visit Amber Fort early morning to avoid crowds and heat",
      "Book Chokhi Dhani in advance for weekends",
      "Carry sunscreen and hats - Jaipur gets hot even in winter afternoons",
      "Best months: October-February for pleasant weather",
      "Try the famous Dal Baati Churma and Pyaaz Kachori with kids",
    ],
    faqs: [
      { question: "How much does a Jaipur family trip from Delhi cost?", answer: "A 2-3 day family trip to Jaipur from Delhi costs Rs 5,500 for a sedan, Rs 7,500 for an Innova, and Rs 12,000 for a Tempo Traveller. This covers round trip, toll, parking, local sightseeing, and driver allowance." },
      { question: "How long does Delhi to Jaipur take by car?", answer: "Delhi to Jaipur takes 4-5 hours via NH-48 expressway (280 km). The road is excellent with 6 lanes most of the way. We recommend leaving by 6-7 AM to reach by noon." },
      { question: "Is Jaipur good for a family trip with toddlers?", answer: "Yes! Jaipur is very toddler-friendly. The forts have ramps, restaurants are family-oriented, and attractions like Chokhi Dhani are designed for all ages. We provide child seats and plan the itinerary with rest breaks." },
      { question: "What is the best time to visit Jaipur with family?", answer: "October to March is ideal with pleasant weather (15-25 deg C). Avoid April-June when temperatures exceed 40 deg C. The Jaipur Literature Festival in January is a bonus cultural experience." },
      { question: "Can we do a Jaipur-Pushkar combo trip?", answer: "Yes! Add 1 day for Pushkar (145 km from Jaipur). Visit the Brahma Temple, camel fair grounds, and Pushkar Lake. Extra cost: Rs 2,000-3,000 depending on vehicle. Great for families who want a spiritual experience." },
      { question: "Are there good vegetarian restaurants in Jaipur for kids?", answer: "Jaipur is a vegetarian paradise! Try LMB (Laxmi Mishthan Bhandar) on Johari Bazaar, Rawat Mishthan for kachori, and Suvarna Mahal for royal dining. Most restaurants serve kid-friendly North Indian food." },
    ],
  },
  "nainital": {
    slug: "family-trip-nainital-from-delhi",
    destination: "Nainital",
    tagline: "Lakeside Bliss for the Whole Family",
    distance: "300 km",
    duration: "3-4 Days",
    bestSeason: "March to June, September to November",
    altitude: "1,938 m",
    familySize: "4-6 members",
    vehicle: {
      name: "Toyota Innova Crysta",
      type: "SUV",
      seats: 7,
      features: ["Comfortable for hill roads", "Spacious boot for family gear", "Rear AC for kids", "Smooth suspension for mountain curves"],
    },
    price: { sedan: 7500, suv: 10000, tempo: 15000 },
    packageIncludes: ["Delhi to Nainital round trip by AC cab", "Experienced hill driver", "All toll and parking charges", "Naini Lake, Zoo, cable car sightseeing", "Driver night allowance"],
    kidFriendlyActivities: [
      { name: "Naini Lake Boating", description: "Pedal boats, row boats, and shikara rides on the iconic crescent-shaped lake. Kids love feeding the fish." },
      { name: "Nainital Zoo", description: "Home to Himalayan black bears, snow leopards, Tibetan wolves, and colorful pheasants. Compact and kid-friendly." },
      { name: "Snow View Point Cable Car", description: "Aerial ropeway to Snow View Point (2,270m) with panoramic Himalayan views. Thrilling ride for kids." },
      { name: "Eco Cave Garden", description: "Natural rock caves shaped like animals (bat cave, tiger cave). Kids crawl through narrow passages - great adventure!" },
      { name: "Bhimtal & Sattal Lakes", description: "Quieter lakes near Nainital with butterfly museum, aquarium, and kayaking options for families." },
    ],
    itinerary: [
      { day: 1, title: "Delhi to Nainital", description: "Early morning departure (5 AM). Drive via Moradabad-Haldwani route (6-7 hours). Stop at Rampur for breakfast. Arrive Nainital by afternoon. Evening boating on Naini Lake and Mall Road walk." },
      { day: 2, title: "Nainital Sightseeing", description: "Morning cable car ride to Snow View Point. Visit Nainital Zoo and Eco Cave Garden. Afternoon at Tiffin Top for views. Evening horse riding on Flats area. Night walk on Mall Road." },
      { day: 3, title: "Bhimtal & Sattal Excursion", description: "Drive to Bhimtal (22 km) for boating and aquarium. Visit Sattal for bird watching and butterfly museum. Lunch at lakeside restaurant. Return to Nainital for last evening shopping." },
      { day: 4, title: "Nainital to Delhi", description: "Post breakfast checkout. Optional visit to Hanumangarhi temple for sunrise views. Drive back to Delhi via Haldwani. Stop at Corbett Waterfall en route. Reach Delhi by 6-7 PM." },
    ],
    hotelAreas: ["Mall Road (lakeside, premium)", "Tallital (budget, lake end)", "Mallital (temple side, mid-range)", "Bhowali (quiet, apple orchards)"],
    safetyFeatures: [
      "GPS-tracked vehicles",
      "Experienced Kumaon hill drivers",
      "Child seat available on request",
      "First-aid kit in every vehicle",
      "24/7 emergency helpline",
      "Pre-planned rest stops every 2 hours",
    ],
    travelTips: [
      "Book hotels near Mall Road for easy lake access",
      "Carry warm clothes - Nainital is cool even in summer",
      "Visit zoo early morning when animals are active",
      "Best season: March-June for pleasant weather, Oct-Nov for clear Himalayan views",
      "Try the famous Bal Mithai sweet from Nainital",
    ],
    faqs: [
      { question: "What is the cost of a Nainital family trip from Delhi?", answer: "A 3-4 day family trip to Nainital from Delhi costs Rs 7,500 for a sedan, Rs 10,000 for an Innova Crysta, and Rs 15,000 for a Tempo Traveller. Includes round trip, toll, parking, and driver allowance." },
      { question: "How far is Nainital from Delhi by car?", answer: "Nainital is approximately 300 km from Delhi, taking 6-7 hours via Moradabad-Haldwani route. The road is good except for the last 30 km of hill driving." },
      { question: "Is Nainital suitable for families with young children?", answer: "Nainital is one of the best hill stations for families with young children. Boating, zoo, cable car, and Eco Cave Garden are all kid-friendly. The town is compact and walkable around the lake." },
      { question: "When is the best time to visit Nainital?", answer: "March to June for pleasant weather (10-27 deg C), September to November for clear mountain views. Avoid monsoon (July-August) as the area receives heavy rainfall and landslides are possible." },
      { question: "Can we combine Nainital and Jim Corbett?", answer: "Yes! Jim Corbett National Park is just 65 km from Nainital. Add 1-2 days for a jungle safari. We offer a combo package for Nainital (2 nights) + Corbett (1 night) at discounted rates." },
      { question: "Is boating safe for kids in Naini Lake?", answer: "Yes, boating on Naini Lake is very safe. Life jackets are provided for everyone. Pedal boats are best for families with small kids. The lake is calm with no currents. Boating hours: 6 AM to 6 PM." },
    ],
  },
  "mussoorie": {
    slug: "family-trip-mussoorie-from-delhi",
    destination: "Mussoorie",
    tagline: "Queen of Hills - Perfect Family Mountain Getaway",
    distance: "290 km",
    duration: "2-3 Days",
    bestSeason: "March to June, September to November",
    altitude: "2,005 m",
    familySize: "4-6 members",
    vehicle: {
      name: "Toyota Innova Crysta",
      type: "SUV",
      seats: 7,
      features: ["Strong engine for Mussoorie hills", "Spacious family cabin", "AC for comfortable travel", "Easy hill maneuverability"],
    },
    price: { sedan: 6500, suv: 9000, tempo: 13000 },
    packageIncludes: ["Delhi to Mussoorie round trip by AC cab", "Hill-experienced driver", "All toll and parking charges", "Kempty Falls, Gun Hill sightseeing", "Driver night allowance"],
    kidFriendlyActivities: [
      { name: "Kempty Falls", description: "Stunning 40-feet waterfall with wading pool. Kids love splashing in the natural pool at the base." },
      { name: "Gun Hill Cable Car", description: "Second highest point in Mussoorie with cable car ride and panoramic views. Fun binoculars for kids to spot peaks." },
      { name: "Company Garden", description: "Beautiful garden with mini lake, artificial waterfall, and amusement rides for children." },
      { name: "Lal Tibba Viewpoint", description: "Highest point in Mussoorie with telescope to view Himalayan peaks including Badrinath and Kedarnath." },
      { name: "Adventure Park Mussoorie", description: "Zip-lining, rock climbing, and nature trails. Age-appropriate activities for kids 5 and above." },
    ],
    itinerary: [
      { day: 1, title: "Delhi to Mussoorie", description: "Morning departure from Delhi (5-6 AM). Drive via Meerut-Roorkee-Dehradun (6-7 hours). Stop at Roorkee for breakfast. Arrive Mussoorie by afternoon. Evening stroll on Mall Road and Camel Back Road." },
      { day: 2, title: "Mussoorie Sightseeing", description: "Morning visit to Kempty Falls. Cable car to Gun Hill Point. Afternoon at Company Garden. Drive to Lal Tibba for sunset views. Evening at Mall Road for shopping and street food." },
      { day: 3, title: "Mussoorie to Delhi", description: "Morning visit to Cloud End or George Everest viewpoint. Post breakfast departure. Optional stop at Dehradun for Robber Cave (family-friendly). Reach Delhi by 6-7 PM." },
    ],
    hotelAreas: ["Mall Road (central, lively)", "Library End (quieter, scenic)", "Landour (colonial charm, walks)", "Picture Palace (mid-range, views)"],
    safetyFeatures: [
      "GPS-tracked vehicles",
      "Experienced Dehradun-Mussoorie hill drivers",
      "Child seat available on request",
      "First-aid kit in every vehicle",
      "24/7 emergency helpline",
      "Well-maintained hill route via Dehradun",
    ],
    travelTips: [
      "Visit Kempty Falls on weekdays to avoid crowds",
      "Carry raincoats during monsoon season",
      "Landour is a hidden gem - quieter and more scenic than main Mussoorie",
      "Best time: April-June for summer escape",
      "Try the famous Maggi and chai at Char Dukan, Landour",
    ],
    faqs: [
      { question: "How much does a Mussoorie family trip from Delhi cost?", answer: "A 2-3 day family trip to Mussoorie from Delhi costs Rs 6,500 for a sedan, Rs 9,000 for an Innova, and Rs 13,000 for a Tempo Traveller. Includes round trip, toll, parking, and driver allowance." },
      { question: "How long does it take to reach Mussoorie from Delhi?", answer: "Delhi to Mussoorie takes 6-7 hours by car (290 km) via Meerut, Roorkee, and Dehradun. The last 35 km from Dehradun is a scenic hill drive." },
      { question: "Is Mussoorie better than Shimla for families?", answer: "Both are excellent! Mussoorie is closer to Delhi (290 vs 350 km), less crowded, and has Kempty Falls which kids love. Shimla has the Toy Train and Kufri. For shorter trips, Mussoorie is more convenient." },
      { question: "Can we combine Mussoorie and Rishikesh?", answer: "Yes! Rishikesh is just 75 km from Mussoorie. Add 1 day for Rishikesh to see the Ganga Aarti, Lakshman Jhula, and river beach. Great combo for families wanting both hills and spirituality." },
      { question: "Is Kempty Falls safe for kids?", answer: "Yes, Kempty Falls has a designated safe wading area with shallow water. However, always supervise children closely. The steps can be slippery. Best to carry water shoes for kids." },
      { question: "What should we pack for Mussoorie?", answer: "Pack warm layers (even in summer evenings are cool), comfortable walking shoes, raincoat/umbrella, sunscreen, and camera. For kids, carry snacks, games for the car ride, and motion sickness medicine." },
    ],
  },
  "jim-corbett": {
    slug: "family-trip-jim-corbett-from-delhi",
    destination: "Jim Corbett",
    tagline: "Wild Safari Adventure for the Whole Family",
    distance: "260 km",
    duration: "2-3 Days",
    bestSeason: "November to June",
    altitude: "400-1,200 m",
    familySize: "4-6 members",
    vehicle: {
      name: "Toyota Innova Crysta",
      type: "SUV",
      seats: 7,
      features: ["Perfect for jungle terrain", "High ground clearance", "Spacious for family and safari gear", "AC for comfortable highway travel"],
    },
    price: { sedan: 6000, suv: 8500, tempo: 12000 },
    packageIncludes: ["Delhi to Jim Corbett round trip by AC cab", "Experienced driver", "All toll and parking charges", "Jeep safari permit assistance", "Driver night allowance"],
    kidFriendlyActivities: [
      { name: "Jungle Safari (Jeep)", description: "Spot tigers, elephants, deer, and exotic birds in their natural habitat. Morning safaris are best for wildlife sighting." },
      { name: "Corbett Waterfall", description: "Beautiful waterfall inside the park area with picnic spots. Easy trek suitable for families with kids." },
      { name: "Garjia Devi Temple", description: "Temple on a rock in the middle of Kosi River. Kids enjoy the bridge walk and watching fish in clear water." },
      { name: "Corbett Museum", description: "Learn about Jim Corbett the hunter-turned-conservationist. Interesting artifacts and stories that educate kids about wildlife." },
      { name: "River Crossing & Nature Walk", description: "Guided nature walks along Kosi and Ramganga rivers. Spot crocodiles, turtles, and kingfishers." },
    ],
    itinerary: [
      { day: 1, title: "Delhi to Jim Corbett", description: "Early morning departure (5 AM). Drive via Moradabad-Kashipur route (5-6 hours). Stop at Moradabad for breakfast. Arrive Corbett by noon. Evening visit to Garjia Temple and Corbett Museum." },
      { day: 2, title: "Safari & Exploration", description: "Early morning jeep safari in Bijrani or Jhirna zone (6 AM). Spot tigers, elephants, deer. Afternoon visit to Corbett Waterfall. Evening nature walk along Kosi River. Night stay at jungle resort." },
      { day: 3, title: "Jim Corbett to Delhi", description: "Optional second morning safari. Post breakfast checkout. Visit Sitabani forest zone (no permit needed). Drive back to Delhi. Optional stop at Nainital (65 km) or direct return. Reach Delhi by 5-6 PM." },
    ],
    hotelAreas: ["Dhikuli (outside park, resorts)", "Ramnagar (town, budget)", "Bijrani Gate (close to safari)", "Kyari (riverside, premium)"],
    safetyFeatures: [
      "GPS-tracked vehicles",
      "Experienced Corbett route drivers",
      "Child seat available on request",
      "First-aid kit in every vehicle",
      "24/7 emergency helpline",
      "Safari with trained naturalist guide",
    ],
    travelTips: [
      "Book safari permits online 45 days in advance on corbettonline.uk.gov.in",
      "Bijrani and Jhirna zones are best for families (easier terrain)",
      "Carry binoculars and camera with zoom lens for safari",
      "Wear earthy colors (green, brown, khaki) during safari",
      "Morning safaris (6 AM) have better wildlife sighting probability",
    ],
    faqs: [
      { question: "How much does a Jim Corbett family trip cost from Delhi?", answer: "A 2-3 day family trip to Jim Corbett from Delhi costs Rs 6,000 for a sedan, Rs 8,500 for an Innova, and Rs 12,000 for a Tempo Traveller. Safari jeep charges (Rs 5,500-8,000 per safari) are extra." },
      { question: "Is Jim Corbett safe for kids?", answer: "Yes! Corbett is very safe for families. Safaris are conducted in enclosed jeeps with trained guides. Resorts are fenced and secure. Children of all ages can enjoy the experience." },
      { question: "Which safari zone is best for families?", answer: "Jhirna zone is open year-round and great for families (easier terrain, good wildlife sighting). Bijrani zone is also excellent. Avoid Dhikala for families with very young kids as it requires overnight stay inside the park." },
      { question: "Can we spot a tiger in Jim Corbett?", answer: "Corbett has 230+ tigers, giving good sighting chances. Morning safaris in Bijrani and Dhikala zones have the highest probability. Tiger sighting is never guaranteed, but you will definitely see elephants, deer, peacocks, and various birds." },
      { question: "When is the best time to visit Corbett?", answer: "November to June is the park season. February-May is best for tiger sighting as animals come to water sources. The park is closed July-October for monsoon. Book safaris well in advance for peak season." },
      { question: "How far is Jim Corbett from Nainital?", answer: "Jim Corbett (Ramnagar) is just 65 km from Nainital (1.5 hours). We offer a combo package: Corbett (2 nights) + Nainital (2 nights) which is perfect for families wanting both jungle and hill station experience." },
    ],
  },
  "kashmir": {
    slug: "family-trip-kashmir-from-delhi",
    destination: "Kashmir",
    tagline: "Paradise on Earth - A Dream Family Vacation",
    distance: "Flight + 300 km by road",
    duration: "5-7 Days",
    bestSeason: "April to October",
    altitude: "1,585-3,500 m",
    familySize: "4-6 members",
    vehicle: {
      name: "Toyota Innova Crysta",
      type: "SUV",
      seats: 7,
      features: ["Powerful for Kashmir mountain roads", "Heated seats for cold weather", "Spacious for family luggage", "High ground clearance for Gulmarg roads"],
    },
    price: { sedan: 22000, suv: 28000, tempo: 38000 },
    packageIncludes: ["Delhi to Srinagar cab (if by road via Jammu)", "Complete Kashmir sightseeing by AC cab", "Srinagar-Gulmarg-Pahalgam-Sonmarg circuit", "Experienced local Kashmiri driver", "Driver allowance and fuel", "Toll and parking charges"],
    kidFriendlyActivities: [
      { name: "Shikara Ride on Dal Lake", description: "Iconic Kashmir experience. Kids love the floating market, lotus gardens, and the gentle boat ride on pristine waters." },
      { name: "Gulmarg Gondola Ride", description: "Asia's highest cable car to 4,200m. Snow views year-round. First phase is suitable for all ages, second phase for older kids." },
      { name: "Pony Ride in Pahalgam", description: "Gentle pony ride through Betaab Valley and Aru Valley. Perfect for kids who dream of horse riding in mountains." },
      { name: "Saffron Fields Visit", description: "Visit Pampore saffron fields (October-November). Kids learn about the world's most expensive spice." },
      { name: "Mughal Gardens Stroll", description: "Nishat Bagh, Shalimar Bagh, and Chashme Shahi. Beautifully maintained gardens perfect for family picnics." },
    ],
    itinerary: [
      { day: 1, title: "Arrival in Srinagar", description: "Fly to Srinagar (or drive from Jammu). Check into houseboat on Dal Lake. Evening shikara ride through floating gardens and market. Overnight on houseboat." },
      { day: 2, title: "Srinagar Sightseeing", description: "Visit Mughal Gardens - Nishat Bagh, Shalimar Bagh, Chashme Shahi. Afternoon at Shankaracharya Temple for city views. Evening walk at Boulevard Road along Dal Lake." },
      { day: 3, title: "Gulmarg Day Trip", description: "Drive to Gulmarg (50 km, 2 hrs). Gondola ride Phase 1 and optional Phase 2. Snow activities, skiing (winter). Pony rides on meadows. Return to Srinagar by evening." },
      { day: 4, title: "Pahalgam Excursion", description: "Drive to Pahalgam (95 km, 2.5 hrs). Visit Betaab Valley, Aru Valley, and Chandanwari. Pony rides for kids. Picnic lunch by Lidder River. Return to Srinagar." },
      { day: 5, title: "Sonmarg Day Trip", description: "Drive to Sonmarg (80 km, 2.5 hrs). Visit Thajiwas Glacier, Zero Point (if open). Pony ride to glacier. Stunning meadows and mountain views. Return to Srinagar." },
      { day: 6, title: "Departure", description: "Morning visit to local market for pashmina shopping. Drive to Srinagar Airport or begin road journey to Jammu. Depart with unforgettable memories." },
    ],
    hotelAreas: ["Dal Lake Houseboats (unique experience)", "Boulevard Road (lakeside hotels)", "Nishat Area (garden views)", "Residency Road (city center, shopping)"],
    safetyFeatures: [
      "GPS-tracked vehicles",
      "Local Kashmiri drivers who know every road",
      "Child seat available on request",
      "First-aid kit and oxygen in vehicle",
      "24/7 emergency helpline",
      "Pre-verified safe routes and hotels",
    ],
    travelTips: [
      "Fly to Srinagar for a comfortable family trip (avoid 24-hour road drive)",
      "Book houseboat on Dal Lake for at least 1 night - kids love it",
      "Carry warm clothes even in summer (Gulmarg is always cold)",
      "Try wazwan cuisine but also carry snacks for picky kid eaters",
      "Pahalgam is the most family-friendly destination in Kashmir",
    ],
    faqs: [
      { question: "How much does a Kashmir family trip cost?", answer: "A 5-7 day Kashmir family trip costs Rs 22,000 for a sedan, Rs 28,000 for an Innova Crysta (recommended), and Rs 38,000 for a Tempo Traveller. This covers all Kashmir sightseeing, fuel, toll, and driver charges. Flights to Srinagar are extra." },
      { question: "Is Kashmir safe for family trips?", answer: "Yes, Kashmir is very safe for tourists. Srinagar, Gulmarg, Pahalgam, and Sonmarg are well-guarded tourist zones. Our local drivers know safe routes and accommodations. Thousands of families visit Kashmir safely every year." },
      { question: "Should we fly or drive to Kashmir?", answer: "We strongly recommend flying to Srinagar (2-hour flight from Delhi, Rs 4,000-8,000 per person). Driving takes 24+ hours via Jammu. Once in Srinagar, our cab covers all local sightseeing." },
      { question: "What is the best time to visit Kashmir with kids?", answer: "April to June is ideal with blooming tulips and pleasant weather. September-October offers stunning autumn colors. December-February is magical with snow but very cold for young kids." },
      { question: "Is the Gulmarg Gondola ride safe for children?", answer: "Yes, the Gulmarg Gondola is safe for all ages. Phase 1 (up to 3,050m) is gentle and suitable for young kids. Phase 2 (up to 4,200m) is for older kids and adults. Warm clothes are essential at the top." },
      { question: "Can we stay on a houseboat with kids?", answer: "Absolutely! Houseboat stays are safe and magical for kids. Modern houseboats have attached bathrooms, heating, and room service. Kids love the shikara pickup/drop and the lake experience. Book a deluxe or premium houseboat for family comfort." },
    ],
  },
  "agra": {
    slug: "family-trip-agra-from-delhi",
    destination: "Agra",
    tagline: "Taj Mahal Wonder for Your Little Ones",
    distance: "233 km",
    duration: "1-2 Days",
    bestSeason: "October to March",
    altitude: "171 m",
    familySize: "4-6 members",
    vehicle: {
      name: "Toyota Innova Crysta",
      type: "SUV",
      seats: 7,
      features: ["Comfortable expressway cruiser", "Spacious for family day trip", "Rear AC for kids", "Large boot for strollers and bags"],
    },
    price: { sedan: 4500, suv: 6500, tempo: 10000 },
    packageIncludes: ["Delhi to Agra round trip by AC cab", "Yamuna Expressway toll included", "Taj Mahal, Agra Fort, Baby Taj visit", "All parking charges", "Driver allowance"],
    kidFriendlyActivities: [
      { name: "Taj Mahal Visit", description: "The 7th Wonder of the World! Kids are amazed by the white marble, the echo inside the dome, and the beautiful gardens." },
      { name: "Agra Fort Exploration", description: "Massive red sandstone fort with secret passages and viewpoints. Kids love exploring the palatial rooms and imagining royal life." },
      { name: "Wildlife SOS Elephant Center", description: "Rescued elephant conservation center at Mathura (30 km from Agra). Educational and heartwarming experience for kids." },
      { name: "Mehtab Bagh Sunset", description: "Perfect sunset view of Taj Mahal from across the river. Great for family photos and a peaceful evening." },
      { name: "Agra Bear Rescue Center", description: "Sloth bear rehabilitation center by Wildlife SOS. Kids learn about animal conservation while seeing rescued bears." },
    ],
    itinerary: [
      { day: 1, title: "Delhi to Agra", description: "Early morning departure (5-6 AM). Drive via Yamuna Expressway (3 hours). Visit Taj Mahal (2 hours). Lunch at Peshawri or Pinch of Spice. Visit Agra Fort. Evening at Mehtab Bagh for Taj sunset view." },
      { day: 2, title: "Agra Exploration & Return", description: "Morning visit to Itimad-ud-Daulah (Baby Taj). Optional drive to Wildlife SOS center at Mathura. Return to Delhi via expressway. Reach Delhi by 5-6 PM." },
    ],
    hotelAreas: ["Taj East Gate (Taj view rooms)", "Fatehabad Road (premium hotels)", "Tajganj (budget, walkable to Taj)", "MG Road (city center)"],
    safetyFeatures: [
      "GPS-tracked vehicles",
      "Yamuna Expressway-trained drivers",
      "Child seat available on request",
      "First-aid kit in every vehicle",
      "24/7 emergency helpline",
      "Express route - minimal road risks",
    ],
    travelTips: [
      "Taj Mahal is closed on Fridays - plan accordingly",
      "Reach Taj Mahal by 7 AM for fewer crowds and better photos",
      "Kids under 15 enter Taj Mahal free",
      "Carry water and snacks - food inside Taj complex is limited",
      "Best months: October-March for pleasant weather",
    ],
    faqs: [
      { question: "How much does a family trip to Agra from Delhi cost?", answer: "A 1-2 day family trip to Agra costs Rs 4,500 for a sedan, Rs 6,500 for an Innova, and Rs 10,000 for a Tempo Traveller. Includes round trip via Yamuna Expressway, toll, parking, and driver allowance." },
      { question: "Can we do Agra as a same-day family trip from Delhi?", answer: "Yes! Our same-day Agra tour covers Taj Mahal, Agra Fort, and Baby Taj. Leave Delhi at 5-6 AM, return by 8-9 PM. Ideal for families with limited time. Overnight option adds Mehtab Bagh sunset and Wildlife SOS visit." },
      { question: "Is the Taj Mahal free for children?", answer: "Children under 15 years enter the Taj Mahal completely free. Adult Indian citizens pay Rs 50, and foreign nationals pay Rs 1,100. This makes Agra very budget-friendly for families." },
      { question: "How long does Delhi to Agra take?", answer: "Delhi to Agra takes just 3-3.5 hours via the 6-lane Yamuna Expressway (165 km expressway + 68 km city roads). Early morning is the best time to start." },
      { question: "What food is available in Agra for kids?", answer: "Agra has many family restaurants. Try Pinch of Spice (North Indian, kid menu), Pizza Hut and McDonald at Taj East Gate, and Peshawri at ITC Mughal for a special dinner. Famous local treat: Petha sweet." },
      { question: "Can we combine Agra with Mathura-Vrindavan?", answer: "Yes! Mathura-Vrindavan is just 55 km from Agra. Visit Krishna Janmabhoomi Temple, Banke Bihari Temple, and Wildlife SOS Elephant Center. Add 1 day for a complete experience." },
    ],
  },
  "udaipur": {
    slug: "family-trip-udaipur-from-delhi",
    destination: "Udaipur",
    tagline: "City of Lakes - Royal Family Experience",
    distance: "660 km",
    duration: "4-5 Days",
    bestSeason: "September to March",
    altitude: "598 m",
    familySize: "4-6 members",
    vehicle: {
      name: "Toyota Innova Crysta",
      type: "SUV",
      seats: 7,
      features: ["Comfortable for long highway drive", "Spacious for family luggage", "Rear AC for kids", "Smooth ride on Rajasthan highways"],
    },
    price: { sedan: 13000, suv: 17000, tempo: 24000 },
    packageIncludes: ["Delhi to Udaipur round trip by AC cab", "All toll and parking charges", "Complete Udaipur local sightseeing", "City Palace, Lake Pichola, Fateh Sagar", "Driver night allowance"],
    kidFriendlyActivities: [
      { name: "Lake Pichola Boat Ride", description: "Scenic boat ride to Jag Mandir island palace. Kids love the lake views, island exploration, and spotting the City Palace from water." },
      { name: "City Palace Museum", description: "Massive palace complex with colorful rooms, mirror work, and balconies. Kids enjoy the maze-like corridors and royal artifacts." },
      { name: "Saheliyon ki Bari Garden", description: "Beautiful garden with fountains, marble elephants, and lotus pool. Designed for royal ladies - kids love the water features." },
      { name: "Vintage Car Museum", description: "Collection of classic Rolls Royce, Mercedes, and Cadillac cars from Mewar royalty. Car-crazy kids are thrilled!" },
      { name: "Shilpgram Craft Village", description: "Living craft village with artisan demos, puppet shows, camel rides, and folk performances. Interactive experience for kids." },
    ],
    itinerary: [
      { day: 1, title: "Delhi to Udaipur", description: "Early morning departure (4-5 AM). Drive via Jaipur bypass and Chittorgarh (10-12 hours). Stop at Neemrana or Ajmer for lunch. Arrive Udaipur by evening. Rest at lakeside hotel." },
      { day: 2, title: "Udaipur City Tour", description: "Visit City Palace, Jagdish Temple, Saheliyon ki Bari. Afternoon boat ride on Lake Pichola to Jag Mandir. Evening at Fateh Sagar Lake with street food." },
      { day: 3, title: "Udaipur Exploration", description: "Morning at Vintage Car Museum and Shilpgram Craft Village. Afternoon at Sajjangarh Monsoon Palace for sunset views. Evening cultural show and rooftop dinner with lake view." },
      { day: 4, title: "Excursion Day", description: "Drive to Haldighati (40 km) for Maharana Pratap history. Visit Nathdwara Temple (50 km) for Shrinathji darshan. Return for last evening shopping at Hathi Pol bazaar." },
      { day: 5, title: "Udaipur to Delhi", description: "Post breakfast checkout. Drive back to Delhi with stops at Chittorgarh Fort (optional) or direct drive. Reach Delhi by 8-9 PM." },
    ],
    hotelAreas: ["Lake Pichola (premium, views)", "Fateh Sagar (mid-range, pleasant)", "Ambamata (budget, temple area)", "Shobhagpura (modern, quiet)"],
    safetyFeatures: [
      "GPS-tracked vehicles",
      "Experienced Rajasthan highway drivers",
      "Child seat available on request",
      "First-aid kit in every vehicle",
      "24/7 emergency helpline",
      "Night halt option at Jaipur to split long drive",
    ],
    travelTips: [
      "Split the long drive with an overnight at Jaipur or Chittorgarh",
      "Book a lakeside hotel for the magical Udaipur experience",
      "Visit City Palace early morning to avoid afternoon heat",
      "Best season: October-February for pleasant Rajasthan weather",
      "Try the famous Dal Baati Churma and Gatte ki Sabzi",
    ],
    faqs: [
      { question: "How much does an Udaipur family trip from Delhi cost?", answer: "A 4-5 day family trip to Udaipur costs Rs 13,000 for a sedan, Rs 17,000 for an Innova, and Rs 24,000 for a Tempo Traveller. This covers the round trip (1,320 km), toll, parking, and driver allowance." },
      { question: "How long does Delhi to Udaipur take by car?", answer: "Delhi to Udaipur is approximately 660 km and takes 10-12 hours. We recommend splitting the journey with an overnight at Jaipur (halfway) or starting very early (4 AM)." },
      { question: "Is the long drive to Udaipur suitable for kids?", answer: "The drive is long but we plan it comfortably with multiple stops, snack breaks, and optional night halt at Jaipur. Our Innova Crysta is spacious enough for kids to nap. Carry entertainment for the drive." },
      { question: "What is the best time to visit Udaipur?", answer: "October to March is ideal with pleasant weather (15-25 deg C). September has beautiful monsoon lakes. Avoid April-June when temperatures exceed 40 deg C." },
      { question: "Can we combine Udaipur with Jaipur and Jodhpur?", answer: "Yes! We offer a Rajasthan triangle package: Jaipur (2 nights) + Udaipur (2 nights) + Jodhpur (1 night) in 6-7 days. Perfect for families who want the complete Rajasthan royal experience." },
      { question: "Is Udaipur safe for families?", answer: "Udaipur is one of the safest cities in India for tourists. It is a well-managed tourist destination with helpful locals. The lakeside areas are well-lit and tourist-friendly even at night." },
    ],
  },
  "rishikesh": {
    slug: "family-trip-rishikesh-from-delhi",
    destination: "Rishikesh",
    tagline: "Ganga, Adventure & Spirituality for Families",
    distance: "240 km",
    duration: "2-3 Days",
    bestSeason: "September to June",
    altitude: "372 m",
    familySize: "4-6 members",
    vehicle: {
      name: "Toyota Innova Crysta",
      type: "SUV",
      seats: 7,
      features: ["Comfortable highway cruiser", "Spacious for family", "AC for Delhi heat + hills", "Easy parking at Rishikesh ghats"],
    },
    price: { sedan: 5500, suv: 7500, tempo: 11000 },
    packageIncludes: ["Delhi to Rishikesh round trip by AC cab", "All toll and parking charges", "Ram Jhula, Lakshman Jhula sightseeing", "Ganga Aarti at Triveni Ghat", "Driver allowance"],
    kidFriendlyActivities: [
      { name: "Ganga Aarti at Triveni Ghat", description: "Mesmerizing fire and chanting ceremony at sunset. Kids are captivated by the lights, bells, and spiritual atmosphere." },
      { name: "Beach Time at Shivpuri", description: "Sandy beaches along the Ganga at Shivpuri. Kids can play in shallow waters and build sand castles. Safe and supervised." },
      { name: "Ram Jhula & Lakshman Jhula Walk", description: "Iconic hanging bridges over the Ganga. Exciting walk for kids with views of ashrams and mountains." },
      { name: "Beatles Ashram (Chaurasi Kutia)", description: "Abandoned ashram with graffiti art in the forest. Older kids and teens love the artistic and historic atmosphere." },
      { name: "Gentle River Rafting (Age 8+)", description: "Family-friendly Grade 1-2 rapids suitable for children above 8. Safe with professional guides and quality equipment." },
    ],
    itinerary: [
      { day: 1, title: "Delhi to Rishikesh", description: "Morning departure from Delhi (6 AM). Drive via Meerut-Haridwar route (5-6 hours). Visit Har Ki Pauri ghat in Haridwar en route. Arrive Rishikesh by afternoon. Evening Ganga Aarti at Triveni Ghat." },
      { day: 2, title: "Rishikesh Exploration", description: "Morning walk across Ram Jhula and Lakshman Jhula. Visit Beatles Ashram. Afternoon at Shivpuri beach or optional rafting for older kids. Evening yoga session (family-friendly) at Parmarth Niketan." },
      { day: 3, title: "Rishikesh to Delhi", description: "Morning visit to Neer Garh Waterfall (short trek). Optional river rafting for adventurous families. Post lunch departure. Stop at Haridwar for shopping (Rudraksh, souvenirs). Reach Delhi by 7-8 PM." },
    ],
    hotelAreas: ["Tapovan (yoga retreat area)", "Ram Jhula (spiritual, central)", "Shivpuri (adventure, riverside)", "Laxman Jhula (backpacker, views)"],
    safetyFeatures: [
      "GPS-tracked vehicles",
      "Experienced Delhi-Rishikesh route drivers",
      "Child seat available on request",
      "First-aid kit in every vehicle",
      "24/7 emergency helpline",
      "Life jackets for all water activities",
    ],
    travelTips: [
      "Combine with Haridwar (20 km) for a complete spiritual trip",
      "Evening Ganga Aarti at Triveni Ghat is a must-see",
      "Carry water shoes for river beach activities",
      "Best time: September-November and February-May",
      "Try the pure vegetarian food at Chotiwala restaurant",
    ],
    faqs: [
      { question: "How much does a Rishikesh family trip from Delhi cost?", answer: "A 2-3 day family trip to Rishikesh costs Rs 5,500 for a sedan, Rs 7,500 for an Innova, and Rs 11,000 for a Tempo Traveller. Includes round trip, toll, parking, and driver allowance." },
      { question: "Is Rishikesh safe for families with kids?", answer: "Yes! Rishikesh is very safe. The town is spiritual and peaceful. Supervised beach areas are safe for kids. River rafting has age limits (8+) with professional safety measures. The walking bridges have side railings." },
      { question: "How long does Delhi to Rishikesh take?", answer: "Delhi to Rishikesh takes 5-6 hours by car (240 km) via Meerut and Haridwar. The road is well-maintained NH-58 with expressway sections." },
      { question: "Can kids do river rafting in Rishikesh?", answer: "Children aged 8 and above can do Grade 1-2 rapids (gentle, family-friendly). All participants get life jackets and helmets. Professional guides accompany each raft. For younger kids, the Shivpuri beach area is perfect." },
      { question: "Should we visit Haridwar with Rishikesh?", answer: "Absolutely! Haridwar is just 20 km from Rishikesh. Visit Har Ki Pauri for the grand Ganga Aarti (larger than Rishikesh) and the temples. We include Haridwar in our Rishikesh itinerary." },
      { question: "What is the best time to visit Rishikesh?", answer: "September to November has the best weather and river conditions. February to May is also great. Monsoon (July-August) makes rafting impossible and roads can be affected. Winter (Dec-Jan) is cold but peaceful." },
    ],
  },
};

export const familyTripSlugs = Object.keys(familyTripData);

export function getFamilyTripBySlug(slug) {
  const key = Object.keys(familyTripData).find(k => familyTripData[k].slug === slug);
  return key ? familyTripData[key] : null;
}
