export const foodTourData = {
  "jaipur": {
    city: "Jaipur",
    slug: "jaipur-food-tour",
    famousDish: "Dal Baati Churma",
    duration: "5-6 hours",
    cabFare: "₹1,200",
    bestTime: "October to March",
    description: "Jaipur is the culinary capital of Rajasthan, where royal Rajasthani thalis meet fiery street food. From the legendary Dal Baati Churma to the iconic Pyaaz Kachori at Rawat Mishthan Bhandar, every bite tells a story of desert ingenuity and royal patronage. The Pink City's food scene spans centuries-old sweet shops, bustling chaat corners at Johari Bazaar, and aromatic kebab stalls near Chandpole Gate.",
    famousFoods: [
      { name: "Dal Baati Churma", desc: "Rajasthan's signature dish -- baked wheat balls (baati) served with five-lentil dal and sweet churma. Traditionally cooked in cow-dung fire for smoky flavor. A must-try at any Rajasthani thali restaurant.", price: "₹150-300 per thali", mustTry: true, heat: 1 },
      { name: "Pyaaz Kachori", desc: "Jaipur's most famous street food -- crispy deep-fried pastry stuffed with spiced onion filling. Rawat Mishthan Bhandar on Station Road has been the gold standard since 1955.", price: "₹25-40 per piece", mustTry: true, heat: 2 },
      { name: "Ghewar", desc: "Jaipur's iconic disc-shaped sweet made from flour batter, soaked in sugar syrup and topped with rabri. Seasonal specialty during Teej and Raksha Bandhan festivals. Laxmi Mishthan Bhandar (LMB) is famous for it.", price: "₹100-400 per piece", mustTry: true, heat: 0 },
      { name: "Laal Maas", desc: "Fiery red mutton curry made with mathania chillies -- a Rajput warrior dish. Intensely spicy and rich. Best at Handi Restaurant or Niros.", price: "₹300-500 per dish", mustTry: false, heat: 3 },
      { name: "Mirchi Bada", desc: "Large green chillies stuffed with spiced potato filling, battered and deep-fried. Jodhpur origin but wildly popular in Jaipur. Crispy outside, soft and spicy inside.", price: "₹15-30 per piece", mustTry: false, heat: 2 },
      { name: "Kulfi Faluda", desc: "Dense, creamy frozen milk dessert served with vermicelli noodles, rose syrup, and basil seeds. Pandit Kulfi on MI Road has been serving it since the 1940s.", price: "₹50-100 per serving", mustTry: false, heat: 0 },
      { name: "Raj Kachori", desc: "Giant crispy shell filled with dahi, chutneys, sprouts, and sev. A chaat masterpiece. Best at Laxmi Mishthan Bhandar (LMB) in Johari Bazaar.", price: "₹60-100 per piece", mustTry: false, heat: 1 },
      { name: "Mawa Kachori", desc: "Sweet kachori filled with mawa (reduced milk solids), dry fruits, and cardamom. Deep-fried and dipped in sugar syrup. A Jaipur specialty dessert.", price: "₹30-60 per piece", mustTry: false, heat: 0 },
    ],
    foodTrail: [
      { time: "7:30 AM", stop: "Rawat Mishthan Bhandar, Station Road", food: "Pyaaz Kachori & Chai", desc: "Start with Jaipur's most iconic breakfast. The pyaaz kachori here has been legendary since 1955. Arrive early to avoid the queue.", price: "₹50-80" },
      { time: "9:00 AM", stop: "Johari Bazaar", food: "Raj Kachori & Lassi", desc: "Walk through the jewelry market and stop at LMB for their famous Raj Kachori. Follow it with a thick, creamy Jaipur lassi.", price: "₹100-150" },
      { time: "10:30 AM", stop: "Pandit Kulfi, MI Road", food: "Kulfi Faluda", desc: "A 70-year-old institution serving the creamiest kulfi in Rajasthan. The matka kulfi with faluda is unforgettable.", price: "₹80-120" },
      { time: "12:30 PM", stop: "Handi Restaurant, MI Road", food: "Dal Baati Churma & Laal Maas", desc: "Sit-down lunch at this iconic restaurant. The Rajasthani thali is a feast of 15+ items. Non-veg lovers must try the Laal Maas.", price: "₹300-600" },
      { time: "3:00 PM", stop: "Samrat Restaurant / Santosh Bhojnalaya", food: "Mirchi Bada & Samosa", desc: "Afternoon snack stop for crispy mirchi bada and Jaipur-style samosas with green chutney.", price: "₹40-80" },
      { time: "5:00 PM", stop: "Chandpole Gate Area", food: "Chaat & Golgappe", desc: "Evening chaat crawl in the old city. Dahi bhalle, aloo tikki, and the spiciest golgappe in Rajasthan.", price: "₹50-100" },
      { time: "6:30 PM", stop: "LMB, Johari Bazaar", food: "Ghewar & Mawa Kachori", desc: "End with Jaipur's signature sweets. Buy Ghewar and Mawa Kachori to take home. This shop has royal patronage.", price: "₹100-400" },
    ],
    restaurants: [
      { name: "Handi Restaurant", cuisine: "Rajasthani / Mughlai", budget: "₹400-700", location: "MI Road", rating: "4.3" },
      { name: "Laxmi Mishthan Bhandar (LMB)", cuisine: "Rajasthani Vegetarian", budget: "₹300-500", location: "Johari Bazaar", rating: "4.2" },
      { name: "Niros", cuisine: "Multi-cuisine", budget: "₹500-800", location: "MI Road", rating: "4.1" },
      { name: "Rawat Mishthan Bhandar", cuisine: "Street Food / Sweets", budget: "₹100-200", location: "Station Road", rating: "4.4" },
      { name: "1135 AD", cuisine: "Fine Dining Rajasthani", budget: "₹1,500-3,000", location: "Amer Fort", rating: "4.5" },
    ],
    faqs: [
      { question: "What food is Jaipur famous for?", answer: "Jaipur is famous for Dal Baati Churma (Rajasthan's signature dish), Pyaaz Kachori (onion-stuffed fried pastry), Ghewar (festival sweet), Laal Maas (fiery mutton curry), Mirchi Bada, Raj Kachori, and Kulfi Faluda. The city has a rich culinary heritage blending royal Rajasthani and Mughlai cuisines." },
      { question: "Where is the best Pyaaz Kachori in Jaipur?", answer: "Rawat Mishthan Bhandar on Station Road is unanimously considered the best since 1955. Other good options include Samrat Restaurant and LMB in Johari Bazaar. Arrive before 9 AM for the freshest batch." },
      { question: "Is Jaipur food very spicy?", answer: "Rajasthani food can be quite spicy, especially Laal Maas and Mirchi Bada. However, many dishes like Dal Baati Churma, Ghewar, and Kulfi are mild. Restaurants adjust spice levels on request. Street food varies -- always ask." },
      { question: "What is the best time for a Jaipur food tour?", answer: "Morning (7-9 AM) for kachori breakfast. Lunch (12-2 PM) for thali restaurants. Evening (5-8 PM) for chaat and street food at Johari Bazaar and Chandpole. October-March is ideal weather for outdoor eating." },
      { question: "Are there good vegetarian options?", answer: "Absolutely! Jaipur is predominantly vegetarian. Dal Baati Churma, Pyaaz Kachori, Ghewar, Raj Kachori, Mirchi Bada -- all are vegetarian. LMB is a famous pure-veg restaurant. Rajasthani thali is mostly vegetarian." },
      { question: "How much does a Jaipur food tour cost?", answer: "Street food budget: ₹300-500 per person for a full day. Restaurant meals: ₹300-700 per person. Our food tour with cab: ₹1,200 (sedan, half-day local). We handle transport between food spots across the Pink City." },
    ],
  },
  "varanasi": {
    city: "Varanasi",
    slug: "varanasi-food-tour",
    famousDish: "Tamatar Chaat",
    duration: "5-6 hours",
    cabFare: "₹1,000",
    bestTime: "October to March",
    description: "Varanasi is one of India's oldest food cities, where culinary traditions are as ancient as its ghats. The narrow lanes of Vishwanath Gali hide legendary sweet shops serving Malaiyo (winter-only milk foam), Kachori-Sabzi breakfast stalls that have fed pilgrims for generations, and chaat corners famous for the unique Tamatar Chaat found nowhere else in India. Banarasi cuisine is a vegetarian paradise, deeply influenced by its spiritual heritage.",
    famousFoods: [
      { name: "Tamatar Chaat", desc: "Varanasi's signature chaat -- a spicy-sweet tomato-based preparation with crispy papdi, sev, and chutneys. Found only in Banaras. Kashi Chaat Bhandar in Godowlia is the most famous.", price: "₹30-60 per plate", mustTry: true, heat: 2 },
      { name: "Malaiyo / Nimish", desc: "A magical winter-only dessert -- whipped milk foam infused with saffron and cardamom. Available only November-February, early morning. Disappears by 9 AM. A Varanasi original.", price: "₹30-50 per bowl", mustTry: true, heat: 0 },
      { name: "Kachori-Sabzi", desc: "Varanasi's daily breakfast -- crispy kachori served with spicy potato-pea sabzi and tangy green chutney. Every gali has its own kachori wala. Ram Bhandar near Godowlia is iconic.", price: "₹20-40 per plate", mustTry: true, heat: 1 },
      { name: "Banarasi Paan", desc: "The legendary betel leaf preparation of Varanasi -- stuffed with gulkand, supari, cardamom, and sweet fillings. A post-meal ritual. Bade Miyan at Godowlia is the most famous paan shop.", price: "₹20-100 per paan", mustTry: false, heat: 0 },
      { name: "Thandai", desc: "A cold spiced milk drink with almonds, fennel, rose petals, and saffron. Varanasi's Thandai is famous throughout India, especially during Holi. Blue Lassi is a popular spot.", price: "₹40-80 per glass", mustTry: false, heat: 0 },
      { name: "Banarasi Lassi", desc: "Thick, creamy yogurt drink served in clay cups. Blue Lassi near Manikarnika Ghat offers 70+ flavors including mango, pomegranate, and chocolate.", price: "₹40-100 per cup", mustTry: false, heat: 0 },
      { name: "Chena Dahi Vada", desc: "Varanasi's unique take on dahi vada -- soft lentil dumplings in sweetened yogurt with chena (cottage cheese) topping. A temple area specialty.", price: "₹30-60 per plate", mustTry: false, heat: 0 },
      { name: "Litti Chokha", desc: "Roasted wheat balls stuffed with sattu (roasted gram flour) served with mashed potato-brinjal chokha. A Bihari influence on Varanasi cuisine.", price: "₹50-100 per plate", mustTry: false, heat: 1 },
    ],
    foodTrail: [
      { time: "6:00 AM", stop: "Dashashwamedh Ghat Area", food: "Malaiyo (Winter) / Thandai", desc: "Start at dawn. In winter, catch the Malaiyo sellers before their delicate foam melts away. In summer, start with chilled Thandai.", price: "₹30-80" },
      { time: "7:30 AM", stop: "Ram Bhandar, Thatheri Bazaar", food: "Kachori-Sabzi", desc: "Varanasi's most famous breakfast spot. The kachori here is served with a legendary aloo sabzi. A 100+ year old institution.", price: "₹30-50" },
      { time: "9:00 AM", stop: "Vishwanath Gali", food: "Jalebi & Rabri", desc: "Walk through the temple lane and stop for hot jalebis with thick rabri at one of the old sweet shops.", price: "₹40-80" },
      { time: "11:00 AM", stop: "Kashi Chaat Bhandar, Godowlia", food: "Tamatar Chaat & Pani Puri", desc: "The legendary chaat shop. Their Tamatar Chaat is unique to Varanasi -- tangy, spicy, and unforgettable.", price: "₹40-80" },
      { time: "1:00 PM", stop: "Kashi Chat / Deena Chat", food: "Chena Dahi Vada & Tikki", desc: "Lunch-time chaat that doubles as a meal. The dahi vada here is unlike anything in Delhi.", price: "₹50-100" },
      { time: "3:30 PM", stop: "Blue Lassi, near Manikarnika", food: "Flavored Lassi", desc: "A tiny legendary shop with 70+ lassi flavors. The owner makes each cup fresh. Try mango, pomegranate, or the special saffron.", price: "₹60-120" },
      { time: "5:00 PM", stop: "Godowlia Chowk", food: "Banarasi Paan", desc: "End your food tour with the iconic Banarasi Paan. Sweet, fragrant, and the perfect digestif after a day of eating.", price: "₹20-100" },
    ],
    restaurants: [
      { name: "Ram Bhandar", cuisine: "Breakfast / Street Food", budget: "₹50-100", location: "Thatheri Bazaar", rating: "4.3" },
      { name: "Kashi Chaat Bhandar", cuisine: "Chaat", budget: "₹50-100", location: "Godowlia", rating: "4.4" },
      { name: "Blue Lassi", cuisine: "Lassi Shop", budget: "₹60-120", location: "Near Manikarnika Ghat", rating: "4.5" },
      { name: "Baati Chokha Restaurant", cuisine: "North Indian / Bihari", budget: "₹200-400", location: "Sigra", rating: "4.2" },
      { name: "Brown Bread Bakery", cuisine: "Cafe / Bakery", budget: "₹200-400", location: "Assi Ghat", rating: "4.3" },
    ],
    faqs: [
      { question: "What food is Varanasi famous for?", answer: "Varanasi is famous for Tamatar Chaat (unique tomato-based chaat), Malaiyo/Nimish (winter-only milk foam dessert), Kachori-Sabzi, Banarasi Paan, Thandai, thick Lassi, and Chena Dahi Vada. The city has a deeply vegetarian food culture rooted in its spiritual heritage." },
      { question: "What is Malaiyo and when can I try it?", answer: "Malaiyo (also called Nimish or Daulat Ki Chaat) is a magical dessert made from whipped milk foam, saffron, and cardamom. Available only in winter (November-February), sold by street vendors early morning. It literally dissolves in your mouth. You must arrive before 9 AM as it melts quickly." },
      { question: "Is street food safe in Varanasi?", answer: "Popular stalls with high turnover are safe. Stick to busy, established vendors. Ram Bhandar, Kashi Chaat Bhandar, and Blue Lassi are all safe and hygienic. Avoid raw items and drink bottled water. Our recommended spots have served millions safely." },
      { question: "Can I combine food tour with ghat visits?", answer: "Yes! Our recommended route follows the ghats. Morning Ganga Aarti at Dashashwamedh, breakfast at Ram Bhandar, walk through Vishwanath Gali to the temple, chaat at Godowlia, lassi near Manikarnika, and evening aarti. Food and spirituality blend seamlessly." },
      { question: "Are there non-vegetarian options?", answer: "Varanasi's old city is predominantly vegetarian due to its religious significance. However, areas like Sigra, Lanka, and the outskirts have non-veg restaurants. Litti Chokha (vegetarian) is a popular savory option. Our drivers know the best spots for all preferences." },
      { question: "How much does a Varanasi food tour cost?", answer: "Street food budget: ₹200-400 per person for a full day. Our food tour with cab: ₹1,000 (sedan, half-day local). The old city lanes are walkable but our cab takes you between the spread-out food zones efficiently." },
    ],
  },
  "lucknow": {
    city: "Lucknow",
    slug: "lucknow-food-tour",
    famousDish: "Tunday Kababi",
    duration: "5-6 hours",
    cabFare: "₹1,000",
    bestTime: "October to March",
    description: "Lucknow is the undisputed kebab capital of India, where Nawabi cuisine reached perfection over centuries. The city's Tunday Kababi has been serving melt-in-your-mouth galawti kebabs since 1905, and the Chowk area is a living museum of Awadhi culinary art. From silky Lucknawi Biryani to the delicate Sheermal bread, from Basket Chaat to the legendary Prakash Ki Kulfi -- Lucknow's food is refined, aromatic, and deeply satisfying.",
    famousFoods: [
      { name: "Tunday Kabab", desc: "Lucknow's most famous food -- ultra-soft galawti kebabs made with 160 spices. Invented in 1905 by a one-armed cook (tunday means one-armed). The original shop in Chowk is a pilgrimage for food lovers.", price: "₹80-150 per plate", mustTry: true, heat: 1 },
      { name: "Lucknawi Biryani", desc: "Distinct from Hyderabadi biryani -- Lucknawi biryani is cooked in the pukki (pre-cooked) style. Rice and meat are cooked separately then layered. Lighter, more aromatic, with whole spices.", price: "₹200-400 per plate", mustTry: true, heat: 1 },
      { name: "Basket Chaat", desc: "Lucknow's unique chaat served in an edible fried potato basket. Filled with dahi, chutneys, aloo tikki, and sev. Royal Cafe at Hazratganj is famous for it.", price: "₹60-100 per plate", mustTry: true, heat: 1 },
      { name: "Sheermal & Kulcha", desc: "Saffron-flavored Mughlai bread baked in tandoor. Sheermal is sweet, Kulcha is savory. Both are Lucknow specialties served with kebabs and curries.", price: "₹20-50 per piece", mustTry: false, heat: 0 },
      { name: "Nihari", desc: "Slow-cooked overnight meat stew, traditionally eaten for breakfast. Rich, thick, and deeply flavorful. Raheem's in Chowk is the most famous nihari shop.", price: "₹150-300 per plate", mustTry: false, heat: 1 },
      { name: "Prakash Ki Kulfi", desc: "Lucknow's legendary kulfi shop near Aminabad. Thick, dense, and creamier than any kulfi you have tried. Their malai kulfi is unforgettable.", price: "₹50-100 per serving", mustTry: false, heat: 0 },
      { name: "Makhan Malai", desc: "Lucknow's winter-only delicacy -- ethereal whipped cream foam flavored with saffron and pistachios. Similar to Varanasi's Malaiyo. Available November-February.", price: "₹30-60 per bowl", mustTry: false, heat: 0 },
      { name: "Paya", desc: "Slow-cooked goat trotters in rich, gelatinous gravy. A traditional Lucknow breakfast dish. Best at Idris Biryani or Wahid Biryani.", price: "₹100-200 per bowl", mustTry: false, heat: 1 },
    ],
    foodTrail: [
      { time: "8:00 AM", stop: "Tunday Kababi, Chowk", food: "Galawti Kebab & Paratha", desc: "Start at the legendary original Tunday Kababi in Chowk (not the Aminabad branch). The galawti kebabs melt on your tongue. Pair with roomali roti.", price: "₹100-200" },
      { time: "9:30 AM", stop: "Raheem's, Chowk", food: "Nihari & Sheermal", desc: "Walk 200 meters to Raheem's for their famous nihari -- slow-cooked overnight. The saffron-scented sheermal bread is the perfect companion.", price: "₹150-300" },
      { time: "11:00 AM", stop: "Chowk Market Walk", food: "Thandai & Kulcha-Nihari", desc: "Explore the narrow lanes of Chowk. Sample Lucknawi thandai, watch kebab artisans at work, and soak in the Nawabi atmosphere.", price: "₹50-100" },
      { time: "1:00 PM", stop: "Wahid / Idris Biryani", food: "Lucknawi Biryani", desc: "Lunch at one of Lucknow's biryani institutions. The pukki-style biryani here is fragrant, layered, and served with raita and salad.", price: "₹200-400" },
      { time: "3:30 PM", stop: "Royal Cafe, Hazratganj", food: "Basket Chaat", desc: "Head to the upscale Hazratganj area for the famous Basket Chaat -- a crispy potato basket filled with chaat goodness. A Lucknow original.", price: "₹80-120" },
      { time: "5:00 PM", stop: "Prakash Ki Kulfi, Aminabad", food: "Malai Kulfi", desc: "End at Lucknow's most loved kulfi shop. The malai kulfi is impossibly rich and dense. A perfect sweet ending.", price: "₹60-100" },
    ],
    restaurants: [
      { name: "Tunday Kababi", cuisine: "Kebabs / Mughlai", budget: "₹100-250", location: "Chowk", rating: "4.4" },
      { name: "Raheem's", cuisine: "Mughlai / Nihari", budget: "₹150-300", location: "Chowk", rating: "4.2" },
      { name: "Wahid Biryani", cuisine: "Biryani", budget: "₹200-400", location: "Aminabad", rating: "4.1" },
      { name: "Idris Biryani", cuisine: "Biryani / Mughlai", budget: "₹200-400", location: "Multiple Outlets", rating: "4.3" },
      { name: "Royal Cafe", cuisine: "Chaat / Snacks", budget: "₹100-200", location: "Hazratganj", rating: "4.2" },
    ],
    faqs: [
      { question: "What food is Lucknow famous for?", answer: "Lucknow is the kebab capital of India. Famous for Tunday Kabab (galawti kebabs with 160 spices), Lucknawi Biryani (pukki style), Basket Chaat, Nihari, Sheermal bread, Makhan Malai (winter dessert), and Prakash Ki Kulfi. Awadhi cuisine is refined, aromatic, and world-renowned." },
      { question: "Where is the original Tunday Kababi?", answer: "The original Tunday Kababi is in Chowk (Old Lucknow), established in 1905. There is a newer branch in Aminabad. Locals consider the Chowk branch superior. Go early (before noon) for the freshest kebabs. The shop is small but the taste is extraordinary." },
      { question: "Is Lucknow food very non-vegetarian?", answer: "Awadhi cuisine is heavily non-vegetarian (kebabs, biryani, nihari, paya). However, Lucknow has excellent vegetarian options too -- Basket Chaat, Makhan Malai, Kulfi, street chaat at Hazratganj, and Shahi Paneer at restaurants. The chaat scene is entirely vegetarian." },
      { question: "Can I combine food tour with heritage sightseeing?", answer: "Yes! Bara Imambara and Chowk food area are adjacent. Visit Bara Imambara in the morning, walk to Chowk for kebabs, then Hazratganj for chaat and British-era architecture. Our drivers create efficient food-plus-heritage routes." },
      { question: "What is the best time to visit Lucknow for food?", answer: "October-March is ideal. Winter brings Makhan Malai (November-February). Ramadan (dates vary) transforms Chowk into a food paradise with special iftar spreads. Eid celebrations have the best kebabs. Avoid May-June (extreme heat)." },
      { question: "How much does a Lucknow food tour cost?", answer: "Street food: ₹300-500 per person. Restaurant meals: ₹200-500. Our food tour with cab: ₹1,000 (sedan, half-day covering Chowk, Aminabad, Hazratganj). Lucknow food is remarkably affordable even at famous establishments." },
    ],
  },
  "amritsar": {
    city: "Amritsar",
    slug: "amritsar-food-tour",
    famousDish: "Amritsari Kulcha",
    duration: "5-6 hours",
    cabFare: "₹1,000",
    bestTime: "October to March",
    description: "Amritsar is Punjab's food capital, where butter flows like water and every meal is a celebration. From the legendary Amritsari Kulcha at Kulcha Land to the massive Lassi at Ahuja Lassi, from the world-famous Langar at the Golden Temple to crispy Amritsari Fish -- this city takes Punjabi cuisine to its glorious extreme. The old city lanes near Hall Bazaar are a food paradise.",
    famousFoods: [
      { name: "Amritsari Kulcha", desc: "Stuffed bread baked in tandoor, served with chole and imli chutney. Amritsar's kulcha is crispier and more buttery than anywhere else. Kulcha Land and Bhai Kulwant Singh are legendary.", price: "₹60-100 per plate", mustTry: true, heat: 1 },
      { name: "Amritsari Fish", desc: "Beer-battered (or gram flour-battered) fried fish -- crispy, golden, and perfectly spiced. A Sikh culinary tradition. Makhan Fish Corner is the gold standard.", price: "₹200-400 per plate", mustTry: true, heat: 1 },
      { name: "Lassi", desc: "Amritsar's famous thick, creamy lassi served in tall steel glasses. Ahuja Lassi and Gian Di Lassi are institutions. So thick you need a spoon.", price: "₹50-100 per glass", mustTry: true, heat: 0 },
      { name: "Langar (Golden Temple)", desc: "The world's largest free kitchen serving 50,000+ meals daily. Simple dal, roti, rice, and kheer. An experience that transcends food -- it is community, equality, and devotion.", price: "Free", mustTry: false, heat: 0 },
      { name: "Chole Bhature", desc: "Spicy chickpea curry with giant deep-fried bread. Amritsar's chole are darker, richer, and spicier than Delhi. Kanha Sweets and Bharawan Da Dhaba serve great versions.", price: "₹80-150 per plate", mustTry: false, heat: 2 },
      { name: "Pinni", desc: "Traditional Punjabi sweet made from wheat flour, ghee, and dry fruits. Dense, rich, and perfect winter food. Available at sweet shops throughout the city.", price: "₹200-400 per kg", mustTry: false, heat: 0 },
      { name: "Tandoori Chicken", desc: "While available across India, Amritsar's version is considered the most authentic -- smoky, juicy, and marinated in thick yogurt-spice paste.", price: "₹200-400 per plate", mustTry: false, heat: 1 },
      { name: "Puri-Chole", desc: "Deep-fried puffed bread with chickpea curry -- a classic Amritsar breakfast. Kanha Sweets near Golden Temple has been serving it for decades.", price: "₹60-100 per plate", mustTry: false, heat: 1 },
    ],
    foodTrail: [
      { time: "7:00 AM", stop: "Kanha Sweets, near Golden Temple", food: "Puri-Chole & Jalebi", desc: "Start with an authentic Punjabi breakfast. Hot puris with spicy chole, followed by crispy jalebis. Fuel for a full day of eating.", price: "₹80-120" },
      { time: "8:30 AM", stop: "Golden Temple", food: "Langar (Free Kitchen)", desc: "Experience the world's largest community kitchen. Sit on the floor with thousands and eat simple, soulful food. An unmissable Amritsar experience.", price: "Free" },
      { time: "10:30 AM", stop: "Kulcha Land / Bhai Kulwant Singh", food: "Amritsari Kulcha", desc: "The legendary kulcha shops. Crispy, buttery stuffed bread with chole and tangy chutney. Worth the queue.", price: "₹80-120" },
      { time: "12:00 PM", stop: "Makhan Fish Corner", food: "Amritsari Fish Fry", desc: "Golden, crispy fried fish with green chutney. A Punjabi non-veg classic. Even vegetarians are tempted here.", price: "₹200-400" },
      { time: "2:00 PM", stop: "Bharawan Da Dhaba", food: "Dal Makhani & Paneer", desc: "Sit-down lunch at this legendary dhaba. Their dal makhani is slow-cooked overnight. Rich, creamy, and legendary.", price: "₹200-400" },
      { time: "4:00 PM", stop: "Ahuja Lassi / Gian Di Lassi", food: "Lassi", desc: "Amritsar's famous thick lassi. So creamy and dense it is practically a meal. The steel glass presentation is iconic.", price: "₹60-100" },
      { time: "5:30 PM", stop: "Hall Bazaar Area", food: "Chaat & Pinni", desc: "Evening walk through Hall Bazaar for chaat, golgappe, and Punjabi sweets. Buy Pinni and Amritsari Papad to take home.", price: "₹100-200" },
    ],
    restaurants: [
      { name: "Bharawan Da Dhaba", cuisine: "Punjabi Vegetarian", budget: "₹200-400", location: "Town Hall", rating: "4.3" },
      { name: "Makhan Fish Corner", cuisine: "Amritsari Fish", budget: "₹200-400", location: "Majitha Road", rating: "4.4" },
      { name: "Kulcha Land", cuisine: "Kulcha", budget: "₹80-150", location: "Maqbool Road", rating: "4.2" },
      { name: "Kanha Sweets", cuisine: "Sweets / Breakfast", budget: "₹100-200", location: "Near Golden Temple", rating: "4.1" },
      { name: "Beera Chicken House", cuisine: "Tandoori / Non-Veg", budget: "₹300-500", location: "Majitha Road", rating: "4.2" },
    ],
    faqs: [
      { question: "What food is Amritsar famous for?", answer: "Amritsar is famous for Amritsari Kulcha, Amritsari Fish Fry, thick Lassi, Chole Bhature, Tandoori Chicken, and Pinni (Punjabi sweet). The Golden Temple Langar (free kitchen) serving 50,000+ daily meals is a must-experience." },
      { question: "Is the Golden Temple Langar open to everyone?", answer: "Yes! The Langar is open to people of all religions, castes, and nationalities, 24/7, 365 days a year. It is free. You sit on the floor in a line and volunteers serve dal, roti, rice, and kheer. Cover your head and remove shoes before entering." },
      { question: "Where is the best Amritsari Kulcha?", answer: "Kulcha Land on Maqbool Road and Bhai Kulwant Singh Kulche Wale are the two most famous. Both have long queues, especially on weekends. Go before 11 AM for shorter waits. The aloo and paneer stuffings are most popular." },
      { question: "Can I do a food tour combined with Golden Temple visit?", answer: "Absolutely! The Golden Temple, old city food spots, and Hall Bazaar are all walking distance from each other. Start with an early morning temple visit, then walk to nearby food spots. Our cab covers the spread-out locations." },
      { question: "Is Amritsar food mostly non-vegetarian?", answer: "No! Amritsar has excellent vegetarian food -- Kulcha, Chole Bhature, Dal Makhani, Langar, Lassi, sweets. Many famous eateries are pure veg. Non-veg is also excellent (fish, chicken, mutton) but vegetarians will not feel left out at all." },
      { question: "How much does an Amritsar food tour cost?", answer: "Street food: ₹300-500 per person. Restaurant meals: ₹200-500. Langar is free. Our food tour with cab: ₹1,000 (sedan, half-day). Amritsar food is very affordable and portions are extremely generous." },
    ],
  },
  "delhi": {
    city: "Delhi",
    slug: "delhi-food-tour",
    famousDish: "Chole Bhature",
    duration: "6-7 hours",
    cabFare: "₹1,500",
    bestTime: "October to March",
    description: "Delhi is India's food capital, a city where Mughlai heritage meets Punjabi exuberance and street food genius. Old Delhi's Chandni Chowk is Asia's oldest and busiest food street, where kebab shops have been running since the Mughal era and Paranthe Wali Gali has served stuffed parathas for 150 years. From Karim's legendary Mughlai cuisine to the dahi bhalle at Natraj, Delhi's food story is epic.",
    famousFoods: [
      { name: "Chole Bhature", desc: "Delhi's most iconic breakfast -- fluffy deep-fried bread with spicy chickpea curry. Sita Ram Diwan Chand in Paharganj has been the undisputed champion since 1950s.", price: "₹80-150 per plate", mustTry: true, heat: 1 },
      { name: "Paranthe Wali Gali", desc: "A 150-year-old lane in Chandni Chowk dedicated entirely to stuffed parathas. 30+ varieties -- aloo, paneer, rabri, papad, mixed. Served with curd and pickle.", price: "₹60-150 per plate", mustTry: true, heat: 1 },
      { name: "Butter Chicken", desc: "Invented in Delhi at Moti Mahal, Daryaganj in 1947. Creamy tomato-based gravy with tender tandoori chicken pieces. Delhi's gift to the world.", price: "₹300-500 per dish", mustTry: true, heat: 0 },
      { name: "Dahi Bhalle", desc: "Soft lentil dumplings in sweetened yogurt with tamarind and green chutney. Natraj Dahi Bhalle Wala in Chandni Chowk has been the benchmark for decades.", price: "₹40-80 per plate", mustTry: false, heat: 0 },
      { name: "Kebabs at Karim's", desc: "Karim's near Jama Masjid has served Mughlai food since 1913. Their seekh kebabs, mutton burra, and nihari are legendary. Direct descendants of Mughal court chefs.", price: "₹150-400 per dish", mustTry: false, heat: 1 },
      { name: "Chaat", desc: "Delhi chaat is a world of its own -- golgappe, dahi puri, aloo tikki, papdi chaat. Every neighborhood has its chaat legend. Old Delhi and Bengali Market are chaat paradise.", price: "₹30-80 per plate", mustTry: false, heat: 2 },
      { name: "Jalebi", desc: "Old Famous Jalebi Wala at Chandni Chowk has been frying jalebis since 1884. Hot, crispy, and dripping with syrup. Best in the early morning.", price: "₹30-60 per plate", mustTry: false, heat: 0 },
      { name: "Nihari", desc: "Overnight slow-cooked meat stew. Al Jawahar and Karim's near Jama Masjid serve the best. Traditional Sunday morning dish.", price: "₹150-300 per bowl", mustTry: false, heat: 1 },
    ],
    foodTrail: [
      { time: "8:00 AM", stop: "Old Famous Jalebi Wala, Chandni Chowk", food: "Hot Jalebi", desc: "Start at this 140-year-old shop. Watch the jalebi master swirl batter into hot oil. Best eaten immediately, standing at the counter.", price: "₹30-60" },
      { time: "9:00 AM", stop: "Paranthe Wali Gali, Chandni Chowk", food: "Stuffed Parathas", desc: "Walk into this legendary lane for breakfast. Try aloo, paneer, and the adventurous rabri paratha. Served with curd and mixed pickle.", price: "₹80-150" },
      { time: "10:30 AM", stop: "Natraj Dahi Bhalle Wala", food: "Dahi Bhalle", desc: "The softest, most perfectly balanced dahi bhalle in India. A Chandni Chowk institution for over 50 years.", price: "₹50-80" },
      { time: "12:00 PM", stop: "Karim's, Jama Masjid", food: "Seekh Kebab & Biryani", desc: "Walk to Jama Masjid for lunch at Karim's -- a direct descendant of Mughal court chefs. The seekh kebab and mutton biryani are extraordinary.", price: "₹200-500" },
      { time: "2:30 PM", stop: "Sita Ram Diwan Chand, Paharganj", food: "Chole Bhature", desc: "Delhi's best chole bhature since the 1950s. The chole are dark, spicy, and deeply flavorful. Served with onion and pickle.", price: "₹100-150" },
      { time: "4:30 PM", stop: "Bengali Market", food: "Chaat & Golgappe", desc: "Evening chaat at Bengali Market. Try the aloo tikki, papdi chaat, and golgappe. Each stall has its own special preparation.", price: "₹50-100" },
      { time: "6:00 PM", stop: "Connaught Place Area", food: "Kulfi & Rabri", desc: "End with kulfi at one of CP's old establishments. Or try the legendary butter chicken at Moti Mahal Delux.", price: "₹80-200" },
    ],
    restaurants: [
      { name: "Karim's", cuisine: "Mughlai", budget: "₹200-500", location: "Jama Masjid", rating: "4.3" },
      { name: "Sita Ram Diwan Chand", cuisine: "Chole Bhature", budget: "₹100-150", location: "Paharganj", rating: "4.4" },
      { name: "Moti Mahal Delux", cuisine: "Tandoori / Mughlai", budget: "₹400-700", location: "Daryaganj", rating: "4.2" },
      { name: "Natraj Dahi Bhalle Wala", cuisine: "Chaat", budget: "₹50-100", location: "Chandni Chowk", rating: "4.3" },
      { name: "Bukhara (ITC Maurya)", cuisine: "Fine Dining North Indian", budget: "₹3,000-6,000", location: "Chanakyapuri", rating: "4.7" },
    ],
    faqs: [
      { question: "What food is Delhi famous for?", answer: "Delhi is famous for Chole Bhature, Butter Chicken (invented here), Paranthe Wali Gali parathas, Mughlai kebabs at Karim's, Dahi Bhalle, Chaat, Jalebi, and Nihari. The city blends Mughal, Punjabi, and street food traditions into India's most diverse food scene." },
      { question: "Is Chandni Chowk safe for food?", answer: "Popular established stalls are safe. Stick to famous shops (Karim's, Natraj, Old Famous Jalebi Wala, Paranthe Wali Gali). Avoid very small unknown vendors. Drink bottled water. Our drivers know exactly which stalls are trustworthy and hygienic." },
      { question: "What is the best time for Delhi street food?", answer: "Morning (8-10 AM) for jalebi and parathas at Chandni Chowk. Lunch (12-2 PM) for Karim's and kebab area near Jama Masjid. Evening (4-8 PM) for chaat at Bengali Market and CP. October-February is the best weather." },
      { question: "Can I do a food tour combined with sightseeing?", answer: "Yes! Red Fort, Jama Masjid, and Chandni Chowk food are all in the same area. Visit Red Fort first (opens at sunrise), then walk to Chandni Chowk for breakfast. Jama Masjid is next to Karim's. Our drivers plan efficient food-sightseeing routes." },
      { question: "Where was Butter Chicken invented?", answer: "Butter Chicken was invented at Moti Mahal in Daryaganj, Delhi by Kundan Lal Gujral in 1947. He also popularized Tandoori Chicken. The original restaurant still operates in Daryaganj. Many claim to be the 'real' Moti Mahal -- the Daryaganj location is the original." },
      { question: "How much does a Delhi food tour cost?", answer: "Street food: ₹400-600 per person for a full day. Restaurant meals: ₹300-700. Our food tour with cab: ₹1,500 (sedan, full-day covering Old Delhi, Paharganj, CP, Bengali Market). Delhi is huge so a car is essential to cover all food zones." },
    ],
  },
  "jodhpur": {
    city: "Jodhpur",
    slug: "jodhpur-food-tour",
    famousDish: "Mirchi Bada",
    duration: "4-5 hours",
    cabFare: "₹1,000",
    bestTime: "October to March",
    description: "Jodhpur, the Blue City, serves Rajasthani cuisine at its most fiery and authentic. The city's signature Mirchi Bada -- giant green chillies stuffed with potato and deep-fried -- is a spice lover's dream. Makhaniya Lassi, Pyaaz Kachori, Mawa Kachori, and Rajasthani thalis at historic havelis make Jodhpur a food destination that rivals Jaipur.",
    famousFoods: [
      { name: "Mirchi Bada", desc: "Jodhpur's most iconic snack -- large green chillies stuffed with spiced potato, battered in gram flour, and deep-fried. Crispy outside, soft and spicy inside. Shahi Samosa is the most famous shop.", price: "₹15-30 per piece", mustTry: true, heat: 3 },
      { name: "Makhaniya Lassi", desc: "Jodhpur's signature thick, buttery lassi with a layer of malai (cream) on top. Richer than regular lassi. Mishrilal Hotel near Clock Tower is legendary.", price: "₹40-80 per glass", mustTry: true, heat: 0 },
      { name: "Mawa Kachori", desc: "Sweet kachori stuffed with mawa (khoya), dry fruits, and cardamom, then fried and dipped in sugar syrup. A Jodhpur-origin sweet snack.", price: "₹30-60 per piece", mustTry: true, heat: 0 },
      { name: "Pyaaz Kachori", desc: "Crispy deep-fried pastry with spiced onion filling. Every sweet shop in Jodhpur makes it, but the old city versions near Sardar Market are the best.", price: "₹20-40 per piece", mustTry: false, heat: 1 },
      { name: "Dal Baati Churma", desc: "Rajasthan's staple -- smoky baked wheat balls with five-lentil dal and sweet churma. Best enjoyed at traditional Rajasthani thali restaurants.", price: "₹150-300 per thali", mustTry: false, heat: 0 },
      { name: "Ker Sangri", desc: "A desert specialty made from dried berries (ker) and beans (sangri) found only in the Thar Desert. Spicy, tangy, and uniquely Jodhpur.", price: "₹100-200 per dish", mustTry: false, heat: 2 },
      { name: "Gulab Jamun", desc: "While found everywhere in India, Jodhpur's version is particularly good. Janta Sweet Home serves soft, syrup-soaked gulab jamuns that are a cut above.", price: "₹30-60 per plate", mustTry: false, heat: 0 },
      { name: "Rajasthani Thali", desc: "A grand platter with 15-20 items: dal, baati, churma, gatte ki sabzi, papad, ker sangri, and multiple sweets. An all-in-one Rajasthani experience.", price: "₹200-500 per thali", mustTry: false, heat: 1 },
    ],
    foodTrail: [
      { time: "8:00 AM", stop: "Shahi Samosa, near Clock Tower", food: "Mirchi Bada & Pyaaz Kachori", desc: "Start at this legendary shop for Jodhpur's spiciest breakfast. The mirchi bada here is the standard against which all others are judged.", price: "₹40-80" },
      { time: "9:30 AM", stop: "Mishrilal Hotel, Clock Tower", food: "Makhaniya Lassi", desc: "The most famous lassi in Rajasthan. Thick, buttery, and served in a clay pot. A 100-year-old institution at the base of the Clock Tower.", price: "₹50-80" },
      { time: "11:00 AM", stop: "Sardar Market Area", food: "Mawa Kachori & Sweets", desc: "Explore the colorful Sardar Market and sample mawa kachori and Jodhpuri sweets. Great for spice shopping too.", price: "₹50-100" },
      { time: "1:00 PM", stop: "Jhankar Choti Haveli / Gypsy", food: "Rajasthani Thali", desc: "Lunch at a traditional haveli restaurant. The full Rajasthani thali with dal baati churma, ker sangri, and bajra roti is a feast.", price: "₹250-500" },
      { time: "3:30 PM", stop: "Old City Walk", food: "Chai & Samosa", desc: "Walk through the blue-painted old city lanes with a cup of masala chai and crispy samosas from street vendors.", price: "₹30-50" },
      { time: "5:00 PM", stop: "Janta Sweet Home", food: "Gulab Jamun & Sweets", desc: "End with Jodhpur's famous sweets. Buy gulab jamun, malpua, and mawa kachori to take home.", price: "₹80-200" },
    ],
    restaurants: [
      { name: "Mishrilal Hotel", cuisine: "Lassi / Snacks", budget: "₹50-100", location: "Clock Tower", rating: "4.4" },
      { name: "Jhankar Choti Haveli", cuisine: "Rajasthani Thali", budget: "₹300-500", location: "Makrana Mohalla", rating: "4.3" },
      { name: "Shahi Samosa", cuisine: "Street Food", budget: "₹40-100", location: "Near Clock Tower", rating: "4.2" },
      { name: "Gypsy Restaurant", cuisine: "Rajasthani", budget: "₹200-400", location: "Near Mehrangarh", rating: "4.1" },
      { name: "Stepwell Cafe (RAAS)", cuisine: "Fine Dining", budget: "₹1,500-3,000", location: "RAAS Hotel", rating: "4.6" },
    ],
    faqs: [
      { question: "What food is Jodhpur famous for?", answer: "Jodhpur is famous for Mirchi Bada (stuffed fried chillies), Makhaniya Lassi (buttery thick lassi), Mawa Kachori, Pyaaz Kachori, Dal Baati Churma, Ker Sangri (desert specialty), and traditional Rajasthani Thali." },
      { question: "Is Jodhpur food very spicy?", answer: "Jodhpur food can be extremely spicy -- Mirchi Bada is literally a stuffed chilli. However, many dishes like Makhaniya Lassi, Mawa Kachori, and Churma are sweet. Rajasthani thali restaurants offer a good balance. Ask for less spice if needed." },
      { question: "Where is the best Mirchi Bada?", answer: "Shahi Samosa near Clock Tower is the most famous. There are also excellent mirchi bada stalls at Sardar Market and along Nai Sarak. They are crispiest when freshly fried -- go during busy times for the freshest ones." },
      { question: "Can I combine food tour with Mehrangarh Fort?", answer: "Yes! Mehrangarh Fort, Clock Tower, and Sardar Market are all in the same area. Visit the fort in the morning, descend to Clock Tower for lassi and mirchi bada, then explore Sardar Market for food and shopping." },
      { question: "What is Ker Sangri?", answer: "Ker Sangri is a unique Thar Desert dish made from dried ker berries and sangri beans that grow in arid conditions. Spicy, tangy, and found only in Rajasthan. It is a must-try for anyone wanting authentic desert cuisine." },
      { question: "How much does a Jodhpur food tour cost?", answer: "Street food: ₹200-400 per person. Thali meals: ₹200-500. Our food tour with cab: ₹1,000 (sedan, half-day local). Jodhpur food is very affordable. The Clock Tower area is walkable but our cab covers distant spots." },
    ],
  },
  "udaipur": {
    city: "Udaipur",
    slug: "udaipur-food-tour",
    famousDish: "Dal Baati Churma",
    duration: "5-6 hours",
    cabFare: "₹1,000",
    bestTime: "October to March",
    description: "Udaipur, the City of Lakes, blends Rajasthani culinary tradition with a lakeside cafe culture that attracts food lovers worldwide. From traditional Dal Baati Churma and Gatte Ki Sabzi to rooftop restaurants overlooking Lake Pichola, Udaipur offers a food experience that is as scenic as it is delicious. The old city near Jagdish Temple hides legendary sweet shops and chaat stalls.",
    famousFoods: [
      { name: "Dal Baati Churma", desc: "The quintessential Rajasthani dish served at its best in Udaipur. Smoky baked wheat balls with rich five-lentil dal and sweet, crumbly churma. Available at every thali restaurant.", price: "₹150-300 per thali", mustTry: true, heat: 0 },
      { name: "Gatte Ki Sabzi", desc: "Gram flour dumplings simmered in a tangy, spiced yogurt-based curry. A Mewari (Udaipur region) specialty that is lighter than many Rajasthani dishes.", price: "₹100-200 per dish", mustTry: true, heat: 1 },
      { name: "Kachori-Sabzi", desc: "Morning breakfast of crispy kachori with spicy aloo-matar sabzi. Every neighborhood has its favorite kachori wala. The old city versions are the most authentic.", price: "₹20-40 per plate", mustTry: true, heat: 1 },
      { name: "Doodh Jalebi", desc: "Crispy jalebis dunked in warm milk -- an Udaipur specialty breakfast item. Sweet, crunchy, and utterly indulgent. Found at sweet shops in the old city.", price: "₹40-80 per plate", mustTry: false, heat: 0 },
      { name: "Malpua", desc: "Sweet pancakes soaked in sugar syrup, often topped with rabri. A traditional Mewari dessert popular during festivals.", price: "₹40-80 per plate", mustTry: false, heat: 0 },
      { name: "Lakeside Rooftop Dining", desc: "Udaipur's unique food experience -- rooftop restaurants with Lake Pichola and City Palace views. Multi-cuisine menus with Rajasthani specialties.", price: "₹300-800 per meal", mustTry: false, heat: 0 },
      { name: "Rajasthani Thali", desc: "A grand platter featuring dal, baati, churma, gatte, papad, ker sangri, bajra roti, and sweets. The best way to taste all of Mewari cuisine in one sitting.", price: "₹200-500 per thali", mustTry: false, heat: 1 },
      { name: "Chai & Biscuits at Ghats", desc: "Simple masala chai at the lakeside ghats with local biscuits. The experience is the attraction -- sipping chai while watching the sun set over Lake Pichola.", price: "₹20-40", mustTry: false, heat: 0 },
    ],
    foodTrail: [
      { time: "7:30 AM", stop: "Old City Sweet Shop, near Jagdish Temple", food: "Kachori-Sabzi & Doodh Jalebi", desc: "Start in the old city with a traditional Mewari breakfast. Hot kachori with spicy sabzi and the unique doodh jalebi.", price: "₹50-80" },
      { time: "9:30 AM", stop: "Jagdish Temple Area", food: "Chai & Malpua", desc: "Walk around the beautiful temple complex and stop for chai and sweet malpua at a local stall.", price: "₹40-60" },
      { time: "11:00 AM", stop: "Hathi Pol Bazaar", food: "Chaat & Lassi", desc: "Explore this vibrant market street for Udaipur chaat -- dahi vada, tikki, and papdi chaat with a local twist.", price: "₹40-80" },
      { time: "1:00 PM", stop: "Natraj Dining Hall / Shreenath", food: "Rajasthani Thali", desc: "Full thali lunch with dal baati churma, gatte ki sabzi, and all the Mewari specialties. Unlimited refills.", price: "₹200-400" },
      { time: "3:30 PM", stop: "Millets of Mewar / Cafe Edelweiss", food: "Lakeside Snacks & Coffee", desc: "Afternoon break at a lakeside cafe. Enjoy the view with local snacks or continental options.", price: "₹150-300" },
      { time: "5:30 PM", stop: "Ambrai or Upre", food: "Rooftop Dinner", desc: "End with a sunset dinner at a rooftop restaurant overlooking Lake Pichola and the illuminated City Palace. A magical food experience.", price: "₹500-1,000" },
    ],
    restaurants: [
      { name: "Ambrai", cuisine: "Multi-cuisine / Rajasthani", budget: "₹500-1,000", location: "Lake Pichola", rating: "4.5" },
      { name: "Natraj Dining Hall", cuisine: "Rajasthani Thali", budget: "₹200-400", location: "Bapu Bazaar", rating: "4.2" },
      { name: "Upre by 1559 AD", cuisine: "Fine Dining", budget: "₹1,000-2,500", location: "Lake Pichola", rating: "4.4" },
      { name: "Millets of Mewar", cuisine: "Healthy / Rajasthani", budget: "₹200-400", location: "Old City", rating: "4.3" },
      { name: "Savage Garden", cuisine: "Cafe / Continental", budget: "₹300-600", location: "Chandpole", rating: "4.2" },
    ],
    faqs: [
      { question: "What food is Udaipur famous for?", answer: "Udaipur is famous for Dal Baati Churma, Gatte Ki Sabzi, Doodh Jalebi, Rajasthani Thali, and lakeside rooftop dining. The Mewari cuisine tradition is lighter and less spicy than Jaipur or Jodhpur styles." },
      { question: "What are the best rooftop restaurants in Udaipur?", answer: "Ambrai (lake-level dining with best views), Upre by 1559 AD (rooftop fine dining), Raaj Bagh (mid-range), and Charcoal by Carlsson. Book in advance for sunset tables, especially October-March." },
      { question: "Can I combine food tour with lake activities?", answer: "Yes! Morning food tour in old city, afternoon boat ride on Lake Pichola, and sunset dinner at a rooftop restaurant. Our drivers plan routes that combine food, heritage, and lake experiences efficiently." },
      { question: "Is Udaipur food vegetarian?", answer: "Predominantly yes. Mewari cuisine is largely vegetarian. Thali restaurants are pure veg. However, lakeside restaurants and tourist-area eateries offer non-veg options. The rooftop restaurants have multi-cuisine menus." },
      { question: "What is Doodh Jalebi?", answer: "Doodh Jalebi is a unique Udaipur breakfast -- crispy hot jalebis dunked in warm sweetened milk. The combination of crunchy and creamy is delightful. Available at sweet shops in the old city early morning." },
      { question: "How much does an Udaipur food tour cost?", answer: "Street food: ₹200-400 per person. Thali lunch: ₹200-500. Rooftop dinner: ₹500-1,500. Our food tour with cab: ₹1,000 (sedan, half-day). The lakeside restaurants are pricier but the experience justifies it." },
    ],
  },
  "mathura": {
    city: "Mathura",
    slug: "mathura-food-tour",
    famousDish: "Mathura Peda",
    duration: "4-5 hours",
    cabFare: "₹800",
    bestTime: "October to March",
    description: "Mathura, the birthplace of Lord Krishna, is a holy city where food is deeply intertwined with devotion. The city is famous for its milk-based sweets -- Mathura Peda is legendary across India. The lanes around Krishna Janmabhoomi temple overflow with lassi shops, peda stalls, and chaat vendors. The entire city is vegetarian, and the food is simple, pure, and incredibly satisfying.",
    famousFoods: [
      { name: "Mathura Peda", desc: "India's most famous peda -- soft, grainy milk fudge flavored with cardamom and saffron. Brijwasi is the most trusted brand. Available in multiple varieties.", price: "₹300-600 per kg", mustTry: true, heat: 0 },
      { name: "Lassi", desc: "Mathura's thick, creamy lassi is served in clay pots at shops near the temples. Sweet, salted, and mango varieties. Some shops have been running for 100+ years.", price: "₹30-60 per glass", mustTry: true, heat: 0 },
      { name: "Kachori-Sabzi", desc: "Morning breakfast staple in Mathura. Crispy kachori with aloo sabzi, served at roadside stalls across the old city. Simple, fresh, and satisfying.", price: "₹20-40 per plate", mustTry: true, heat: 1 },
      { name: "Jalebi-Rabri", desc: "Hot crispy jalebis with cold thick rabri (reduced milk cream). The contrast of hot and cold, crunchy and creamy is magical. Best at old city sweet shops.", price: "₹40-80 per plate", mustTry: false, heat: 0 },
      { name: "Chaat", desc: "Mathura chaat has its own style -- sweeter and tangier. Aloo tikki, golgappe, and dahi puri from stalls near Vishram Ghat are popular.", price: "₹20-50 per plate", mustTry: false, heat: 1 },
      { name: "Temple Prasad", desc: "Various temples offer prasad (blessed food) -- laddoos, peda, and panchamrit (milk-honey-yogurt mix). Krishna Janmabhoomi and Banke Bihari Temple prasad is special.", price: "₹10-50", mustTry: false, heat: 0 },
      { name: "Dubki Wale Aloo", desc: "A Mathura specialty -- small potatoes in a spicy, tangy gravy. A popular lunch item served with puri or rice at local eateries.", price: "₹40-80 per plate", mustTry: false, heat: 1 },
      { name: "Khurchan", desc: "Thin layers of dried milk (similar to malai) scraped from large pans. A Mathura milk specialty, often flavored with saffron. Seasonal winter item.", price: "₹200-400 per kg", mustTry: false, heat: 0 },
    ],
    foodTrail: [
      { time: "7:00 AM", stop: "Old City Kachori Stall", food: "Kachori-Sabzi", desc: "Start with Mathura's classic breakfast near the ghats. Hot, crispy kachori with spicy aloo sabzi. Simple and perfect.", price: "₹30-50" },
      { time: "8:30 AM", stop: "Krishna Janmabhoomi Temple Area", food: "Temple Prasad & Peda", desc: "Visit the birthplace of Lord Krishna and receive blessed prasad. Buy fresh peda from shops right outside the temple.", price: "₹30-100" },
      { time: "10:00 AM", stop: "Brijwasi Sweet Shop", food: "Mathura Peda Tasting", desc: "Visit the most famous peda brand in India. Sample different varieties -- plain, dry fruit, kesar. Buy boxes to take home.", price: "₹100-500" },
      { time: "11:30 AM", stop: "Vishram Ghat Area", food: "Lassi & Jalebi-Rabri", desc: "Walk to the sacred Vishram Ghat and enjoy thick lassi in a clay pot and hot jalebi with cold rabri.", price: "₹60-120" },
      { time: "1:00 PM", stop: "Local Vegetarian Restaurant", food: "Dubki Wale Aloo & Puri", desc: "Lunch at a simple Mathura eatery. The dubki wale aloo with puris is a local favorite you will not find elsewhere.", price: "₹60-120" },
      { time: "3:00 PM", stop: "Holi Gate Area", food: "Chaat & Sweets", desc: "Afternoon chaat walk near Holi Gate. Sample aloo tikki, golgappe, and buy more sweets for the road.", price: "₹50-100" },
    ],
    restaurants: [
      { name: "Brijwasi", cuisine: "Sweets / Vegetarian", budget: "₹100-300", location: "Multiple Outlets", rating: "4.3" },
      { name: "Shankar Sweets", cuisine: "Sweets / Snacks", budget: "₹50-150", location: "Holi Gate", rating: "4.1" },
      { name: "Zaika Restaurant", cuisine: "North Indian Veg", budget: "₹150-300", location: "Near Bus Stand", rating: "4.0" },
      { name: "Hotel Brij Raj Bhawan", cuisine: "Multi-cuisine Veg", budget: "₹200-400", location: "Station Road", rating: "4.1" },
    ],
    faqs: [
      { question: "What food is Mathura famous for?", answer: "Mathura is famous for Mathura Peda (India's most iconic milk sweet), thick Lassi, Kachori-Sabzi, Jalebi-Rabri, and Khurchan (dried milk layers). All food in Mathura is vegetarian due to its sacred status as Krishna's birthplace." },
      { question: "Where is the best Peda in Mathura?", answer: "Brijwasi is the most trusted and famous brand with multiple outlets. Other good options include Shankar Sweets and shops near Krishna Janmabhoomi temple. Always buy from established shops for freshness and quality." },
      { question: "Is all food in Mathura vegetarian?", answer: "Yes, Mathura is a completely vegetarian city. No meat, fish, or eggs are sold in the old city area. Restaurants in the outskirts may have eggs but meat is not available. The city's food culture is entirely plant-based and dairy-based." },
      { question: "Can I combine Mathura food tour with Vrindavan?", answer: "Absolutely! Mathura and Vrindavan are just 12 km apart. Do Mathura food and temples in the morning, then drive to Vrindavan for Banke Bihari Temple, Prem Mandir, and more sweets and lassi. Our cab covers both easily." },
      { question: "Can I visit Mathura from Agra?", answer: "Yes! Mathura is only 50 km from Agra (about 1 hour by car). We offer Agra + Mathura + Vrindavan combined day trips. Add ₹1,500 to your Agra tour for the Mathura-Vrindavan extension." },
      { question: "How much does a Mathura food tour cost?", answer: "Street food: ₹150-300 per person. Sweets shopping: ₹200-500 (to take home). Our food tour with cab: ₹800 (sedan, half-day local). Add ₹500 for Vrindavan extension. Mathura food is very affordable." },
    ],
  },
  "haridwar": {
    city: "Haridwar",
    slug: "haridwar-food-tour",
    famousDish: "Chole Bhature",
    duration: "4-5 hours",
    cabFare: "₹800",
    bestTime: "October to March",
    description: "Haridwar, the gateway to the Gods, is a sacred city where the food is pure, vegetarian, and deeply tied to spiritual traditions. The ghats along the Ganga are lined with halwai (sweet maker) shops, chaat stalls, and lassi corners. The city's chole bhature is legendary, the aloo puri is a pilgrim's staple, and the prasad from temples carries generations of devotion. No onion, no garlic -- just pure, sattvic food.",
    famousFoods: [
      { name: "Chole Bhature", desc: "Haridwar's version is lighter and often made without onion-garlic (sattvic). Mohan Ji Puri Wale is the most famous, with queues from dawn to dusk.", price: "₹60-100 per plate", mustTry: true, heat: 1 },
      { name: "Aloo Puri", desc: "Deep-fried puffed bread with spicy potato curry. A pilgrim's breakfast staple. Every dhaba along the ghats serves it. Simple, filling, and satisfying.", price: "₹40-70 per plate", mustTry: true, heat: 1 },
      { name: "Kachori-Sabzi", desc: "Crispy kachori with spicy sabzi, available at every corner of the old city. The best are found near Har Ki Pauri ghat.", price: "₹20-40 per plate", mustTry: true, heat: 1 },
      { name: "Jalebi", desc: "Hot, crispy jalebis from halwai shops along the ghats. Best eaten fresh in the morning. The shops near Mansa Devi ropeway are popular.", price: "₹20-50 per plate", mustTry: false, heat: 0 },
      { name: "Lassi & Rabri", desc: "Thick lassi and creamy rabri from traditional shops. The clay-pot lassi near Har Ki Pauri is a must-try.", price: "₹30-60 per glass", mustTry: false, heat: 0 },
      { name: "Ganga Jal Lemonade", desc: "Fresh lime water made with Ganga water (filtered). A unique Haridwar experience. Available at stalls along the ghats.", price: "₹10-20 per glass", mustTry: false, heat: 0 },
      { name: "Temple Prasad", desc: "Laddoos, halwa, and panchamrit from various temples. Mansa Devi, Chandi Devi, and Har Ki Pauri temples all offer prasad.", price: "₹10-50", mustTry: false, heat: 0 },
      { name: "Rajma Chawal", desc: "Kidney beans curry with rice -- a North Indian comfort food popular in Haridwar. Many dhabas along Railway Road serve excellent versions.", price: "₹60-100 per plate", mustTry: false, heat: 0 },
    ],
    foodTrail: [
      { time: "6:00 AM", stop: "Har Ki Pauri Ghat Area", food: "Morning Chai & Jalebi", desc: "Watch the sunrise Ganga Aarti while sipping chai and munching on fresh jalebis from a ghat-side stall.", price: "₹20-40" },
      { time: "7:30 AM", stop: "Mohan Ji Puri Wale", food: "Chole Bhature", desc: "Haridwar's most famous food stop. The sattvic chole bhature here draw queues from early morning. Arrive early.", price: "₹70-100" },
      { time: "9:00 AM", stop: "Near Mansa Devi Ropeway", food: "Kachori-Sabzi", desc: "Before or after the Mansa Devi temple visit, enjoy hot kachori-sabzi from the stalls near the ropeway base.", price: "₹30-50" },
      { time: "11:00 AM", stop: "Upper Road / Bara Bazaar", food: "Lassi & Rabri", desc: "Explore the bustling bazaar and cool down with thick lassi in a clay pot and sweet rabri.", price: "₹40-80" },
      { time: "1:00 PM", stop: "Hoshiyar Puri / Big Ben Restaurant", food: "Rajma Chawal & Thali", desc: "Lunch at a popular vegetarian restaurant. Rajma chawal, dal fry, and a simple North Indian thali.", price: "₹100-200" },
      { time: "3:00 PM", stop: "Ghat Area Chaat Stalls", food: "Chaat & Golgappe", desc: "Afternoon chaat walk along the ghats. Dahi bhalle, aloo tikki, and golgappe with Ganga breeze.", price: "₹40-80" },
    ],
    restaurants: [
      { name: "Mohan Ji Puri Wale", cuisine: "Chole Bhature", budget: "₹70-120", location: "Upper Road", rating: "4.4" },
      { name: "Hoshiyar Puri", cuisine: "North Indian Veg", budget: "₹100-250", location: "Railway Road", rating: "4.2" },
      { name: "Big Ben Restaurant", cuisine: "Multi-cuisine Veg", budget: "₹150-300", location: "Railway Road", rating: "4.1" },
      { name: "Chotiwala Restaurant", cuisine: "North Indian Veg", budget: "₹150-300", location: "Near Laxman Jhula (Rishikesh)", rating: "4.0" },
    ],
    faqs: [
      { question: "What food is Haridwar famous for?", answer: "Haridwar is famous for sattvic (no onion, no garlic) Chole Bhature, Aloo Puri, Kachori-Sabzi, Jalebi, Lassi, and temple Prasad. All food in Haridwar is pure vegetarian. Mohan Ji Puri Wale is the most iconic food stop." },
      { question: "Is all food in Haridwar vegetarian?", answer: "Yes! Haridwar is a holy city where only vegetarian food is served. Most traditional establishments also avoid onion and garlic (sattvic cooking). No meat, fish, or eggs are available in the main city area." },
      { question: "Can I combine Haridwar food tour with Rishikesh?", answer: "Yes! Haridwar and Rishikesh are just 20 km apart. Do Haridwar food and Ganga Aarti in the morning, then drive to Rishikesh for cafes, Beatles Ashram, and Ram Jhula. Our cab covers both cities easily." },
      { question: "What is sattvic food?", answer: "Sattvic food is cooked without onion, garlic, and meat. It is believed to promote purity and spiritual clarity. Most traditional restaurants in Haridwar follow sattvic principles. The food is surprisingly flavorful using other spices and herbs." },
      { question: "When is the best time to visit Haridwar?", answer: "October-March for pleasant weather. Kumbh Mela (every 12 years) is the biggest event. Ganga Dussehra (June), Kanwar Yatra (July-August), and major Hindu festivals bring special food offerings. Avoid peak monsoon." },
      { question: "How much does a Haridwar food tour cost?", answer: "Street food: ₹150-300 per person. Restaurant meals: ₹100-250. Our food tour with cab: ₹800 (sedan, half-day local). Add ₹500 for Rishikesh extension. Haridwar food is very affordable." },
    ],
  },
  "pushkar": {
    city: "Pushkar",
    slug: "pushkar-food-tour",
    famousDish: "Malpua",
    duration: "4-5 hours",
    cabFare: "₹800",
    bestTime: "October to March",
    description: "Pushkar is a tiny, sacred lakeside town where food is pure vegetarian and deeply connected to its spiritual heritage. The town has developed a unique cafe culture alongside traditional Rajasthani food, making it a favorite among international travelers. Malpua (sweet pancakes), Dal Baati, and lakeside chai are the highlights. During the famous Pushkar Camel Fair (November), the food scene explodes with special Rajasthani feasts.",
    famousFoods: [
      { name: "Malpua", desc: "Pushkar's signature sweet -- thick pancakes soaked in sugar syrup and topped with rabri. The Brahmin cooks near Pushkar Lake have perfected this over generations.", price: "₹40-80 per plate", mustTry: true, heat: 0 },
      { name: "Dal Baati Churma", desc: "The Rajasthani staple is available everywhere in Pushkar. Smoky baked wheat balls with lentil dal and sweet churma. Best at traditional Rajasthani restaurants.", price: "₹100-250 per thali", mustTry: true, heat: 0 },
      { name: "Poha-Jalebi", desc: "A morning breakfast combination -- flattened rice (poha) with hot jalebis. Pushkar's version is light and flavorful, perfect before a temple visit.", price: "₹30-60 per plate", mustTry: true, heat: 0 },
      { name: "Cafe Culture", desc: "Pushkar has dozens of rooftop cafes serving Israeli, Italian, and continental food alongside Indian dishes. Sunset views over Pushkar Lake from cafe rooftops are magical.", price: "₹200-500 per meal", mustTry: false, heat: 0 },
      { name: "Lassi", desc: "Thick, fresh Rajasthani lassi available in sweet, salted, and fruit varieties. Many cafes make special saffron and rose lassi.", price: "₹40-80 per glass", mustTry: false, heat: 0 },
      { name: "Kachori", desc: "Morning kachori with sabzi from stalls near the lake. Simple, hot, and satisfying. A pilgrim's breakfast.", price: "₹20-40 per plate", mustTry: false, heat: 1 },
      { name: "Temple Prasad", desc: "The Brahma Temple (one of very few Brahma temples in the world) offers special prasad. Laddoos and pedas from temple shops.", price: "₹10-50", mustTry: false, heat: 0 },
      { name: "Aloo Paratha & Curd", desc: "Simple Rajasthani breakfast of stuffed potato paratha with fresh curd. Available at every dhaba and guesthouse.", price: "₹50-100 per plate", mustTry: false, heat: 0 },
    ],
    foodTrail: [
      { time: "7:00 AM", stop: "Lake-side Stalls", food: "Poha-Jalebi & Chai", desc: "Start with a light breakfast by the sacred Pushkar Lake. Watch the morning prayers while enjoying poha and hot chai.", price: "₹30-50" },
      { time: "8:30 AM", stop: "Brahma Temple Area", food: "Kachori-Sabzi & Temple Prasad", desc: "Visit the rare Brahma Temple and pick up prasad. Enjoy kachori from stalls near the temple.", price: "₹30-60" },
      { time: "10:30 AM", stop: "Sweet Shop, Main Market", food: "Malpua & Rabri", desc: "The highlight -- Pushkar's famous malpua. Hot, sweet pancakes topped with thick rabri. Heavenly.", price: "₹50-80" },
      { time: "12:30 PM", stop: "Rajasthani Restaurant", food: "Dal Baati Churma Thali", desc: "Traditional Rajasthani thali lunch. Dal baati churma, gatte ki sabzi, bajra roti, and sweets.", price: "₹150-300" },
      { time: "3:00 PM", stop: "Sunset Cafe / Out of the Blue", food: "Rooftop Cafe Snacks", desc: "Afternoon at a rooftop cafe overlooking the lake. Israeli shakshuka, Italian pasta, or Indian pakoras with masala chai.", price: "₹200-400" },
      { time: "5:30 PM", stop: "Ghat Area", food: "Evening Chai & Snacks", desc: "End with chai at the ghats as the sun sets over Pushkar Lake. Buy some laddoos and malpua for the journey.", price: "₹30-50" },
    ],
    restaurants: [
      { name: "Out of the Blue", cuisine: "Cafe / Continental", budget: "₹200-500", location: "Main Market", rating: "4.4" },
      { name: "Sunset Cafe", cuisine: "Multi-cuisine", budget: "₹200-400", location: "Lake View", rating: "4.3" },
      { name: "Honey & Spice", cuisine: "Cafe / Bakery", budget: "₹150-350", location: "Sadar Bazaar", rating: "4.2" },
      { name: "Om Shiva Garden Restaurant", cuisine: "Indian / Israeli", budget: "₹150-350", location: "Main Market", rating: "4.1" },
    ],
    faqs: [
      { question: "What food is Pushkar famous for?", answer: "Pushkar is famous for Malpua (sweet pancakes with rabri), Dal Baati Churma, Poha-Jalebi breakfast, and its unique rooftop cafe culture. All food is vegetarian. The town blends Rajasthani tradition with backpacker-friendly international cuisine." },
      { question: "Is all food in Pushkar vegetarian?", answer: "Yes! Pushkar is a sacred town and only vegetarian food is served. No meat, fish, or eggs. Alcohol is also officially banned (though some cafes serve discreetly). The food is sattvic and pure." },
      { question: "When is the Pushkar Camel Fair?", answer: "The Pushkar Camel Fair is held in November (dates based on the Hindu calendar, usually around Kartik Purnima). During the fair, the food scene is incredible -- special Rajasthani feasts, desert camp dining, and food stalls everywhere." },
      { question: "Can I combine Pushkar with Ajmer food tour?", answer: "Yes! Ajmer is just 14 km from Pushkar. Visit Ajmer Sharif Dargah and try the non-veg food specialties around Dargah Bazaar, then head to Pushkar for vegetarian lakeside food. Our cab covers both easily." },
      { question: "What is the cafe culture like in Pushkar?", answer: "Pushkar has a thriving rooftop cafe scene catering to international travelers. Israeli food (shakshuka, hummus), Italian (pasta, pizza), and Indian fusion. Sunset Cafe, Out of the Blue, and Honey & Spice are popular." },
      { question: "How much does a Pushkar food tour cost?", answer: "Street food: ₹150-300 per person. Cafe meals: ₹200-500. Our food tour with cab: ₹800 (from Ajmer) or ₹2,500 (from Jaipur day trip). Pushkar is small and walkable but a cab is needed to get there." },
    ],
  },
};
