export const friendsTripData = {
  "rishikesh": {
    slug: "friends-trip-rishikesh",
    destination: "Rishikesh",
    tagline: "Rafting, Camping & Bonfires with Your Squad",
    distance: "240 km from Delhi",
    duration: "2-3 Days",
    bestSeason: "September to June",
    groupSize: "8-15 people",
    vehicle: {
      name: "Tempo Traveller",
      type: "12-17 Seater",
      seats: "12-17",
      features: ["Push-back reclining seats", "Ample luggage space for camping gear", "Music system with AUX/Bluetooth", "AC with individual vents", "Charging points for phones"],
    },
    price: { tempo12: 11000, tempo17: 14000, perPerson12: 920, perPerson17: 825 },
    packageIncludes: ["Delhi to Rishikesh round trip by AC Tempo Traveller", "All toll and parking charges", "Experienced highway driver", "Local Rishikesh sightseeing", "Driver allowance", "Music system for the road trip vibe"],
    adventureActivities: [
      { name: "White Water River Rafting", description: "16 km rafting from Shivpuri to Rishikesh with Grade 3-4 rapids. The ultimate squad adventure with names like Roller Coaster, Golf Course, and Club House rapids.", price: "Rs 800-1,500/person" },
      { name: "Bungee Jumping (83m)", description: "India's highest bungee jump at Jumpin Heights. 83 meters of pure adrenaline. The ultimate dare among friends.", price: "Rs 3,550/person" },
      { name: "Cliff Jumping", description: "Jump from 25-30 feet cliffs into deep river pools at Shivpuri. Safe with guides, thrilling with friends.", price: "Rs 500/person" },
      { name: "Camping & Bonfire", description: "Riverside camp at Shivpuri with tents, bonfire, music, BBQ dinner, and star gazing. The classic friends trip experience.", price: "Rs 1,200-2,500/person" },
      { name: "Flying Fox & Giant Swing", description: "Fly across a valley on a 1 km zipline or experience a giant swing at Jumpin Heights. Screaming with friends is half the fun.", price: "Rs 2,000-3,550/person" },
      { name: "Body Surfing & Beach Volleyball", description: "Free activities at the Shivpuri river beach. Body surf in rapids, play volleyball, and chill on white sand.", price: "Free" },
    ],
    itinerary: [
      { day: 1, title: "Delhi to Rishikesh", description: "Early morning departure (5-6 AM) with music blasting in the Tempo Traveller. Breakfast stop at Murthal for parathas. Reach Rishikesh by noon. Check into riverside camp. Afternoon at Shivpuri beach - volleyball, body surfing. Evening bonfire with BBQ and music." },
      { day: 2, title: "Adventure Day", description: "Morning river rafting (16 km, 3-4 hours). Lunch at camp. Afternoon bungee jumping or cliff jumping for the brave ones. Evening walk at Ram Jhula and Lakshman Jhula. Night bonfire with games, music, and star gazing." },
      { day: 3, title: "Rishikesh to Delhi", description: "Morning yoga session (optional) or Beatles Ashram visit. Brunch at Freedom Cafe or Little Buddha. Depart for Delhi post lunch. Optional Haridwar Ganga Aarti stop. Reach Delhi by 9-10 PM." },
    ],
    campingOptions: [
      { name: "Riverside Camp Shivpuri", description: "Basic tents by the river with bonfire, meals, and adventure activities", priceRange: "Rs 1,200-1,800/person" },
      { name: "Luxury Camp Byasi", description: "Premium tents with attached washroom, multi-cuisine food, and all activities", priceRange: "Rs 2,500-4,000/person" },
      { name: "Hostel McLeodganj", description: "Budget dorm beds with common areas, kitchen, and social vibes", priceRange: "Rs 500-800/person" },
    ],
    nightlifeOptions: [
      "Bonfire with music and BBQ at riverside camps",
      "The 60s Cafe and Beatles Cafe in Rishikesh",
      "Night trek to Neer Garh Waterfall (guided)",
      "Star gazing sessions at Shivpuri beach",
      "Card games and Mafia nights at camp",
    ],
    budgetBreakdown: {
      transport: "Rs 825-920/person (Tempo Traveller round trip)",
      camping: "Rs 1,200-2,500/person (2 nights with meals)",
      rafting: "Rs 800-1,500/person",
      bungee: "Rs 3,550/person (optional)",
      food: "Rs 500-1,000/person (extra meals)",
      total: "Rs 3,500-8,500/person for 2-3 days",
    },
    safetyFeatures: [
      "GPS-tracked Tempo Traveller",
      "Experienced highway driver",
      "All adventure activities with certified operators",
      "Life jackets and helmets for rafting",
      "First-aid kit in vehicle",
      "24/7 emergency helpline",
      "Camp security and staff",
    ],
    faqs: [
      { question: "How much does a friends trip to Rishikesh cost per person?", answer: "A 2-3 day Rishikesh friends trip costs Rs 3,500-8,500 per person depending on activities. Transport by Tempo Traveller is Rs 825-920/person, camping Rs 1,200-2,500/person, and rafting Rs 800-1,500/person. Bungee (Rs 3,550) is optional." },
      { question: "What is the best vehicle for a group trip to Rishikesh?", answer: "A 12-seater or 17-seater Tempo Traveller is perfect. It fits 8-15 friends comfortably with luggage space, music system, AC, and reclining seats. Much better than multiple cars - everyone travels together!" },
      { question: "Is river rafting safe for beginners?", answer: "Yes! Rishikesh rafting is safe for beginners (Grade 3 rapids). All participants get life jackets, helmets, and professional guides. The 16 km Shivpuri-Rishikesh stretch is the most popular for groups." },
      { question: "Can we play music in the Tempo Traveller?", answer: "Absolutely! Our Tempo Travellers come with music systems with Bluetooth/AUX connectivity. Create your road trip playlist and enjoy the drive. The music system makes the 5-6 hour drive a party on wheels." },
      { question: "What is the best time for a Rishikesh friends trip?", answer: "September-November is the best (pleasant weather, exciting rapids after monsoon). February-May is also great. Avoid July-August (monsoon closes rafting). December-January is cold but peaceful." },
      { question: "Can we book camping and activities through you?", answer: "We primarily provide transport (Tempo Traveller), but we can recommend and help coordinate trusted camps and activity operators. Many groups book transport with us and camps directly." },
    ],
  },
  "manali": {
    slug: "friends-trip-manali",
    destination: "Manali",
    tagline: "Snow, Paragliding & Mountain Madness with Friends",
    distance: "540 km from Delhi",
    duration: "4-5 Days",
    bestSeason: "March to June, December to February",
    groupSize: "8-15 people",
    vehicle: {
      name: "Tempo Traveller",
      type: "12-17 Seater",
      seats: "12-17",
      features: ["Push-back reclining seats for overnight drive", "Huge luggage capacity", "Music system with Bluetooth", "AC with individual vents", "Curtains for privacy"],
    },
    price: { tempo12: 18000, tempo17: 22000, perPerson12: 1500, perPerson17: 1295 },
    packageIncludes: ["Delhi to Manali round trip by AC Tempo Traveller", "All toll and parking", "Hill-experienced driver", "Solang Valley & Manali sightseeing", "Driver night allowance", "Music system for road trip"],
    adventureActivities: [
      { name: "Paragliding at Solang Valley", description: "Tandem paragliding over the stunning Solang Valley. 15-20 minute flight with Himalayan views. Everyone gets photos and video.", price: "Rs 1,500-2,500/person" },
      { name: "Skiing & Snow Activities", description: "Skiing, snowboarding, snow tubing at Solang Valley (Dec-Mar). Even beginners can try with instructors.", price: "Rs 500-2,000/person" },
      { name: "River Rafting at Kullu", description: "Grade 2-3 rapids on the Beas River. 12 km rafting stretch perfect for groups who want moderate adventure.", price: "Rs 700-1,200/person" },
      { name: "Zorbing at Solang", description: "Roll down a snow-covered slope inside a giant transparent ball. Hilarious with friends watching and recording.", price: "Rs 500-800/person" },
      { name: "Mountain Biking", description: "Rent mountain bikes and ride through Manali to Old Manali or along the Beas River trail. Great group activity.", price: "Rs 500-800/person" },
      { name: "Rohtang Pass Snow Fight", description: "Reach 3,978m and have the most epic snowball fight. Snow available June-October at the top.", price: "Included in sightseeing" },
    ],
    itinerary: [
      { day: 1, title: "Delhi to Manali", description: "Early departure (3-4 AM) or overnight drive. Road trip playlist on full volume. Breakfast at Murthal, lunch at Chandigarh/Mandi. Arrive Manali by evening. Check into hotel/hostel. Evening Mall Road exploration." },
      { day: 2, title: "Solang Valley Adventure", description: "Full day at Solang Valley. Paragliding, zorbing, snow activities. Group photos in snow. Evening cafe hopping in Old Manali. Bonfire at hotel with games." },
      { day: 3, title: "Rohtang Pass / Kullu", description: "Drive to Rohtang Pass (if open) for snow fights and views. Or drive to Kullu for river rafting. Afternoon at Naggar Castle. Evening group dinner at a riverside restaurant." },
      { day: 4, title: "Manali Exploration", description: "Visit Hadimba Temple, Vashisht Hot Springs, Tibetan Monastery. Afternoon mountain biking or Club House games. Evening shopping for souvenirs. Last night bonfire party." },
      { day: 5, title: "Manali to Delhi", description: "Post breakfast departure. Scenic drive back through Kullu Valley. Group photo stops at viewpoints. Dinner at Murthal. Reach Delhi by midnight." },
    ],
    campingOptions: [
      { name: "Sethan Village Camp", description: "Camp at 2,700m with mountain views, bonfire, and snow (winter)", priceRange: "Rs 1,500-2,500/person" },
      { name: "Hamta Valley Camp", description: "Riverside camp at Hamta with trekking and adventure activities", priceRange: "Rs 2,000-3,500/person" },
      { name: "Manali Hostels", description: "Dorm beds with common areas, games room, and group vibe", priceRange: "Rs 400-800/person" },
    ],
    nightlifeOptions: [
      "Old Manali cafe scene - live music, bonfire, chill vibes",
      "Johnson Bar and Restaurant - Manali's popular hangout",
      "Rooftop restaurants with mountain views",
      "Bonfire and BBQ at hotel/camp",
      "Card games, Mafia, Truth or Dare at the hotel",
    ],
    budgetBreakdown: {
      transport: "Rs 1,295-1,500/person (Tempo Traveller round trip)",
      hotel: "Rs 500-1,500/person/night (shared rooms/dorms)",
      paragliding: "Rs 1,500-2,500/person",
      rafting: "Rs 700-1,200/person",
      food: "Rs 500-1,000/person/day",
      total: "Rs 6,000-15,000/person for 4-5 days",
    },
    safetyFeatures: [
      "GPS-tracked Tempo Traveller",
      "Experienced hill driver with 5+ years on Manali route",
      "Music system and entertainment for long drive",
      "All adventure operators are certified",
      "First-aid kit and oxygen cylinder",
      "24/7 emergency helpline",
      "Rohtang permit assistance",
    ],
    faqs: [
      { question: "How much does a Manali friends trip cost per person?", answer: "A 4-5 day Manali trip costs Rs 6,000-15,000 per person. Transport is Rs 1,295-1,500/person by Tempo Traveller, hotel Rs 500-1,500/person/night, and activities Rs 2,000-5,000/person total." },
      { question: "Is Tempo Traveller comfortable for the long Manali drive?", answer: "Our Tempo Travellers have push-back reclining seats, AC, curtains, and music system. The 12-14 hour drive is comfortable with planned stops. Many groups do an overnight drive to save a day." },
      { question: "Can we do an overnight drive to Manali?", answer: "Yes! Many friend groups prefer leaving Delhi at 10-11 PM and reaching Manali by morning. The Tempo Traveller's reclining seats allow sleeping. We provide experienced night drivers for this route." },
      { question: "What is the best time for a Manali friends trip?", answer: "March-June for snow at Solang + paragliding. December-February for full snow experience in Manali town. Avoid July-September monsoon (landslide risk). October-November is pleasant but no snow." },
      { question: "Do we need a Rohtang Pass permit?", answer: "Yes, Rohtang Pass requires an online permit (Rs 550/person). We help you apply and get permits. Only 1,200 vehicles are allowed per day, so book early. Permits are not needed for Solang Valley." },
      { question: "Can we fit 15 people in one Tempo Traveller?", answer: "A 17-seater Tempo Traveller comfortably fits 15 people with luggage. For 12-13 friends, a 12-seater is sufficient. For groups above 17, we arrange two vehicles at discounted rates." },
    ],
  },
  "kasol": {
    slug: "friends-trip-kasol",
    destination: "Kasol",
    tagline: "Mini Israel of India - Trek, Chill & Vibe",
    distance: "520 km from Delhi",
    duration: "3-4 Days",
    bestSeason: "March to June, September to November",
    groupSize: "8-15 people",
    vehicle: {
      name: "Tempo Traveller",
      type: "12-17 Seater",
      seats: "12-17",
      features: ["Push-back seats for mountain roads", "Music system for vibes", "Luggage space for trekking gear", "AC with individual vents", "Sturdy hill suspension"],
    },
    price: { tempo12: 16000, tempo17: 20000, perPerson12: 1335, perPerson17: 1175 },
    packageIncludes: ["Delhi to Kasol round trip by AC Tempo Traveller", "All toll and parking", "Hill-experienced driver", "Kasol and Manikaran sightseeing", "Driver night allowance", "Music system for the journey"],
    adventureActivities: [
      { name: "Kheerganga Trek", description: "12 km trek to natural hot springs at 2,960m. Camp overnight with bonfire and stargazing. The trek passes through forests, waterfalls, and meadows.", price: "Rs 1,500-2,500/person (with camping)" },
      { name: "Tosh Village Trek", description: "Short 2 km uphill walk to the charming Tosh village with stunning valley views and laid-back cafes.", price: "Free (self-guided)" },
      { name: "Malana Village Visit", description: "Visit the ancient village of Malana (restricted entry, guided only). Unique culture and stunning mountain setting.", price: "Rs 500/person (guide fee)" },
      { name: "River Crossing & Rock Climbing", description: "Cross the Parvati River on makeshift bridges and try rock climbing at designated spots near Kasol.", price: "Rs 300-500/person" },
      { name: "Riverside Chilling", description: "The classic Kasol activity - sit by the Parvati River, skip stones, play guitar, and just vibe with friends.", price: "Free" },
      { name: "Manikaran Hot Springs", description: "Natural hot sulfur springs where you can cook eggs. Visit the Gurudwara and temple. Spiritual and unique.", price: "Free" },
    ],
    itinerary: [
      { day: 1, title: "Delhi to Kasol", description: "Overnight departure from Delhi (10-11 PM) or early morning (4 AM). Music and road trip games. Breakfast at Chandigarh. Drive through scenic Kullu Valley. Reach Kasol by afternoon. Settle into guesthouse. Evening at riverside." },
      { day: 2, title: "Kasol & Manikaran", description: "Morning walk by Parvati River. Brunch at Evergreen Cafe or Jim Morrison Cafe. Visit Manikaran Hot Springs and Gurudwara. Evening trek to Chalal village for sunset views. Night bonfire and music." },
      { day: 3, title: "Kheerganga Trek", description: "Early departure for Kheerganga trek (6-7 hours up). Trek through forests and waterfalls. Reach hot springs by afternoon. Camp overnight at Kheerganga. Bonfire under billions of stars." },
      { day: 4, title: "Return to Delhi", description: "Early morning hot spring dip at Kheerganga. Trek down (4-5 hours). Return to Kasol. Late lunch. Depart for Delhi. Overnight drive back or stop at Mandi. Reach Delhi by morning." },
    ],
    campingOptions: [
      { name: "Kheerganga Campsite", description: "Tent at the top with hot springs, bonfire, and billion-star sky", priceRange: "Rs 1,500-2,500/person" },
      { name: "Kasol Riverside Camp", description: "Tents by the Parvati River with bonfire and meals", priceRange: "Rs 1,000-1,800/person" },
      { name: "Kasol Hostels/Guesthouses", description: "Budget rooms and dorms in Kasol village with cafe vibes", priceRange: "Rs 300-800/person" },
    ],
    nightlifeOptions: [
      "Riverside bonfire with guitar and music",
      "Jim Morrison Cafe - legendary Kasol hangout",
      "Evergreen Cafe - Israeli food and chill vibes",
      "Chalal village evening walk with mountain views",
      "Star gazing at Kheerganga campsite",
    ],
    budgetBreakdown: {
      transport: "Rs 1,175-1,335/person (Tempo Traveller round trip)",
      stay: "Rs 300-800/person/night (guesthouse/hostel)",
      kheerganga: "Rs 1,500-2,500/person (trek + camping)",
      food: "Rs 400-800/person/day",
      total: "Rs 4,000-10,000/person for 3-4 days",
    },
    safetyFeatures: [
      "GPS-tracked Tempo Traveller",
      "Experienced Kullu Valley hill driver",
      "Trek guides available for Kheerganga",
      "First-aid kit in vehicle",
      "24/7 emergency helpline",
      "Group safety briefing before treks",
    ],
    faqs: [
      { question: "How much does a Kasol friends trip cost per person?", answer: "A 3-4 day Kasol trip costs Rs 4,000-10,000 per person. Transport by Tempo Traveller is Rs 1,175-1,335/person, guesthouse Rs 300-800/person/night, and Kheerganga trek Rs 1,500-2,500/person. Kasol is budget-friendly!" },
      { question: "Is the road to Kasol safe?", answer: "The road to Kasol via Kullu-Bhuntar is well-maintained. The last 30 km from Bhuntar to Kasol is a scenic but narrow mountain road. Our experienced hill drivers handle it safely." },
      { question: "How difficult is the Kheerganga trek?", answer: "Kheerganga is a moderate trek (12 km one way, 6-7 hours up, 4-5 hours down). Anyone with basic fitness can do it. The trail is well-marked. The hot springs at the top make it all worth it." },
      { question: "What should we carry for Kasol?", answer: "Comfortable trekking shoes, warm layers, rain jacket, power bank (limited charging), torch, basic first-aid, and camera. For Kheerganga, add a day pack, water bottle, and energy snacks." },
      { question: "Is there phone network in Kasol?", answer: "BSNL works best in Kasol. Airtel and Jio have patchy coverage. At Kheerganga, there is almost no network. Embrace the digital detox! Inform family before trekking up." },
      { question: "Can we do Kasol without Kheerganga?", answer: "Yes! Kasol has plenty to do - Manikaran Hot Springs, Tosh Village, Chalal Walk, riverside cafes, and the laid-back vibe. Kheerganga is a bonus for the adventurous, not mandatory." },
    ],
  },
  "jaisalmer": {
    slug: "friends-trip-jaisalmer",
    destination: "Jaisalmer",
    tagline: "Desert Safari, Dunes & Starry Nights with the Gang",
    distance: "780 km from Delhi",
    duration: "4-5 Days",
    bestSeason: "October to March",
    groupSize: "8-15 people",
    vehicle: {
      name: "Tempo Traveller",
      type: "12-17 Seater",
      seats: "12-17",
      features: ["AC essential for Rajasthan heat", "Push-back seats for long drive", "Music system with Bluetooth", "Large luggage capacity", "Comfortable highway cruiser"],
    },
    price: { tempo12: 24000, tempo17: 30000, perPerson12: 2000, perPerson17: 1765 },
    packageIncludes: ["Delhi to Jaisalmer round trip by AC Tempo Traveller", "All toll and parking", "Experienced Rajasthan driver", "Local Jaisalmer sightseeing", "Sam Sand Dunes visit", "Driver night allowance"],
    adventureActivities: [
      { name: "Desert Safari on Camels", description: "Ride camels into the Sam Sand Dunes at sunset. The golden desert stretching to the horizon is a sight your group will never forget.", price: "Rs 800-1,500/person" },
      { name: "Dune Bashing (Jeep Safari)", description: "Adrenaline-pumping jeep ride over sand dunes. Screaming, laughing, and bouncing through the desert together.", price: "Rs 1,500-2,500/person" },
      { name: "Desert Camping with Cultural Show", description: "Sleep under a billion stars on the dunes. Rajasthani folk music, fire dance, BBQ dinner, and desert bonfire.", price: "Rs 2,000-4,000/person" },
      { name: "Parasailing at Sam Dunes", description: "Get pulled into the sky over the desert by a jeep. See the vast Thar Desert from above.", price: "Rs 500-800/person" },
      { name: "Quad Biking on Dunes", description: "Ride ATVs over the golden sand dunes. No experience needed, just throttle and go!", price: "Rs 500-1,000/person" },
      { name: "Jaisalmer Fort Night Walk", description: "Explore the living fort after dark when it's lit up golden. The narrow lanes, rooftop cafes, and fort walls are magical at night.", price: "Free" },
    ],
    itinerary: [
      { day: 1, title: "Delhi to Jaisalmer", description: "Overnight departure from Delhi (8-9 PM) or early morning (4 AM). The 12-14 hour drive passes through Jodhpur. Road trip playlist and games. Arrive Jaisalmer by evening. Check into hotel near fort." },
      { day: 2, title: "Jaisalmer Fort & City", description: "Morning Jaisalmer Fort exploration - Jain Temples, Palace Museum, havelis. Visit Patwon Ki Haveli and Salim Singh Ki Haveli. Afternoon at Gadisar Lake. Evening at rooftop cafe with fort view." },
      { day: 3, title: "Sam Sand Dunes", description: "Afternoon drive to Sam Sand Dunes (40 km). Camel safari at sunset. Dune bashing, quad biking, parasailing. Evening cultural show with folk music and fire dance. Night camping under stars with BBQ dinner." },
      { day: 4, title: "Desert & Departure", description: "Sunrise at sand dunes. Return to Jaisalmer. Visit Kuldhara Ghost Village (abandoned 200 years ago). Post lunch departure for Delhi. Overnight drive or stop at Jodhpur." },
      { day: 5, title: "Arrive Delhi", description: "Arrive Delhi by morning if overnight drive. Or explore Jodhpur (Mehrangarh Fort) if stopping and arrive Delhi by evening." },
    ],
    campingOptions: [
      { name: "Sam Sand Dunes Luxury Camp", description: "AC Swiss tents on the dunes with cultural show, meals, and activities", priceRange: "Rs 3,000-5,000/person" },
      { name: "Sam Dunes Basic Camp", description: "Non-AC tents with bonfire, folk show, and dinner on the dunes", priceRange: "Rs 1,500-2,500/person" },
      { name: "Jaisalmer Fort Hostels", description: "Rooftop dorm beds inside the living fort with epic views", priceRange: "Rs 400-800/person" },
    ],
    nightlifeOptions: [
      "Desert camping with folk music and fire dance",
      "Jaisalmer Fort rooftop cafes (1st Gate, Kuku Coffee Shop)",
      "Stargazing in the desert - zero light pollution",
      "Fort night walk through 800-year-old lanes",
      "Gadisar Lake evening walk",
    ],
    budgetBreakdown: {
      transport: "Rs 1,765-2,000/person (Tempo Traveller round trip)",
      hotel: "Rs 500-1,500/person/night",
      desert_camp: "Rs 1,500-5,000/person (one night with activities)",
      camelSafari: "Rs 800-1,500/person",
      food: "Rs 400-800/person/day",
      total: "Rs 7,000-18,000/person for 4-5 days",
    },
    safetyFeatures: [
      "GPS-tracked Tempo Traveller",
      "Experienced Rajasthan highway driver",
      "Desert safari with trained guides",
      "First-aid kit in vehicle",
      "24/7 emergency helpline",
      "Campsite security staff",
    ],
    faqs: [
      { question: "How much does a Jaisalmer friends trip cost per person?", answer: "A 4-5 day Jaisalmer trip costs Rs 7,000-18,000 per person. Transport by Tempo Traveller is Rs 1,765-2,000/person, desert camping Rs 1,500-5,000/person, and other activities Rs 2,000-5,000/person." },
      { question: "Is the long drive to Jaisalmer worth it?", answer: "Absolutely! The road trip through Rajasthan with friends is half the fun. The 12-14 hour drive passes through the changing landscape from green to golden desert. With music and games, it flies by." },
      { question: "When is the best time for Jaisalmer?", answer: "October to March is ideal with pleasant desert weather (15-25 deg C). Avoid April-September when temperatures exceed 45 deg C. The Desert Festival in February is spectacular." },
      { question: "Is desert camping safe?", answer: "Yes! Established camps at Sam Sand Dunes are safe and well-managed. They have security staff, fenced areas, and well-organized cultural programs. The desert is peaceful and safe at night." },
      { question: "Can we add Jodhpur to the Jaisalmer trip?", answer: "Yes! Jodhpur (Blue City) is on the route, 285 km from Jaisalmer. Add 1 day for Mehrangarh Fort, blue city walk, and the famous Mirchi Vada. We can plan a Jaisalmer + Jodhpur combo." },
      { question: "What should we wear in the desert?", answer: "Wear light, loose cotton clothes. Carry sunglasses, sunscreen, and a scarf/bandana for sand protection. Comfortable walking shoes for fort exploration. Layer up for cold desert nights (especially December-January)." },
    ],
  },
  "goa": {
    slug: "friends-trip-goa-from-delhi",
    destination: "Goa",
    tagline: "Beaches, Parties & Good Times with Your Crew",
    distance: "Flight + Local by Tempo",
    duration: "4-5 Days",
    bestSeason: "November to February",
    groupSize: "8-15 people",
    vehicle: {
      name: "Tempo Traveller (Goa Local)",
      type: "12-17 Seater",
      seats: "12-17",
      features: ["AC for Goa heat", "Music system for beach vibes", "Spacious for beach gear", "Local Goa driver who knows hidden spots", "Flexible scheduling for party hours"],
    },
    price: { tempo12: 8000, tempo17: 10000, perPerson12: 670, perPerson17: 590, note: "Goa local transport only. Flights extra." },
    packageIncludes: ["Airport pickup and drop in Goa", "4-5 days Goa local sightseeing by Tempo Traveller", "North Goa and South Goa beach tours", "Church and fort visits", "Driver allowance", "Flexible timing for nightlife"],
    adventureActivities: [
      { name: "Water Sports at Baga Beach", description: "Parasailing, jet ski, banana boat, bumper ride, and speed boat. The complete water sports package for the squad.", price: "Rs 1,500-3,000/person (combo)" },
      { name: "Scuba Diving at Grande Island", description: "Explore underwater coral reefs and marine life. Beginner-friendly with instructors. Unique group experience.", price: "Rs 3,500-5,000/person" },
      { name: "Dudhsagar Waterfall Trip", description: "India's 4th highest waterfall. Jeep ride through the jungle followed by swimming under the 310m cascade.", price: "Rs 1,500-2,000/person" },
      { name: "Casino Night", description: "Try your luck at one of Goa's floating casinos. Big Daddy, Deltin Royale offer gaming, dinner, and entertainment.", price: "Rs 2,500-5,000/person" },
      { name: "Kayaking in Backwaters", description: "Paddle through Goa's mangrove backwaters and spot crocodiles, kingfishers, and eagles. Peaceful group adventure.", price: "Rs 800-1,500/person" },
      { name: "Sunset Cruise on Mandovi", description: "Party cruise on the Mandovi River with DJ music, snacks, and stunning sunset views. Great for groups.", price: "Rs 500-1,200/person" },
    ],
    itinerary: [
      { day: 1, title: "Arrive Goa", description: "Fly from Delhi to Goa (2.5 hours). Tempo Traveller airport pickup. Check into North Goa villa/hostel. Evening at Baga/Calangute beach. Night at Tito's Lane or Club Cubana." },
      { day: 2, title: "North Goa Beach Hopping", description: "Morning water sports at Baga Beach. Visit Vagator Beach and Chapora Fort (Dil Chahta Hai point!). Afternoon at Anjuna flea market (Wednesday). Sunset at Morjim/Ashwem Beach. Night party at Curlies or Hill Top." },
      { day: 3, title: "Adventure Day", description: "Full day Dudhsagar Waterfall trip (or scuba diving at Grande Island). Return by evening. Night at casino or Tito's." },
      { day: 4, title: "South Goa & Culture", description: "Drive to South Goa. Visit Basilica of Bom Jesus (UNESCO), Se Cathedral. Relax at Palolem Beach. Sunset kayaking in backwaters. Evening sunset cruise on Mandovi River." },
      { day: 5, title: "Last Day & Departure", description: "Morning at Dona Paula or Miramar Beach. Shopping at Mapusa market. Airport drop for evening flight to Delhi." },
    ],
    campingOptions: [
      { name: "Beach Villa Rental", description: "Private villa near Baga/Calangute for the entire group. Pool, BBQ, party space", priceRange: "Rs 1,000-2,500/person/night" },
      { name: "Goa Hostels", description: "Dorm beds at Jungle Hostel, The Hosteller, or Woke Hostel with pool and party vibes", priceRange: "Rs 500-1,000/person/night" },
      { name: "Beach Huts Palolem", description: "Beachfront huts with waves as your alarm. Classic Goa experience", priceRange: "Rs 800-2,000/person/night" },
    ],
    nightlifeOptions: [
      "Tito's Lane, Baga - Goa's famous party street",
      "Club Cubana - Nightclub on the hill",
      "Curlies Beach Shack, Anjuna - Beachside parties",
      "Silent Noise Club, Palolem - Silent disco on the beach",
      "Casino boats on Mandovi River",
      "Saturday Night Market, Arpora",
    ],
    budgetBreakdown: {
      flights: "Rs 3,000-7,000/person (Delhi-Goa return)",
      transport: "Rs 590-670/person (Tempo Traveller in Goa, 4-5 days)",
      stay: "Rs 500-2,500/person/night",
      waterSports: "Rs 1,500-3,000/person",
      food: "Rs 500-1,500/person/day",
      nightlife: "Rs 500-2,000/person/night",
      total: "Rs 10,000-30,000/person for 4-5 days (including flights)",
    },
    safetyFeatures: [
      "GPS-tracked Tempo Traveller",
      "Local Goa driver who knows safe routes",
      "Available for late-night pickups from clubs",
      "First-aid kit in vehicle",
      "24/7 emergency helpline",
      "Water sports with certified operators only",
    ],
    faqs: [
      { question: "How much does a Goa friends trip cost per person?", answer: "A 4-5 day Goa trip costs Rs 10,000-30,000 per person including flights from Delhi (Rs 3,000-7,000), Goa transport (Rs 590-670/person), stay (Rs 500-2,500/night), activities, food, and nightlife." },
      { question: "Should we drive to Goa or fly?", answer: "Fly! Delhi to Goa is 1,800 km and takes 30+ hours by road. Flights are just 2.5 hours and cost Rs 3,000-7,000. We provide Tempo Traveller for local Goa transport from the airport." },
      { question: "Is Tempo Traveller useful in Goa?", answer: "Yes! A Tempo Traveller is perfect for group beach hopping, Dudhsagar trip, and moving between North and South Goa. It is much cheaper than separate scooter rentals for a large group." },
      { question: "When is the best time for a Goa friends trip?", answer: "November to February is peak season with the best weather, parties, and festivals. December-January has New Year parties but higher prices. October and March are shoulder season with fewer crowds and lower prices." },
      { question: "North Goa or South Goa for friends?", answer: "North Goa is for parties, nightlife, water sports, and energy. South Goa is for relaxation, clean beaches, and peace. Most friend groups stay in North Goa and do a day trip to South Goa." },
      { question: "Can the Tempo Traveller wait while we party at night?", answer: "Yes! Our drivers are flexible with group schedules. They can drop you at clubs and pick up when you are ready. Night pickup is included in the package. Just coordinate timings with the driver." },
    ],
  },
  "bachelor": {
    slug: "bachelor-trip-north-india",
    destination: "Bachelor Trip - North India",
    tagline: "The Ultimate Pre-Wedding Adventure with the Boys (or Girls!)",
    distance: "Varies by destination",
    duration: "3-5 Days",
    bestSeason: "September to June",
    groupSize: "10-20 people",
    vehicle: {
      name: "Tempo Traveller / Mini Bus",
      type: "17-27 Seater",
      seats: "17-27",
      features: ["Push-back reclining seats", "Massive luggage space", "Premium music system with subwoofer", "AC with individual vents", "Charging points", "LED interior lights for party vibe"],
    },
    price: { tempo17: 16000, minibus: 22000, perPerson17: 940, perPerson27: 815, note: "Base price for Rishikesh. Varies by destination." },
    packageIncludes: ["Round trip by AC Tempo Traveller / Mini Bus", "All toll and parking charges", "Experienced driver", "Destination sightseeing", "Driver allowance", "Premium music system", "Bachelor party banner on vehicle (on request)"],
    topDestinations: [
      { name: "Rishikesh", description: "Rafting, bungee, camping, bonfire - the #1 bachelor trip destination. 240 km from Delhi.", price: "Rs 815-940/person transport" },
      { name: "Manali", description: "Snow, paragliding, Old Manali nightlife. 540 km from Delhi.", price: "Rs 1,295-1,500/person transport" },
      { name: "Kasol + Kheerganga", description: "Trekking, hot springs, riverside chilling. 520 km from Delhi.", price: "Rs 1,175-1,335/person transport" },
      { name: "Jaisalmer", description: "Desert camp, dune bashing, starry nights. 780 km from Delhi.", price: "Rs 1,765-2,000/person transport" },
      { name: "Bir Billing", description: "India's paragliding capital. Fly over Himalayas. 500 km from Delhi.", price: "Rs 1,200-1,500/person transport" },
      { name: "Chopta-Tungnath", description: "High-altitude trek to world's highest Shiva temple. 420 km from Delhi.", price: "Rs 1,100-1,300/person transport" },
    ],
    adventureActivities: [
      { name: "River Rafting Package", description: "16-24 km rafting with cliff jumping and body surfing. Complete water adventure package.", price: "Rs 800-2,000/person" },
      { name: "Bungee + Flying Fox Combo", description: "India's highest bungee (83m) and 1 km zipline at Rishikesh. Double dare for the bachelor.", price: "Rs 5,000-6,000/person" },
      { name: "Paragliding", description: "Tandem paragliding at Bir Billing or Solang Valley. Videos included for group roasting later.", price: "Rs 1,500-2,500/person" },
      { name: "Desert Safari Package", description: "Camel ride, dune bashing, quad biking, and desert camping at Jaisalmer.", price: "Rs 3,000-6,000/person" },
      { name: "Camping & Bonfire Night", description: "Riverside or mountain camp with bonfire, BBQ, music, and bachelor games.", price: "Rs 1,200-3,000/person" },
      { name: "Trekking Package", description: "Group trek to Kheerganga, Triund, Chandrashila, or Kedarkantha.", price: "Rs 2,000-5,000/person" },
    ],
    itinerary: [
      { day: 1, title: "The Grand Departure", description: "Decorated Tempo Traveller pickup from groom's house (or bride's for bachelorette!). Music, snacks, and party on wheels. Drive to chosen destination. Check-in and evening bonfire with bachelor games." },
      { day: 2, title: "Adventure Day", description: "Full day of adventure activities based on destination - rafting, paragliding, dune bashing, or trekking. Group photos and videos. Evening celebration dinner with cake and speeches." },
      { day: 3, title: "Exploration & Fun", description: "Local sightseeing, shopping, and more activities. Free time for relaxation. Afternoon games and challenges. Evening farewell party with bonfire." },
      { day: 4, title: "Return Journey", description: "Post breakfast departure. Highlights reel playing on phones. Drive back with stops for food. Arrive Delhi with memories for a lifetime." },
    ],
    bachelorGameIdeas: [
      "Dare challenges during rafting",
      "Best embarrassing story about the bachelor",
      "Scavenger hunt at the destination",
      "Group cooking challenge at camp",
      "Truth or Dare around the bonfire",
      "Bachelor trivia - how well do friends know the groom/bride",
    ],
    budgetBreakdown: {
      transport: "Rs 815-2,000/person (varies by destination and vehicle)",
      stay: "Rs 500-2,000/person/night",
      activities: "Rs 2,000-8,000/person",
      food: "Rs 400-1,000/person/day",
      celebration: "Rs 200-500/person (cake, decorations, props)",
      total: "Rs 5,000-20,000/person for 3-5 days",
    },
    safetyFeatures: [
      "GPS-tracked Tempo Traveller / Mini Bus",
      "Experienced route drivers",
      "All adventure operators certified",
      "First-aid kit in vehicle",
      "24/7 emergency helpline",
      "Designated driver - your group can relax",
      "Flexible timing for celebrations",
    ],
    faqs: [
      { question: "What is the best destination for a bachelor trip from Delhi?", answer: "Rishikesh is #1 for bachelor trips - closest (240 km), most adventure options (rafting, bungee, camping), and budget-friendly. Manali is great for snow, Kasol for trekking vibes, and Jaisalmer for a desert experience." },
      { question: "How much does a bachelor trip cost per person?", answer: "A bachelor trip costs Rs 5,000-20,000 per person depending on destination and activities. Rishikesh is cheapest (Rs 5,000-10,000), Jaisalmer is pricier (Rs 10,000-20,000). We help plan within your group budget." },
      { question: "Can you fit 20 people in one vehicle?", answer: "A 17-seater Tempo Traveller fits up to 17 comfortably. For 18-27 people, we have mini buses. For 20+ people, a 27-seater mini bus (Rs 22,000+) is ideal. We can also arrange 2 Tempo Travellers at group rates." },
      { question: "Can you decorate the vehicle for the bachelor party?", answer: "Yes! We offer vehicle decoration with banners, balloons, and party props for Rs 1,500. We can add a just getting married or bachelor party banner. Your group sets the vibe, we provide the wheels." },
      { question: "Do you do bachelorette trips too?", answer: "Absolutely! We do bachelorette trips with the same destinations and activities. Popular bachelorette choices include Rishikesh (camping + yoga), Kasol (trekking + cafes), and Goa (beaches + parties)." },
      { question: "Can the group drink alcohol on the Tempo Traveller?", answer: "While we do not officially serve alcohol, groups are free to carry their own refreshments. We do request responsible behavior and no littering. Our drivers are non-judgmental and professional." },
    ],
  },
};

export const friendsTripSlugs = Object.keys(friendsTripData);

export function getFriendsTripBySlug(slug) {
  const key = Object.keys(friendsTripData).find(k => friendsTripData[k].slug === slug);
  return key ? friendsTripData[key] : null;
}
