export const honeymoonTripData = {
  "hub": {
    slug: "honeymoon-trip-by-car",
    isHub: true,
    destination: "Honeymoon by Car",
    tagline: "Begin Your Forever with a Romantic Road Trip",
    heroDescription: "Explore India's most romantic destinations with a private car. Decorated vehicles, scenic routes, and unforgettable memories. From snow-capped Shimla to royal Udaipur, find your perfect honeymoon road trip.",
    allDestinations: [
      { name: "Shimla & Manali", slug: "honeymoon-shimla-manali-by-car", romance: 5, days: "5-6", price: 14500, highlight: "Snow-capped mountains & valley views" },
      { name: "Mussoorie", slug: "honeymoon-mussoorie-by-car", romance: 4, days: "2-3", price: 9000, highlight: "Queen of Hills & misty romance" },
      { name: "Nainital", slug: "honeymoon-nainital-by-car", romance: 4, days: "3-4", price: 10000, highlight: "Lakeside romance & boat rides" },
      { name: "Udaipur", slug: "honeymoon-udaipur-by-car", romance: 5, days: "4-5", price: 17000, highlight: "City of Lakes & royal palaces" },
      { name: "Kashmir", slug: "honeymoon-kashmir-by-car", romance: 5, days: "5-7", price: 28000, highlight: "Paradise on Earth & houseboats" },
      { name: "Manali", slug: "honeymoon-manali-by-car", romance: 5, days: "4-5", price: 14500, highlight: "Snow, adventure & cozy cabins" },
      { name: "Jaipur & Udaipur", slug: "honeymoon-jaipur-udaipur", romance: 4, days: "5-6", price: 16000, highlight: "Royal Rajasthan heritage circuit" },
      { name: "Agra Taj Mahal", slug: "romantic-trip-agra-taj-mahal", romance: 5, days: "1-2", price: 4500, highlight: "Symbol of eternal love" },
      { name: "Dharamshala", slug: "honeymoon-dharamshala", romance: 4, days: "3-4", price: 11000, highlight: "Himalayan peace & Tibetan charm" },
    ],
    faqs: [
      { question: "Why choose a honeymoon road trip by car?", answer: "A honeymoon by car offers complete privacy, flexible schedules, scenic route stops for photos, decorated car option (Rs 2,000 extra), and the romance of a private journey. No airport rushes, no shared buses - just you two and the open road." },
      { question: "Can you decorate the car for our honeymoon?", answer: "Yes! We offer car decoration with fresh flowers, ribbons, and just married signage for Rs 2,000 extra. We also include complimentary welcome drinks and a flower bouquet for all honeymoon bookings." },
      { question: "Which is the most romantic destination for honeymoon by car from Delhi?", answer: "Shimla-Manali combo is the most popular (snow, valleys, cozy hotels). Kashmir is the most romantic overall. Udaipur offers royal lakeside romance. Mussoorie is perfect for a quick 2-3 day romantic getaway." },
      { question: "What type of car is best for a honeymoon trip?", answer: "We recommend a sedan (Swift Dzire or Honda Amaze) for couples as it offers privacy, comfort, and lower cost. For couples who prefer SUV comfort, the Innova Crysta is available. The sedan feels more intimate for two." },
      { question: "Do you offer honeymoon packages with hotel bookings?", answer: "We primarily offer cab services, but we can recommend and help book couple-friendly hotels at all destinations. Many couples prefer to book their own romantic stays. We ensure our driver is discreet and professional." },
      { question: "What is included in the decorated car package?", answer: "The Rs 2,000 decorated car package includes: fresh flower decoration on car bonnet and inside, just married ribbon banner, welcome flower bouquet, complimentary water bottles and chocolates, and a congratulations card from Triveni Cabs." },
    ],
  },
  "shimla-manali": {
    slug: "honeymoon-shimla-manali-by-car",
    destination: "Shimla & Manali",
    tagline: "Snow-Kissed Romance in the Himalayas",
    distance: "550 km (Delhi-Shimla-Manali)",
    duration: "5-6 Days",
    bestSeason: "March to June, October to December",
    romanceRating: 5,
    vehicle: {
      name: "Swift Dzire / Honda Amaze",
      type: "Sedan",
      seats: 4,
      features: ["Private and intimate for couples", "AC for comfortable travel", "Good mileage on highways", "Smooth hill driving"],
      suvOption: { name: "Toyota Innova Crysta", price: 18000 },
    },
    price: { sedan: 14500, suv: 18000 },
    decoratedCarPrice: 2000,
    packageIncludes: ["Delhi-Shimla-Manali-Delhi by AC sedan", "Experienced hill driver", "All toll and parking charges", "Local sightseeing at both destinations", "Driver night allowance", "Complimentary flower bouquet"],
    coupleActivities: [
      { name: "Sunset at The Ridge, Shimla", description: "Watch the sun paint the sky orange over the Himalayas while holding hands at Shimla's most iconic viewpoint." },
      { name: "Solang Valley Snow Play", description: "Build a snowman together, try skiing, or just cuddle in the snow. Solang's white landscape is pure romance." },
      { name: "Rohtang Pass Adventure", description: "Stand together at 3,978m with snow all around. The shared thrill of reaching the top creates lasting memories." },
      { name: "Old Manali Cafe Hopping", description: "Explore cozy riverside cafes with mountain views, live music, and the most romantic ambiance in the hills." },
      { name: "Mall Road Evening Walk", description: "Hand-in-hand walk through the charming colonial Mall Road in Shimla. Hot chocolate, shopping, and mountain air." },
    ],
    romanticSpots: [
      { name: "Hidimba Temple Forest", description: "Ancient temple surrounded by tall deodar cedars. The misty forest walk is magical for couples." },
      { name: "Kufri Valley", description: "Pony rides together through snow-dusted paths with panoramic Himalayan views." },
      { name: "Beas River Viewpoint", description: "Sit by the gushing Beas River in Manali. The sound of water and mountain views create perfect romance." },
      { name: "Jakhoo Hill Sunrise", description: "Wake up early for a sunrise trek. The golden light on snow peaks is a photographers dream for couple photos." },
    ],
    photographySpots: ["The Ridge with mountain backdrop", "Solang Valley snow landscape", "Hadimba Temple deodar forest", "Mall Road colonial architecture", "Rohtang Pass snow point", "Old Manali riverside cafes"],
    itinerary: [
      { day: 1, title: "Delhi to Shimla", description: "Early morning decorated car pickup from Delhi. Drive through scenic Chandigarh route. Stop at Timber Trail for lunch with valley views. Arrive Shimla by evening. Romantic walk on Mall Road. Candlelight dinner at hotel." },
      { day: 2, title: "Shimla Romance", description: "Morning at Jakhoo Hill for sunrise. Visit The Ridge and Christ Church. Afternoon at Kufri for pony rides. Evening at Scandal Point and Mall Road shopping. Special dinner at a rooftop restaurant." },
      { day: 3, title: "Shimla to Manali", description: "Scenic drive from Shimla to Manali (260 km, 7-8 hours). Stop at Kullu for riverside lunch. Check into cozy Manali hotel. Evening walk at Old Manali." },
      { day: 4, title: "Manali Magic", description: "Visit Solang Valley for snow activities. Rohtang Pass if open (June-Oct). Afternoon at Hidimba Temple forest. Evening cafe hopping in Old Manali. Bonfire at hotel." },
      { day: 5, title: "Manali Local & Departure Prep", description: "Morning at Vashisht Hot Springs together. Visit Tibetan Monastery and Club House. Afternoon shopping for shawls and souvenirs. Pack for early departure next day." },
      { day: 6, title: "Manali to Delhi", description: "Early departure from Manali. Scenic drive back through Kullu Valley. Lunch stop at Mandi. Arrive Delhi by late evening with beautiful memories." },
    ],
    hotelRecommendations: ["Snow Valley Resort, Shimla (couple packages)", "Manu Allaya, Manali (mountain view rooms)", "The Orchard Greens, Manali (riverside)", "Woodville Palace, Shimla (heritage romance)"],
    faqs: [
      { question: "How much does a Shimla-Manali honeymoon by car cost?", answer: "A 5-6 day Shimla-Manali honeymoon by sedan costs Rs 14,500, and by Innova Crysta Rs 18,000. Add Rs 2,000 for decorated car with flowers. This includes round trip from Delhi, all toll, parking, and driver charges." },
      { question: "Is driving from Delhi to Shimla and Manali romantic?", answer: "Absolutely! The drive passes through scenic valleys, pine forests, and mountain roads. With your own private car, you can stop anywhere for photos. The Shimla-Manali highway is one of India's most beautiful drives." },
      { question: "Which is better for honeymoon - sedan or SUV?", answer: "Most couples prefer a sedan (Swift Dzire/Honda Amaze) as it feels more intimate and costs less. The Innova is better if you carry heavy luggage or prefer extra comfort on hill roads." },
      { question: "What is the best time for Shimla-Manali honeymoon?", answer: "March-June for pleasant weather and green valleys. December-February for snow romance (magical but cold). October-November for clear mountain views and autumn colors. Avoid July-September monsoon." },
      { question: "Can you arrange a surprise for my partner during the trip?", answer: "Yes! We can arrange: cake and flowers at hotel check-in, surprise decorated car, special stops at scenic viewpoints, and coordinate with hotels for candlelight dinner. Just tell us your plans when booking." },
      { question: "How many days are ideal for Shimla-Manali honeymoon?", answer: "5-6 days is perfect: 2 nights in Shimla + 3 nights in Manali. If time is limited, 4 days works: 1 night Shimla + 2 nights Manali. We do not recommend less than 4 days as the driving is long." },
    ],
  },
  "mussoorie": {
    slug: "honeymoon-mussoorie-by-car",
    destination: "Mussoorie",
    tagline: "Misty Mountain Romance in the Queen of Hills",
    distance: "290 km",
    duration: "2-3 Days",
    bestSeason: "March to June, September to November",
    romanceRating: 4,
    vehicle: {
      name: "Swift Dzire / Honda Amaze",
      type: "Sedan",
      seats: 4,
      features: ["Private couple journey", "Comfortable AC travel", "Good for hill driving", "Intimate setting"],
      suvOption: { name: "Toyota Innova Crysta", price: 12000 },
    },
    price: { sedan: 9000, suv: 12000 },
    decoratedCarPrice: 2000,
    packageIncludes: ["Delhi to Mussoorie round trip by AC sedan", "Hill-experienced driver", "All toll and parking", "Kempty Falls, Gun Hill sightseeing", "Driver night allowance", "Complimentary flower bouquet"],
    coupleActivities: [
      { name: "Camel Back Road Walk", description: "The most romantic walk in Mussoorie. Quiet tree-lined path with mountain views, perfect for hand-in-hand strolling." },
      { name: "Gun Hill Sunset", description: "Cable car ride to Gun Hill followed by a spectacular sunset over the Doon Valley. Golden hour couple photos." },
      { name: "Landour Heritage Walk", description: "Colonial-era Landour has charming bakeries, bookshops, and Ruskin Bond's favorite haunts. Perfect couple exploration." },
      { name: "Cloud End Nature Walk", description: "Walk through dense oak and deodar forests to Cloud End. Misty, quiet, and incredibly romantic." },
      { name: "Kempty Falls Picnic", description: "Private moments by the stunning waterfall. The sound of cascading water adds to the romantic atmosphere." },
    ],
    romanticSpots: [
      { name: "George Everest Viewpoint", description: "Ruins of the surveyor's house with 360-degree Himalayan views. Sunset here is legendary for couples." },
      { name: "Company Garden", description: "Beautiful flower garden with a mini lake. Peaceful spot for couple photos and relaxation." },
      { name: "Char Dukan, Landour", description: "Four famous shops serving Maggi, chai, and bun-omelette. Simple romance with mountain views." },
      { name: "Lal Tibba", description: "Highest point in Mussoorie. On clear days, see snow peaks from Badrinath to Kedarnath." },
    ],
    photographySpots: ["George Everest sunset point", "Camel Back Road misty morning", "Gun Hill cable car", "Kempty Falls rainbows", "Landour colonial streets", "Company Garden flowers"],
    itinerary: [
      { day: 1, title: "Delhi to Mussoorie", description: "Morning pickup in decorated car. Drive via Meerut-Dehradun (6-7 hours). Scenic Rajaji National Park stretch. Arrive Mussoorie afternoon. Evening walk on Camel Back Road. Dinner at Lovely Omelette Center or rooftop restaurant." },
      { day: 2, title: "Mussoorie Romance Day", description: "Morning at Kempty Falls. Cable car to Gun Hill for views. Afternoon heritage walk in Landour. Tea at Char Dukan. Sunset at George Everest viewpoint. Romantic dinner at Mall Road." },
      { day: 3, title: "Mussoorie to Delhi", description: "Morning at Company Garden or Cloud End. Checkout and drive to Delhi. Optional stop at Robber Cave, Dehradun for adventure. Reach Delhi by evening." },
    ],
    hotelRecommendations: ["JW Marriott, Mussoorie (luxury)", "Jaypee Residency Manor (heritage)", "The Claridges Nabha (boutique)", "Rokeby Manor, Landour (colonial charm)"],
    faqs: [
      { question: "How much does a Mussoorie honeymoon by car cost?", answer: "A 2-3 day Mussoorie honeymoon by sedan costs Rs 9,000 and by Innova Rs 12,000. Decorated car is Rs 2,000 extra. Includes round trip from Delhi, toll, parking, and driver charges." },
      { question: "Is Mussoorie good for honeymoon?", answer: "Mussoorie is excellent for a short honeymoon (2-3 days). The misty hills, colonial charm, Camel Back Road walks, and Landour cafes create perfect romance. It is closer to Delhi than Shimla, ideal for couples with limited leave." },
      { question: "What is the best season for Mussoorie honeymoon?", answer: "April-June for pleasant weather and clear views. September-November for monsoon freshness and fewer crowds. December-February for cozy winter romance. Avoid heavy monsoon (July-August)." },
      { question: "Can we extend to Rishikesh or Dehradun?", answer: "Yes! Rishikesh is 75 km from Mussoorie. Add 1 day for Ganga Aarti, cafe hopping, and river beach. Dehradun has Robber Cave and Forest Research Institute. Great extensions for couples." },
      { question: "Which area in Mussoorie is best for honeymoon hotels?", answer: "Landour area offers the most romantic stay with colonial charm and mountain views. Mall Road is convenient and lively. Library End is quieter. Kempty Falls road has budget resorts." },
      { question: "Is the drive to Mussoorie scenic?", answer: "Yes! The drive passes through Rajaji National Park where you might spot elephants. The final 35 km climb from Dehradun offers stunning valley views, hairpin bends, and deodar forests." },
    ],
  },
  "nainital": {
    slug: "honeymoon-nainital-by-car",
    destination: "Nainital",
    tagline: "Lakeside Romance Under the Stars",
    distance: "300 km",
    duration: "3-4 Days",
    bestSeason: "March to June, September to November",
    romanceRating: 4,
    vehicle: {
      name: "Swift Dzire / Honda Amaze",
      type: "Sedan",
      seats: 4,
      features: ["Private and cozy for couples", "AC comfort for hills", "Good road handling", "Compact for hill parking"],
      suvOption: { name: "Toyota Innova Crysta", price: 13000 },
    },
    price: { sedan: 10000, suv: 13000 },
    decoratedCarPrice: 2000,
    packageIncludes: ["Delhi to Nainital round trip by AC sedan", "Hill-experienced driver", "All toll and parking", "Lake boating, cable car sightseeing", "Driver night allowance", "Complimentary flower bouquet"],
    coupleActivities: [
      { name: "Moonlight Boat Ride", description: "Shikara-style boat ride on Naini Lake under the stars. The reflection of city lights on water creates pure magic." },
      { name: "Snow View Point Sunrise", description: "Cable car ride at dawn to see the first light hit Himalayan snow peaks. Breathtaking and romantic." },
      { name: "Tiffin Top Picnic", description: "Short trek to Dorothy Seat viewpoint. Pack a picnic and enjoy panoramic views together in solitude." },
      { name: "Mall Road Evening Stroll", description: "Atmospheric walk along the lake with street food, shops, and mountain-reflected lake views." },
      { name: "Sattal Lake Day", description: "Drive to the peaceful seven lakes of Sattal. Kayaking together on crystal-clear water surrounded by forests." },
    ],
    romanticSpots: [
      { name: "Lovers Point (Hanumangarhi)", description: "Sunset viewpoint above Nainital with stunning lake and mountain panorama." },
      { name: "Eco Cave Garden Walk", description: "Fun adventure through natural caves followed by garden relaxation. Playful romance." },
      { name: "Bhimtal Lake", description: "Quieter than Naini Lake with an island restaurant in the middle. Perfect for a private lunch." },
      { name: "Naina Peak Trek", description: "Highest point near Nainital. Short trek rewarded with the best views. Great couple challenge." },
    ],
    photographySpots: ["Naini Lake reflections at dawn", "Snow View Point panorama", "Tiffin Top with mountain backdrop", "Bhimtal island restaurant", "Mall Road evening lights", "Sattal forest lakes"],
    itinerary: [
      { day: 1, title: "Delhi to Nainital", description: "Morning departure in decorated car. Drive via Moradabad-Haldwani (6-7 hours). Arrive Nainital afternoon. Evening boat ride on Naini Lake. Romantic dinner at lakeside restaurant." },
      { day: 2, title: "Nainital Romance", description: "Morning cable car to Snow View Point. Visit Tiffin Top for couple picnic. Afternoon at Eco Cave Garden. Sunset at Lovers Point. Evening Mall Road walk and street food." },
      { day: 3, title: "Bhimtal & Sattal Excursion", description: "Drive to Bhimtal for island restaurant lunch. Kayaking at Sattal Lake. Visit butterfly museum. Return for last romantic evening at Nainital with lakeside dinner." },
      { day: 4, title: "Nainital to Delhi", description: "Leisurely morning checkout. Optional Naina Peak trek. Drive back to Delhi through scenic Kumaon hills. Reach Delhi by evening." },
    ],
    hotelRecommendations: ["The Naini Retreat (heritage lake view)", "Manu Maharani (lakeside luxury)", "The Palace Belvedere (colonial)", "Shervani Hilltop (panoramic views)"],
    faqs: [
      { question: "How much does a Nainital honeymoon by car cost?", answer: "A 3-4 day Nainital honeymoon by sedan costs Rs 10,000 and by Innova Rs 13,000. Decorated car with flowers costs Rs 2,000 extra. Includes round trip from Delhi, toll, parking, and driver charges." },
      { question: "Is Nainital romantic for honeymoon?", answer: "Nainital is wonderfully romantic with its crescent-shaped lake, mountain backdrop, cozy hotels, and peaceful atmosphere. The evening boat rides, Mall Road walks, and Sattal excursion make it perfect for couples." },
      { question: "What is the best time for Nainital honeymoon?", answer: "March-June for pleasant lakeside weather. September-October for clear mountain views after monsoon. November-February for cozy winter romance. The lake is beautiful in every season." },
      { question: "Can we combine Nainital with Corbett for honeymoon?", answer: "Yes! Jim Corbett is just 65 km from Nainital. Add 1 night for a jungle safari experience. The combination of lakeside romance and jungle adventure is unique." },
      { question: "Are there couple-friendly hotels in Nainital?", answer: "Yes, many hotels offer honeymoon packages with decorated rooms, lake-view rooms, and candlelight dinner. The Naini Retreat and Manu Maharani are top picks for couples." },
      { question: "Is boating on Naini Lake romantic?", answer: "Absolutely! A shikara ride on Naini Lake, especially during sunset or under stars, is one of the most romantic experiences in the hills. Private boats are available for couples." },
    ],
  },
  "udaipur": {
    slug: "honeymoon-udaipur-by-car",
    destination: "Udaipur",
    tagline: "The Venice of the East - Royal Romance",
    distance: "660 km",
    duration: "4-5 Days",
    bestSeason: "September to March",
    romanceRating: 5,
    vehicle: {
      name: "Swift Dzire / Honda Amaze",
      type: "Sedan",
      seats: 4,
      features: ["Comfortable long-distance cruiser", "Fuel-efficient for long routes", "AC for Rajasthan heat", "Intimate couple journey"],
      suvOption: { name: "Toyota Innova Crysta", price: 22000 },
    },
    price: { sedan: 17000, suv: 22000 },
    decoratedCarPrice: 2000,
    packageIncludes: ["Delhi to Udaipur round trip by AC sedan", "All toll and parking charges", "Complete Udaipur sightseeing", "Lake Pichola boat ride", "Driver night allowance", "Complimentary flower bouquet"],
    coupleActivities: [
      { name: "Sunset Boat Ride on Lake Pichola", description: "Glide past the City Palace and Jag Mandir island as the sun sets. The golden light on water is India's most romantic boat ride." },
      { name: "Rooftop Dinner with Lake View", description: "Udaipur has stunning rooftop restaurants overlooking Lake Pichola. Candlelight dinner with the illuminated City Palace as backdrop." },
      { name: "Jag Mandir Island Visit", description: "Private island palace on Lake Pichola. Walk through manicured gardens and imagine being Mughal royalty together." },
      { name: "Monsoon Palace Sunset", description: "Drive up to Sajjangarh Palace for the most spectacular sunset view over Udaipur's lakes and Aravallis." },
      { name: "Heritage Walk in Old City", description: "Walk through narrow lanes of the old city, discovering hidden temples, havelis, and artisan workshops together." },
    ],
    romanticSpots: [
      { name: "Ambrai Ghat", description: "Best view of City Palace and Lake Pichola. Evening here with chai is unforgettable for couples." },
      { name: "Fateh Sagar Evening", description: "Walk around the lake, take a boat to Nehru Park island, and enjoy street food. Peaceful couple time." },
      { name: "Saheliyon Ki Bari", description: "Garden of maidens with fountains and lotus pools. Beautiful and serene spot for couple photos." },
      { name: "Bagore Ki Haveli", description: "Evening Rajasthani dance performance in a historic haveli by the lake. Cultural and romantic." },
    ],
    photographySpots: ["Lake Pichola boat ride sunset", "City Palace courtyard", "Ambrai Ghat evening", "Monsoon Palace panorama", "Jagdish Temple steps", "Old city colorful lanes"],
    itinerary: [
      { day: 1, title: "Delhi to Udaipur", description: "Early morning departure (4 AM). Drive via Jaipur bypass. Lunch stop at Ajmer/Nathdwara. Arrive Udaipur by evening. Check into lakeside hotel. Evening walk at Ambrai Ghat." },
      { day: 2, title: "Udaipur Royal Romance", description: "Morning at City Palace Museum. Boat ride on Lake Pichola to Jag Mandir. Lunch at island restaurant. Afternoon at Saheliyon ki Bari. Sunset at Monsoon Palace. Rooftop candlelight dinner." },
      { day: 3, title: "Udaipur Exploration", description: "Morning heritage walk in old city. Visit Jagdish Temple and Bagore ki Haveli. Afternoon at Fateh Sagar Lake boating. Evening Rajasthani dance show at Bagore ki Haveli." },
      { day: 4, title: "Leisure & Shopping", description: "Relaxed morning at hotel spa. Afternoon shopping at Hathi Pol for miniature paintings and silver jewelry. Evening sunset cruise on Lake Pichola. Farewell dinner." },
      { day: 5, title: "Udaipur to Delhi", description: "Post breakfast departure. Optional stop at Chittorgarh Fort (history of Rani Padmini). Drive back to Delhi. Arrive by late evening." },
    ],
    hotelRecommendations: ["Taj Lake Palace (floating palace luxury)", "The Oberoi Udaivilas (world's best)", "Fateh Prakash Palace (heritage)", "Lake Pichola Hotel (mid-range, views)"],
    faqs: [
      { question: "How much does an Udaipur honeymoon by car cost?", answer: "A 4-5 day Udaipur honeymoon by sedan costs Rs 17,000 and by Innova Rs 22,000. Decorated car is Rs 2,000 extra. Includes round trip from Delhi (1,320 km), toll, parking, and driver charges." },
      { question: "Is Udaipur the most romantic city in India?", answer: "Udaipur is consistently rated as India's most romantic destination. The lakes, palaces, rooftop restaurants, and Rajasthani culture create an unmatched romantic atmosphere. Many Bollywood movies are shot here for this reason." },
      { question: "Should we fly or drive to Udaipur for honeymoon?", answer: "Both work well. Driving (10-12 hours) is romantic with scenic Rajasthan landscape but tiring. We recommend driving with an overnight stop at Jaipur or Ajmer. Flying (1.5 hours) saves time for more Udaipur exploration." },
      { question: "What is the best time for Udaipur honeymoon?", answer: "October-March is ideal with pleasant weather (15-28 deg C). September is magical with full monsoon lakes. Avoid April-June extreme heat. Winter evenings are perfect for rooftop dining." },
      { question: "Can we stay at the Taj Lake Palace?", answer: "The Taj Lake Palace is a floating palace hotel on Lake Pichola (Rs 30,000+ per night). We can drop and pick up from the boat jetty. It is the ultimate honeymoon experience if budget allows." },
      { question: "Can we combine Udaipur with Mount Abu?", answer: "Yes! Mount Abu (Rajasthan's only hill station) is 165 km from Udaipur. Add 1-2 days for Nakki Lake, sunset point, and Dilwara Temples. It is a lovely romantic extension." },
    ],
  },
  "kashmir": {
    slug: "honeymoon-kashmir-by-car",
    destination: "Kashmir",
    tagline: "Paradise on Earth - The Ultimate Honeymoon",
    distance: "Flight + 300 km local",
    duration: "5-7 Days",
    bestSeason: "April to October",
    romanceRating: 5,
    vehicle: {
      name: "Swift Dzire / Honda Amaze",
      type: "Sedan",
      seats: 4,
      features: ["Comfortable for Kashmir roads", "AC sedan for couple privacy", "Local experienced driver", "Perfect for valley drives"],
      suvOption: { name: "Toyota Innova Crysta", price: 35000 },
    },
    price: { sedan: 28000, suv: 35000 },
    decoratedCarPrice: 2000,
    packageIncludes: ["Complete Kashmir cab service (Srinagar local + Gulmarg + Pahalgam + Sonmarg)", "Experienced local Kashmiri driver", "All fuel, toll, and parking", "Houseboat coordination", "Driver allowance", "Complimentary flower bouquet"],
    coupleActivities: [
      { name: "Houseboat Stay on Dal Lake", description: "Sleep on a decorated houseboat with hand-carved walnut wood interiors. Wake up to misty lake views and shikara chai delivery." },
      { name: "Shikara Ride Through Floating Gardens", description: "Glide through lotus gardens and floating markets on Dal Lake. The most romantic boat ride in India." },
      { name: "Gulmarg Gondola Snow Experience", description: "Ride Asia's highest cable car together. Play in snow at 4,200m. The shared adventure strengthens the bond." },
      { name: "Betaab Valley Picnic", description: "Named after a Bollywood movie, this valley in Pahalgam is incredibly scenic. Perfect for a couple picnic by the stream." },
      { name: "Saffron Field Walk", description: "Walk through purple saffron flowers in Pampore (October). The world's most romantic spice in the world's most romantic destination." },
    ],
    romanticSpots: [
      { name: "Nigeen Lake", description: "Quieter than Dal Lake, Nigeen offers the most serene couple experience. Book a Nigeen houseboat for total privacy." },
      { name: "Aru Valley", description: "Meadow paradise in Pahalgam. Walk through wildflower meadows with snow peaks in background. Pure romance." },
      { name: "Chashme Shahi Garden", description: "The smallest Mughal garden but the most intimate. Natural spring water and fewer crowds." },
      { name: "Zero Point, Sonmarg", description: "The end of the road where snow meets sky. Standing together at the edge of the world." },
    ],
    photographySpots: ["Dal Lake houseboat sunrise", "Gulmarg gondola snow backdrop", "Betaab Valley green meadows", "Nishat Bagh fountain terrace", "Aru Valley wildflower fields", "Boulevard Road evening lights"],
    itinerary: [
      { day: 1, title: "Arrival in Srinagar", description: "Fly to Srinagar. Decorated car pickup. Check into houseboat on Dal Lake. Shikara ride through floating gardens. Romantic dinner on houseboat deck." },
      { day: 2, title: "Srinagar Romance", description: "Morning Mughal Gardens tour - Nishat Bagh, Shalimar Bagh, Chashme Shahi. Afternoon shopping on Boulevard Road for pashmina and saffron. Evening at Shankaracharya Temple for city views." },
      { day: 3, title: "Gulmarg Day Trip", description: "Drive to Gulmarg (50 km). Gondola ride Phase 1 and 2. Snow play and couple photos. Optional skiing in winter. Pony ride on meadows. Return for dinner." },
      { day: 4, title: "Pahalgam Excursion", description: "Drive to Pahalgam (95 km). Visit Betaab Valley, Aru Valley. Pony ride together. Picnic lunch by Lidder River. Optional Chandanwari visit. Return by evening." },
      { day: 5, title: "Sonmarg Day Trip", description: "Drive to Sonmarg (80 km). Visit Thajiwas Glacier. Pony ride to Zero Point. Stunning meadow views. Return to Srinagar for final evening." },
      { day: 6, title: "Leisure & Departure", description: "Morning at leisure on houseboat. Final shikara ride. Shopping for souvenirs. Transfer to airport for departure flight." },
    ],
    hotelRecommendations: ["The LaLiT Grand Palace (5-star heritage)", "Vivanta Dal View (lakeside luxury)", "Young Bombay Houseboats (premium houseboat)", "WelcomHotel Pine N Peak (Pahalgam)"],
    faqs: [
      { question: "How much does a Kashmir honeymoon package cost?", answer: "A 5-7 day Kashmir honeymoon cab package costs Rs 28,000 for a sedan and Rs 35,000 for an Innova. This covers all Kashmir sightseeing (Srinagar, Gulmarg, Pahalgam, Sonmarg). Flights and hotels are extra." },
      { question: "Is Kashmir safe for honeymoon couples?", answer: "Absolutely! Kashmir is very safe for tourists, especially honeymooners. The locals are warm and hospitable. Tourist areas are well-secured. Thousands of couples honeymoon in Kashmir every year." },
      { question: "Should we stay on a houseboat?", answer: "Yes! Staying at least 1-2 nights on a Dal Lake houseboat is a must for honeymoon couples. Choose a deluxe or premium houseboat for the best experience. The shikara pickup and lake lifestyle are incredibly romantic." },
      { question: "What is the best month for Kashmir honeymoon?", answer: "April (tulip festival) and May-June (pleasant, green) are most popular. September-October has stunning autumn foliage. March is for snow romance. Each season offers unique beauty." },
      { question: "Can you arrange a decorated houseboat?", answer: "Yes! We coordinate with houseboats for room decoration with flowers, candles, and special dinner for honeymooners. Most premium houseboats offer honeymoon packages with extras." },
      { question: "How should we reach Kashmir?", answer: "Fly directly to Srinagar from Delhi (2-hour flight, Rs 4,000-8,000). We pick you up at the airport in a decorated car. Driving is not recommended for honeymoon as it takes 24+ hours." },
    ],
  },
  "manali": {
    slug: "honeymoon-manali-by-car",
    destination: "Manali",
    tagline: "Snow, Stars & Love in the Valley of Gods",
    distance: "540 km",
    duration: "4-5 Days",
    bestSeason: "March to June, December to February",
    romanceRating: 5,
    vehicle: {
      name: "Swift Dzire / Honda Amaze",
      type: "Sedan",
      seats: 4,
      features: ["Private couple experience", "AC for comfort", "Hill-capable sedan", "Intimate travel setting"],
      suvOption: { name: "Toyota Innova Crysta", price: 18500 },
    },
    price: { sedan: 14500, suv: 18500 },
    decoratedCarPrice: 2000,
    packageIncludes: ["Delhi to Manali round trip by AC sedan", "Hill-experienced driver", "All toll and parking", "Solang Valley, Rohtang sightseeing", "Driver night allowance", "Complimentary flower bouquet"],
    coupleActivities: [
      { name: "Solang Valley Snow Day", description: "Play in snow together, try paragliding, or just enjoy the white landscape. Winter makes it magical, summer offers adventure." },
      { name: "Old Manali Cafe Hopping", description: "Cozy cafes by the Manalsu stream with live music, bonfire nights, and mountain views. The heartbeat of Manali romance." },
      { name: "Rohtang Pass Adventure", description: "Conquer 3,978m together. Snow, wind, and incredible views. The shared achievement creates lifelong memories." },
      { name: "Beas River Riverside Walk", description: "Stroll along the roaring Beas River through pine forests. The sound of water and birds is nature's love song." },
      { name: "Naggar Castle Visit", description: "Medieval castle-turned-heritage-hotel with stunning valley views. Have coffee together in a 500-year-old castle." },
    ],
    romanticSpots: [
      { name: "Hidimba Temple Forest", description: "Walk hand-in-hand through towering deodar cedars. Misty mornings here are pure romance." },
      { name: "Jogini Waterfall Trek", description: "Moderate trek from Vashisht ending at a beautiful waterfall. Rewarding couple adventure." },
      { name: "Manali Nature Park", description: "Dense forest park with walking trails. Quiet, green, and perfect for couple time in nature." },
      { name: "Hampta Pass View Point", description: "Drive to the road head for stunning views of the Hampta Valley. Clear days show snow peaks." },
    ],
    photographySpots: ["Solang Valley snow landscape", "Hidimba Temple forest backdrop", "Old Manali bridge and stream", "Rohtang Pass snow point", "Beas River valley views", "Naggar Castle panorama"],
    itinerary: [
      { day: 1, title: "Delhi to Manali", description: "Very early departure (3-4 AM) in decorated car. Drive via Chandigarh-Mandi route (12-14 hours). Breakfast at Murthal, lunch at Mandi. Arrive Manali by evening. Check into cozy hotel. Rest and acclimatize." },
      { day: 2, title: "Solang & Rohtang", description: "Drive to Solang Valley for snow activities and paragliding. If Rohtang is open, continue to snow point. Incredible couple photos. Return for evening cafe hopping in Old Manali." },
      { day: 3, title: "Manali Sightseeing", description: "Morning at Hidimba Temple and Manu Temple. Vashisht Hot Springs dip together. Afternoon at Club House. Evening riverside walk along Beas River. Bonfire dinner at hotel." },
      { day: 4, title: "Naggar & Kullu", description: "Drive to Naggar Castle and Roerich Art Gallery. Visit apple orchards (seasonal). Afternoon in Kullu for optional rafting. Return for farewell romantic dinner in Old Manali." },
      { day: 5, title: "Manali to Delhi", description: "Post breakfast departure. Scenic drive back through Kullu Valley. Lunch at Sundernagar. Arrive Delhi by late evening with beautiful memories." },
    ],
    hotelRecommendations: ["The Himalayan (luxury, couple spa)", "Manu Allaya (mountain views)", "Solang Valley Resort (close to snow)", "Johnson Lodge (heritage cottage)"],
    faqs: [
      { question: "How much does a Manali honeymoon by car cost?", answer: "A 4-5 day Manali honeymoon by sedan costs Rs 14,500 and by Innova Rs 18,500. Decorated car with flowers is Rs 2,000 extra. Includes round trip from Delhi, toll, parking, and driver charges." },
      { question: "Is the Delhi to Manali drive romantic?", answer: "The drive passes through changing landscapes - plains, valleys, rivers, and mountains. With a private car, you can stop anywhere for photos and chai. The Kullu Valley section is especially scenic." },
      { question: "Should we choose Manali or Shimla for honeymoon?", answer: "Manali is more romantic with snow activities, riverside cafes, and a bohemian vibe. Shimla has colonial charm and Mall Road elegance. For the best experience, do a Shimla-Manali combo (5-6 days)." },
      { question: "What should we pack for Manali honeymoon?", answer: "Warm clothes (layers), comfortable walking shoes, camera, power bank (charging points rare in hills), rain jacket, and sunscreen. We provide a packing guide when you book." },
      { question: "Can we see snow in Manali?", answer: "December to March: Manali town has snow. April-May: Solang Valley and Rohtang have snow. June-October: Only Rohtang Pass top has snow. Snow is almost always accessible in some form." },
      { question: "Are there couple-friendly hotels in Manali?", answer: "Yes, Manali has many couple-friendly hotels. The Himalayan and Manu Allaya offer honeymoon packages with decorated rooms, candlelight dinner, and couple spa. Old Manali has boutique guesthouses." },
    ],
  },
  "jaipur-udaipur": {
    slug: "honeymoon-jaipur-udaipur",
    destination: "Jaipur & Udaipur",
    tagline: "Royal Rajasthan Romance - Palaces, Lakes & Heritage",
    distance: "720 km (Delhi-Jaipur-Udaipur-Delhi)",
    duration: "5-6 Days",
    bestSeason: "October to March",
    romanceRating: 4,
    vehicle: {
      name: "Swift Dzire / Honda Amaze",
      type: "Sedan",
      seats: 4,
      features: ["Comfortable highway sedan", "AC for Rajasthan climate", "Fuel-efficient", "Intimate couple setting"],
      suvOption: { name: "Toyota Innova Crysta", price: 21000 },
    },
    price: { sedan: 16000, suv: 21000 },
    decoratedCarPrice: 2000,
    packageIncludes: ["Delhi-Jaipur-Udaipur-Delhi by AC sedan", "All toll and parking charges", "Sightseeing at both cities", "Lake Pichola boat ride", "Driver night allowance", "Complimentary flower bouquet"],
    coupleActivities: [
      { name: "Amber Fort Elephant Ride", description: "Ride an elephant together up to the majestic Amber Fort. Royal entry for a royal couple." },
      { name: "Lake Pichola Sunset Cruise", description: "The most romantic boat ride in India. Watch the City Palace glow golden as the sun sets." },
      { name: "Jaipur Rooftop Dining", description: "Dine under the stars with Amber Fort lit up in the distance. Several rooftop restaurants offer this experience." },
      { name: "Nahargarh Fort Night View", description: "Drive up to Nahargarh for the famous Jaipur night view. The entire Pink City lit up below you." },
      { name: "Udaipur Heritage Walk", description: "Explore narrow lanes, hidden temples, and artisan workshops in the old city. Romantic discovery together." },
    ],
    romanticSpots: [
      { name: "Jai Mahal Palace Gardens", description: "Stunning palace hotel gardens open for dining. Royal romance in a 250-year-old palace." },
      { name: "Ambrai Ghat, Udaipur", description: "Best view of City Palace from across the lake. Evening chai here is unforgettable." },
      { name: "Patrika Gate", description: "Colorful Jaipur landmark perfect for couple photos. The architecture is stunning." },
      { name: "Monsoon Palace Sunset", description: "Drive up to Sajjangarh for 360-degree views of Udaipur's lakes and mountains." },
    ],
    photographySpots: ["Hawa Mahal facade", "Amber Fort elephant gate", "Lake Pichola sunset", "City Palace courtyard", "Patrika Gate colors", "Monsoon Palace panorama"],
    itinerary: [
      { day: 1, title: "Delhi to Jaipur", description: "Morning departure in decorated car. Drive to Jaipur via NH-48 (4-5 hours). Visit Amber Fort with elephant ride. Evening at Nahargarh Fort for sunset. Romantic dinner at 1135 AD restaurant." },
      { day: 2, title: "Jaipur Exploration", description: "Visit City Palace, Hawa Mahal, Jantar Mantar. Lunch at a rooftop restaurant. Afternoon at Albert Hall Museum. Evening shopping at Johari Bazaar. Chokhi Dhani for dinner." },
      { day: 3, title: "Jaipur to Udaipur", description: "Drive Jaipur to Udaipur (390 km, 6-7 hours). Stop at Chittorgarh Fort (Rani Padmini history). Arrive Udaipur by evening. Check into lakeside hotel. Evening at Ambrai Ghat." },
      { day: 4, title: "Udaipur Romance", description: "Morning at City Palace. Boat ride on Lake Pichola to Jag Mandir. Afternoon at Saheliyon ki Bari. Sunset at Monsoon Palace. Rooftop candlelight dinner overlooking the lake." },
      { day: 5, title: "Udaipur Leisure", description: "Morning spa at hotel. Afternoon shopping at Hathi Pol for miniature paintings. Evening dance performance at Bagore ki Haveli. Farewell dinner." },
      { day: 6, title: "Udaipur to Delhi", description: "Post breakfast departure. Drive Udaipur to Delhi (660 km, 10-12 hours) or option to take a shorter route via Ajmer with lunch stop. Arrive Delhi by evening." },
    ],
    hotelRecommendations: ["Samode Haveli, Jaipur (heritage)", "Rambagh Palace, Jaipur (5-star)", "Taj Lake Palace, Udaipur (floating)", "Fateh Prakash Palace, Udaipur (heritage)"],
    faqs: [
      { question: "How much does a Jaipur-Udaipur honeymoon by car cost?", answer: "A 5-6 day Jaipur-Udaipur honeymoon by sedan costs Rs 16,000 and by Innova Rs 21,000. Decorated car is Rs 2,000 extra. Covers the complete circuit: Delhi-Jaipur-Udaipur-Delhi." },
      { question: "Is the Rajasthan circuit good for honeymoon?", answer: "The Jaipur-Udaipur combo is one of India's best honeymoon circuits. Jaipur offers royal heritage and forts, while Udaipur provides lake romance and palace dining. The contrast makes it unforgettable." },
      { question: "Should we add Jodhpur to the itinerary?", answer: "If you have 7-8 days, adding Jodhpur (Blue City) is excellent. It adds the Mehrangarh Fort and desert experience. Route: Delhi-Jaipur-Jodhpur-Udaipur-Delhi." },
      { question: "What is the best time for this circuit?", answer: "October to March is ideal for Rajasthan with pleasant weather (15-25 deg C). November-February is peak season. Avoid April-June extreme heat (40 deg C+)." },
      { question: "How long is the Jaipur to Udaipur drive?", answer: "Jaipur to Udaipur is 390 km and takes 6-7 hours. The road passes through scenic Aravalli hills. We recommend a stop at Chittorgarh Fort (romantic history of Rani Padmini)." },
      { question: "Can we stay at heritage palace hotels?", answer: "Yes! Rajasthan is famous for palace hotels. Samode Haveli and Rambagh Palace in Jaipur, Taj Lake Palace and Fateh Prakash Palace in Udaipur offer unforgettable royal honeymoon stays." },
    ],
  },
  "agra": {
    slug: "romantic-trip-agra-taj-mahal",
    destination: "Agra - Taj Mahal",
    tagline: "The Monument of Love - Where Romance Began",
    distance: "233 km",
    duration: "1-2 Days",
    bestSeason: "October to March",
    romanceRating: 5,
    vehicle: {
      name: "Swift Dzire / Honda Amaze",
      type: "Sedan",
      seats: 4,
      features: ["Quick expressway sedan", "AC for comfort", "Intimate for couples", "Large boot for overnight bags"],
      suvOption: { name: "Toyota Innova Crysta", price: 8500 },
    },
    price: { sedan: 4500, suv: 8500 },
    decoratedCarPrice: 2000,
    packageIncludes: ["Delhi to Agra round trip by AC sedan", "Yamuna Expressway toll included", "Taj Mahal and Agra Fort visit", "All parking charges", "Driver allowance", "Complimentary flower bouquet"],
    coupleActivities: [
      { name: "Taj Mahal at Sunrise", description: "The Taj bathed in golden morning light is the world's most romantic sight. Fewer crowds, perfect photos, and pure magic." },
      { name: "Mehtab Bagh Sunset", description: "Watch the Taj Mahal turn pink, then gold, then white as the sun sets from across the Yamuna River. Breathtaking." },
      { name: "Agra Fort Love Stories", description: "Hear the tale of Shah Jahan imprisoned in Agra Fort, gazing at the Taj Mahal he built for his beloved Mumtaz." },
      { name: "Candlelight Dinner at Oberoi", description: "The Oberoi Amarvilas offers Taj Mahal view dining. The most exclusive romantic dinner in India." },
      { name: "Baby Taj (Itimad-ud-Daulah)", description: "Smaller and more intimate than the Taj, this jewel box is perfect for quiet couple moments." },
    ],
    romanticSpots: [
      { name: "Taj Mahal Diana Bench", description: "The famous bench where Princess Diana sat. Now an iconic couple photo spot." },
      { name: "Mehtab Bagh River View", description: "Garden across the Yamuna built specifically to view the Taj. Best sunset viewpoint." },
      { name: "Agra Fort Musamman Burj", description: "The octagonal tower where Shah Jahan spent his last years gazing at the Taj. Poetic romance." },
      { name: "Chambal River Safari", description: "Drive to Chambal (60 km) for a river safari spotting gharials and dolphins. Adventurous romance." },
    ],
    photographySpots: ["Taj Mahal sunrise from garden", "Diana bench couple photo", "Mehtab Bagh Taj reflection", "Agra Fort Taj view window", "Baby Taj intricate detail", "Great Gate Taj framing"],
    itinerary: [
      { day: 1, title: "Delhi to Agra", description: "Early departure in decorated car (4:30 AM). Drive via Yamuna Expressway (3 hours). Reach Taj Mahal by sunrise. Spend 2 hours at Taj Mahal. Visit Agra Fort. Lunch at Peshawri. Evening at Mehtab Bagh for Taj sunset." },
      { day: 2, title: "Agra & Return", description: "Morning at Itimad-ud-Daulah (Baby Taj) in peaceful morning light. Visit Chini Ka Rauza. Optional Chambal Safari or shopping at Subhash Emporium. Afternoon drive back to Delhi. Reach by 5-6 PM." },
    ],
    hotelRecommendations: ["The Oberoi Amarvilas (Taj view rooms)", "ITC Mughal (Mughal gardens)", "Courtyard by Marriott (modern)", "Crystal Sarovar Premiere (mid-range)"],
    faqs: [
      { question: "How much does a romantic Agra trip from Delhi cost?", answer: "A 1-2 day romantic trip to Agra by sedan costs Rs 4,500 (same day) or Rs 6,500 (overnight) from Delhi. Decorated car with flowers is Rs 2,000 extra. Includes Yamuna Expressway toll, parking, and driver." },
      { question: "Why is the Taj Mahal romantic?", answer: "The Taj Mahal was built by Emperor Shah Jahan as a monument of love for his wife Mumtaz Mahal. It took 22 years and 20,000 workers. The white marble changes color with sunlight. It is the world's greatest love story in stone." },
      { question: "What is the best time to see Taj Mahal for couples?", answer: "Sunrise (6-7 AM) is the most romantic time - golden light, fewer crowds, and cool weather. Full moon nights (5 nights per month) offer special night viewing for an extraordinary experience." },
      { question: "Is the Taj Mahal closed on Fridays?", answer: "Yes, the Taj Mahal is closed every Friday for prayers. Plan your visit on any other day. Full moon night viewing is available on the night before, the night of, and the night after the full moon (not on Fridays)." },
      { question: "Can we have dinner with a Taj view?", answer: "Yes! The Oberoi Amarvilas offers Taj Mahal view dining (premium). Several rooftop restaurants near the east gate also offer Taj views at affordable prices. We can recommend the best options." },
      { question: "Should we do a same-day or overnight Agra trip?", answer: "For romance, an overnight trip is much better. You can see the Taj at sunrise AND sunset from Mehtab Bagh. Plus, the Oberoi Amarvilas Taj view room experience is unforgettable. Same day works if time is limited." },
    ],
  },
  "dharamshala": {
    slug: "honeymoon-dharamshala",
    destination: "Dharamshala",
    tagline: "Himalayan Peace & Tibetan Romance",
    distance: "480 km",
    duration: "3-4 Days",
    bestSeason: "March to June, September to November",
    romanceRating: 4,
    vehicle: {
      name: "Swift Dzire / Honda Amaze",
      type: "Sedan",
      seats: 4,
      features: ["Hill-capable sedan", "AC for varied climate", "Comfortable on highways", "Cozy couple travel"],
      suvOption: { name: "Toyota Innova Crysta", price: 15000 },
    },
    price: { sedan: 11000, suv: 15000 },
    decoratedCarPrice: 2000,
    packageIncludes: ["Delhi to Dharamshala round trip by AC sedan", "Hill-experienced driver", "All toll and parking", "McLeodganj, Bhagsunag sightseeing", "Driver night allowance", "Complimentary flower bouquet"],
    coupleActivities: [
      { name: "Naddi View Point Sunrise", description: "Watch the Dhauladhar range turn golden at sunrise from Naddi village. One of the most romantic sunrise views in India." },
      { name: "McLeodganj Cafe Trail", description: "Cozy Tibetan and Italian cafes with mountain views. Spend a lazy afternoon hopping between cafes and bookshops." },
      { name: "Bhagsunag Waterfall Trek", description: "Easy 20-minute trek to a beautiful waterfall. Refreshing dip together and a cafe at the top." },
      { name: "Triund Trek (1 Day)", description: "Moderate 9 km trek rewarded with the most spectacular campsite above the clouds. Star camping optional." },
      { name: "Tibetan Cooking Class", description: "Learn to make momos and thukpa together. Fun, interactive couple activity at a Tibetan cooking school." },
    ],
    romanticSpots: [
      { name: "Dharamkot Village", description: "Hippie village above McLeodganj with stunning views, organic cafes, and peaceful vibes." },
      { name: "Dal Lake Dharamshala", description: "Small lake surrounded by deodar trees. Peaceful morning walks for couples away from crowds." },
      { name: "St. John Church Trail", description: "Beautiful colonial church in a pine forest. The walk through the forest is serene and romantic." },
      { name: "Kangra Valley Viewpoint", description: "Drive to Kangra Art Museum area for stunning valley views. Tea gardens and mountain panorama." },
    ],
    photographySpots: ["Naddi sunrise with Dhauladhar", "McLeodganj colorful lanes", "Bhagsunag waterfall", "Triund hilltop campsite", "Dharamkot mountain views", "Tibetan monastery prayer flags"],
    itinerary: [
      { day: 1, title: "Delhi to Dharamshala", description: "Early morning departure (4-5 AM). Drive via Chandigarh-Hamirpur route (9-10 hours). Arrive McLeodganj by afternoon. Check into mountain view hotel. Evening walk at McLeodganj market." },
      { day: 2, title: "McLeodganj & Bhagsunag", description: "Morning at Bhagsunag Waterfall trek. Visit Dalai Lama Temple complex. Afternoon Tibetan cooking class. Evening cafe hopping and sunset at Naddi Viewpoint." },
      { day: 3, title: "Dharamkot & Exploration", description: "Morning visit to Dharamkot village. Trek to Gallu Devi Temple viewpoint. Afternoon at Dal Lake. Evening at St. John Church and sunset. Farewell dinner at an Italian cafe." },
      { day: 4, title: "Dharamshala to Delhi", description: "Post breakfast departure. Optional stop at Kangra Fort (oldest in India). Drive back via Hamirpur. Reach Delhi by evening." },
    ],
    hotelRecommendations: ["Hyatt Regency (luxury, valley view)", "Fortune Park Moksha (McLeodganj)", "The Pink House (boutique, mountain view)", "Norbulingka Institute guesthouse"],
    faqs: [
      { question: "How much does a Dharamshala honeymoon by car cost?", answer: "A 3-4 day Dharamshala honeymoon by sedan costs Rs 11,000 and by Innova Rs 15,000. Decorated car is Rs 2,000 extra. Includes round trip from Delhi, toll, parking, and driver charges." },
      { question: "Is Dharamshala good for honeymoon?", answer: "Dharamshala (McLeodganj) is perfect for couples who love mountains, cafes, trekking, and Tibetan culture. It is less commercialized than Shimla/Manali and offers a more authentic, peaceful honeymoon experience." },
      { question: "What is the best time for Dharamshala honeymoon?", answer: "March-June for pleasant weather and clear mountain views. September-November for post-monsoon freshness and snow-capped peaks. Avoid July-August heavy monsoon." },
      { question: "Can we do Triund Trek on our honeymoon?", answer: "Yes! The Triund Trek is a moderate 9 km walk taking 4-5 hours. The campsite above the clouds is magical for couples. You can camp overnight (tent and sleeping bag available for rent) or return same day." },
      { question: "How far is McLeodganj from Dharamshala?", answer: "McLeodganj is just 4 km above Dharamshala town. Most tourists stay in McLeodganj for the mountain views, cafes, and Dalai Lama temple. Our driver drops you to your hotel in McLeodganj." },
      { question: "Is the drive to Dharamshala scenic?", answer: "The last 2 hours from Kangra to Dharamshala are very scenic with tea gardens, Kangra Valley views, and pine forests. The drive through Hamirpur is also pleasant through rural Himachal." },
    ],
  },
};

export const honeymoonTripSlugs = Object.keys(honeymoonTripData);

export function getHoneymoonTripBySlug(slug) {
  const key = Object.keys(honeymoonTripData).find(k => honeymoonTripData[k].slug === slug);
  return key ? honeymoonTripData[key] : null;
}
