// src/utilis/packageData.js - Complete data for 15 Hotel+Cab Package pages

const packages = {
  "manali-2-nights-with-cab": {
    slug: "manali-2-nights-with-cab",
    destination: "Manali",
    duration: "2 Nights / 3 Days",
    startingPrice: 8999,
    perPerson: true,
    includes: ["2 nights hotel stay", "AC cab for all sightseeing", "Pickup & drop from Chandigarh/Delhi", "Breakfast at hotel", "Driver with local knowledge", "All tolls and parking"],
    itinerary: [
      { day: 1, title: "Arrival & Solang Valley", activities: ["Pickup from Chandigarh/Delhi", "Drive to Manali via scenic route", "Check-in at hotel", "Visit Solang Valley for adventure activities", "Evening free at Mall Road"] },
      { day: 2, title: "Manali Sightseeing", activities: ["Breakfast at hotel", "Visit Hadimba Temple", "Explore Old Manali & cafes", "Vashisht Hot Springs", "Manu Temple & Tibetan Monastery", "Evening at leisure"] },
      { day: 3, title: "Rohtang/Atal Tunnel & Departure", activities: ["Early morning Rohtang Pass excursion (seasonal)", "Atal Tunnel visit", "Lunch and checkout", "Drop to Chandigarh/Delhi"] },
    ],
    hotelOptions: [
      { category: "Budget (3-Star)", price: 8999 },
      { category: "Deluxe (4-Star)", price: 13999 },
      { category: "Premium (5-Star)", price: 22999 },
    ],
    faqs: [
      { question: "What is included in the Manali 2-night package?", answer: "The package includes 2 nights hotel stay, AC cab for all sightseeing and transfers, breakfast, driver, toll, and parking. Lunch, dinner, and activity tickets are extra." },
      { question: "Is Rohtang Pass included in this package?", answer: "Yes, a Rohtang Pass excursion is included (seasonal, May-November). In winter, we include Atal Tunnel and Solang Valley snow point instead. Rohtang permit (₹550/person) is extra." },
      { question: "Can I customize this Manali package?", answer: "Absolutely! Add extra nights, upgrade hotels, include Kasol/Manikaran side trip, or change pickup city. Call 7668570551 for a custom quote." },
      { question: "What is the best time for a Manali trip?", answer: "March to June for pleasant weather and adventure activities. December to February for snow experience. Avoid July-August due to monsoon landslides." },
      { question: "How far is Manali from Delhi?", answer: "Manali is 530 km from Delhi (12-13 hours) and 310 km from Chandigarh (7-8 hours). We provide comfortable AC cab for the entire journey." },
      { question: "Can I extend this package to 3 or 4 nights?", answer: "Yes! Extra night costs ₹2,500-5,000 depending on hotel category. We recommend 3 nights for a relaxed Manali experience with Rohtang Pass day trip." },
    ],
  },
  "shimla-2-nights-with-cab": {
    slug: "shimla-2-nights-with-cab",
    destination: "Shimla",
    duration: "2 Nights / 3 Days",
    startingPrice: 7999,
    perPerson: true,
    includes: ["2 nights hotel stay", "AC cab for sightseeing", "Pickup & drop from Chandigarh/Delhi", "Breakfast at hotel", "Kufri excursion", "All tolls and parking"],
    itinerary: [
      { day: 1, title: "Arrival & Mall Road", activities: ["Pickup from Chandigarh/Delhi", "Drive to Shimla via scenic route", "Check-in and rest", "Evening walk on Mall Road", "Visit Christ Church & The Ridge"] },
      { day: 2, title: "Kufri & Shimla Sightseeing", activities: ["Breakfast at hotel", "Kufri adventure park & pony rides", "Green Valley viewpoint", "Jakhoo Temple", "Scandal Point & Lakkar Bazaar", "Evening free"] },
      { day: 3, title: "Mashobra & Departure", activities: ["Breakfast and checkout", "Visit Mashobra apple orchards", "Naldehra Golf Course viewpoint", "Lunch en route", "Drop to Chandigarh/Delhi"] },
    ],
    hotelOptions: [
      { category: "Budget (3-Star)", price: 7999 },
      { category: "Deluxe (4-Star)", price: 11999 },
      { category: "Premium (5-Star)", price: 19999 },
    ],
    faqs: [
      { question: "What is included in the Shimla 2-night package?", answer: "Package includes 2 nights hotel, AC cab for all transfers and sightseeing, daily breakfast, Kufri excursion, tolls, and parking. Activities and other meals are extra." },
      { question: "Is snowfall guaranteed in Shimla?", answer: "Snowfall in Shimla typically occurs December to February but is not guaranteed. Kufri at higher altitude has better chances. We'll adjust itinerary based on conditions." },
      { question: "Can I combine Shimla and Manali?", answer: "Yes! Our popular Shimla-Manali combo is 5 nights / 6 days starting from ₹17,999. The Shimla-Manali highway is one of India's most scenic drives." },
      { question: "What is the best time to visit Shimla?", answer: "March to June for pleasant weather, October-November for autumn colors, December-February for snow. Shimla is beautiful year-round." },
      { question: "How far is Shimla from Delhi?", answer: "Shimla is 350 km from Delhi (7-8 hours drive) and 115 km from Chandigarh (3 hours). The mountain drive after Kalka is very scenic." },
      { question: "Is the package price per person or per room?", answer: "Starting price is per person on twin-sharing basis. Single occupancy is available at a supplement. Contact us for family packages with child rates." },
    ],
  },
  "jaipur-2-nights-with-cab": {
    slug: "jaipur-2-nights-with-cab",
    destination: "Jaipur",
    duration: "2 Nights / 3 Days",
    startingPrice: 6999,
    perPerson: true,
    includes: ["2 nights hotel stay", "AC cab for sightseeing", "Pickup & drop from Delhi", "Breakfast", "Full-day Jaipur sightseeing", "All tolls and parking"],
    itinerary: [
      { day: 1, title: "Delhi to Jaipur & Evening", activities: ["Morning pickup from Delhi", "Drive to Jaipur via NH-48 (5 hrs)", "Check-in and lunch", "Evening visit to Nahargarh Fort for sunset", "Chokhi Dhani dinner (optional)"] },
      { day: 2, title: "Full Day Jaipur Sightseeing", activities: ["Breakfast at hotel", "Amber Fort (morning)", "Jal Mahal photo stop", "City Palace & Jantar Mantar", "Hawa Mahal", "Johari Bazaar shopping", "Evening at leisure"] },
      { day: 3, title: "Local Visits & Return", activities: ["Breakfast and checkout", "Albert Hall Museum", "Birla Temple", "Lunch", "Drive back to Delhi", "Evening arrival"] },
    ],
    hotelOptions: [
      { category: "Budget (3-Star)", price: 6999 },
      { category: "Deluxe (4-Star)", price: 10999 },
      { category: "Heritage Haveli", price: 14999 },
    ],
    faqs: [
      { question: "What sightseeing is included in the Jaipur package?", answer: "Full-day Jaipur sightseeing including Amber Fort, City Palace, Jantar Mantar, Hawa Mahal, Nahargarh Fort, and Johari Bazaar. Entry tickets are extra (₹500-1000 approx)." },
      { question: "Can I add Ajmer-Pushkar to this trip?", answer: "Yes! Ajmer-Pushkar day trip from Jaipur (280 km round trip) can be added for ₹2,500 extra. Or extend to 3 nights and visit as a separate day." },
      { question: "Is there a heritage hotel option?", answer: "Yes, Jaipur is famous for heritage haveli hotels. Our Heritage Haveli option (₹14,999) includes stay at a converted Rajput mansion with traditional architecture." },
      { question: "What is the best time to visit Jaipur?", answer: "October to March is ideal with pleasant weather (15-25°C). Avoid April-June when temperatures exceed 40°C. November has the Jaipur Literature Festival." },
      { question: "How far is Jaipur from Delhi?", answer: "Jaipur is 280 km from Delhi, about 5 hours via NH-48 (Jaipur Expressway). The highway is excellent with multiple rest stops." },
      { question: "Can I extend to Golden Triangle (Delhi-Agra-Jaipur)?", answer: "Yes! Our Golden Triangle 4N/5D package starts from ₹14,999 per person including Delhi, Agra (Taj Mahal), and Jaipur with all transfers and hotels." },
    ],
  },
  "udaipur-2-nights-with-cab": {
    slug: "udaipur-2-nights-with-cab",
    destination: "Udaipur",
    duration: "2 Nights / 3 Days",
    startingPrice: 8999,
    perPerson: true,
    includes: ["2 nights hotel stay", "AC cab for sightseeing", "Airport/station pickup & drop", "Breakfast", "Lake Pichola boat ride", "Full-day sightseeing"],
    itinerary: [
      { day: 1, title: "Arrival & Lake Evening", activities: ["Arrival at Udaipur airport/station", "Hotel check-in", "City Palace visit", "Sunset boat ride on Lake Pichola", "Dinner at lakeside restaurant"] },
      { day: 2, title: "Full Day Sightseeing", activities: ["Breakfast at hotel", "Jagdish Temple", "Saheliyon Ki Bari", "Fateh Sagar Lake", "Moti Magri (Maharana Pratap Memorial)", "Ambrai Ghat sunset", "Evening free at Hathi Pol bazaar"] },
      { day: 3, title: "Excursion & Departure", activities: ["Breakfast", "Sajjangarh Monsoon Palace", "Shilpgram craft village", "Lunch", "Drop to airport/station"] },
    ],
    hotelOptions: [
      { category: "Budget (3-Star)", price: 8999 },
      { category: "Lake View (4-Star)", price: 14999 },
      { category: "Heritage Palace", price: 24999 },
    ],
    faqs: [
      { question: "Does the Udaipur package include a boat ride?", answer: "Yes, the Lake Pichola sunset boat ride is included. This is the highlight of Udaipur — you'll see the iconic Lake Palace Hotel and Jag Mandir from the water." },
      { question: "Can I stay at a lake-view hotel?", answer: "Yes! Our Lake View (4-Star) option at ₹14,999 guarantees a room overlooking Lake Pichola. The Heritage Palace option offers a royal experience." },
      { question: "What is the best time to visit Udaipur?", answer: "October to March for comfortable weather. September-October after monsoon when all lakes are full is absolutely magical. Avoid April-June heat." },
      { question: "Can I add Chittorgarh or Mount Abu?", answer: "Yes! Chittorgarh (115 km, half-day) or Mount Abu (165 km, overnight) can be added. Extend the package by 1-2 nights." },
      { question: "How do I reach Udaipur?", answer: "Udaipur has a domestic airport (1-hr flight from Delhi/Mumbai). Also connected by train. We provide pickup from airport/station included in the package." },
      { question: "Is Udaipur good for honeymoon?", answer: "Udaipur is India's #1 honeymoon destination! The lake views, heritage palaces, and romantic ambiance make it perfect. We can arrange candlelight dinner and special experiences." },
    ],
  },
  "rishikesh-2-nights-with-cab": {
    slug: "rishikesh-2-nights-with-cab",
    destination: "Rishikesh",
    duration: "2 Nights / 3 Days",
    startingPrice: 6499,
    perPerson: true,
    includes: ["2 nights hotel stay", "AC cab for transfers", "Pickup & drop from Delhi/Haridwar", "Breakfast", "Ganga Aarti experience", "All tolls"],
    itinerary: [
      { day: 1, title: "Arrival & Spiritual Evening", activities: ["Pickup from Delhi/Haridwar", "Drive to Rishikesh", "Hotel check-in", "Visit Ram Jhula & Laxman Jhula", "Triveni Ghat Ganga Aarti (evening)"] },
      { day: 2, title: "Adventure & Sightseeing", activities: ["Breakfast", "River rafting (16/26 km stretch)", "Beatles Ashram visit", "Cafe hopping at Laxman Jhula", "Yoga session (optional)", "Evening free at Tapovan"] },
      { day: 3, title: "Waterfalls & Departure", activities: ["Early breakfast", "Neer Garh Waterfall trek", "Visit Parmarth Niketan Ashram", "Lunch", "Drop to Delhi/Haridwar"] },
    ],
    hotelOptions: [
      { category: "Budget (Ashram/Hostel)", price: 6499 },
      { category: "Riverside Resort", price: 10999 },
      { category: "Luxury Camp", price: 15999 },
    ],
    faqs: [
      { question: "Is river rafting included in the package?", answer: "The cab transfer to the rafting point is included. Rafting cost (₹600-1500 per person depending on stretch) is extra. We'll arrange the best operators for you." },
      { question: "Is Rishikesh safe for solo female travelers?", answer: "Yes, Rishikesh is one of India's safest destinations, especially around the main ashram areas. Our drivers provide door-to-door service for extra safety." },
      { question: "Can I add Haridwar to this package?", answer: "Haridwar is just 35 km away and can be easily combined. We include a Haridwar Ganga Aarti evening in the extended 3N package for ₹8,999." },
      { question: "What adventure activities are available?", answer: "Rishikesh offers river rafting, bungee jumping (₹3,500), giant swing (₹3,500), cliff jumping, kayaking, and camping. We can arrange all activities." },
      { question: "When is the best time for Rishikesh?", answer: "September to November and February to May. Rafting season is September to June. Avoid July-August monsoon when river current is too strong." },
      { question: "Can I do yoga retreat instead of adventure?", answer: "Yes! We can arrange yoga retreat packages at famous ashrams like Parmarth Niketan or Sivananda Ashram. Minimum 3 nights recommended for yoga retreats." },
    ],
  },
  "nainital-2-nights-with-cab": {
    slug: "nainital-2-nights-with-cab",
    destination: "Nainital",
    duration: "2 Nights / 3 Days",
    startingPrice: 7499,
    perPerson: true,
    includes: ["2 nights hotel stay", "AC cab for all transfers", "Pickup & drop from Delhi", "Breakfast", "Naini Lake boating", "All tolls and parking"],
    itinerary: [
      { day: 1, title: "Delhi to Nainital", activities: ["Morning pickup from Delhi", "Drive to Nainital (290 km, 7 hrs)", "Stop at Kathgodam for lunch", "Check-in and rest", "Evening walk on Mall Road"] },
      { day: 2, title: "Full Day Sightseeing", activities: ["Breakfast", "Naini Lake boating", "Naina Devi Temple", "Snow View Point (ropeway)", "Tiffin Top trek (optional)", "Eco Cave Garden", "Evening Mall Road shopping"] },
      { day: 3, title: "Bhimtal & Return", activities: ["Breakfast and checkout", "Bhimtal Lake visit", "Naukuchiatal (nine-cornered lake)", "Lunch en route", "Drive back to Delhi"] },
    ],
    hotelOptions: [
      { category: "Budget (3-Star)", price: 7499 },
      { category: "Lake View (4-Star)", price: 11999 },
      { category: "Premium Resort", price: 18999 },
    ],
    faqs: [
      { question: "Does the package include Naini Lake boating?", answer: "Yes, one boating session on Naini Lake is included. You can choose paddle boat or rowing boat. Yacht rides are available at extra cost." },
      { question: "Is Nainital good for families with children?", answer: "Excellent choice! Kids love the lake, zoo, ropeway, Eco Cave Garden, and horse riding. It's safe, clean, and very family-friendly." },
      { question: "What is the best time for Nainital?", answer: "March to June for pleasant weather, October-November for clear mountain views, December-February for snowfall at higher points. Avoid monsoon." },
      { question: "Can I add Jim Corbett to this trip?", answer: "Yes! Jim Corbett is 65 km from Nainital. Add 1 night for safari experience. Our Nainital + Jim Corbett combo (3N/4D) starts at ₹12,999." },
      { question: "How far is Nainital from Delhi?", answer: "Nainital is 290 km from Delhi (7 hours drive via NH-9 and Kathgodam route). The last 30 km is a scenic mountain drive." },
      { question: "Is the road to Nainital safe?", answer: "The Delhi-Kathgodam highway is excellent. The mountain stretch to Nainital is well-maintained but winding. Our experienced hill drivers ensure complete safety." },
    ],
  },
  "kashmir-5-nights-with-cab": {
    slug: "kashmir-5-nights-with-cab",
    destination: "Kashmir",
    duration: "5 Nights / 6 Days",
    startingPrice: 19999,
    perPerson: true,
    includes: ["5 nights hotel (2N Srinagar + 1N Gulmarg + 2N Houseboat)", "AC cab for all transfers", "Airport pickup & drop", "Breakfast & dinner", "Shikara ride", "All permits"],
    itinerary: [
      { day: 1, title: "Arrival in Srinagar", activities: ["Airport pickup", "Hotel check-in", "Mughal Gardens (Shalimar, Nishat, Cheshmashahi)", "Evening Shikara ride on Dal Lake", "Dinner at hotel"] },
      { day: 2, title: "Gulmarg Day", activities: ["Drive to Gulmarg (50 km, 1.5 hrs)", "Gondola Phase 1 & 2 (world's highest)", "Snow activities (seasonal)", "ATV ride or pony ride", "Return to Srinagar / Stay in Gulmarg"] },
      { day: 3, title: "Pahalgam Excursion", activities: ["Drive to Pahalgam (95 km, 2.5 hrs)", "Betaab Valley", "Aru Valley", "Chandanwari (Amarnath trek starting point)", "Return to Srinagar"] },
      { day: 4, title: "Sonmarg Day Trip", activities: ["Drive to Sonmarg (80 km, 2.5 hrs)", "Thajiwas Glacier trek", "Zero Point (seasonal)", "Scenic Sindh Valley views", "Return to houseboat", "Night on Dal Lake houseboat"] },
      { day: 5, title: "Srinagar Local & Houseboat", activities: ["Breakfast on houseboat", "Floating market visit (early morning)", "Shankaracharya Temple", "Local handicraft shopping", "Walnut wood & Pashmina shopping", "Dinner on houseboat"] },
      { day: 6, title: "Departure", activities: ["Breakfast", "Checkout", "Drop to Srinagar airport", "Memories for a lifetime"] },
    ],
    hotelOptions: [
      { category: "Budget (3-Star + Houseboat)", price: 19999 },
      { category: "Deluxe (4-Star + Premium Houseboat)", price: 32999 },
      { category: "Luxury (5-Star + Royal Houseboat)", price: 49999 },
    ],
    faqs: [
      { question: "Is Kashmir safe for tourists?", answer: "Yes, Kashmir's tourist areas (Srinagar, Gulmarg, Pahalgam, Sonmarg) are completely safe and heavily patrolled. Millions of tourists visit every year without any issues." },
      { question: "Does the package include a houseboat stay?", answer: "Yes! 2 nights on a traditional Kashmiri houseboat on Dal Lake are included. It's an iconic experience with meals served on the boat." },
      { question: "What is the best time for Kashmir?", answer: "March-June for tulip gardens and pleasant weather, July-August for green meadows, December-February for snow. Each season offers a unique Kashmir experience." },
      { question: "Is Gondola ride at Gulmarg included?", answer: "Gondola tickets are extra (Phase 1: ₹740, Phase 2: ₹920 per person). We arrange priority tickets and our driver manages the logistics." },
      { question: "Can I extend this to Leh-Ladakh?", answer: "Yes! The Srinagar-Leh highway (434 km) is an epic drive. Add 3-4 days for Leh-Ladakh extension. Road is open June-October only." },
      { question: "How do I reach Srinagar?", answer: "Srinagar has a well-connected domestic airport (1.5 hrs from Delhi). Direct flights from all major cities. We provide airport pickup included in the package." },
    ],
  },
  "rajasthan-5-nights-with-cab": {
    slug: "rajasthan-5-nights-with-cab",
    destination: "Rajasthan",
    duration: "5 Nights / 6 Days",
    startingPrice: 16999,
    perPerson: true,
    includes: ["5 nights hotel stay", "AC cab for entire trip", "Delhi pickup & drop", "Breakfast", "Desert safari in Jaisalmer (if included)", "All tolls and parking"],
    itinerary: [
      { day: 1, title: "Delhi to Jaipur", activities: ["Morning pickup from Delhi", "Drive to Jaipur (280 km, 5 hrs)", "Check-in", "Evening at Nahargarh Fort sunset", "Local dinner"] },
      { day: 2, title: "Jaipur Sightseeing", activities: ["Amber Fort", "City Palace & Jantar Mantar", "Hawa Mahal", "Johari Bazaar shopping", "Evening free"] },
      { day: 3, title: "Jaipur to Jodhpur", activities: ["Drive to Jodhpur (340 km, 6 hrs)", "Check-in", "Evening Mehrangarh Fort visit", "Blue City walk", "Clock Tower bazaar"] },
      { day: 4, title: "Jodhpur to Jaisalmer", activities: ["Drive to Jaisalmer (285 km, 5 hrs)", "Check-in", "Jaisalmer Fort exploration", "Patwon Ki Haveli", "Evening Sam Sand Dunes desert safari"] },
      { day: 5, title: "Jaisalmer to Udaipur", activities: ["Drive to Udaipur (550 km, 9 hrs)", "Scenic desert-to-lake drive", "Check-in", "Evening Lake Pichola boat ride", "Farewell dinner"] },
      { day: 6, title: "Udaipur & Return", activities: ["City Palace", "Jagdish Temple", "Lunch", "Flight/train to Delhi (or drive)"] },
    ],
    hotelOptions: [
      { category: "Budget (3-Star)", price: 16999 },
      { category: "Heritage Hotels", price: 26999 },
      { category: "Royal Palace Hotels", price: 44999 },
    ],
    faqs: [
      { question: "Which Rajasthan cities are covered in 5 nights?", answer: "Jaipur (2N), Jodhpur (1N), Jaisalmer (1N), and Udaipur (1N). This covers the Pink, Blue, Golden, and White cities of Rajasthan." },
      { question: "Is desert camping included?", answer: "The desert safari at Sam Sand Dunes is included in the itinerary. If you want overnight desert camping instead of hotel, it can be arranged at similar cost." },
      { question: "Can I stay at heritage hotels?", answer: "Yes! Rajasthan is famous for heritage hotels (converted forts and palaces). Our Heritage Hotels option at ₹26,999 includes authentic royal stays." },
      { question: "What is the best time for Rajasthan?", answer: "October to March — perfect weather (15-25°C). The Pushkar Camel Fair (November) and Jaisalmer Desert Festival (February) add extra charm." },
      { question: "Is the Jaisalmer to Udaipur drive too long?", answer: "Yes, it's 550 km (9 hrs). Alternative: skip Udaipur and return to Delhi from Jaisalmer, or take a budget flight from Udaipur. We can customize the route." },
      { question: "Can I add Pushkar or Ranthambore?", answer: "Yes! Pushkar is on the Jaipur-Jodhpur route (add 1N). Ranthambore adds 1-2 nights between Jaipur and Jodhpur. Both are highly recommended." },
    ],
  },
  "golden-triangle-3-nights-with-cab": {
    slug: "golden-triangle-3-nights-with-cab",
    destination: "Golden Triangle",
    duration: "3 Nights / 4 Days",
    startingPrice: 9999,
    perPerson: true,
    includes: ["3 nights hotel (1N Delhi + 1N Agra + 1N Jaipur)", "AC cab for entire trip", "Breakfast", "Taj Mahal sunrise", "Full sightseeing all 3 cities", "All tolls and parking"],
    itinerary: [
      { day: 1, title: "Delhi Sightseeing", activities: ["Pickup from hotel/airport", "India Gate & Rashtrapati Bhavan", "Qutub Minar", "Humayun's Tomb", "Red Fort", "Chandni Chowk food walk", "Overnight Delhi"] },
      { day: 2, title: "Delhi to Agra", activities: ["Drive to Agra (230 km, 3 hrs)", "Check-in", "Agra Fort visit", "Mehtab Bagh sunset (Taj view)", "Local petha shopping", "Overnight Agra"] },
      { day: 3, title: "Taj Mahal & Agra to Jaipur", activities: ["Sunrise at Taj Mahal", "Breakfast", "Fatehpur Sikri en route", "Drive to Jaipur (240 km, 4.5 hrs)", "Evening Hawa Mahal", "Overnight Jaipur"] },
      { day: 4, title: "Jaipur & Return to Delhi", activities: ["Amber Fort", "City Palace & Jantar Mantar", "Lunch", "Drive to Delhi (280 km, 5 hrs)", "Drop at hotel/airport"] },
    ],
    hotelOptions: [
      { category: "Budget (3-Star)", price: 9999 },
      { category: "Deluxe (4-Star)", price: 15999 },
      { category: "Premium (5-Star)", price: 27999 },
    ],
    faqs: [
      { question: "Is the Golden Triangle package worth it for 3 nights?", answer: "Absolutely! 3N/4D is the most popular Golden Triangle format. You see Delhi, Agra (Taj Mahal), and Jaipur — India's 3 most iconic cities — with comfortable pacing." },
      { question: "Is Taj Mahal sunrise visit included?", answer: "Yes, our driver takes you to Taj Mahal at 5:30 AM for the magical sunrise experience. Entry ticket (₹1,100 for foreigners, ₹50 for Indians) is extra." },
      { question: "Can I start the trip from Jaipur instead of Delhi?", answer: "Yes! We offer Jaipur-Agra-Delhi and Agra-Delhi-Jaipur variants. The circular route works in any direction." },
      { question: "What is included in meals?", answer: "Daily breakfast is included. Lunch and dinner are on your own. We recommend famous local spots — Karim's in Delhi, Pinch of Spice in Agra, Chokhi Dhani in Jaipur." },
      { question: "Can I add Mathura-Vrindavan?", answer: "Yes! Mathura-Vrindavan is on the Delhi-Agra route. Add 2-3 hours for a visit to Krishna Janmabhoomi and Banke Bihari Temple. No extra night needed." },
      { question: "Is this package suitable for foreign tourists?", answer: "Very popular with international visitors! We provide English-speaking drivers and can arrange licensed guides at each city. All hotels are tourist-certified." },
    ],
  },
  "chardham-10-nights-with-cab": {
    slug: "chardham-10-nights-with-cab",
    destination: "Char Dham",
    duration: "10 Nights / 11 Days",
    startingPrice: 29999,
    perPerson: true,
    includes: ["10 nights hotel stay", "AC SUV cab for entire trip", "Delhi/Haridwar pickup & drop", "Breakfast & dinner", "All permits", "Emergency oxygen cylinder"],
    itinerary: [
      { day: 1, title: "Delhi to Haridwar", activities: ["Pickup from Delhi", "Drive to Haridwar (230 km)", "Ganga Aarti at Har Ki Pauri", "Overnight Haridwar"] },
      { day: 2, title: "Haridwar to Barkot", activities: ["Drive to Barkot (210 km, 7 hrs)", "En route Mussoorie viewpoint", "Arrive Barkot (base for Yamunotri)", "Rest and acclimatize"] },
      { day: 3, title: "Yamunotri Dham", activities: ["Drive to Janki Chatti (40 km)", "Trek to Yamunotri Temple (6 km)", "Holy dip in Surya Kund", "Return trek and drive to Barkot"] },
      { day: 4, title: "Barkot to Uttarkashi", activities: ["Drive to Uttarkashi (100 km, 4 hrs)", "Visit Vishwanath Temple", "Shakti Temple", "Rest and overnight"] },
      { day: 5, title: "Gangotri Dham", activities: ["Drive to Gangotri (100 km, 4 hrs)", "Gangotri Temple darshan", "Bhagirathi river source", "Return to Uttarkashi"] },
      { day: 6, title: "Uttarkashi to Guptkashi", activities: ["Drive to Guptkashi (220 km, 8 hrs)", "Scenic Mandakini Valley drive", "Rest and prepare for Kedarnath"] },
      { day: 7, title: "Kedarnath Dham", activities: ["Drive to Sonprayag/Gaurikund", "Trek/helicopter to Kedarnath (16 km)", "Kedarnath Temple darshan", "Return trek or overnight near temple"] },
      { day: 8, title: "Kedarnath to Badrinath", activities: ["Drive to Badrinath via Chopta (250 km, 9 hrs)", "Scenic Himalayan drive", "Arrive Badrinath", "Evening Mana Village visit"] },
      { day: 9, title: "Badrinath Dham", activities: ["Early morning Badrinath Temple darshan", "Tapt Kund holy bath", "Mana Village (last Indian village)", "Vasudhara Falls", "Return to Badrinath"] },
      { day: 10, title: "Badrinath to Rudraprayag", activities: ["Drive to Rudraprayag (160 km, 6 hrs)", "Visit Devprayag confluence", "Rest overnight"] },
      { day: 11, title: "Rudraprayag to Delhi", activities: ["Drive to Haridwar/Delhi (165/395 km)", "Departure with Char Dham memories"] },
    ],
    hotelOptions: [
      { category: "Budget (Dharamshala/3-Star)", price: 29999 },
      { category: "Deluxe (4-Star Hotels)", price: 44999 },
      { category: "Premium (Best Available)", price: 64999 },
    ],
    faqs: [
      { question: "When is the best time for Char Dham Yatra?", answer: "May to June and September to October. The temples open in April/May and close in November (Diwali). Monsoon (July-August) is risky due to landslides." },
      { question: "Is Char Dham suitable for elderly people?", answer: "Yamunotri (6 km trek) and Kedarnath (16 km trek) require walking. Palki (palanquin) and helicopter services are available for elderly. Badrinath and Gangotri are road-accessible." },
      { question: "Why is SUV recommended for Char Dham?", answer: "Char Dham involves mountain roads at 10,000+ ft altitude. SUV (Innova) offers better ground clearance, power on steep inclines, and comfort for long drives." },
      { question: "Is helicopter service available for Kedarnath?", answer: "Yes, helicopter service (₹7,000-10,000 per person one-way) operates from Guptkashi/Phata to Kedarnath. Book 1-2 months in advance as slots fill quickly." },
      { question: "What should I pack for Char Dham?", answer: "Warm layers, rain jacket, comfortable trekking shoes, medicines, water bottle, torch, and energy snacks. We provide an emergency oxygen cylinder in the vehicle." },
      { question: "Can I do Do Dham (2 temples) instead?", answer: "Yes! Popular Do Dham options: Kedarnath + Badrinath (5N/6D from ₹14,999) or Yamunotri + Gangotri (4N/5D from ₹11,999). Call 7668570551 to customize." },
    ],
  },
  "varanasi-2-nights-with-cab": {
    slug: "varanasi-2-nights-with-cab",
    destination: "Varanasi",
    duration: "2 Nights / 3 Days",
    startingPrice: 7499,
    perPerson: true,
    includes: ["2 nights hotel stay", "AC cab for transfers", "Airport/station pickup & drop", "Breakfast", "Boat ride on Ganga", "Sarnath excursion"],
    itinerary: [
      { day: 1, title: "Arrival & Ganga Aarti", activities: ["Airport/station pickup", "Hotel check-in", "Evening walk through old Varanasi lanes", "Dashashwamedh Ghat Ganga Aarti (7 PM)", "Dinner at local restaurant"] },
      { day: 2, title: "Sunrise Boat Ride & Temples", activities: ["5 AM sunrise boat ride on Ganga", "Watch cremation ghats from boat", "Breakfast", "Kashi Vishwanath Temple", "Sarnath Buddhist site (10 km)", "Evening free for exploration"] },
      { day: 3, title: "Local Visits & Departure", activities: ["Breakfast", "BHU campus & Bharat Kala Bhavan museum", "Ramnagar Fort", "Local shopping (Banarasi silk)", "Drop to airport/station"] },
    ],
    hotelOptions: [
      { category: "Budget (3-Star)", price: 7499 },
      { category: "Heritage Haveli", price: 12999 },
      { category: "Ghat View Premium", price: 18999 },
    ],
    faqs: [
      { question: "Is the Ganga boat ride included?", answer: "Yes, a sunrise boat ride on the Ganga is included. This is the most magical experience in Varanasi — watching the sun rise over the ancient ghats." },
      { question: "Is Varanasi safe for tourists?", answer: "Yes, Varanasi is safe for tourists. The main ghat areas and tourist zones are well-patrolled. Our drivers know the city intimately and ensure your safety." },
      { question: "Can I add Ayodhya to this trip?", answer: "Yes! Ayodhya is 200 km from Varanasi (4 hours). Add 1 night for the Ram Mandir visit. Our Varanasi + Ayodhya combo (3N/4D) starts at ₹11,999." },
      { question: "What is the best time for Varanasi?", answer: "October to March for comfortable weather. Dev Deepawali (November) when all ghats are lit with diyas is absolutely magical." },
      { question: "Can I witness a cremation ceremony?", answer: "You can observe cremation ghats (Manikarnika, Harishchandra) from a respectful distance during the boat ride. Photography is not permitted at cremation ghats." },
      { question: "Should I buy Banarasi silk in Varanasi?", answer: "Absolutely! Varanasi is the original source of Banarasi silk sarees. Our driver can take you to authentic weavers, not tourist shops, for genuine products at factory prices." },
    ],
  },
  "amritsar-2-nights-with-cab": {
    slug: "amritsar-2-nights-with-cab",
    destination: "Amritsar",
    duration: "2 Nights / 3 Days",
    startingPrice: 7999,
    perPerson: true,
    includes: ["2 nights hotel stay", "AC cab for all transfers", "Delhi pickup & drop", "Breakfast", "Wagah Border trip", "All tolls and parking"],
    itinerary: [
      { day: 1, title: "Delhi to Amritsar", activities: ["Morning pickup from Delhi", "Drive to Amritsar (450 km, 7 hrs)", "Check-in", "Evening Golden Temple visit", "Langar (community kitchen) experience"] },
      { day: 2, title: "Amritsar Sightseeing", activities: ["Breakfast", "Golden Temple morning visit", "Jallianwala Bagh", "Partition Museum", "Afternoon Wagah Border ceremony", "Amritsari kulcha food trail", "Evening free"] },
      { day: 3, title: "Local Visits & Return", activities: ["Breakfast", "Maharaja Ranjit Singh Museum", "Hall Bazaar shopping", "Lunch (Amritsari fish fry)", "Drive to Delhi or station drop"] },
    ],
    hotelOptions: [
      { category: "Budget (3-Star)", price: 7999 },
      { category: "Deluxe (4-Star)", price: 12999 },
      { category: "Heritage (near Golden Temple)", price: 17999 },
    ],
    faqs: [
      { question: "Is Wagah Border ceremony included?", answer: "Yes, we include the cab transfer to Wagah Border (30 km from Amritsar). The ceremony is free to attend. Arrive 2 hours early for good seats — our driver manages timing." },
      { question: "Can I visit the Golden Temple at night?", answer: "The Golden Temple is open 24 hours. The evening illumination (after 8 PM) and early morning (4 AM Palki Sahib ceremony) are the most magical times." },
      { question: "Is the Amritsar food tour included?", answer: "Our driver doubles as a local food guide! He'll take you to the best kulcha spots, lassi shops, and street food — included in the cab service." },
      { question: "Can I extend to Dharamshala?", answer: "Yes! Dharamshala is 190 km from Amritsar (4 hours). Add 2 nights for Dharamshala-McLeodganj. Our Amritsar + Dharamshala combo (4N/5D) starts at ₹14,999." },
      { question: "How far is Amritsar from Delhi?", answer: "Amritsar is 450 km from Delhi (7 hours via NH-44 through Punjab). The highway is excellent. Alternatively, take Shatabdi Express (6 hrs) and we provide station pickup." },
      { question: "What is the best time for Amritsar?", answer: "October to March for pleasant weather. Baisakhi (April 13) and Guru Nanak Jayanti (November) are special celebrations at the Golden Temple." },
    ],
  },
  "leh-ladakh-7-nights-with-cab": {
    slug: "leh-ladakh-7-nights-with-cab",
    destination: "Leh Ladakh",
    duration: "7 Nights / 8 Days",
    startingPrice: 24999,
    perPerson: true,
    includes: ["7 nights hotel/camp stay", "AC SUV cab for entire trip", "Airport pickup & drop", "Breakfast & dinner", "All permits (Inner Line)", "Oxygen cylinder"],
    itinerary: [
      { day: 1, title: "Arrival in Leh", activities: ["Airport pickup", "Hotel check-in", "Complete rest for acclimatization", "Evening walk to Leh Market", "Overnight Leh"] },
      { day: 2, title: "Leh Local Sightseeing", activities: ["Shanti Stupa", "Leh Palace", "Hall of Fame Museum", "Magnetic Hill", "Gurudwara Pathar Sahib", "Sangam Point (Indus-Zanskar confluence)"] },
      { day: 3, title: "Leh to Nubra Valley", activities: ["Drive via Khardung La (17,982 ft)", "Descend to Nubra Valley", "Diskit Monastery", "Double humped camel ride at Hunder dunes", "Overnight Nubra (camp)"] },
      { day: 4, title: "Nubra to Pangong Lake", activities: ["Drive to Pangong Lake via Shyok Road", "Arrive at Pangong Tso (14,270 ft)", "Famous 3 Idiots lake", "Sunset at Pangong", "Overnight camp at Pangong"] },
      { day: 5, title: "Pangong to Leh", activities: ["Sunrise at Pangong Lake", "Drive back to Leh via Chang La (17,590 ft)", "Thiksey Monastery en route", "Hemis Monastery", "Overnight Leh"] },
      { day: 6, title: "Leh to Tso Moriri", activities: ["Drive to Tso Moriri (250 km, 7 hrs)", "Scenic drive through Chumur", "Tso Moriri Lake evening", "Overnight Korzok village"] },
      { day: 7, title: "Tso Moriri to Leh", activities: ["Morning at Tso Moriri", "Drive to Leh via Puga Hot Springs", "Tso Kar Lake en route", "Arrive Leh", "Farewell dinner"] },
      { day: 8, title: "Departure", activities: ["Breakfast", "Drop to Leh airport", "Departure with memories of a lifetime"] },
    ],
    hotelOptions: [
      { category: "Budget (Guest House + Camp)", price: 24999 },
      { category: "Deluxe (4-Star + Luxury Camp)", price: 39999 },
      { category: "Premium (Best Hotels + Glamping)", price: 59999 },
    ],
    faqs: [
      { question: "When is the best time for Leh Ladakh?", answer: "June to September. Roads open from June (Manali route) and May (Srinagar route). July-August has the warmest weather. September offers clear skies." },
      { question: "Do I need to worry about altitude sickness?", answer: "Day 1 is dedicated to acclimatization in Leh (11,500 ft). We provide oxygen cylinders in the vehicle. Stay hydrated, avoid alcohol, and move slowly on Day 1." },
      { question: "Why is SUV mandatory for Ladakh?", answer: "Ladakh roads include Khardung La (17,982 ft) and Chang La (17,590 ft) with rough patches. SUV offers necessary ground clearance, power, and safety." },
      { question: "Is the Inner Line Permit included?", answer: "Yes, all permits (Inner Line Permit for Nubra, Pangong, Tso Moriri) are arranged and included in the package cost." },
      { question: "Can I drive from Delhi instead of flying?", answer: "Yes! The Delhi-Manali-Leh (1,000 km) or Delhi-Srinagar-Leh (900 km) drives are epic adventures. Add 2-3 days each way. We offer this as an extended package." },
      { question: "Is Ladakh safe for couples?", answer: "Ladakh is one of India's safest destinations. Very low crime, friendly locals, and well-patrolled tourist areas. Perfect for adventurous couples." },
    ],
  },
  "spiti-valley-5-nights-with-cab": {
    slug: "spiti-valley-5-nights-with-cab",
    destination: "Spiti Valley",
    duration: "5 Nights / 6 Days",
    startingPrice: 18999,
    perPerson: true,
    includes: ["5 nights hotel/homestay", "SUV cab for entire trip", "Chandigarh/Manali pickup & drop", "Breakfast & dinner", "All permits", "Experienced mountain driver"],
    itinerary: [
      { day: 1, title: "Manali to Kaza", activities: ["Early start from Manali", "Cross Rohtang Pass / Atal Tunnel", "Kunzum Pass (15,060 ft)", "Arrive Kaza (capital of Spiti)", "Rest and acclimatize"] },
      { day: 2, title: "Kaza & Key Monastery", activities: ["Key Monastery (largest in Spiti)", "Kibber Village (14,200 ft)", "Chicham Bridge (highest bridge in Asia)", "Kaza market walk", "Evening stargazing"] },
      { day: 3, title: "Chandratal Lake", activities: ["Drive to Chandratal Lake (Moon Lake)", "Trek to the lake", "Pristine crescent-shaped alpine lake", "Return to Kaza", "Overnight Kaza"] },
      { day: 4, title: "Kaza to Tabo", activities: ["Drive to Tabo (45 km)", "Tabo Monastery (1,000+ years old)", "Dhankar Monastery & Lake", "Pin Valley National Park", "Overnight Tabo"] },
      { day: 5, title: "Tabo to Kalpa/Nako", activities: ["Drive to Kalpa or Nako (170 km)", "Nako Lake & Nako Monastery", "Kinnaur Kailash views", "Apple orchards", "Overnight Kalpa/Nako"] },
      { day: 6, title: "Return Journey", activities: ["Drive to Shimla/Chandigarh", "Scenic Kinnaur Valley drive", "Reckong Peo viewpoint", "Departure"] },
    ],
    hotelOptions: [
      { category: "Homestay (Basic)", price: 18999 },
      { category: "Guest House (Comfortable)", price: 26999 },
      { category: "Best Available (Premium)", price: 36999 },
    ],
    faqs: [
      { question: "When can I visit Spiti Valley?", answer: "June to October via Manali (Rohtang Pass route). Year-round via Shimla-Kinnaur route (though risky in winter). July-September is the peak season." },
      { question: "Why is SUV mandatory for Spiti?", answer: "Spiti has some of India's most challenging roads with river crossings, high passes, and unpaved sections. SUV is essential for safety and comfort." },
      { question: "Is Spiti suitable for beginners?", answer: "Spiti requires basic fitness and altitude tolerance (12,000-15,000 ft). If you can walk 2-3 km without breathlessness, you're fine. We plan acclimatization days." },
      { question: "What about mobile connectivity?", answer: "BSNL has the best coverage in Spiti, but signal is limited. Kaza has basic connectivity. Enjoy the digital detox! Inform family about limited connectivity in advance." },
      { question: "Can I do Spiti as a circuit from Chandigarh?", answer: "Yes! The classic circuit is Chandigarh → Shimla → Kinnaur → Kaza → Manali → Chandigarh (or reverse). This requires 7-8 days and covers both entry routes." },
      { question: "What should I pack for Spiti?", answer: "Heavy warm layers, sunscreen SPF 50+, sunglasses, medicines (Diamox for altitude), torch, power bank, and snacks. Hotels/homestays may have basic amenities." },
    ],
  },
  "jim-corbett-2-nights-with-cab": {
    slug: "jim-corbett-2-nights-with-cab",
    destination: "Jim Corbett",
    duration: "2 Nights / 3 Days",
    startingPrice: 7999,
    perPerson: true,
    includes: ["2 nights resort stay", "AC cab for all transfers", "Delhi pickup & drop", "Breakfast & dinner", "1 jungle safari", "All tolls and parking"],
    itinerary: [
      { day: 1, title: "Delhi to Jim Corbett", activities: ["Morning pickup from Delhi", "Drive to Jim Corbett (260 km, 5.5 hrs)", "Check-in at resort", "Afternoon nature walk / bird watching", "Evening bonfire at resort"] },
      { day: 2, title: "Safari & Exploration", activities: ["Early morning jungle safari (Bijrani/Dhikala zone)", "Spot tigers, elephants, deer, and crocodiles", "Breakfast at resort", "Afternoon at leisure / pool", "Evening Corbett Museum visit", "Dinner at resort"] },
      { day: 3, title: "Garjia Temple & Return", activities: ["Breakfast", "Visit Garjia Temple on a rock island", "Kosi River viewpoint", "Drive to Delhi", "Evening arrival"] },
    ],
    hotelOptions: [
      { category: "Budget Resort", price: 7999 },
      { category: "Jungle Lodge", price: 13999 },
      { category: "Luxury Wildlife Resort", price: 21999 },
    ],
    faqs: [
      { question: "Is jungle safari included?", answer: "Yes, 1 jeep safari in Bijrani zone is included. Additional safaris can be booked at ₹4,500-6,000 per jeep. Dhikala zone (full-day) requires advance booking." },
      { question: "Will I see a tiger at Jim Corbett?", answer: "Jim Corbett has 250+ tigers, offering India's best tiger sighting probability. Morning safaris have higher success rates. We book the best zones based on recent sightings." },
      { question: "Which zone is best for tiger sighting?", answer: "Dhikala and Bijrani have the highest tiger sighting rates. Jhirna is open year-round and is also good. Our team checks recent sighting data before booking your zone." },
      { question: "When is the best time to visit Corbett?", answer: "November to June for wildlife viewing. February-May is peak tiger sighting season (vegetation thins, animals come to water). Monsoon closes most zones." },
      { question: "Is Corbett safe for children?", answer: "Yes, children love the safari experience! Kids under 5 are not allowed in Dhikala zone. Other zones welcome families. The resort activities (bonfire, nature walks) are kid-friendly." },
      { question: "Can I add Nainital to this trip?", answer: "Nainital is just 65 km from Corbett. Add 1 night for a lake + wildlife combo. Our Corbett + Nainital (3N/4D) package starts at ₹12,999." },
    ],
  },
};

export function getPackage(slug) {
  return packages[slug] || null;
}

export function getAllPackageSlugs() {
  return Object.keys(packages);
}

export function getRelatedPackages(slug, limit = 3) {
  const all = Object.values(packages);
  return all.filter(p => p.slug !== slug).slice(0, limit);
}
