// src/utilis/roadTripData.js - Complete data for 9 Road Trip Circuit Guide pages
// Pricing: Sedan ₹11/km, SUV ₹14/km

const roadTrips = {
  "golden-triangle-by-car": {
    slug: "golden-triangle-by-car",
    name: "Golden Triangle by Car",
    tagline: "Delhi → Agra → Jaipur — India's Most Iconic Road Trip Circuit",
    totalDistance: 720,
    totalDays: 5,
    stops: [
      { city: "Delhi", nights: 1, highlights: ["India Gate", "Red Fort", "Qutub Minar", "Chandni Chowk food walk"] },
      { city: "Agra", nights: 1, highlights: ["Taj Mahal sunrise", "Agra Fort", "Mehtab Bagh sunset", "Petha tasting"] },
      { city: "Jaipur", nights: 2, highlights: ["Amber Fort elephant ride", "Hawa Mahal", "City Palace", "Johari Bazaar shopping"] },
      { city: "Delhi", nights: 0, highlights: ["Return via Neemrana Fort (optional stop)"] },
    ],
    totalCost: { sedan: 7920, suv: 10080 },
    highlights: [
      "3 UNESCO World Heritage Sites in one trip",
      "Best-maintained highways (NH-44, NH-48, NH-21)",
      "Mix of Mughal & Rajput architecture",
      "Famous food stops: Murthal paranthas, Agra petha, Jaipur dal baati",
      "Perfect 5-day circuit with no backtracking",
    ],
    bestSeason: "October to March — Pleasant weather, clear skies for monument photography",
    faqs: [
      { question: "How many days do I need for the Golden Triangle road trip?", answer: "Ideally 5 days / 4 nights covers all major sights comfortably. Delhi (1N), Agra (1N), Jaipur (2N). A rushed 3-day version is possible but you'll miss key attractions." },
      { question: "What is the total cost of Golden Triangle by car?", answer: "With Triveni Cabs, the Golden Triangle circuit costs from ₹7,920 (Sedan) to ₹10,080 (SUV) for the 720 km journey. This includes driver, fuel, and AC. Toll, parking, and state tax are extra." },
      { question: "Which is the best route for Delhi-Agra-Jaipur by car?", answer: "The standard route is Delhi → Agra (230 km via Yamuna Expressway, 3 hrs) → Jaipur (240 km via NH-21, 4.5 hrs) → Delhi (280 km via NH-48, 5 hrs). All are excellent highways." },
      { question: "Is the Golden Triangle road trip safe for families?", answer: "Absolutely. The Golden Triangle routes are among India's safest and best-maintained highways. Our GPS-tracked vehicles and experienced drivers ensure complete safety. 24/7 support available." },
      { question: "Can I customize the Golden Triangle itinerary?", answer: "Yes! Popular add-ons include Mathura-Vrindavan (near Agra), Ranthambore (between Agra-Jaipur), and Pushkar (near Jaipur). Call 7668570551 to customize." },
      { question: "What car types are available for the Golden Triangle trip?", answer: "We offer Sedan (Swift Dzire, 4-seater), SUV (Innova Crysta, 6-seater), and Tempo Traveller (12-seater) for the Golden Triangle circuit. All vehicles are AC, well-maintained, and GPS-equipped." },
    ],
  },
  "delhi-shimla-manali-chandigarh-circuit": {
    slug: "delhi-shimla-manali-chandigarh-circuit",
    name: "Delhi – Shimla – Manali – Chandigarh Circuit",
    tagline: "The Ultimate Himalayan Road Trip — Snow Peaks, Pine Forests & Mountain Passes",
    totalDistance: 1050,
    totalDays: 8,
    stops: [
      { city: "Shimla", nights: 2, highlights: ["Mall Road", "Jakhoo Temple", "Kufri adventure park", "Christ Church", "The Ridge sunset"] },
      { city: "Manali", nights: 3, highlights: ["Solang Valley", "Rohtang Pass", "Old Manali cafes", "Hadimba Temple", "Atal Tunnel"] },
      { city: "Chandigarh", nights: 1, highlights: ["Rock Garden", "Sukhna Lake", "Rose Garden", "Sector 17 market"] },
    ],
    totalCost: { sedan: 11550, suv: 14700 },
    highlights: [
      "Cross 3 Himalayan hill stations in one circuit",
      "Scenic Shimla-Manali highway (250 km mountain drive)",
      "Snow activities at Solang Valley & Rohtang Pass",
      "No backtracking — circular route via Chandigarh",
      "Mix of colonial charm (Shimla) & adventure (Manali)",
    ],
    bestSeason: "March to June for clear roads; December to February for snow experience",
    faqs: [
      { question: "How long is the Delhi-Shimla-Manali-Chandigarh road trip?", answer: "Plan 7-8 days for a comfortable trip. Delhi to Shimla (350 km, 7 hrs), Shimla to Manali (250 km, 8 hrs), Manali to Chandigarh (310 km, 9 hrs), Chandigarh to Delhi (250 km, 4 hrs). Total 1,050 km." },
      { question: "What is the cost of Delhi to Shimla Manali trip by car?", answer: "The complete circuit costs from ₹11,550 (Sedan) to ₹14,700 (SUV) for the 1,050 km route. Driver night charges, toll, and parking are additional." },
      { question: "Is Rohtang Pass open during the road trip?", answer: "Rohtang Pass is typically open from May to November. In winter, Atal Tunnel (completed 2020) provides year-round access to Lahaul-Spiti. Always check BRO updates before planning." },
      { question: "Can we do Shimla-Manali road trip in winter?", answer: "Yes, but expect snow on the Shimla-Manali highway. Our drivers are experienced in winter driving. Carry warm clothes, snow boots, and be prepared for occasional road closures." },
      { question: "Which is better for families — Shimla or Manali?", answer: "Both are family-friendly. Shimla offers colonial charm, easy walks, and Kufri. Manali offers adventure activities and snow. That's why this circuit covers both!" },
      { question: "What are the best food stops on this route?", answer: "Murthal (Delhi-Shimla highway), Barog (Kalka-Shimla), Pandoh (Shimla-Manali), Kullu (local trout fish), and Chandigarh (Sector 17 street food). Our drivers know all the best dhabas." },
    ],
  },
  "uttarakhand-hill-station-circuit": {
    slug: "uttarakhand-hill-station-circuit",
    name: "Uttarakhand Hill Station Circuit",
    tagline: "Mussoorie → Nainital → Jim Corbett — Mountains, Lakes & Wildlife",
    totalDistance: 780,
    totalDays: 7,
    stops: [
      { city: "Mussoorie", nights: 2, highlights: ["Kempty Falls", "Gun Hill Point", "Camel's Back Road", "Lal Tibba viewpoint"] },
      { city: "Nainital", nights: 2, highlights: ["Naini Lake boating", "Naina Devi Temple", "Snow View Point", "Mall Road shopping"] },
      { city: "Jim Corbett", nights: 1, highlights: ["Jungle safari", "Bijrani zone wildlife", "Corbett Museum", "River rafting"] },
    ],
    totalCost: { sedan: 8580, suv: 10920 },
    highlights: [
      "3 iconic Uttarakhand destinations in one trip",
      "Mountain lakes, waterfalls & wildlife in a single circuit",
      "Scenic Kumaon Hills drive through oak forests",
      "Tiger spotting at Jim Corbett National Park",
      "Comfortable hill stations at 6,000-7,000 ft altitude",
    ],
    bestSeason: "March to June and September to November. Monsoon (July-Aug) has landslide risk.",
    faqs: [
      { question: "How many days for Mussoorie, Nainital & Jim Corbett trip?", answer: "7 days is ideal: Mussoorie (2N), Nainital (2N), Jim Corbett (1N), plus travel days. You can shorten to 5 days by reducing one night each at hill stations." },
      { question: "What is the cost of Uttarakhand hill station circuit by car?", answer: "The 780 km circuit costs from ₹8,580 (Sedan) to ₹10,920 (SUV). This covers driver, fuel, and AC. Toll, parking, safari permits, and driver allowance are extra." },
      { question: "Is Jim Corbett National Park open year-round?", answer: "Corbett's Jhirna zone is open year-round. Bijrani and Dhikala zones close during monsoon (June 15 to November 15). Book safari permits in advance during peak season." },
      { question: "Which car is best for Uttarakhand hill stations?", answer: "SUV (Innova/Ertiga) is recommended for Uttarakhand's mountain roads. Sedans are fine for Mussoorie but SUVs offer better ground clearance and comfort on winding hill roads." },
      { question: "Can we include Rishikesh in this circuit?", answer: "Yes! Add Rishikesh as a stop between Delhi and Mussoorie. It adds about 50 km and 1 night. Perfect for adventure lovers — river rafting, bungee jumping, and yoga." },
      { question: "What are road conditions in Uttarakhand?", answer: "Delhi-Mussoorie is excellent (NH-58). Mussoorie-Nainital route goes through scenic but narrow mountain roads. Nainital-Corbett is well-maintained. Our experienced hill drivers ensure safe travel." },
    ],
  },
  "varanasi-ayodhya-prayagraj-circuit": {
    slug: "varanasi-ayodhya-prayagraj-circuit",
    name: "Varanasi – Ayodhya – Prayagraj Circuit",
    tagline: "India's Holiest Triangle — Ghats, Temples & Sacred Rivers",
    totalDistance: 650,
    totalDays: 6,
    stops: [
      { city: "Varanasi", nights: 2, highlights: ["Ganga Aarti at Dashashwamedh Ghat", "Kashi Vishwanath Temple", "Sunrise boat ride", "Sarnath Buddhist site"] },
      { city: "Ayodhya", nights: 2, highlights: ["Ram Mandir", "Hanuman Garhi", "Saryu Ghat", "Nageshwarnath Temple"] },
      { city: "Prayagraj", nights: 1, highlights: ["Triveni Sangam", "Anand Bhawan", "Allahabad Fort", "Khusro Bagh"] },
    ],
    totalCost: { sedan: 7150, suv: 9100 },
    highlights: [
      "Visit 3 holiest cities of Hinduism in one trip",
      "Newly built Ram Mandir in Ayodhya",
      "Witness Ganga Aarti in Varanasi — world-famous ritual",
      "Sacred confluence of 3 rivers at Triveni Sangam",
      "Excellent UP Expressway connectivity",
    ],
    bestSeason: "October to March — Avoid summer heat (April-June). Dev Deepawali (November) is magical.",
    faqs: [
      { question: "How many days for Varanasi-Ayodhya-Prayagraj trip?", answer: "6 days is perfect: Varanasi (2N), Ayodhya (2N), Prayagraj (1N). You can cover it in 4 days if you reduce stays, but you'll miss evening aartis and sunrise experiences." },
      { question: "What is the cost of this spiritual circuit by car?", answer: "The 650 km circuit costs from ₹7,150 (Sedan) to ₹9,100 (SUV). Driver charges, toll, and parking are additional. This is one of the most affordable circuits in India." },
      { question: "Is there a direct highway between Varanasi and Ayodhya?", answer: "Yes, the Purvanchal Expressway connects the two cities. The 200 km drive takes about 3-4 hours. The new expressway has excellent road conditions and rest areas." },
      { question: "Can I visit Ram Mandir without long queues?", answer: "Weekday mornings (6-8 AM) have shortest queues. Our local drivers know the best timing and parking spots. VIP darshan is also available on some days." },
      { question: "What should I pack for this spiritual trip?", answer: "Modest clothing for temple visits, comfortable walking shoes for ghats, a light shawl/dupatta, and sun protection. Many temples have dress codes — our drivers will brief you." },
      { question: "Is this circuit suitable for elderly travelers?", answer: "Yes, with SUV comfort and door-to-door service. Our drivers assist at ghats and temples. We can arrange wheelchair-friendly boats in Varanasi and priority darshan where available." },
    ],
  },
  "amritsar-dharamshala-dalhousie-circuit": {
    slug: "amritsar-dharamshala-dalhousie-circuit",
    name: "Amritsar – Dharamshala – Dalhousie Circuit",
    tagline: "Golden Temple to Himalayan Monasteries — Punjab & Himachal's Best",
    totalDistance: 820,
    totalDays: 7,
    stops: [
      { city: "Amritsar", nights: 2, highlights: ["Golden Temple", "Wagah Border ceremony", "Jallianwala Bagh", "Amritsari kulcha food trail"] },
      { city: "Dharamshala", nights: 2, highlights: ["Dalai Lama Temple Complex", "Bhagsu Waterfall", "Triund trek", "Tibetan market"] },
      { city: "Dalhousie", nights: 2, highlights: ["Khajjiar (Mini Switzerland)", "Panchpula waterfall", "Kalatop Wildlife Sanctuary", "Chamera Lake"] },
    ],
    totalCost: { sedan: 9020, suv: 11480 },
    highlights: [
      "Golden Temple — the most visited religious site in the world",
      "Wagah Border flag-lowering ceremony (goosebumps guaranteed)",
      "Dalai Lama's residence & Tibetan Buddhist culture in Dharamshala",
      "Khajjiar — India's Mini Switzerland at 6,500 ft",
      "Mix of spiritual, cultural & hill station experiences",
    ],
    bestSeason: "March to June and September to November. Monsoon roads can be tricky in Himachal.",
    faqs: [
      { question: "How many days for Amritsar-Dharamshala-Dalhousie?", answer: "7 days is ideal: Amritsar (2N), Dharamshala (2N), Dalhousie (2N). The drive between cities is scenic and takes 4-5 hours each, so you don't lose full days to travel." },
      { question: "What is the cost of this Punjab-Himachal circuit?", answer: "The 820 km circuit costs from ₹9,020 (Sedan) to ₹11,480 (SUV). This covers driver, fuel, and AC. Toll, parking, driver allowance are additional." },
      { question: "What's the best time to visit Wagah Border?", answer: "The flag-lowering ceremony happens daily at sunset (5:30 PM in winter, 6:00 PM in summer). Arrive 2 hours early for good seats. Our driver will drop you and pick up after the ceremony." },
      { question: "Is the road from Dharamshala to Dalhousie safe?", answer: "Yes, the 120 km route via Nurpur is well-maintained. It's a scenic drive through pine forests taking about 4 hours. Our experienced hill drivers know every curve of this road." },
      { question: "Can we add Khajjiar as a day trip from Dalhousie?", answer: "Khajjiar is only 24 km from Dalhousie (1 hour drive). It's included as a highlight in the Dalhousie stay. You can also combine it with Chamba visit for a full day excursion." },
      { question: "Is this circuit suitable for a honeymoon trip?", answer: "Absolutely! The mix of the spiritual Golden Temple, romantic McLeodganj cafes, and scenic Dalhousie makes it perfect for couples. We can arrange special hotel packages too." },
    ],
  },
  "rajasthan-heritage-jaipur-jodhpur-udaipur-jaisalmer": {
    slug: "rajasthan-heritage-jaipur-jodhpur-udaipur-jaisalmer",
    name: "Rajasthan Heritage Circuit",
    tagline: "Jaipur → Jodhpur → Jaisalmer → Udaipur — Royal Forts, Desert Dunes & Lake Palaces",
    totalDistance: 1180,
    totalDays: 10,
    stops: [
      { city: "Jaipur", nights: 2, highlights: ["Amber Fort", "Hawa Mahal", "City Palace", "Nahargarh Fort sunset", "Johari Bazaar"] },
      { city: "Jodhpur", nights: 2, highlights: ["Mehrangarh Fort", "Blue City walk", "Umaid Bhawan Palace", "Clock Tower market", "Zip-lining at Mehrangarh"] },
      { city: "Jaisalmer", nights: 2, highlights: ["Jaisalmer Fort (living fort)", "Sam Sand Dunes safari", "Desert camping under stars", "Patwon Ki Haveli"] },
      { city: "Udaipur", nights: 2, highlights: ["Lake Pichola boat ride", "City Palace", "Jagdish Temple", "Fateh Sagar Lake", "Ambrai Ghat sunset"] },
    ],
    totalCost: { sedan: 12980, suv: 16520 },
    highlights: [
      "4 royal cities of Rajasthan — Pink, Blue, Golden & White City",
      "UNESCO forts, desert safaris & lake palaces in one trip",
      "Sleep under the stars in Thar Desert at Sam Dunes",
      "Best-maintained state highways in Rajasthan",
      "Rich Rajasthani cuisine: dal baati churma, laal maas, ker sangri",
    ],
    bestSeason: "October to March — Perfect desert weather. Avoid April-June extreme heat.",
    faqs: [
      { question: "How many days for the complete Rajasthan circuit?", answer: "10 days covers all 4 cities comfortably: Jaipur (2N), Jodhpur (2N), Jaisalmer (2N), Udaipur (2N), plus travel days. You can do a shorter 7-day version by reducing nights." },
      { question: "What is the cost of Rajasthan heritage circuit by car?", answer: "The 1,180 km circuit costs from ₹12,980 (Sedan) to ₹16,520 (SUV). Toll, parking, desert safari, and driver allowance are additional." },
      { question: "Which car is best for Rajasthan road trip?", answer: "SUV (Innova Crysta) is highly recommended. The Jodhpur-Jaisalmer stretch has long desert highways and SUV offers better comfort. For couples, Sedan works fine." },
      { question: "Is the desert safari in Jaisalmer worth it?", answer: "Absolutely! The Sam Sand Dunes sunset camel safari followed by overnight desert camping with folk music and dinner under the stars is a once-in-a-lifetime experience. Book through us for best rates." },
      { question: "Can we add Pushkar or Ranthambore to this circuit?", answer: "Yes! Pushkar adds 1 night (near Jaipur-Jodhpur route). Ranthambore adds 1-2 nights (between Jaipur-Jodhpur). Both are worth the detour. Call 7668570551 to customize." },
      { question: "What is the best direction for this circuit?", answer: "We recommend Jaipur → Jodhpur → Jaisalmer → Udaipur as it flows geographically west then south. Return to Delhi from Udaipur via flight (1.5 hrs) or drive (660 km, 10 hrs)." },
    ],
  },
  "weekend-road-trips-from-delhi": {
    slug: "weekend-road-trips-from-delhi",
    name: "Weekend Road Trips from Delhi",
    tagline: "Top 10 Getaways Within 300 km — Perfect for a 2-Day Escape",
    totalDistance: 300,
    totalDays: 2,
    stops: [
      { city: "Neemrana", nights: 0, highlights: ["Neemrana Fort Palace", "Zip-lining across the fort", "Heritage walk"] },
      { city: "Mathura-Vrindavan", nights: 1, highlights: ["Krishna Janmabhoomi", "Banke Bihari Temple", "Prem Mandir light show"] },
      { city: "Agra", nights: 1, highlights: ["Taj Mahal sunrise", "Agra Fort", "Mehtab Bagh sunset"] },
      { city: "Rishikesh", nights: 1, highlights: ["River rafting", "Laxman Jhula", "Triveni Ghat aarti"] },
      { city: "Jim Corbett", nights: 1, highlights: ["Jungle safari", "Bijrani zone", "Garjia Temple"] },
      { city: "Mussoorie", nights: 1, highlights: ["Kempty Falls", "Gun Hill ropeway", "Mall Road"] },
      { city: "Nainital", nights: 1, highlights: ["Naini Lake boating", "Snow View", "Mall Road shopping"] },
      { city: "Alwar-Sariska", nights: 1, highlights: ["Sariska Tiger Reserve", "Bhangarh Fort", "Siliserh Lake"] },
    ],
    totalCost: { sedan: 3300, suv: 4200 },
    highlights: [
      "All destinations within 300 km / 5 hours from Delhi",
      "Perfect Friday-to-Sunday getaways",
      "Mix of heritage, adventure, wildlife & spiritual options",
      "One-way cab from ₹3,300 (Sedan) for any destination",
      "Pick-up from your doorstep in Delhi/NCR",
    ],
    bestSeason: "Year-round — each destination has its own best season. Hill stations peak in summer, wildlife parks in winter.",
    faqs: [
      { question: "What are the best weekend getaways from Delhi by car?", answer: "Top picks: Agra (230 km, 3 hrs), Mathura (180 km, 3 hrs), Rishikesh (240 km, 5.5 hrs), Mussoorie (290 km, 6 hrs), Jim Corbett (260 km, 5.5 hrs), Neemrana (120 km, 2 hrs), and Alwar (160 km, 3 hrs)." },
      { question: "How much does a weekend road trip from Delhi cost?", answer: "With Triveni Cabs, a weekend trip starts from ₹3,300 (Sedan) for destinations within 300 km. This covers one-way travel. Round trip with 2 days use starts from ₹5,500." },
      { question: "Can I book a cab for a 2-day weekend trip?", answer: "Yes! We offer multi-day packages with driver stay included. The driver stays with you throughout the trip. Per-day rates: Sedan ₹2,500, SUV ₹3,500 (including 250 km/day)." },
      { question: "Which weekend trip is best for couples from Delhi?", answer: "Mussoorie (Queen of Hills, romantic walks), Rishikesh (adventure + spa), Neemrana Fort (heritage luxury), and Agra (Taj Mahal magic). Each offers unique couple experiences." },
      { question: "Which weekend trip is best for families with kids?", answer: "Jim Corbett (jungle safari, kids love it), Nainital (boating, horse riding, zoo), and Mathura-Vrindavan (cultural, colorful temples). All are well-suited for family enjoyment." },
      { question: "Can I get early morning pickup from Delhi for a weekend trip?", answer: "Absolutely! We offer 24/7 pickup. For weekend trips, 5-6 AM departure is recommended to beat Delhi traffic and maximize your time at the destination. Book the night before." },
    ],
  },
  "weekend-road-trips-from-jaipur": {
    slug: "weekend-road-trips-from-jaipur",
    name: "Weekend Road Trips from Jaipur",
    tagline: "Top Getaways Within 400 km — Forts, Wildlife & Desert Adventures",
    totalDistance: 400,
    totalDays: 2,
    stops: [
      { city: "Pushkar", nights: 1, highlights: ["Pushkar Lake", "Brahma Temple", "Desert camping", "Camel fair grounds"] },
      { city: "Ranthambore", nights: 1, highlights: ["Tiger safari", "Ranthambore Fort", "Wildlife photography"] },
      { city: "Udaipur", nights: 1, highlights: ["Lake Pichola", "City Palace", "Fateh Sagar Lake"] },
      { city: "Mount Abu", nights: 1, highlights: ["Dilwara Temples", "Nakki Lake", "Sunset Point"] },
      { city: "Ajmer", nights: 0, highlights: ["Ajmer Sharif Dargah", "Ana Sagar Lake", "Adhai Din Ka Jhonpra"] },
      { city: "Bundi", nights: 1, highlights: ["Taragarh Fort", "Step wells", "Bundi Palace murals"] },
      { city: "Chittorgarh", nights: 1, highlights: ["Chittorgarh Fort", "Vijay Stambh", "Padmini Palace"] },
      { city: "Bikaner", nights: 1, highlights: ["Junagarh Fort", "Karni Mata Temple", "Camel research farm"] },
    ],
    totalCost: { sedan: 4400, suv: 5600 },
    highlights: [
      "Rajasthan's best-kept secrets within driving distance",
      "Tiger spotting at Ranthambore (3 hrs from Jaipur)",
      "Holy Pushkar — only Brahma Temple in the world",
      "UNESCO fort at Chittorgarh — Rajput valor & sacrifice",
      "Weekend rates from ₹4,400 (Sedan) including fuel & driver",
    ],
    bestSeason: "October to March — Ideal Rajasthan weather. Pushkar Camel Fair in November is unmissable.",
    faqs: [
      { question: "What are the best weekend trips from Jaipur by car?", answer: "Top picks: Pushkar (145 km, 3 hrs), Ranthambore (180 km, 3.5 hrs), Ajmer (135 km, 2.5 hrs), Udaipur (395 km, 6 hrs), Bundi (215 km, 4 hrs), and Chittorgarh (310 km, 5 hrs)." },
      { question: "How much does a weekend trip from Jaipur cost?", answer: "With Triveni Cabs, weekend trips from Jaipur start at ₹4,400 (Sedan) for destinations within 400 km. Round trip with 2-day use starts from ₹6,000." },
      { question: "Can I do Ranthambore as a day trip from Jaipur?", answer: "Technically yes (3 hrs each way), but we recommend 1 night stay. Morning safaris start at 6 AM and evening safaris at 2 PM — staying overnight lets you do both." },
      { question: "Is Udaipur feasible for a weekend from Jaipur?", answer: "Yes, if you leave early Friday. The 6-hour drive via NH-48 is scenic. Spend Saturday exploring the City of Lakes and return Sunday. An SUV makes the long drive comfortable." },
      { question: "Which is the closest weekend getaway from Jaipur?", answer: "Ajmer-Pushkar at 135-145 km (2.5-3 hrs) is the closest meaningful weekend destination. You can cover both in a single weekend — Ajmer for Dargah and Pushkar for the lake temple." },
      { question: "Are night drives safe from Jaipur?", answer: "Main highways (NH-48 to Udaipur, NH-52 to Ranthambore) are well-lit and safe. However, we recommend starting by 6 AM instead. Our drivers are experienced in all conditions and vehicles have GPS tracking." },
    ],
  },
  "weekend-road-trips-from-chandigarh": {
    slug: "weekend-road-trips-from-chandigarh",
    name: "Weekend Road Trips from Chandigarh",
    tagline: "Himalayan Escapes Within 300 km — Hills, Valleys & Adventure",
    totalDistance: 300,
    totalDays: 2,
    stops: [
      { city: "Kasauli", nights: 1, highlights: ["Monkey Point", "Gilbert Trail", "Christ Church", "Sunset Point"] },
      { city: "Shimla", nights: 1, highlights: ["Mall Road", "Jakhoo Temple", "Ridge", "Kufri"] },
      { city: "Manali", nights: 1, highlights: ["Solang Valley", "Old Manali", "Hadimba Temple", "Rohtang Pass"] },
      { city: "Dharamshala", nights: 1, highlights: ["Dalai Lama Temple", "Bhagsu Waterfall", "Triund trek"] },
      { city: "Chail", nights: 1, highlights: ["Chail Palace", "World's highest cricket ground", "Sidh Baba Temple"] },
      { city: "Nalagarh", nights: 1, highlights: ["Nalagarh Fort heritage stay", "Gobind Sagar Lake", "Nature walks"] },
      { city: "Parwanoo", nights: 0, highlights: ["Timber Trail cable car", "Cactus Garden", "Fruit orchards"] },
      { city: "Morni Hills", nights: 1, highlights: ["Morni Fort", "Tikkar Taal Lake", "Bird watching", "Camping"] },
    ],
    totalCost: { sedan: 3300, suv: 4200 },
    highlights: [
      "6+ hill stations within 3-5 hours from Chandigarh",
      "Escape to the Himalayas every weekend",
      "Adventure: trekking, paragliding, river rafting options",
      "Scenic mountain drives through pine and deodar forests",
      "Cab from ₹3,300 for any destination within 300 km",
    ],
    bestSeason: "Year-round — Summer for pleasant hills, Winter for snow, Monsoon for lush greenery (check road conditions).",
    faqs: [
      { question: "What are the best weekend trips from Chandigarh?", answer: "Top picks: Kasauli (60 km, 1.5 hrs), Shimla (115 km, 3 hrs), Chail (100 km, 3 hrs), Parwanoo (35 km, 1 hr), Dharamshala (240 km, 5 hrs), and Morni Hills (45 km, 1.5 hrs)." },
      { question: "How much does a weekend hill trip from Chandigarh cost?", answer: "Weekend trips start from ₹3,300 (Sedan) for destinations within 300 km. Round trip with 2-day hire starts from ₹5,000 with 250 km/day allowance." },
      { question: "Is Shimla or Kasauli better for a quick weekend?", answer: "Kasauli (1.5 hrs from Chandigarh) is better for a relaxed, quiet weekend. Shimla (3 hrs) offers more activities and shopping but is more crowded. Both are excellent choices." },
      { question: "Can I reach Manali from Chandigarh in a weekend?", answer: "It's a 6-hour drive (310 km). Leave Friday evening and you'll have all of Saturday in Manali. Return Sunday. For maximum time, take a 3-day weekend." },
      { question: "Which is the closest hill station from Chandigarh?", answer: "Parwanoo is just 35 km (1 hour). Morni Hills is 45 km (1.5 hours). Kasauli is 60 km (1.5 hours). All three make perfect day trips or overnight getaways." },
      { question: "Are mountain roads safe during monsoon?", answer: "Most hill stations near Chandigarh have well-maintained roads. During heavy monsoon, avoid Manali route due to landslide risk. Kasauli and Shimla roads are relatively safer. Our drivers monitor conditions in real-time." },
    ],
  },
};

export function getRoadTrip(slug) {
  return roadTrips[slug] || null;
}

export function getAllRoadTripSlugs() {
  return Object.keys(roadTrips);
}

export function getRelatedRoadTrips(slug, limit = 3) {
  const all = Object.values(roadTrips);
  return all.filter(t => t.slug !== slug).slice(0, limit);
}
