// City metadata for tempo traveller service
export const tempoCities = {
  Delhi: {
    slug: 'delhi',
    name: 'Delhi',
    tagline: 'Gateway to North India',
    description: 'Start your journey from India\'s capital. Connect to hill stations, spiritual destinations, and royal cities.',
    icon: '🏛️',
    landmark: 'India Gate',
    region: 'North India',
    state: 'Delhi NCR',
    image: '/images/sightseeing/Delhi/Delhi_hero_section.jpg',
    color: 'from-blue-500 via-indigo-500 to-purple-600',
    bgGradient: 'from-blue-900/90 via-indigo-900/80 to-purple-900/90',
    accentColor: 'blue',
    popularDestinations: ['Manali', 'Shimla', 'Jaipur'],
    highlights: ['Most Connected', '10+ Routes', 'Hill Stations & Heritage']
  },
  Chandigarh: {
    slug: 'chandigarh',
    name: 'Chandigarh',
    tagline: 'The City Beautiful',
    description: 'Explore from India\'s best planned city. Perfect gateway to Himachal Pradesh and Punjab.',
    icon: '🌳',
    landmark: 'Rock Garden',
    region: 'North India',
    state: 'Punjab/Haryana',
    image: '/images/sightseeing/Chandigarh/Chandigarh_hero_section.jpg',
    color: 'from-emerald-500 via-teal-500 to-cyan-600',
    bgGradient: 'from-emerald-900/90 via-teal-900/80 to-cyan-900/90',
    accentColor: 'emerald',
    popularDestinations: ['Shimla', 'Manali', 'Dharamshala'],
    highlights: ['Hill Station Gateway', '7 Routes', 'Scenic Drives']
  },
  Jaipur: {
    slug: 'jaipur',
    name: 'Jaipur',
    tagline: 'The Pink City',
    description: 'Royal Rajasthan awaits! Explore desert cities, lake palaces, and heritage forts from Jaipur.',
    icon: '🏰',
    landmark: 'Hawa Mahal',
    region: 'Rajasthan',
    state: 'Rajasthan',
    image: '/images/sightseeing/Jaipur/jaipur_hero_section_image.jpg',
    color: 'from-rose-500 via-pink-500 to-orange-500',
    bgGradient: 'from-rose-900/90 via-pink-900/80 to-orange-900/90',
    accentColor: 'rose',
    popularDestinations: ['Udaipur', 'Jodhpur', 'Jaisalmer'],
    highlights: ['Royal Circuit', '7 Routes', 'Desert & Lakes']
  },
  Agra: {
    slug: 'agra',
    name: 'Agra',
    tagline: 'City of Taj Mahal',
    description: 'Home of the iconic Taj Mahal. Connect to Delhi, Jaipur, and spiritual destinations.',
    icon: '🕌',
    landmark: 'Taj Mahal',
    region: 'Uttar Pradesh',
    state: 'Uttar Pradesh',
    image: '/images/sightseeing/Agra/Agra_Hero_section.jpg',
    color: 'from-amber-500 via-yellow-500 to-orange-500',
    bgGradient: 'from-amber-900/90 via-yellow-900/80 to-orange-900/90',
    accentColor: 'amber',
    popularDestinations: ['Delhi', 'Jaipur', 'Mathura'],
    highlights: ['Heritage Hub', '5 Routes', 'Golden Triangle']
  },
  Haridwar: {
    slug: 'haridwar',
    name: 'Haridwar',
    tagline: 'Gateway to Gods',
    description: 'Sacred city on the Ganges. Your gateway to Char Dham pilgrimage and spiritual Uttarakhand.',
    icon: '🙏',
    landmark: 'Har Ki Pauri',
    region: 'Uttarakhand',
    state: 'Uttarakhand',
    image: '/images/chardham/chardham-haridwar-hero.webp',
    color: 'from-orange-500 via-amber-500 to-yellow-500',
    bgGradient: 'from-orange-900/90 via-amber-900/80 to-yellow-900/90',
    accentColor: 'orange',
    popularDestinations: ['Badrinath', 'Kedarnath', 'Rishikesh'],
    highlights: ['Char Dham Base', '5 Routes', 'Spiritual Journey']
  },
  Rishikesh: {
    slug: 'rishikesh',
    name: 'Rishikesh',
    tagline: 'Yoga Capital of World',
    description: 'Adventure meets spirituality. Base camp for Char Dham and thrilling Himalayan adventures.',
    icon: '🧘',
    landmark: 'Laxman Jhula',
    region: 'Uttarakhand',
    state: 'Uttarakhand',
    image: '/images/chardham/chardham-rishikesh-hero.webp',
    color: 'from-teal-500 via-cyan-500 to-blue-500',
    bgGradient: 'from-teal-900/90 via-cyan-900/80 to-blue-900/90',
    accentColor: 'teal',
    popularDestinations: ['Auli', 'Chopta', 'Badrinath'],
    highlights: ['Adventure Hub', '5 Routes', 'Yoga & Rafting']
  },
  Dehradun: {
    slug: 'dehradun',
    name: 'Dehradun',
    tagline: 'Doon Valley Gateway',
    description: 'Capital of Uttarakhand. Perfect starting point for Mussoorie and Char Dham Yatra.',
    icon: '🌲',
    landmark: 'Robber\'s Cave',
    region: 'Uttarakhand',
    state: 'Uttarakhand',
    image: '/images/chardham/chardham-dehradun-hero.webp',
    color: 'from-green-500 via-emerald-500 to-teal-500',
    bgGradient: 'from-green-900/90 via-emerald-900/80 to-teal-900/90',
    accentColor: 'green',
    popularDestinations: ['Mussoorie', 'Badrinath', 'Kedarnath'],
    highlights: ['Valley Views', '5 Routes', 'Hill Stations']
  },
  Amritsar: {
    slug: 'amritsar',
    name: 'Amritsar',
    tagline: 'Holy City of Sikhs',
    description: 'Home of the Golden Temple. Connect to Vaishno Devi and explore Punjab\'s rich culture.',
    icon: '🛕',
    landmark: 'Golden Temple',
    region: 'Punjab',
    state: 'Punjab',
    image: '/images/sightseeing/Ajmer_Pushkar/Ajmer_shariff_hero_section.jpg',
    color: 'from-yellow-500 via-amber-500 to-orange-500',
    bgGradient: 'from-yellow-900/90 via-amber-900/80 to-orange-900/90',
    accentColor: 'yellow',
    popularDestinations: ['Vaishno Devi Katra', 'Delhi', 'Chandigarh'],
    highlights: ['Spiritual Center', '3 Routes', 'Wagah Border']
  },
  Lucknow: {
    slug: 'lucknow',
    name: 'Lucknow',
    tagline: 'City of Nawabs',
    description: 'Experience Awadhi culture and connect to spiritual destinations of Eastern UP.',
    icon: '🏯',
    landmark: 'Bara Imambara',
    region: 'Uttar Pradesh',
    state: 'Uttar Pradesh',
    image: '/images/sightseeing/Chittorgarh/chittogarh_hero_section.jpg',
    color: 'from-violet-500 via-purple-500 to-fuchsia-500',
    bgGradient: 'from-violet-900/90 via-purple-900/80 to-fuchsia-900/90',
    accentColor: 'violet',
    popularDestinations: ['Varanasi', 'Ayodhya', 'Delhi'],
    highlights: ['Nawabi Heritage', '4 Routes', 'Cultural Hub']
  },
  Varanasi: {
    slug: 'varanasi',
    name: 'Varanasi',
    tagline: 'Oldest Living City',
    description: 'Spiritual capital of India. Gateway to Buddhist circuit and Eastern UP pilgrimage.',
    icon: '🔥',
    landmark: 'Dashashwamedh Ghat',
    region: 'Uttar Pradesh',
    state: 'Uttar Pradesh',
    image: '/images/sightseeing/Varanasi/varanasi_hero_section.jpg',
    color: 'from-orange-600 via-red-500 to-rose-500',
    bgGradient: 'from-orange-900/90 via-red-900/80 to-rose-900/90',
    accentColor: 'orange',
    popularDestinations: ['Prayagraj', 'Ayodhya', 'Lucknow'],
    highlights: ['Ganga Aarti', '3 Routes', 'Ancient City']
  },
  Udaipur: {
    slug: 'udaipur',
    name: 'Udaipur',
    tagline: 'City of Lakes',
    description: 'Venice of the East. Explore royal palaces and connect to Rajasthan\'s finest destinations.',
    icon: '🏞️',
    landmark: 'Lake Pichola',
    region: 'Rajasthan',
    state: 'Rajasthan',
    image: '/images/sightseeing/Mount_Abu/Nakki_Lake.jpg',
    color: 'from-cyan-500 via-blue-500 to-indigo-500',
    bgGradient: 'from-cyan-900/90 via-blue-900/80 to-indigo-900/90',
    accentColor: 'cyan',
    popularDestinations: ['Mount Abu', 'Jodhpur', 'Jaipur'],
    highlights: ['Lake City', '4 Routes', 'Royal Palaces']
  },
  Jodhpur: {
    slug: 'jodhpur',
    name: 'Jodhpur',
    tagline: 'The Blue City',
    description: 'Gateway to Thar Desert. Majestic forts and connect to Jaisalmer\'s golden sands.',
    icon: '🏜️',
    landmark: 'Mehrangarh Fort',
    region: 'Rajasthan',
    state: 'Rajasthan',
    image: '/images/sightseeing/Bikaner/Bikaner_hero_section.jpg',
    color: 'from-blue-600 via-indigo-600 to-violet-600',
    bgGradient: 'from-blue-900/90 via-indigo-900/80 to-violet-900/90',
    accentColor: 'blue',
    popularDestinations: ['Jaisalmer', 'Udaipur', 'Jaipur'],
    highlights: ['Desert Gateway', '3 Routes', 'Blue Houses']
  },
  Ajmer: {
    slug: 'ajmer',
    name: 'Ajmer',
    tagline: 'Sufi Heritage City',
    description: 'Home of Ajmer Sharif Dargah. Spiritual hub connecting to Pushkar and royal cities.',
    icon: '🕋',
    landmark: 'Ajmer Sharif',
    region: 'Rajasthan',
    state: 'Rajasthan',
    image: '/images/sightseeing/Ajmer_Pushkar/Ajmer_shariff_hero_section.jpg',
    color: 'from-emerald-600 via-green-600 to-teal-600',
    bgGradient: 'from-emerald-900/90 via-green-900/80 to-teal-900/90',
    accentColor: 'emerald',
    popularDestinations: ['Pushkar', 'Jaipur', 'Udaipur'],
    highlights: ['Sufi Shrine', '3 Routes', 'Pilgrimage']
  },
  Pushkar: {
    slug: 'pushkar',
    name: 'Pushkar',
    tagline: 'Sacred Lake Town',
    description: 'Only Brahma temple in India. Serene lake town perfect for spiritual retreats.',
    icon: '🙏',
    landmark: 'Pushkar Lake',
    region: 'Rajasthan',
    state: 'Rajasthan',
    image: '/images/sightseeing/Ajmer_Pushkar/Pushkar_Lake_Ghats.jpg',
    color: 'from-purple-500 via-fuchsia-500 to-pink-500',
    bgGradient: 'from-purple-900/90 via-fuchsia-900/80 to-pink-900/90',
    accentColor: 'purple',
    popularDestinations: ['Ajmer', 'Udaipur', 'Jaipur'],
    highlights: ['Brahma Temple', '3 Routes', 'Camel Fair']
  },
  Shimla: {
    slug: 'shimla',
    name: 'Shimla',
    tagline: 'Queen of Hills',
    description: 'The summer capital of British India. Gateway to Kinnaur and Spiti valleys.',
    icon: '🏔️',
    landmark: 'The Ridge',
    region: 'Himachal Pradesh',
    state: 'Himachal Pradesh',
    image: '/images/sightseeing/Shimla/shimla_hero_section.jpg',
    color: 'from-sky-500 via-cyan-500 to-blue-500',
    bgGradient: 'from-sky-900/90 via-cyan-900/80 to-blue-900/90',
    accentColor: 'sky',
    popularDestinations: ['Manali', 'Chandigarh', 'Delhi'],
    highlights: ['Hill Capital', '5 Routes', 'Colonial Charm']
  },
  Manali: {
    slug: 'manali',
    name: 'Manali',
    tagline: 'Valley of Gods',
    description: 'Adventure capital of Himachal. Gateway to Leh-Ladakh and Lahaul Valley.',
    icon: '🏂',
    landmark: 'Rohtang Pass',
    region: 'Himachal Pradesh',
    state: 'Himachal Pradesh',
    image: '/images/sightseeing/Manali/Manali_hero_section.jpg',
    color: 'from-teal-500 via-emerald-500 to-green-500',
    bgGradient: 'from-teal-900/90 via-emerald-900/80 to-green-900/90',
    accentColor: 'teal',
    popularDestinations: ['Leh', 'Shimla', 'Kasol'],
    highlights: ['Snow Points', '5 Routes', 'Adventure Hub']
  },
  Ahmedabad: {
    slug: 'ahmedabad',
    name: 'Ahmedabad',
    tagline: 'India\'s First World Heritage City',
    description: 'The commercial heart of Gujarat. Gateway to Statue of Unity and Gir National Park.',
    icon: '🕌',
    landmark: 'Sabarmati Ashram',
    region: 'Gujarat',
    state: 'Gujarat',
    image: '/images/sightseeing/Ahmedabad/Ahmedabad_hero_section.jpg',
    color: 'from-orange-500 via-amber-500 to-yellow-500',
    bgGradient: 'from-orange-900/90 via-amber-900/80 to-yellow-900/90',
    accentColor: 'orange',
    popularDestinations: ['Udaipur', 'Statue of Unity', 'Dwarka'],
    highlights: ['Heritage City', '5 Routes', 'Business Hub']
  }
};

export const tempoFleet = [
  {
    id: 1,
    name: "12 Seater Tempo Traveller",
    capacity: "11-12 Passengers",
    outstationRate: "₹23/km",
    localRate: "₹6,000-7,500/Day",
    features: ["Comfortable Pushback Seats", "AC", "Music System", "Charging Points"],
    image: "/images/tempo/12_seater.jpg",
    color: "from-blue-500 to-blue-600"
  },
  {
    id: 2,
    name: "16 Seater Tempo Traveller",
    capacity: "15-16 Passengers",
    outstationRate: "₹25/km",
    localRate: "₹7,500-8,500/Day",
    features: ["Spacious Seating", "Air-conditioned", "Ample Luggage Space", "GPS Tracking"],
    image: "/images/tempo/16_seater.jpg",
    color: "from-green-500 to-green-600"
  },
  {
    id: 3,
    name: "17 Seater Tempo Traveller",
    capacity: "14-17 Passengers",
    outstationRate: "₹26/km",
    localRate: "₹9,000-10,500/Day",
    features: ["Luxury Pushback Seats", "Music System", "Charging Points", "Premium Interiors"],
    image: "/images/tempo/17_seater.jpg",
    color: "from-purple-500 to-purple-600",
    popular: true
  },
  {
    id: 4,
    name: "20 Seater Luxury Tempo Traveller",
    capacity: "18-20 Passengers",
    outstationRate: "₹27/km",
    localRate: "₹9,000-10,000/Day",
    features: ["LED TV", "Music System", "AC", "Ample Luggage Space"],
    image: "/images/tempo/20_seater.jpg",
    color: "from-orange-500 to-orange-600"
  },
  {
    id: 5,
    name: "26 Seater Maharaja Edition",
    capacity: "22-26 Passengers",
    outstationRate: "₹26/km",
    localRate: "₹10,000-11,000/Day",
    features: ["Super Luxury Interiors", "Recliner Seats", "Premium Comfort", "Entertainment System"],
    image: "/images/tempo/26_seater.jpg",
    color: "from-yellow-500 to-yellow-600",
    premium: true
  }
];

export const tempoRoutes = {
  Delhi: [
    { name: "Shimla", type: "Hill Station" },
    { name: "Manali", type: "Adventure" },
    { name: "Dharamshala", type: "Spiritual" },
    { name: "Amritsar", type: "Heritage" },
    { name: "Haridwar", type: "Spiritual" },
    { name: "Rishikesh", type: "Spiritual" },
    { name: "Jaipur", type: "Royal" },
    { name: "Agra", type: "Heritage" },
    { name: "Mathura", type: "Spiritual" },
    { name: "Vrindavan", type: "Spiritual" },
    { name: "Shimla Manali Kullu Kasol", type: "Circuit" },
    { name: "Haridwar Rishikesh Dehradun Mussoorie", type: "Circuit" },
    { name: "Agra Mathura Vrindavan", type: "Circuit" },
    { name: "Jaipur Jodhpur Jaisalmer", type: "Circuit" },
    { name: "Nainital Bhimtal Jim Corbett", type: "Wildlife" },
    { name: "Amritsar Golden Temple Wagah Border", type: "Heritage" },
    { name: "Udaipur Mount Abu Chittorgarh", type: "Royal" },
    { name: "Varanasi Ayodhya Prayagraj Gaya", type: "Spiritual" },
    { name: "Lucknow Kanpur Ayodhya", type: "Heritage" },
    { name: "Chandigarh Mohali Panchkula", type: "Local" },
    { name: "Goa Corporate Trips", type: "Long Road" },
    { name: "Auli Chopta Tungnath", type: "Adventure" },
    { name: "Kasol Kheerganga Manikaran", type: "Adventure" },
    { name: "Leh Ladakh Nubra Valley", type: "Adventure" },
    { name: "Katra Vaishno Devi Jammu", type: "Spiritual" },
    { name: "Ayodhya Ram Mandir Tour", type: "Spiritual" },
    { name: "Pushkar Ajmer Sharif", type: "Spiritual" }
  ],
  Chandigarh: [
    { name: "Shimla", type: "Hill Station" },
    { name: "Manali", type: "Adventure" },
    { name: "Dharamshala", type: "Spiritual" },
    { name: "Dalhousie", type: "Hill Station" },
    { name: "Amritsar", type: "Heritage" },
    { name: "Delhi", type: "Metro" },
    { name: "Jaipur", type: "Royal" },
    { name: "Manali Kasol Kullu", type: "Hill Station" },
    { name: "Shimla Kufri Narkanda", type: "Hill Station" },
    { name: "Dharamshala Dalhousie Khajjiar", type: "Hill Station" },
    { name: "Amritsar Wagah Border", type: "Heritage" },
    { name: "Dehradun Mussoorie Rishikesh", type: "Circuit" },
    { name: "Jaipur Udaipur", type: "Royal" },
    { name: "Leh Ladakh", type: "Adventure" }
  ],
  Jaipur: [
    { name: "Delhi", type: "Metro" },
    { name: "Agra", type: "Heritage" },
    { name: "Shimla", type: "Hill Station" },
    { name: "Manali", type: "Adventure" },
    { name: "Nainital", type: "Hill Station" },
    { name: "Corbett", type: "Wildlife" },
    { name: "Ayodhya", type: "Spiritual" },
    { name: "Varanasi", type: "Spiritual" },
    { name: "Udaipur", type: "Lakes" },
    { name: "Jodhpur", type: "Blue City" },
    { name: "Jaisalmer", type: "Desert" },
    { name: "Ajmer", type: "Spiritual" },
    { name: "Pushkar", type: "Spiritual" },
    { name: "Jodhpur Jaisalmer Desert Tour", type: "Desert" },
    { name: "Udaipur Mount Abu", type: "Royal" },
    { name: "Ajmer Pushkar", type: "Spiritual" },
    { name: "Delhi Agra (Golden Triangle)", type: "Circuit" },
    { name: "Haridwar Rishikesh", type: "Spiritual" },
    { name: "Shimla Manali", type: "Hill Station" },
    { name: "Amritsar Golden Temple", type: "Heritage" }
  ],
  Agra: [
    { name: "Delhi", type: "Metro" },
    { name: "Jaipur", type: "Royal" },
    { name: "Mathura", type: "Spiritual" },
    { name: "Vrindavan", type: "Spiritual" },
    { name: "Gwalior", type: "Heritage" },
    { name: "Mount Abu", type: "Hill Station" },
    { name: "Delhi Jaipur (Golden Triangle)", type: "Circuit" },
    { name: "Mathura Vrindavan", type: "Spiritual" },
    { name: "Haridwar Rishikesh", type: "Spiritual" },
    { name: "Shimla Manali", type: "Hill Station" },
    { name: "Nainital Corbett", type: "Wildlife" },
    { name: "Ayodhya Varanasi", type: "Spiritual" },
    { name: "Udaipur Mount Abu", type: "Royal" }
  ],
  Haridwar: [
    { name: "Badrinath", type: "Char Dham" },
    { name: "Kedarnath", type: "Char Dham" },
    { name: "Yamunotri", type: "Char Dham" },
    { name: "Gangotri", type: "Char Dham" },
    { name: "Rishikesh", type: "Spiritual" },
    { name: "Kedarnath Badrinath Yamunotri Gangotri (Char Dham)", type: "Char Dham" },
    { name: "Mussoorie Dehradun", type: "Hill Station" },
    { name: "Nainital Corbett", type: "Wildlife" },
    { name: "Delhi Agra", type: "Heritage" },
    { name: "Jaipur Udaipur Mount Abu", type: "Royal" }
  ],
  Rishikesh: [
    { name: "Auli", type: "Adventure" },
    { name: "Chopta", type: "Adventure" },
    { name: "Haridwar", type: "Spiritual" },
    { name: "Badrinath", type: "Char Dham" },
    { name: "Kedarnath", type: "Char Dham" }
  ],
  Dehradun: [
    { name: "Mussoorie", type: "Hill Station" },
    { name: "Badrinath", type: "Char Dham" },
    { name: "Kedarnath", type: "Char Dham" },
    { name: "Yamunotri", type: "Char Dham" },
    { name: "Gangotri", type: "Char Dham" },
    { name: "Mussoorie", type: "Hill Station" },
    { name: "Kedarnath Badrinath", type: "Spiritual" },
    { name: "Rishikesh Haridwar", type: "Spiritual" },
    { name: "Shimla Manali", type: "Hill Station" },
    { name: "Nainital Corbett", type: "Wildlife" },
    { name: "Delhi Agra Jaipur", type: "Circuit" }
  ],
  Amritsar: [
    { name: "Vaishno Devi Katra", type: "Spiritual" },
    { name: "Delhi", type: "Metro" },
    { name: "Chandigarh", type: "Modern City" },
    { name: "Dharamshala Dalhousie Khajjiar", type: "Hill Station" },
    { name: "Shimla Manali Kasol", type: "Hill Station" },
    { name: "Chandigarh", type: "Metro" },
    { name: "Jaipur Udaipur", type: "Royal" },
    { name: "Delhi Agra", type: "Heritage" }
  ],
  Lucknow: [
    { name: "Varanasi", type: "Spiritual" },
    { name: "Ayodhya", type: "Spiritual" },
    { name: "Delhi", type: "Metro" },
    { name: "Agra", type: "Heritage" },
    { name: "Ayodhya Varanasi Prayagraj", type: "Spiritual" },
    { name: "Delhi Agra Jaipur", type: "Circuit" },
    { name: "Nainital Corbett Mussoorie", type: "Hill Station" },
    { name: "Shimla Manali", type: "Hill Station" },
    { name: "Haridwar Rishikesh", type: "Spiritual" }
  ],
  Varanasi: [
    { name: "Prayagraj", type: "Spiritual" },
    { name: "Ayodhya", type: "Spiritual" },
    { name: "Lucknow", type: "Heritage" },
    { name: "Ayodhya Prayagraj Chitrakoot", type: "Spiritual" },
    { name: "Delhi Agra Mathura", type: "Circuit" },
    { name: "Haridwar Rishikesh", type: "Spiritual" },
    { name: "Lucknow", type: "Heritage" },
    { name: "Rajasthan Tour (Jaipur Udaipur Jodhpur Jaisalmer)", type: "Royal" }
  ],
  Udaipur: [
    { name: "Mount Abu", type: "Hill Station" },
    { name: "Ahmedabad", type: "Commercial" },
    { name: "Jodhpur", type: "Blue City" },
    { name: "Jaipur", type: "Royal" },
    { name: "Mount Abu", type: "Hill Station" },
    { name: "Jodhpur Jaisalmer", type: "Royal" },
    { name: "Jaipur Ajmer Pushkar", type: "Circuit" },
    { name: "Delhi Agra", type: "Heritage" },
    { name: "Ahmedabad Statue of Unity", type: "Circuit" }
  ],
  Jodhpur: [
    { name: "Jaisalmer", type: "Desert" },
    { name: "Udaipur", type: "Lakes" },
    { name: "Jaipur", type: "Royal" },
    { name: "Jaisalmer Desert Tour", type: "Desert" },
    { name: "Udaipur Mount Abu", type: "Royal" },
    { name: "Jaipur Ajmer Pushkar", type: "Circuit" },
    { name: "Delhi Agra", type: "Heritage" },
    { name: "Ahmedabad", type: "Commercial" }
  ],
  Ajmer: [
    { name: "Pushkar", type: "Spiritual" },
    { name: "Jaipur", type: "Royal" },
    { name: "Udaipur", type: "Lakes" },
    { name: "Pushkar", type: "Spiritual" },
    { name: "Jaipur", type: "Royal" },
    { name: "Udaipur", type: "Lakes" }
  ],
  Pushkar: [
    { name: "Ajmer", type: "Spiritual" },
    { name: "Udaipur", type: "Lakes" },
    { name: "Jaipur", type: "Royal" },
    { name: "Ajmer", type: "Spiritual" },
    { name: "Udaipur", type: "Lakes" },
    { name: "Jaipur", type: "Royal" }
  ],
  Shimla: [
    { name: "Manali Kasol Kullu", type: "Hill Station" },
    { name: "Chandigarh", type: "Metro" },
    { name: "Delhi", type: "Metro" },
    { name: "Dharamshala Dalhousie", type: "Hill Station" },
    { name: "Amritsar Golden Temple", type: "Heritage" }
  ],
  Manali: [
    { name: "Kasol Kheerganga Manikaran", type: "Adventure" },
    { name: "Leh Ladakh", type: "Adventure" },
    { name: "Shimla", type: "Hill Station" },
    { name: "Chandigarh", type: "Metro" },
    { name: "Delhi", type: "Metro" }
  ],
  Ahmedabad: [
    { name: "Udaipur Mount Abu", type: "Royal" },
    { name: "Jaipur Jodhpur Jaisalmer", type: "Royal" },
    { name: "Delhi Agra Mathura", type: "Circuit" },
    { name: "Statue of Unity", type: "Tourism" },
    { name: "Amritsar Golden Temple", type: "Heritage" }
  ]
};

// Local sightseeing data for each destination city
export const localSightseeing = {
  Shimla: [
    "Mall Road", "Ridge Road", "Christ Church", "Jakhu Temple",
    "Kufri", "Chail", "Naldehra", "Mashobra"
  ],
  Manali: [
    "Hadimba Temple", "Solang Valley", "Rohtang Pass", "Old Manali",
    "Vashisht Hot Springs", "Jogini Falls", "Manu Temple"
  ],
  Dharamshala: [
    "McLeod Ganj", "Dalai Lama Temple", "Bhagsu Waterfall",
    "Triund Trek", "Norbulingka Institute", "St. John Church"
  ],
  Amritsar: [
    "Golden Temple", "Wagah Border", "Jallianwala Bagh",
    "Partition Museum", "Gobindgarh Fort", "Ram Tirath"
  ],
  Haridwar: [
    "Har Ki Pauri", "Mansa Devi Temple", "Chandi Devi Temple",
    "Maya Devi Temple", "Bharat Mata Mandir", "Patanjali Yogpeeth"
  ],
  Rishikesh: [
    "Laxman Jhula", "Ram Jhula", "Beatles Ashram", "Triveni Ghat",
    "Parmarth Niketan", "Neelkanth Mahadev", "Kunjapuri Temple"
  ],
  Jaipur: [
    "Amber Fort", "Hawa Mahal", "City Palace", "Jantar Mantar",
    "Nahargarh Fort", "Jaigarh Fort", "Albert Hall Museum"
  ],
  Agra: [
    "Taj Mahal", "Agra Fort", "Fatehpur Sikri", "Mehtab Bagh",
    "Itmad-ud-Daulah", "Sikandra", "Agra Bear Rescue"
  ],
  Delhi: [
    "Red Fort", "India Gate", "Qutub Minar", "Lotus Temple",
    "Akshardham", "Humayun's Tomb", "Connaught Place"
  ],
  Udaipur: [
    "City Palace", "Lake Pichola", "Jag Mandir", "Fateh Sagar Lake",
    "Saheliyon Ki Bari", "Jagdish Temple", "Monsoon Palace"
  ],
  Jodhpur: [
    "Mehrangarh Fort", "Umaid Bhawan Palace", "Jaswant Thada",
    "Clock Tower", "Mandore Gardens", "Rao Jodha Desert Rock Park"
  ],
  Varanasi: [
    "Kashi Vishwanath Temple", "Dashashwamedh Ghat", "Sarnath",
    "Assi Ghat", "Manikarnika Ghat", "BHU Campus", "Ramnagar Fort"
  ],
  Lucknow: [
    "Bara Imambara", "Chota Imambara", "Rumi Darwaza",
    "British Residency", "Hazratganj", "Ambedkar Park"
  ],
  Ayodhya: [
    "Ram Janmabhoomi", "Hanuman Garhi", "Kanak Bhawan",
    "Dashrath Mahal", "Sita ki Rasoi", "Ramkot"
  ]
};

// Route-specific descriptions for top 50 tempo traveller routes
export const routeDescriptions = {
  'delhi-to-manali': {
    travelTime: '12-14 hours',
    distance: '530 km',
    bestSeason: 'March to June, September to November',
    highlights: 'The Delhi to Manali road trip via tempo traveller is one of North India\'s most scenic journeys. Drive through the plains of Haryana, stop at the famous Murthal dhabas for parathas, enter the hills at Chandigarh, and wind through the Kullu Valley with stunning views of the Beas River. The route passes through Sundernagar, Mandi, and the adventure town of Kullu before reaching Manali.',
    stops: ['Murthal (famous dhabas)', 'Chandigarh (rest stop)', 'Bilaspur (scenic lake)', 'Mandi (lunch break)', 'Kullu (valley views)', 'Manali'],
    roadConditions: 'NH44 till Chandigarh (excellent 4-lane expressway), NH21 mountain roads (good, hairpin bends after Mandi)',
  },
  'delhi-to-shimla': {
    travelTime: '7-9 hours',
    distance: '350 km',
    bestSeason: 'March to June, October to February (snowfall)',
    highlights: 'The Delhi to Shimla tempo traveller journey takes you from the bustling capital to the Queen of Hills. Travel via NH44 through Haryana, cross Chandigarh, and ascend through pine-covered mountains on NH5. The Kalka-Shimla stretch offers breathtaking views of the Shivalik Hills with 100+ curves providing panoramic vistas.',
    stops: ['Murthal (breakfast stop)', 'Pinjore Gardens (quick visit)', 'Kalka (foothills)', 'Solan (scenic)', 'Shimla'],
    roadConditions: 'NH44 till Chandigarh (excellent), Chandigarh-Kalka (good), Kalka-Shimla (steep mountain road, well-maintained)',
  },
  'delhi-to-jaipur': {
    travelTime: '5-6 hours',
    distance: '280 km',
    bestSeason: 'October to March (pleasant winter weather)',
    highlights: 'The Delhi to Jaipur tempo traveller route is part of the famous Golden Triangle circuit. Travel on the excellent Delhi-Jaipur Expressway (NH48) through the Aravalli hills. The journey is smooth and fast, passing through Gurugram, Manesar, and Neemrana where you can spot the historic Neemrana Fort. The landscape transitions from urban to semi-arid Rajasthan terrain.',
    stops: ['Manesar (toll plaza)', 'Neemrana Fort (photo stop)', 'Behror (food stop)', 'Shahpura (rest)', 'Jaipur'],
    roadConditions: 'Delhi-Jaipur Expressway NH48 (excellent 6-lane highway, one of India\'s best roads)',
  },
  'delhi-to-agra': {
    travelTime: '3-4 hours',
    distance: '233 km',
    bestSeason: 'October to March (avoid summer heat)',
    highlights: 'The Delhi to Agra tempo traveller trip covers one of India\'s most popular routes via the Yamuna Expressway. This modern 6-lane expressway makes the journey incredibly smooth and fast. Perfect for group day trips to the Taj Mahal, Agra Fort, and Fatehpur Sikri. The route offers flat terrain with farmland views on both sides.',
    stops: ['Greater Noida (expressway start)', 'Mathura (Krishna Janmabhoomi)', 'Vrindavan (optional detour)', 'Agra'],
    roadConditions: 'Yamuna Expressway (excellent 6-lane, 165 km toll road) + NH2 section (good)',
  },
  'delhi-to-haridwar': {
    travelTime: '5-6 hours',
    distance: '220 km',
    bestSeason: 'Year-round (best February to April for Ganga Aarti)',
    highlights: 'The Delhi to Haridwar tempo traveller journey takes you to one of India\'s seven holiest cities. Travel on NH334 through Meerut and Muzaffarnagar, with the landscape gradually transitioning from plains to the foothills of the Shivalik range. The sacred Ganges at Har Ki Pauri awaits. This route is especially popular during Kumbh Mela and Kanwar Yatra.',
    stops: ['Meerut (rest stop)', 'Muzaffarnagar (food break)', 'Roorkee (historic IIT)', 'Haridwar (Har Ki Pauri)'],
    roadConditions: 'NH334 Delhi-Meerut Expressway (excellent), Meerut-Haridwar (good 4-lane highway)',
  },
  'delhi-to-rishikesh': {
    travelTime: '6-7 hours',
    distance: '240 km',
    bestSeason: 'September to November, February to May',
    highlights: 'The Delhi to Rishikesh tempo traveller route takes your group to the Yoga Capital of the World. Travel through Haridwar and continue 25 km further to Rishikesh, nestled where the Ganges exits the Himalayas. Ideal for groups seeking adventure (rafting, bungee) and spirituality. The Beatles Ashram, Laxman Jhula, and riverside cafes make this a memorable trip.',
    stops: ['Meerut (breakfast)', 'Muzaffarnagar (rest)', 'Roorkee', 'Haridwar (Ganga darshan)', 'Rishikesh'],
    roadConditions: 'Delhi-Meerut Expressway (excellent), NH334 to Haridwar (good), Haridwar-Rishikesh (good 2-lane road)',
  },
  'delhi-to-mussoorie': {
    travelTime: '7-8 hours',
    distance: '290 km',
    bestSeason: 'March to June, September to November',
    highlights: 'The Delhi to Mussoorie tempo traveller journey takes you to the Queen of Hills via Dehradun. After crossing the plains, the road climbs through dense sal forests to Mussoorie at 2,005 meters. The last 35 km from Dehradun features sharp hairpin bends with stunning valley views. Kempty Falls, Gun Hill, and Mall Road are popular group destinations.',
    stops: ['Meerut (rest stop)', 'Muzaffarnagar', 'Roorkee', 'Dehradun (refreshments)', 'Mussoorie'],
    roadConditions: 'NH334 (good highway), Dehradun-Mussoorie (steep mountain road with hairpin bends, well-maintained)',
  },
  'delhi-to-nainital': {
    travelTime: '7-8 hours',
    distance: '315 km',
    bestSeason: 'March to June, September to November',
    highlights: 'The Delhi to Nainital tempo traveller route takes your group to the enchanting Lake District of India. Travel via Moradabad and Haldwani, entering the Kumaon Hills. The beautiful Naini Lake surrounded by seven hills is the centerpiece. Naina Devi Temple, Snow View Point, and boating on the lake are must-do activities for groups.',
    stops: ['Ghaziabad (start)', 'Moradabad (brass city, food stop)', 'Rampur', 'Haldwani (gateway to Kumaon)', 'Kathgodam', 'Nainital'],
    roadConditions: 'NH9 to Moradabad (good 4-lane), Moradabad-Haldwani (good), Haldwani-Nainital (mountain road, well-paved)',
  },
  'delhi-to-chandigarh': {
    travelTime: '4-5 hours',
    distance: '250 km',
    bestSeason: 'Year-round (pleasant October to March)',
    highlights: 'The Delhi to Chandigarh tempo traveller journey takes you to India\'s best planned city. Travel on the excellent NH44 (Grand Trunk Road) through Haryana, passing Panipat (historic battlefield), Karnal, and Ambala. Chandigarh\'s Rock Garden, Sukhna Lake, and the Rose Garden are perfect for group outings. This is also the gateway to Himachal Pradesh.',
    stops: ['Murthal (paratha stop)', 'Panipat (historical)', 'Karnal (rest stop)', 'Ambala', 'Chandigarh'],
    roadConditions: 'NH44 (excellent 6-lane national highway, one of India\'s best maintained roads)',
  },
  'delhi-to-amritsar': {
    travelTime: '8-9 hours',
    distance: '450 km',
    bestSeason: 'October to March (pleasant weather for Golden Temple visit)',
    highlights: 'The Delhi to Amritsar tempo traveller trip takes your group to the spiritual heart of Sikhism. Travel on NH44 through the fertile Punjab plains, passing Karnal, Ambala, Ludhiana, and Jalandhar. The Golden Temple\'s stunning architecture, Wagah Border ceremony, and Jallianwala Bagh are must-visit landmarks. Famous Amritsari kulchas and lassi await your group.',
    stops: ['Murthal (parathas)', 'Karnal/Ambala (rest)', 'Ludhiana (lunch break)', 'Jalandhar', 'Amritsar'],
    roadConditions: 'NH44 (excellent 4-6 lane highway throughout, some construction zones near Ludhiana)',
  },
  'delhi-to-dehradun': {
    travelTime: '6-7 hours',
    distance: '250 km',
    bestSeason: 'Year-round (best March to June, September to November)',
    highlights: 'The Delhi to Dehradun tempo traveller journey leads to the capital of Uttarakhand, nestled in the Doon Valley. Travel via NH334 through Meerut and Roorkee. Dehradun serves as the gateway to Mussoorie, Char Dham, and Uttarakhand\'s hill stations. Robber\'s Cave, FRI (Forest Research Institute), and Sahastradhara are popular group spots.',
    stops: ['Meerut (snacks)', 'Muzaffarnagar (rest)', 'Roorkee (IIT campus)', 'Dehradun'],
    roadConditions: 'Delhi-Meerut Expressway (excellent), NH334 (good 4-lane highway till Dehradun)',
  },
  'delhi-to-jim-corbett': {
    travelTime: '6-7 hours',
    distance: '260 km',
    bestSeason: 'November to June (park open), best December to March for tiger sightings',
    highlights: 'The Delhi to Jim Corbett National Park tempo traveller route takes your group to India\'s oldest national park, established in 1936. Travel via NH9 through Moradabad and Kashipur to Ramnagar, the park\'s gateway. Home to Bengal tigers, elephants, and over 600 bird species, Corbett offers thrilling jungle safaris. Book your safari permits in advance during peak season.',
    stops: ['Ghaziabad', 'Moradabad (food stop)', 'Kashipur', 'Ramnagar (park gate)', 'Jim Corbett zones'],
    roadConditions: 'NH9 (good 4-lane till Moradabad), Moradabad-Ramnagar (good 2-lane road through terai region)',
  },
  'delhi-to-dharamshala': {
    travelTime: '10-11 hours',
    distance: '475 km',
    bestSeason: 'March to June, September to November',
    highlights: 'The Delhi to Dharamshala tempo traveller journey takes your group to the home of the Dalai Lama in the Kangra Valley. Travel via Chandigarh and through the scenic Himachal roads. McLeod Ganj, Bhagsu Waterfall, Triund Trek, and the Dalai Lama Temple Complex are major attractions. The Tibetan culture and momos are highlights for every visitor.',
    stops: ['Murthal (breakfast)', 'Chandigarh (rest stop)', 'Una (Himachal entry)', 'Kangra', 'Dharamshala/McLeod Ganj'],
    roadConditions: 'NH44 to Chandigarh (excellent), Chandigarh-Dharamshala via NH503 (good mountain roads, some narrow stretches)',
  },
  'delhi-to-varanasi': {
    travelTime: '12-14 hours',
    distance: '820 km',
    bestSeason: 'October to March (pleasant weather for ghat walks)',
    highlights: 'The Delhi to Varanasi tempo traveller route is a spiritual odyssey to India\'s oldest living city. Travel via the Lucknow-Agra Expressway and NH-2. Varanasi\'s Ganga Aarti at Dashashwamedh Ghat, Kashi Vishwanath Temple, boat rides at sunrise, and Sarnath (where Buddha gave his first sermon) make this a profound journey. An overnight journey is recommended.',
    stops: ['Agra bypass', 'Kanpur (rest stop)', 'Lucknow (lunch option)', 'Prayagraj (optional)', 'Varanasi'],
    roadConditions: 'Yamuna Expressway + Agra-Lucknow Expressway (excellent), NH-2 Lucknow-Varanasi (good 4-lane)',
  },
  'delhi-to-udaipur': {
    travelTime: '10-11 hours',
    distance: '660 km',
    bestSeason: 'September to March (lake city at its best after monsoon)',
    highlights: 'The Delhi to Udaipur tempo traveller journey takes your group to the Venice of the East. Travel via Jaipur on NH48 and then south through the Aravalli Hills on NH48/NH8. Udaipur\'s City Palace, Lake Pichola, Jag Mandir, and the romantic sunset views are unforgettable. This is a popular route for destination wedding groups.',
    stops: ['Manesar (toll)', 'Jaipur (lunch/bypass)', 'Ajmer (optional stop)', 'Chittorgarh Fort (heritage)', 'Udaipur'],
    roadConditions: 'NH48 Delhi-Jaipur (excellent expressway), Jaipur-Udaipur via NH48 (good 4-lane, scenic Aravalli stretch)',
  },
  'delhi-to-jodhpur': {
    travelTime: '9-10 hours',
    distance: '580 km',
    bestSeason: 'October to March (desert weather is pleasant)',
    highlights: 'The Delhi to Jodhpur tempo traveller route leads to the magnificent Blue City of Rajasthan. Travel via Jaipur and through the Thar Desert fringe. Mehrangarh Fort (one of India\'s largest), Umaid Bhawan Palace, the blue-painted old city streets, and Jaswant Thada are awe-inspiring. The Rajasthani thali and mirchi vada are food highlights.',
    stops: ['Manesar', 'Jaipur (rest/bypass)', 'Ajmer (optional)', 'Beawar', 'Pali', 'Jodhpur'],
    roadConditions: 'NH48 to Jaipur (excellent), NH62 Jaipur-Jodhpur (good 2-4 lane, desert terrain)',
  },
  'delhi-to-jaisalmer': {
    travelTime: '13-14 hours',
    distance: '780 km',
    bestSeason: 'October to February (cool desert nights, Desert Festival in Feb)',
    highlights: 'The Delhi to Jaisalmer tempo traveller journey takes your group to the Golden City of Rajasthan, deep in the Thar Desert. Travel via Jodhpur and watch the landscape transform into golden sand dunes. Jaisalmer Fort (a living fort with residents), Sam Sand Dunes camel safari, Patwon Ki Haveli, and desert camping under the stars are unforgettable experiences.',
    stops: ['Jaipur (rest/bypass)', 'Jodhpur (lunch break)', 'Pokhran (nuclear test site)', 'Jaisalmer'],
    roadConditions: 'NH48 + NH62 to Jodhpur (good), NH15 Jodhpur-Jaisalmer (good 2-lane desert road, sparse traffic)',
  },
  'delhi-to-kasol': {
    travelTime: '12-13 hours',
    distance: '520 km',
    bestSeason: 'March to June, September to November',
    highlights: 'The Delhi to Kasol tempo traveller route leads to the Mini Israel of India in Parvati Valley. Travel via Chandigarh and Mandi, then through the stunning Parvati Valley along the Parvati River. Kasol\'s hippie cafes, Manikaran Gurudwara with its hot springs, Kheerganga trek, and Tosh village are top group destinations. The Israeli cuisine and scenic camping spots are unique.',
    stops: ['Murthal (breakfast)', 'Chandigarh (rest)', 'Mandi (lunch)', 'Bhuntar (Parvati Valley entry)', 'Kasol'],
    roadConditions: 'NH44 + NH21 to Mandi (good), Mandi-Kasol via NH305 (narrow mountain road along Parvati River, scenic but winding)',
  },
  'delhi-to-ayodhya': {
    travelTime: '10-11 hours',
    distance: '636 km',
    bestSeason: 'October to March (pleasant weather for temple visits)',
    highlights: 'The Delhi to Ayodhya tempo traveller journey takes your group to the birthplace of Lord Ram. Travel via the Lucknow-Agra Expressway and Lucknow, then continue to Ayodhya. The newly built Ram Mandir, Hanuman Garhi, Kanak Bhawan, and the banks of the Saryu River are the main attractions. This route has become extremely popular since the Ram Mandir inauguration.',
    stops: ['Greater Noida (expressway start)', 'Agra bypass', 'Lucknow (lunch, Tunday Kebabs)', 'Barabanki', 'Ayodhya'],
    roadConditions: 'Yamuna Expressway + Agra-Lucknow Expressway (excellent), Lucknow-Ayodhya NH330 (good 4-lane)',
  },
  'delhi-to-lucknow': {
    travelTime: '8-9 hours',
    distance: '555 km',
    bestSeason: 'October to March (best for Nawabi food walks)',
    highlights: 'The Delhi to Lucknow tempo traveller route leads to the City of Nawabs. Travel on the excellent Agra-Lucknow Expressway for the fastest journey. Lucknow\'s Bara Imambara, Rumi Darwaza, Hazratganj market, and the legendary Tunday Kebabs and Awadhi biryani make this a cultural and culinary delight. The British Residency offers a glimpse into India\'s history.',
    stops: ['Greater Noida', 'Agra bypass (Yamuna Expressway)', 'Kannauj (perfume city)', 'Lucknow'],
    roadConditions: 'Yamuna Expressway + Agra-Lucknow Expressway (excellent 6-lane, fastest route ~6 hours)',
  },
  'jaipur-to-udaipur': {
    travelTime: '6-7 hours',
    distance: '395 km',
    bestSeason: 'September to March (lakes full after monsoon)',
    highlights: 'The Jaipur to Udaipur tempo traveller route is a royal Rajasthan journey through the Aravalli Hills. Travel via NH48 through Ajmer, Beawar, and the historic Chittorgarh Fort. The road winds through scenic Aravalli passes with views of ancient forts and rural Rajasthan. Udaipur\'s lakeside palaces and sunset boat rides on Lake Pichola are the perfect group experience.',
    stops: ['Ajmer (Dargah visit)', 'Pushkar (optional detour)', 'Beawar', 'Chittorgarh (fort visit)', 'Udaipur'],
    roadConditions: 'NH48 (good 4-lane national highway, gentle Aravalli curves, well-maintained)',
  },
  'jaipur-to-jodhpur': {
    travelTime: '5-6 hours',
    distance: '335 km',
    bestSeason: 'October to March (pleasant desert weather)',
    highlights: 'The Jaipur to Jodhpur tempo traveller journey connects the Pink City to the Blue City across the Thar Desert fringe. Travel via NH62 through Ajmer and Beawar. The landscape transitions from Aravalli scrubland to arid desert terrain. Jodhpur\'s majestic Mehrangarh Fort perched on a rocky outcrop is visible from miles away, a dramatic first impression for groups.',
    stops: ['Dudu', 'Ajmer (quick stop)', 'Beawar (food stop)', 'Pali', 'Jodhpur'],
    roadConditions: 'NH62 (good 2-4 lane highway, flat desert terrain, easy drive)',
  },
  'jaipur-to-jaisalmer': {
    travelTime: '9-10 hours',
    distance: '565 km',
    bestSeason: 'October to February (Desert Festival in February)',
    highlights: 'The Jaipur to Jaisalmer tempo traveller route is the ultimate desert road trip. Travel through Jodhpur and deep into the Thar Desert. Watch the vegetation thin out and the golden sands take over. Jaisalmer\'s living sandstone fort, intricate havelis, Sam Sand Dunes with camel safaris and cultural shows under desert stars create memories for a lifetime.',
    stops: ['Ajmer (rest)', 'Jodhpur (lunch, Mehrangarh Fort view)', 'Pokhran', 'Jaisalmer'],
    roadConditions: 'NH62 to Jodhpur (good), NH15 to Jaisalmer (good 2-lane, straight desert road with sparse traffic)',
  },
  'jaipur-to-ajmer': {
    travelTime: '2-3 hours',
    distance: '135 km',
    bestSeason: 'Year-round (October to March is ideal)',
    highlights: 'The Jaipur to Ajmer tempo traveller trip is a short and comfortable ride through Rajasthan\'s Aravalli region. Ajmer is home to the revered Ajmer Sharif Dargah, one of India\'s most important Sufi shrines visited by people of all faiths. Ana Sagar Lake and Taragarh Fort offer scenic group outings. Combine with a Pushkar visit for a complete pilgrimage.',
    stops: ['Dudu', 'Kishangarh (marble city)', 'Ajmer'],
    roadConditions: 'NH48/NH8 (excellent 4-6 lane highway, quick and smooth journey)',
  },
  'jaipur-to-pushkar': {
    travelTime: '3-3.5 hours',
    distance: '145 km',
    bestSeason: 'October to March (Pushkar Fair in November)',
    highlights: 'The Jaipur to Pushkar tempo traveller route takes your group to the sacred lake town with the only Brahma temple in the world. Travel via Ajmer and over the scenic Nag Pahar (Snake Mountain) pass. Pushkar Lake, the 52 ghats, the famous Pushkar Fair (November), and the vibrant bazaar with hippie culture make this a unique destination for groups.',
    stops: ['Dudu', 'Kishangarh', 'Ajmer (Dargah stop)', 'Pushkar (via Nag Pahar)'],
    roadConditions: 'NH48 to Ajmer (excellent), Ajmer-Pushkar (good mountain pass road, 14 km scenic stretch)',
  },
  'jaipur-to-mount-abu': {
    travelTime: '8-9 hours',
    distance: '490 km',
    bestSeason: 'October to March (pleasant hill climate)',
    highlights: 'The Jaipur to Mount Abu tempo traveller route leads to Rajasthan\'s only hill station. Travel south through Udaipur or via Pali-Sirohi through the Aravalli range. Mount Abu\'s Dilwara Jain Temples (12th century, exquisite marble carvings), Nakki Lake, Guru Shikhar (highest point in Rajasthan at 1,722m), and Sunset Point are perfect for group excursions.',
    stops: ['Beawar', 'Pali (food stop)', 'Sirohi (gateway to Mount Abu)', 'Mount Abu'],
    roadConditions: 'NH48 + NH27 (good highways), final 28 km hill road to Mount Abu (steep curves, well-maintained)',
  },
  'jaipur-to-delhi': {
    travelTime: '5-6 hours',
    distance: '280 km',
    bestSeason: 'Year-round',
    highlights: 'The Jaipur to Delhi tempo traveller return journey on NH48 is fast and comfortable. Groups can stop at Neemrana Fort Palace for a heritage lunch experience, or at the Khushro Bagh food court near Behror. The expressway offers smooth travel, making it ideal for corporate teams returning from Rajasthan offsites or wedding parties heading back to Delhi.',
    stops: ['Jaipur', 'Shahpura', 'Behror (food court)', 'Neemrana Fort (heritage stop)', 'Delhi'],
    roadConditions: 'Delhi-Jaipur Expressway NH48 (excellent 6-lane highway)',
  },
  'jaipur-to-agra': {
    travelTime: '4-5 hours',
    distance: '240 km',
    bestSeason: 'October to March (ideal for Taj Mahal visit)',
    highlights: 'The Jaipur to Agra tempo traveller journey completes the Golden Triangle circuit. Travel via NH21 through Bharatpur, home to the Keoladeo Bird Sanctuary (UNESCO World Heritage Site). The route passes through the Karauli and Dholpur regions. Reaching Agra, the Taj Mahal, Agra Fort, and Fatehpur Sikri offer world-class heritage experiences for groups.',
    stops: ['Dausa', 'Bharatpur (bird sanctuary stop)', 'Fatehpur Sikri (heritage visit)', 'Agra'],
    roadConditions: 'NH21 (good 2-4 lane highway, mostly flat terrain through eastern Rajasthan and UP border)',
  },
  'agra-to-jaipur': {
    travelTime: '4-5 hours',
    distance: '240 km',
    bestSeason: 'October to March',
    highlights: 'The Agra to Jaipur tempo traveller route is the return leg of the Golden Triangle. After visiting the Taj Mahal at sunrise, groups can head to the Pink City. Stop at Fatehpur Sikri (Akbar\'s abandoned capital) and Bharatpur Bird Sanctuary en route. Jaipur\'s Amber Fort, Hawa Mahal, and City Palace await for an evening of royal Rajasthan exploration.',
    stops: ['Agra', 'Fatehpur Sikri (Mughal heritage)', 'Bharatpur (optional)', 'Dausa', 'Jaipur'],
    roadConditions: 'NH21 (good highway, flat terrain, comfortable drive)',
  },
  'agra-to-delhi': {
    travelTime: '3-4 hours',
    distance: '233 km',
    bestSeason: 'Year-round',
    highlights: 'The Agra to Delhi tempo traveller return journey is fast and convenient via the Yamuna Expressway. After an early morning Taj Mahal visit, groups can return to Delhi comfortably by lunch. The 165 km Yamuna Expressway section is one of India\'s best roads, with rest stops and food plazas available. Alternatively, take NH2 via Mathura for a more scenic route.',
    stops: ['Agra', 'Mathura (optional Krishna temple stop)', 'Yamuna Expressway rest areas', 'Greater Noida', 'Delhi'],
    roadConditions: 'Yamuna Expressway (excellent 6-lane, 165 km) + Noida-Delhi section (good urban roads)',
  },
  'agra-to-lucknow': {
    travelTime: '5-6 hours',
    distance: '335 km',
    bestSeason: 'October to March',
    highlights: 'The Agra to Lucknow tempo traveller route connects the Mughal capital to the City of Nawabs via the Agra-Lucknow Expressway. This modern expressway makes the journey fast and smooth. Groups can explore the transition from Mughal architecture to Awadhi culture. Lucknow\'s kebab trail, Bara Imambara, and Rumi Darwaza offer a completely different cultural experience.',
    stops: ['Agra', 'Firozabad (glass bangle city)', 'Etawah (rest stop)', 'Kannauj (perfume capital)', 'Lucknow'],
    roadConditions: 'Agra-Lucknow Expressway (excellent 6-lane, fast and smooth)',
  },
  'agra-to-varanasi': {
    travelTime: '10-11 hours',
    distance: '610 km',
    bestSeason: 'October to March (pleasant weather for ghat walks)',
    highlights: 'The Agra to Varanasi tempo traveller journey connects two of India\'s most iconic cities. Travel via the Agra-Lucknow Expressway and then NH-2. From the Mughal grandeur of the Taj Mahal to the ancient spirituality of Varanasi\'s ghats, this route spans centuries of Indian civilization. The Ganga Aarti at Dashashwamedh Ghat is an unmissable experience for groups.',
    stops: ['Agra', 'Lucknow (lunch, Tunday Kebabs)', 'Prayagraj (Sangam optional)', 'Varanasi'],
    roadConditions: 'Agra-Lucknow Expressway (excellent), NH-2 Lucknow-Varanasi (good 4-lane highway)',
  },
  'agra-to-mathura': {
    travelTime: '1-1.5 hours',
    distance: '58 km',
    bestSeason: 'Year-round (Holi in Mathura/Vrindavan is spectacular)',
    highlights: 'The Agra to Mathura tempo traveller trip is a short pilgrimage to Lord Krishna\'s birthplace. Travel via NH2 through the Braj region. Krishna Janmabhoomi temple, Dwarkadhish Temple, and the nearby Vrindavan (with Banke Bihari Temple, ISKCON, and Prem Mandir) make this a spiritually enriching group excursion. Combine with Vrindavan for a full day tour.',
    stops: ['Agra', 'Mathura (Krishna Janmabhoomi)', 'Vrindavan (optional, 12 km further)'],
    roadConditions: 'NH2 (good 4-lane highway, short and easy drive)',
  },
  'chandigarh-to-manali': {
    travelTime: '7-8 hours',
    distance: '310 km',
    bestSeason: 'March to June, September to November',
    highlights: 'The Chandigarh to Manali tempo traveller route is one of the most scenic mountain drives in India. Travel through Bilaspur along the Govind Sagar Lake, then through Mandi and the Kullu Valley. The Beas River accompanies you for much of the journey. The apple orchards, pine forests, and snow-capped peaks create a stunning backdrop for group photos.',
    stops: ['Bilaspur (Govind Sagar Lake view)', 'Sundernagar', 'Mandi (lunch on Beas banks)', 'Kullu (shawl shopping)', 'Manali'],
    roadConditions: 'NH21 (good mountain highway, hairpin bends after Mandi, well-maintained)',
  },
  'chandigarh-to-shimla': {
    travelTime: '3-4 hours',
    distance: '115 km',
    bestSeason: 'Year-round (snowfall December-February, pleasant March-June)',
    highlights: 'The Chandigarh to Shimla tempo traveller trip is a beautiful hill journey through the Shivalik range. The road climbs from Kalka through 800+ curves with panoramic views of terraced farms and pine forests. Shimla\'s colonial architecture, Mall Road, Christ Church, and Jakhu Temple are perfect for group exploration. Stop at Barog for a tunnel walk.',
    stops: ['Panchkula', 'Kalka (foothills start)', 'Barog (tunnel, rest stop)', 'Solan (mushroom city)', 'Shimla'],
    roadConditions: 'NH5 Chandigarh-Shimla (good mountain road, steep curves after Kalka, well-maintained)',
  },
  'chandigarh-to-dharamshala': {
    travelTime: '5-6 hours',
    distance: '240 km',
    bestSeason: 'March to June, September to November',
    highlights: 'The Chandigarh to Dharamshala tempo traveller journey leads through Punjab\'s green fields and into the Kangra Valley. Travel via NH503 through Una and Kangra. Dharamshala and McLeod Ganj offer Tibetan culture, the Dalai Lama Temple, Bhagsu Waterfall, and the starting point for the famous Triund Trek. The Tibetan momos and thukpa are group favorites.',
    stops: ['Rupnagar (Anandpur Sahib nearby)', 'Una', 'Kangra (fort visit)', 'Dharamshala/McLeod Ganj'],
    roadConditions: 'NH503 (good 2-4 lane highway, gentle hills through Kangra Valley)',
  },
  'chandigarh-to-delhi': {
    travelTime: '4-5 hours',
    distance: '250 km',
    bestSeason: 'Year-round',
    highlights: 'The Chandigarh to Delhi tempo traveller return journey on NH44 is smooth and fast. Groups returning from Himachal trips can enjoy a comfortable ride through Haryana. Stop at Ambala for authentic Punjabi food, or Murthal for legendary parathas. The highway is one of India\'s best-maintained, making it ideal for tired groups after a hill station holiday.',
    stops: ['Chandigarh', 'Ambala (Punjabi food)', 'Karnal (rest)', 'Panipat', 'Murthal (parathas)', 'Delhi'],
    roadConditions: 'NH44 (excellent 6-lane national highway)',
  },
  'chandigarh-to-amritsar': {
    travelTime: '4-5 hours',
    distance: '230 km',
    bestSeason: 'October to March (pleasant for Golden Temple visit)',
    highlights: 'The Chandigarh to Amritsar tempo traveller route passes through the heart of Punjab. Travel on NH44 through Ludhiana and Jalandhar, surrounded by mustard and wheat fields. The Golden Temple\'s sacred sarovar, the patriotic Wagah Border ceremony, and Amritsar\'s street food (kulcha, lassi, jalebi) create a memorable group experience.',
    stops: ['Rupnagar', 'Ludhiana (rest stop)', 'Phagwara', 'Jalandhar (food stop)', 'Amritsar'],
    roadConditions: 'NH44 (good 4-lane highway through Punjab plains)',
  },
  'haridwar-to-rishikesh': {
    travelTime: '45 minutes - 1 hour',
    distance: '25 km',
    bestSeason: 'Year-round (rafting September to May)',
    highlights: 'The Haridwar to Rishikesh tempo traveller transfer is a short scenic drive along the Ganges. From the sacred Har Ki Pauri ghats to the adventure capital of India, this short journey transitions from traditional pilgrimage to yoga and adventure tourism. Perfect for groups combining spiritual and adventure activities. River rafting camps line the route.',
    stops: ['Haridwar (Har Ki Pauri)', 'Rishikesh (Laxman Jhula/Ram Jhula)'],
    roadConditions: 'NH7 (good 2-lane road along the Ganges, scenic and well-maintained)',
  },
  'haridwar-to-mussoorie': {
    travelTime: '2.5-3 hours',
    distance: '90 km',
    bestSeason: 'March to June, September to November',
    highlights: 'The Haridwar to Mussoorie tempo traveller route takes your group from the sacred Ganges to the Queen of Hills. Travel via Dehradun, then climb the winding 35 km mountain road to Mussoorie at 2,005 meters. Kempty Falls, Gun Hill Point, Camel\'s Back Road, and Mall Road shopping are popular group activities. The views of the Doon Valley from Mussoorie are spectacular.',
    stops: ['Haridwar', 'Dehradun (refreshments)', 'Mussoorie (via Library Road or Mall Road)'],
    roadConditions: 'Haridwar-Dehradun (good highway), Dehradun-Mussoorie (steep mountain road with hairpin bends, well-paved)',
  },
  'haridwar-to-dehradun': {
    travelTime: '1-1.5 hours',
    distance: '55 km',
    bestSeason: 'Year-round',
    highlights: 'The Haridwar to Dehradun tempo traveller transfer is a quick trip connecting the sacred Ganges city to Uttarakhand\'s capital. The road passes through the Rajaji Tiger Reserve corridor where groups sometimes spot elephants. Dehradun\'s Robber\'s Cave, FRI museum, and Paltan Bazaar offer pleasant group outings before heading to Mussoorie or other Uttarakhand destinations.',
    stops: ['Haridwar', 'Rajaji National Park stretch', 'Dehradun'],
    roadConditions: 'NH7 (good 2-4 lane highway through Rajaji corridor)',
  },
  'haridwar-to-delhi': {
    travelTime: '5-6 hours',
    distance: '220 km',
    bestSeason: 'Year-round',
    highlights: 'The Haridwar to Delhi tempo traveller return journey is comfortable via NH334. After performing Ganga Aarti and visiting temples, groups can head back to Delhi relaxed. The route passes through Roorkee (India\'s first engineering college), Muzaffarnagar, and Meerut. Early morning departures help avoid traffic when entering Delhi.',
    stops: ['Haridwar', 'Roorkee (rest stop)', 'Muzaffarnagar', 'Meerut', 'Delhi'],
    roadConditions: 'NH334 (good highway), Delhi-Meerut Expressway section (excellent)',
  },
  'haridwar-to-badrinath': {
    travelTime: '10-11 hours',
    distance: '315 km',
    bestSeason: 'May to June, September to October (temple open May-November)',
    highlights: 'The Haridwar to Badrinath tempo traveller pilgrimage route follows the sacred Char Dham path along the Alaknanda River. Pass through Devprayag (Ganga\'s origin confluence), Rudraprayag, Karnaprayag, and Joshimath before reaching Badrinath at 3,133 meters. The Badrinath Temple dedicated to Lord Vishnu, Mana Village (last Indian village), and Vasudhara Falls are must-visits.',
    stops: ['Rishikesh (quick darshan)', 'Devprayag (holy Sangam)', 'Rudraprayag (confluence)', 'Joshimath (Narsingh Temple)', 'Badrinath'],
    roadConditions: 'NH7 (mountain road, mostly single lane after Rishikesh, subject to landslides during monsoon, drive during daylight only)',
  },
  'dehradun-to-mussoorie': {
    travelTime: '1-1.5 hours',
    distance: '35 km',
    bestSeason: 'Year-round (snowfall December-February, pleasant March-June)',
    highlights: 'The Dehradun to Mussoorie tempo traveller trip is a scenic mountain climb through dense forests. The road ascends from the Doon Valley at 640m to Mussoorie at 2,005m with stunning valley views and hairpin bends. Perfect for groups on weekend getaways. Kempty Falls (midway stop), Cloud\'s End, Lal Tibba (highest point), and Company Garden are group favorites.',
    stops: ['Dehradun', 'Kempty Falls (midway)', 'Mussoorie (Library/Picture Palace end)'],
    roadConditions: 'Dehradun-Mussoorie road (steep, winding hill road with hairpin bends, well-maintained but narrow in places)',
  },
  'rishikesh-to-badrinath': {
    travelTime: '9-10 hours',
    distance: '295 km',
    bestSeason: 'May to June, September to October',
    highlights: 'The Rishikesh to Badrinath tempo traveller pilgrimage follows the Alaknanda River through the heart of Garhwal Himalayas. Pass through five sacred prayags (confluences), with Devprayag being the most significant where Bhagirathi and Alaknanda merge to form the Ganga. The route offers dramatic mountain scenery, waterfalls, and the spiritual energy of ancient temples.',
    stops: ['Devprayag (Ganga origin)', 'Srinagar (Garhwal)', 'Rudraprayag', 'Karnaprayag', 'Joshimath (Auli ropeway)', 'Badrinath'],
    roadConditions: 'NH7 (mountain road, mostly well-maintained but narrow, avoid monsoon months, several landslide-prone stretches)',
  },
  'lucknow-to-varanasi': {
    travelTime: '5-6 hours',
    distance: '320 km',
    bestSeason: 'October to March (pleasant for ghat exploration)',
    highlights: 'The Lucknow to Varanasi tempo traveller route connects two of UP\'s most culturally rich cities via NH-2. From Awadhi nawabi culture to the world\'s oldest continuously inhabited city, this journey spans civilizations. Varanasi\'s Kashi Vishwanath Temple, Ganga Aarti, sunrise boat rides, and the ancient university town of Sarnath make this a deeply enriching group experience.',
    stops: ['Lucknow', 'Sultanpur', 'Jaunpur (Atala Mosque)', 'Varanasi'],
    roadConditions: 'NH-2 (good 4-lane highway, flat terrain, comfortable drive)',
  },
  'lucknow-to-ayodhya': {
    travelTime: '2.5-3 hours',
    distance: '135 km',
    bestSeason: 'Year-round (Ram Navami festival in March/April is special)',
    highlights: 'The Lucknow to Ayodhya tempo traveller trip is a pilgrimage to the birthplace of Lord Ram. The newly constructed Ram Mandir has made Ayodhya one of India\'s most visited destinations. Travel via NH330 through the flat Awadh plains. Hanuman Garhi, Kanak Bhawan, Dashrath Mahal, and the serene banks of the Saryu River offer a complete spiritual experience.',
    stops: ['Lucknow', 'Barabanki (rest stop)', 'Ayodhya (Ram Mandir, Hanuman Garhi)'],
    roadConditions: 'NH330 (good 4-lane highway, flat terrain, quick and comfortable)',
  },
  'amritsar-to-dharamshala': {
    travelTime: '4-5 hours',
    distance: '200 km',
    bestSeason: 'March to June, September to November',
    highlights: 'The Amritsar to Dharamshala tempo traveller journey takes your group from the Golden Temple to the Dalai Lama\'s residence. Travel south through Punjab\'s green fields and into the Kangra Valley of Himachal Pradesh. The transition from flatland to hills is gradual and scenic. Dharamshala and McLeod Ganj offer Tibetan monasteries, Bhagsu Waterfall, and the famous Triund Trek.',
    stops: ['Amritsar', 'Pathankot (border of Punjab-HP)', 'Kangra (fort and temple)', 'Dharamshala/McLeod Ganj'],
    roadConditions: 'NH3 to Pathankot (good highway), Pathankot-Dharamshala (good mountain road through Kangra Valley)',
  },
  'udaipur-to-jodhpur': {
    travelTime: '4-5 hours',
    distance: '250 km',
    bestSeason: 'October to March',
    highlights: 'The Udaipur to Jodhpur tempo traveller route connects the City of Lakes to the Blue City through the Aravalli foothills. Travel via NH62 through Ranakpur (famous Jain temple with 1,444 carved pillars) and Pali. The landscape transitions from lush Aravalli hills around Udaipur to the semi-arid terrain near Jodhpur. Both cities are popular for destination weddings.',
    stops: ['Udaipur', 'Ranakpur (Jain Temple stop)', 'Pali (food break)', 'Jodhpur'],
    roadConditions: 'NH62 (good 2-4 lane highway, scenic Aravalli section near Ranakpur)',
  },
  'varanasi-to-ayodhya': {
    travelTime: '4-5 hours',
    distance: '200 km',
    bestSeason: 'October to March',
    highlights: 'The Varanasi to Ayodhya tempo traveller pilgrimage connects two of Hinduism\'s holiest cities. After experiencing the Ganga Aarti and Kashi Vishwanath darshan, groups travel to the birthplace of Lord Ram. The route passes through the spiritual heartland of Uttar Pradesh via Jaunpur. The newly built Ram Mandir has made this a must-do combined pilgrimage for groups.',
    stops: ['Varanasi (morning Ganga darshan)', 'Jaunpur (historic Sharqi monuments)', 'Sultanpur', 'Ayodhya'],
    roadConditions: 'NH-2 + NH330 (good 4-lane highways, flat terrain)',
  },
};