// src/utilis/travelOptionsData.js - Complete data for 20 Multi-Modal Travel Comparison pages

function createTravelRoute({ slug, origin, destination, modes, verdict, faqOverrides }) {
  const carMode = modes.find(m => m.mode === 'Car');
  const busMode = modes.find(m => m.mode === 'Bus');
  const trainMode = modes.find(m => m.mode === 'Train');
  const defaultFaqs = [
    { question: `What is the best way to travel from ${origin} to ${destination}?`, answer: verdict },
    { question: `How much does a cab from ${origin} to ${destination} cost?`, answer: `A cab from ${origin} to ${destination} costs from ${carMode ? carMode.cost : 'N/A'} (Sedan, includes driver, fuel, AC). Toll and parking extra. Call 7668570551 for exact quote.` },
    { question: `Is it cheaper to take a bus or cab from ${origin} to ${destination}?`, answer: `Bus is cheaper (${busMode ? busMode.cost : 'N/A'}) but a cab (${carMode ? carMode.cost : 'N/A'}) offers door-to-door service, AC comfort, flexible stops, and is faster. For 3-4 people sharing, cab per-person cost is comparable to bus.` },
    { question: `How long does it take from ${origin} to ${destination} by car?`, answer: `By car: ${carMode ? carMode.duration : 'N/A'}. By train: ${trainMode ? trainMode.duration : 'N/A'}. By bus: ${busMode ? busMode.duration : 'N/A'}. Car offers the most flexibility with door-to-door service.` },
    { question: `Can I book a one-way cab from ${origin} to ${destination}?`, answer: `Yes, Triveni Cabs offers one-way cab service from ${origin} to ${destination}. One-way saves up to 50% compared to round-trip. Book via call (7668570551) or WhatsApp.` },
    { question: `Which is more comfortable - train or cab from ${origin} to ${destination}?`, answer: `Cab offers the most comfort: private AC vehicle, door-to-door service, stop anywhere, flexible timing. Train offers more legroom but fixed schedule and station-to-station travel.` },
  ];
  return { slug, origin, destination, modes, verdict, faqs: faqOverrides || defaultFaqs };
}

const travelRoutes = {
  "delhi-to-manali": createTravelRoute({ slug: "delhi-to-manali", origin: "Delhi", destination: "Manali", modes: [ { mode: "Car", duration: "12-13 hrs", cost: "₹5,830", comfort: 4, flexibility: 5, bestFor: "Families, groups, scenic stops" }, { mode: "Bus", duration: "14-16 hrs", cost: "₹800-2,500", comfort: 2, flexibility: 1, bestFor: "Budget solo travelers" }, { mode: "Train", duration: "12 hrs to Chandigarh + 6 hrs cab", cost: "₹600-2,000 + ₹3,410", comfort: 3, flexibility: 2, bestFor: "Train journey lovers" }, { mode: "Flight", duration: "1.5 hrs to Kullu + 1.5 hrs cab", cost: "₹4,000-10,000 + ₹1,500", comfort: 4, flexibility: 3, bestFor: "Time-pressed travelers" } ], verdict: "Car is the best option for families and groups. The Delhi-Manali highway offers stunning scenery with stops at Murthal and Chandigarh. For solo budget travelers, Volvo bus overnight is practical. Flight + cab is fastest but most expensive." }),
  "delhi-to-shimla": createTravelRoute({ slug: "delhi-to-shimla", origin: "Delhi", destination: "Shimla", modes: [ { mode: "Car", duration: "7-8 hrs", cost: "₹3,850", comfort: 4, flexibility: 5, bestFor: "Families, scenic drive lovers" }, { mode: "Bus", duration: "8-10 hrs", cost: "₹600-1,800", comfort: 2, flexibility: 1, bestFor: "Budget travelers" }, { mode: "Train", duration: "4 hrs to Kalka + 5 hrs toy train", cost: "₹300-1,500 + ₹300", comfort: 3, flexibility: 2, bestFor: "Heritage toy train experience" }, { mode: "Flight", duration: "1.5 hrs to Chandigarh + 3 hrs cab", cost: "₹3,500-8,000 + ₹1,500", comfort: 4, flexibility: 3, bestFor: "Time-pressed travelers" } ], verdict: "Car is recommended for most travelers. Comfortable 7-hour drive with scenic mountain sections. The Kalka-Shimla toy train is a UNESCO heritage experience worth trying once." }),
  "delhi-to-jaipur": createTravelRoute({ slug: "delhi-to-jaipur", origin: "Delhi", destination: "Jaipur", modes: [ { mode: "Car", duration: "4.5-5.5 hrs", cost: "₹3,080", comfort: 5, flexibility: 5, bestFor: "Families, flexible schedule" }, { mode: "Bus", duration: "5-6 hrs", cost: "₹500-1,200", comfort: 3, flexibility: 1, bestFor: "Budget solo travelers" }, { mode: "Train", duration: "4.5-5 hrs", cost: "₹400-1,800", comfort: 4, flexibility: 2, bestFor: "Shatabdi/Vande Bharat" }, { mode: "Flight", duration: "1 hr", cost: "₹3,000-7,000", comfort: 4, flexibility: 3, bestFor: "Business travelers" } ], verdict: "Car is ideal for groups of 2+. The Jaipur Expressway (NH-48) is excellent. Vande Bharat/Shatabdi is great for solo travelers. Flight check-in time negates the benefit for this short distance." }),
  "delhi-to-agra": createTravelRoute({ slug: "delhi-to-agra", origin: "Delhi", destination: "Agra", modes: [ { mode: "Car", duration: "3-3.5 hrs", cost: "₹2,530", comfort: 5, flexibility: 5, bestFor: "Day trips, families, Taj sunrise" }, { mode: "Bus", duration: "4-5 hrs", cost: "₹300-800", comfort: 2, flexibility: 1, bestFor: "Extreme budget travelers" }, { mode: "Train", duration: "2-3 hrs", cost: "₹200-1,500", comfort: 4, flexibility: 2, bestFor: "Gatimaan Express experience" }, { mode: "Flight", duration: "No direct flight", cost: "N/A", comfort: 0, flexibility: 0, bestFor: "Not available" } ], verdict: "Car is the clear winner for Agra trips. Yamuna Expressway takes just 3 hours with door-to-door service. Gatimaan Express is great but requires station transfers." }),
  "delhi-to-haridwar": createTravelRoute({ slug: "delhi-to-haridwar", origin: "Delhi", destination: "Haridwar", modes: [ { mode: "Car", duration: "5-6 hrs", cost: "₹2,530", comfort: 4, flexibility: 5, bestFor: "Families, pilgrims" }, { mode: "Bus", duration: "6-7 hrs", cost: "₹400-1,000", comfort: 2, flexibility: 1, bestFor: "Budget travelers" }, { mode: "Train", duration: "4.5-6 hrs", cost: "₹300-1,500", comfort: 3, flexibility: 2, bestFor: "Jan Shatabdi travelers" }, { mode: "Flight", duration: "1 hr to Dehradun + 1 hr cab", cost: "₹3,000-7,000 + ₹1,500", comfort: 4, flexibility: 3, bestFor: "Time-pressed travelers" } ], verdict: "Car is best for pilgrimage trips. Carry luggage, stop at Murthal, and continue directly to ghat-side hotel. For Haridwar + Rishikesh combo, car is essential." }),
  "delhi-to-rishikesh": createTravelRoute({ slug: "delhi-to-rishikesh", origin: "Delhi", destination: "Rishikesh", modes: [ { mode: "Car", duration: "5.5-6.5 hrs", cost: "₹2,640", comfort: 4, flexibility: 5, bestFor: "Adventure groups, families" }, { mode: "Bus", duration: "7-8 hrs", cost: "₹450-1,200", comfort: 2, flexibility: 1, bestFor: "Budget backpackers" }, { mode: "Train", duration: "5-6 hrs to Haridwar + 1 hr cab", cost: "₹300-1,500 + ₹999", comfort: 3, flexibility: 2, bestFor: "Solo travelers" }, { mode: "Flight", duration: "1 hr to Dehradun + 45 min cab", cost: "₹3,000-7,000 + ₹1,500", comfort: 4, flexibility: 3, bestFor: "Premium travelers" } ], verdict: "Car is the most practical option. Carry rafting gear, stop wherever you want, and enjoy the scenic Uttarakhand drive." }),
  "delhi-to-chandigarh": createTravelRoute({ slug: "delhi-to-chandigarh", origin: "Delhi", destination: "Chandigarh", modes: [ { mode: "Car", duration: "4-5 hrs", cost: "₹2,750", comfort: 5, flexibility: 5, bestFor: "Families, hill station onward" }, { mode: "Bus", duration: "4.5-6 hrs", cost: "₹400-1,000", comfort: 3, flexibility: 1, bestFor: "Budget travelers" }, { mode: "Train", duration: "3-4 hrs", cost: "₹300-1,800", comfort: 4, flexibility: 2, bestFor: "Shatabdi Express" }, { mode: "Flight", duration: "1 hr", cost: "₹3,000-7,000", comfort: 4, flexibility: 3, bestFor: "Business travelers" } ], verdict: "Car is excellent on NH-44 and essential if continuing to Shimla/Manali. Shatabdi Express is fast for solo travelers." }),
  "delhi-to-amritsar": createTravelRoute({ slug: "delhi-to-amritsar", origin: "Delhi", destination: "Amritsar", modes: [ { mode: "Car", duration: "7-8 hrs", cost: "₹4,950", comfort: 4, flexibility: 5, bestFor: "Families, Wagah Border trip" }, { mode: "Bus", duration: "8-10 hrs", cost: "₹600-1,800", comfort: 2, flexibility: 1, bestFor: "Budget travelers" }, { mode: "Train", duration: "5-6 hrs", cost: "₹400-2,500", comfort: 4, flexibility: 2, bestFor: "Shatabdi / Vande Bharat" }, { mode: "Flight", duration: "1.5 hrs", cost: "₹3,000-8,000", comfort: 5, flexibility: 3, bestFor: "Time-pressed travelers" } ], verdict: "Train (Shatabdi/Vande Bharat) is best for solo/couples. Car is ideal for families wanting Wagah Border trip. Flight is practical when booked early." }),
  "delhi-to-varanasi": createTravelRoute({ slug: "delhi-to-varanasi", origin: "Delhi", destination: "Varanasi", modes: [ { mode: "Car", duration: "12-14 hrs", cost: "₹6,600", comfort: 3, flexibility: 5, bestFor: "Groups, multi-city trips" }, { mode: "Bus", duration: "14-16 hrs", cost: "₹800-2,000", comfort: 1, flexibility: 1, bestFor: "Budget travelers" }, { mode: "Train", duration: "8-12 hrs", cost: "₹500-3,500", comfort: 4, flexibility: 2, bestFor: "Most travelers (Vande Bharat)" }, { mode: "Flight", duration: "1.5 hrs", cost: "₹3,000-8,000", comfort: 5, flexibility: 3, bestFor: "Time-pressed travelers" } ], verdict: "Flight or train is recommended over car (800 km is too far). Vande Bharat Express (8 hrs) is excellent. Book a local cab in Varanasi separately." }),
  "delhi-to-nainital": createTravelRoute({ slug: "delhi-to-nainital", origin: "Delhi", destination: "Nainital", modes: [ { mode: "Car", duration: "6.5-7.5 hrs", cost: "₹3,300", comfort: 4, flexibility: 5, bestFor: "Families, weekend trips" }, { mode: "Bus", duration: "8-10 hrs", cost: "₹500-1,500", comfort: 2, flexibility: 1, bestFor: "Budget solo travelers" }, { mode: "Train", duration: "5 hrs to Kathgodam + 1.5 hrs cab", cost: "₹300-1,800 + ₹999", comfort: 3, flexibility: 2, bestFor: "Train lovers" }, { mode: "Flight", duration: "1 hr to Pantnagar + 2 hrs cab", cost: "₹4,000-8,000 + ₹1,500", comfort: 3, flexibility: 3, bestFor: "Premium travelers" } ], verdict: "Car is the best option for Nainital. You need a vehicle for local sightseeing anyway. Kathgodam Shatabdi + local cab is a good alternative." }),
  "delhi-to-mussoorie": createTravelRoute({ slug: "delhi-to-mussoorie", origin: "Delhi", destination: "Mussoorie", modes: [ { mode: "Car", duration: "6-7 hrs", cost: "₹3,300", comfort: 4, flexibility: 5, bestFor: "Families, weekend getaways" }, { mode: "Bus", duration: "7-9 hrs", cost: "₹500-1,200", comfort: 2, flexibility: 1, bestFor: "Budget travelers" }, { mode: "Train", duration: "4.5 hrs to Dehradun + 1.5 hrs cab", cost: "₹300-1,800 + ₹999", comfort: 3, flexibility: 2, bestFor: "Shatabdi lovers" }, { mode: "Flight", duration: "1 hr to Dehradun + 1.5 hrs cab", cost: "₹3,000-7,000 + ₹999", comfort: 4, flexibility: 3, bestFor: "Time-pressed travelers" } ], verdict: "Car is ideal for Mussoorie. The drive is scenic and you need a car for local sightseeing. Dehradun Shatabdi + cab is a comfortable alternative." }),
  "delhi-to-kasol": createTravelRoute({ slug: "delhi-to-kasol", origin: "Delhi", destination: "Kasol", modes: [ { mode: "Car", duration: "11-12 hrs", cost: "₹5,280", comfort: 4, flexibility: 5, bestFor: "Groups, stop at Manikaran" }, { mode: "Bus", duration: "12-14 hrs", cost: "₹700-2,000", comfort: 2, flexibility: 1, bestFor: "Budget backpackers" }, { mode: "Train", duration: "12 hrs + 7 hrs cab", cost: "₹600-2,000 + ₹3,000", comfort: 2, flexibility: 2, bestFor: "Not recommended" }, { mode: "Flight", duration: "1.5 hrs to Kullu + 1.5 hrs cab", cost: "₹4,000-10,000 + ₹1,500", comfort: 3, flexibility: 3, bestFor: "Premium travelers" } ], verdict: "Car or overnight Volvo bus are practical options. Car is best for groups and offers flexibility to stop at Manikaran, Kullu, and scenic viewpoints." }),
  "delhi-to-dharamshala": createTravelRoute({ slug: "delhi-to-dharamshala", origin: "Delhi", destination: "Dharamshala", modes: [ { mode: "Car", duration: "9-10 hrs", cost: "₹4,840", comfort: 4, flexibility: 5, bestFor: "Families, Amritsar combo" }, { mode: "Bus", duration: "10-12 hrs", cost: "₹600-1,800", comfort: 2, flexibility: 1, bestFor: "Budget travelers" }, { mode: "Train", duration: "8 hrs to Pathankot + 3 hrs cab", cost: "₹400-2,000 + ₹1,500", comfort: 3, flexibility: 2, bestFor: "Train + mountain drive" }, { mode: "Flight", duration: "1.5 hrs to Gaggal + 30 min cab", cost: "₹3,500-9,000 + ₹500", comfort: 5, flexibility: 3, bestFor: "Time-pressed travelers" } ], verdict: "Flight to Gaggal airport is the most convenient. Car is best for families combining with Amritsar or Dalhousie." }),
  "delhi-to-udaipur": createTravelRoute({ slug: "delhi-to-udaipur", origin: "Delhi", destination: "Udaipur", modes: [ { mode: "Car", duration: "10-11 hrs", cost: "₹7,260", comfort: 3, flexibility: 5, bestFor: "Multi-city Rajasthan trips" }, { mode: "Bus", duration: "12-14 hrs", cost: "₹700-2,200", comfort: 2, flexibility: 1, bestFor: "Budget travelers" }, { mode: "Train", duration: "10-12 hrs", cost: "₹500-3,000", comfort: 4, flexibility: 2, bestFor: "Mewar Express" }, { mode: "Flight", duration: "1.5 hrs", cost: "₹3,000-8,000", comfort: 5, flexibility: 3, bestFor: "Most travelers" } ], verdict: "Flight is recommended for Delhi-Udaipur (660 km is long by road). Book a local cab separately. Car makes sense only for a Rajasthan circuit." }),
  "jaipur-to-udaipur": createTravelRoute({ slug: "jaipur-to-udaipur", origin: "Jaipur", destination: "Udaipur", modes: [ { mode: "Car", duration: "6-7 hrs", cost: "₹4,345", comfort: 4, flexibility: 5, bestFor: "Rajasthan circuit, scenic drive" }, { mode: "Bus", duration: "7-9 hrs", cost: "₹500-1,500", comfort: 2, flexibility: 1, bestFor: "Budget travelers" }, { mode: "Train", duration: "6-8 hrs", cost: "₹300-2,000", comfort: 3, flexibility: 2, bestFor: "Overnight travel" }, { mode: "Flight", duration: "1 hr", cost: "₹3,000-7,000", comfort: 5, flexibility: 3, bestFor: "Time-pressed travelers" } ], verdict: "Car is the best choice. The NH-48 offers beautiful Aravalli Hills scenery with optional Chittorgarh Fort stop. Essential for Rajasthan circuit." }),
  "jaipur-to-jodhpur": createTravelRoute({ slug: "jaipur-to-jodhpur", origin: "Jaipur", destination: "Jodhpur", modes: [ { mode: "Car", duration: "5-6 hrs", cost: "₹3,740", comfort: 4, flexibility: 5, bestFor: "Rajasthan circuit" }, { mode: "Bus", duration: "6-7 hrs", cost: "₹400-1,200", comfort: 2, flexibility: 1, bestFor: "Budget travelers" }, { mode: "Train", duration: "5-6 hrs", cost: "₹300-1,800", comfort: 3, flexibility: 2, bestFor: "Mandore Express" }, { mode: "Flight", duration: "1 hr", cost: "₹2,500-6,000", comfort: 4, flexibility: 3, bestFor: "Business travelers" } ], verdict: "Car is ideal. Good highway with flexible timing. You can stop at Ajmer-Pushkar en route. Essential for Rajasthan road trip circuit." }),
  "chandigarh-to-manali": createTravelRoute({ slug: "chandigarh-to-manali", origin: "Chandigarh", destination: "Manali", modes: [ { mode: "Car", duration: "7-8 hrs", cost: "₹3,410", comfort: 4, flexibility: 5, bestFor: "Families, scenic mountain drive" }, { mode: "Bus", duration: "8-10 hrs", cost: "₹400-1,500", comfort: 2, flexibility: 1, bestFor: "Budget travelers" }, { mode: "Train", duration: "No direct train", cost: "N/A", comfort: 0, flexibility: 0, bestFor: "Not available" }, { mode: "Flight", duration: "No direct flight", cost: "N/A", comfort: 0, flexibility: 0, bestFor: "Not available" } ], verdict: "Car is the only comfortable option. No direct train or flight. The 310 km mountain drive through Bilaspur, Mandi, and Kullu is stunning." }),
  "lucknow-to-varanasi": createTravelRoute({ slug: "lucknow-to-varanasi", origin: "Lucknow", destination: "Varanasi", modes: [ { mode: "Car", duration: "5-6 hrs", cost: "₹3,300", comfort: 4, flexibility: 5, bestFor: "Families, spiritual tour" }, { mode: "Bus", duration: "6-8 hrs", cost: "₹400-1,000", comfort: 2, flexibility: 1, bestFor: "Budget travelers" }, { mode: "Train", duration: "4-6 hrs", cost: "₹200-1,500", comfort: 4, flexibility: 2, bestFor: "Most travelers" }, { mode: "Flight", duration: "1 hr", cost: "₹2,500-6,000", comfort: 5, flexibility: 3, bestFor: "Time-pressed travelers" } ], verdict: "Car is excellent via Purvanchal Expressway. Perfect if combining with Ayodhya and Prayagraj. Train is comfortable and frequent." }),
  "agra-to-jaipur": createTravelRoute({ slug: "agra-to-jaipur", origin: "Agra", destination: "Jaipur", modes: [ { mode: "Car", duration: "4-5 hrs", cost: "₹2,640", comfort: 4, flexibility: 5, bestFor: "Golden Triangle travelers" }, { mode: "Bus", duration: "5-7 hrs", cost: "₹400-1,000", comfort: 2, flexibility: 1, bestFor: "Budget travelers" }, { mode: "Train", duration: "4-5 hrs", cost: "₹200-1,200", comfort: 3, flexibility: 2, bestFor: "Solo travelers" }, { mode: "Flight", duration: "No direct flight", cost: "N/A", comfort: 0, flexibility: 0, bestFor: "Not available" } ], verdict: "Car is the best option. NH-21 is well-maintained with optional stops at Fatehpur Sikri and Bharatpur. Essential for Golden Triangle circuit." }),
  "delhi-to-leh": createTravelRoute({ slug: "delhi-to-leh", origin: "Delhi", destination: "Leh", modes: [ { mode: "Car", duration: "2 days (1,000 km via Manali)", cost: "₹22,000-30,000", comfort: 3, flexibility: 5, bestFor: "Epic road trip enthusiasts" }, { mode: "Bus", duration: "2 days", cost: "₹2,000-4,000", comfort: 1, flexibility: 1, bestFor: "Extreme budget adventurers" }, { mode: "Train", duration: "No direct train", cost: "N/A", comfort: 0, flexibility: 0, bestFor: "Not available" }, { mode: "Flight", duration: "1.5 hrs", cost: "₹4,000-12,000", comfort: 5, flexibility: 3, bestFor: "Most travelers" } ], verdict: "Flight is recommended for most travelers. Saves 2 days. The Delhi-Manali-Leh road trip is a bucket-list adventure but requires 2 days each way and SUV (June-September only)." }),
};

export function getTravelOptionsRoute(slug) {
  return travelRoutes[slug] || null;
}

export function getAllTravelOptionsSlugs() {
  return Object.keys(travelRoutes);
}

export function getRelatedTravelRoutes(slug, limit = 4) {
  const all = Object.values(travelRoutes);
  return all.filter(r => r.slug !== slug).slice(0, limit);
}
